### ISSUE TITLE
Collaborative Notes

### ISSUE THREAD

**Issue by FredMa01** [nextcloud/notes#1011]
Hello,
I am using Notes plugin on computer and android. It's great.
The only regret is that it is not possible to share notes to complete them with several users.
I try to share the [Notes] directory between 2 users but it doesn't work...
Would this be a possible feature ?

Thanks
Fred

**Comment by stefan-niedermann** [comment]
The person you have shared your folder with, needs to place the shared folder within his own notes folder.

See also https://github.com/nextcloud/notes/issues/38 and https://github.com/nextcloud/notes/issues/285 - closing this as duplicate therefore.
