### ISSUE TITLE
iOS automatic notes synchronization 

### ISSUE THREAD

**Issue by Oberlurch3000** [nextcloud/notes#1015]
When using shared notes with other users the iOS app isn't automatically synchronizing changes that where made on an other device. While the android app is looking for changes and showing the latest version with the iOS app you get an message where you have to choose which version you what to choose (local or cloud). This leads to changes accidentally getting overwritten.
Further when choosing one version it results in an endless loading screen. You have to close the app and open again to enter the note.

**Comment by stefan-niedermann** [comment]
This is the reposizory of the notes server app, please open your issue in the repository of the notes-ios app.
