### ISSUE TITLE
Conflict during file save, please resolve

### ISSUE THREAD

**Issue by Egor3f** [nextcloud/notes#1019]
## Steps to reproduce
1. Open a note in nextcloud notes
2. Enable rich text editor

### Expected behaviour
Note is opened

### Actual behaviour
Nothing happens and there is an exception in browser console:
[ERROR] text: Conflict during file save, please resolve {app: 'text', uid: 'MyUsername', level: 2}

Bug is sporadic, happens only with 1 note, others are loading successfully. This note also loaded successfully some time ago, and I'm not sure when exactly problem started.

## Server
Please complete the following information.

- Notes app version: 4.7.2
- Nextcloud version: Nextcloud Hub 4 (26.0.0)
- OS: Linux 5.15.0-67-generic x86_64
- Web server: Apache in Docker
- PHP version: 8.1.17
- Database: mysql 10.5.18

**Nextcloud configuration:**

<details>
```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nc.efprojects.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "26.0.0.11",
        "overwrite.cli.url": "http:\/\/nc.efprojects.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpport": "465",
        "maintenance": false,
        "overwriteprotocol": "https",
        "loglevel": 2
    }
}
```
</details>

## Client
Please complete the following information.

- Browser (incl. version): Vivaldi 5.7.2921.65 (Stable channel) (x86_64) 
 - OS: macOS 13.2.1

## Log files
Add relevant parts of your `nextcloud.log` and/or your browser's JavaScript console here.
### Browser log:
POST https://my-domain.com/apps/text/session/sync 409
ConsoleLogger.js:59 [ERROR] text: Conflict during file save, please resolve {app: 'text', uid: 'MyUsername', level: 2}
### Nextcloud log:
The only corresponding entry is: (log entry appeared several hours before this bug happened)
OC\DB\Exceptions\DbalException: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2313-MyUsername' for key 'notes_meta_file_user_index'

**Comment by Yiannis128** [comment]
This is very annoying, I've faced this issue but with more than 1 case, maybe it's cause I have a lot of notes in my Notes app. Hopefully it gets looked at.
