### ISSUE TITLE
Real-time collborative editing and WYSIWYG via integration with "Nextcloud Text" App

### ISSUE THREAD

**Issue by chadsell** [nextcloud/notes#1024]
I have been using Google Keep with my wife to share notes and checklists for years. I'd love to be able to switch to Nextcloud Notes and ditch Google, but there are a few missing key features that are deal-breakers for this use case.  These features exist in the Nextcloud Text app, though, so perhaps it's possible to intergrate them?

**Features:**
Collborative editing:  Multiple clients can edit notes _at the same time_ and all edits are _real-time synced_ across clients. This allows me to leave my note open on my desktop and still make edits while out and about on mobile.  It also allows my wife and I to work on notes together without having to constantly check for editing collisions.

WYSIWYG:  I like markdown in general, but my wife is never going to learn it just for the simple notes and lists that we share.

**Possible solution**
_Nextcloud Text_ already allows for collborative editing and has a WYSIWYG editor. Unfortunately, it doesn't have a nice interface for navigating and tagging notes, but instead relies on the native Nextcloud Files interface.
I'd love to be able to select "Nextcloud Text" as the editor while using Notes.  Or to have the features of Text added as an option in Notes.

**Comment by stefan-niedermann** [comment]
So, you mixed up plenty of topics in this issue, let's sort them out:

- Using tags is discussed in https://github.com/nextcloud/notes/issues/299
- Using Nextcloud Text as editor is available in the latest version, you can switch to it in the bottom left <kbd>Notes settings</kbd> section
- Sharing is discussed in https://github.com/nextcloud/notes/issues/38 and https://github.com/nextcloud/notes/issues/285

If I didn't miss anything, please close this issue to avoid concurrent discussions (and while I appreciate the feedback, please search for existing issue before opening a new one to avoid unnecessary work for you and us 😉)

**Comment by chadsell** [comment]
Sorry for any lack of clarity in my initial post. I only brought up tags and sharing to provide context, since the prompt for a feature requests said to be detailed about the use case.

Anyway, I'm on Notes 4.7.2, which appears to be the most recent version, and I don't have an option to use Nextcloud Text as the editor. Perhaps this will end up being a bug issue, not a feature request.  Am I missing some other setting or prerequisite somewhere to enable this option? Or should I open an bug report?

And maybe this will become clear if I can get Nextcloud Text set as my editor, but does using Text as editor allow for real-time collaborative editing, and does it work on the Android app? Because that's even more important to me than WYSIWYG editing. 

I'll concede that real-time collaboration and WYSIWYG are two separate issues, but I was thinking they would both be solved by the intergration of Nextcloud Text... at least in the way I was envisioning it. So perhaps my feature request was an X/Y problem. 

Allow me to restate my primary feature request without the X/Y confusion:

- I would like to be able to have real-time collaborative editing 
  - between multiple clients (multiple web interface, android client, etc.) for one user. 
  - I would like to have real-time collaborative editing between multiple users.  
  - If my wife clicks a checkbox on a list we share, I want to see that item checked off within a moment or two. 
  - Likewise, if I leave a note open on my desktop web interface, I want to be able to edit that note on the mobile app and have everything sync properly, instead of causing version collisions. 

If this feature is available using Nextcloud Text, let me know and I'll just focus on getting that working on my system.  If using Nextcloud Text as the editor does NOT allow for real-time collaborative editing, then my feature request remains.

**Comment by stefan-niedermann** [comment]
Well, at least in the german translations it's called "Rich text mode" (lowest entry in the settings area, beside "Edit mode" and "Preview mode"). It actually is the Nextcloud Text editor.

![Screenshot_20230419-231648_Fennec](https://user-images.githubusercontent.com/4741199/233202098-ed11c14c-3026-4574-945b-5968010237ea.png)

**Comment by chadsell** [comment]
I only have "open in edit mode" and "open in preview mode" in that menu.  I've tried uninstalling and reinstalling the notes app, but that didn't change anything.
I'm running NextcloudPi, which is currently on Nextcloud 25.0.5, If that makes a difference.

**Comment by stefan-niedermann** [comment]
Do you have the Nextcloud Text app installes and enabled? It's a separate app...

**Comment by chadsell** [comment]
Haha, yes, of course I do... But I don't blame you for asking!

**Comment by juliushaertl** [comment]
Collaborative editing using the Text app is only available starting with Nextcloud 26, since it requires the new APIs provided by the text app, so this will not be available on 25.
