### ISSUE TITLE
Note title changes to match the first line of the note every time a note is saved

### ISSUE THREAD

**Issue by dinosmm** [nextcloud/notes#1029]
Please make a clear and concise description of what the bug is.

## Steps to reproduce
1. Open a note
2. Edit the note (write or delete something)
3. Move to a different note, or click to a different Nextcloud app/exit Nextcloud, then reopen Nextcloud Notes

### Expected behaviour
Note should have been saved with its existing name

### Actual behaviour
Note name changes to match the first line of the note. This happens every time I edit any note.
Even if I rename the note, next time I edit it its title changes back to match the first line in the note (which is not the title I want). This did NOT happen when NC 25.

## Server
Please complete the following information.

- Notes app version: 4.7.2
- Nextcloud version: 26.0.1
- OS: Ubuntu 22.04
- Web server: Nginx 1.18.0
- PHP version: 8.1.2
- Database: Postgresql 14

**Nextcloud configuration:**

<details>
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "domain",
            "127.0.0.1"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "26.0.1.1",
        "overwrite.cli.url": domain
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "5432",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_X_FORWARDED_FOR"
        ],
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "default_phone_region": "GB",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtptimeout": 30,
        "log_type": "file",
        "logfile": "\/home\/dinosm\/log\/nextcloud.log",
        "loglevel": 0,
        "logdateformat": "F d, Y H:i:s",
        "maintenance": false,
        "trashbin_retention_obligation": "5, 15",
        "app_install_overwrite": [
            "radio",
            "files_trackdownloads",
            "twofactor_admin",
            "electronicsignatures",
            "riotchat",
            "extract",
            "impersonate",
            "files_videoplayer",
            "apporder"
        ],
        "has_rebuilt_cache": true,
        "theme": "",
        "projects.enabled": false,
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "enable_previews": true,
        "preview_max_memory": 512,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI"
        ],
        "memories.exiftool": "\/var\/www\/nextcloud\/apps\/memories\/exiftool-bin\/exiftool-amd64-glibc",
        "memories.gis_type": 2,
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "memories.vod.disable": false,
        "memories.vod.path": "\/var\/www\/nextcloud\/apps\/memories\/exiftool-bin\/go-vod-amd64"
    }
}
```
</details>

## Client
Please complete the following information.

- Browser (incl. version): 
 - OS: 

## Log files
There don't seem to be any log entries generated when this happens, I can only see log entries relating to expiring previous versions of the notes. If someone could let me know what to search for in the log I am happy to go hunting and paste any relevant entries.

**Comment by martinmarcosjr** [comment]
I'm having exactly the same issue.

**Comment by juliushaertl** [comment]
This has been a change probably done too fast in #958 as this was part of our design discussions in #967 with @jancborchardt:

> - [ ]  Title handling: Adjust more to Apple Notes in that the first line is taken as title, also if you change it manually


I can see this might not be always the expected behaviour. @jancborchardt What is your take on this?

**Comment by martinmarcosjr** [comment]
I have a note that is just a piece of code and, no matter how many times I rename it, the title always automatically changes to "```" 
:)

**Comment by dinosmm** [comment]
> I can see this might not be always the expected behaviour.

I would say it is not, I have got used to having a separate title for each note, but the notes start straight away with no title in the actual note body (after all, it's only a note, not a Word document).
The Notes app worked like that before it was integrated into NC Core, I am not sure why the integration should have made it work any differently.

**Comment by juliushaertl** [comment]
Quickly discussed this with @jancborchardt and we'll see if we can adapt the logic so that the filename is only changed if it wasn't changed manually. Otherwise we'd revert the change to the previous behaviour to only update when the note was create for the first time.
