### ISSUE TITLE
Share note

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/notes#1041]
Right now we could share a note manually, and then the recipient needs to move it to matching Notes folder.

As discussed with @jancborchardt and @AndyScherzinger this should be done better.
It might need server changes.

Once this note app has api to share a note, we can implement it in clients.

**Comment by stefan-niedermann** [comment]
Duplicate of https://github.com/nextcloud/notes/issues/38 and / or https://github.com/nextcloud/notes/issues/285 ?

**Comment by jancborchardt** [comment]
Closing in favor of the existing issue https://github.com/nextcloud/notes/issues/38 :)
