### ISSUE TITLE
Optional LaTeX support, or rich text

### ISSUE THREAD

**Issue by candroid-man** [nextcloud/notes#1049]
**Is your feature request related to a problem? Please describe.**
I may be the only one that thinks this, but Markdown is stupid. But it's even more stupid without LaTeX, or something to show the formatting you've made in real time, much like how the standard text editor in the Files app works. Because of this, the Notes app is mostly useless because it doesn't do anything that the standard Files text editor can't.

**Describe the solution you'd like**
If you want to continue using Markdown, consider using LaTeX as it makes the user experience much better. If you like the idea of moving away from Markdown, you could do rich text and have a proper formatting bar specifically designed for taking notes (such as what Notesnook offers). Neither of these options restrict users to non-standard file types, and these files can be easily exported into other programs if necessary.

**Describe alternatives you've considered**
Even if you don't want to do any of that, at least give the Notes app some actual use case. As of right now, the text editor in Files has more features and has a better editing experience. #38 has been there since 2016, so if you want to share your notes, you have to share the file itself anyway.

**Comment by adroslice** [comment]
A lot of people love markdown. I wouldn't be opposed to adding LaTeX as an alternate note format, but it should certainly not be the default.
In addition to that, having all my formatting rendered as plain text really helps copy-pasting things back and forth and keeping things consistent. A WYSIWYG-Editor is a different experience, not necessarily a better one.

**Comment by juliushaertl** [comment]
We currently have no plans to add other formats than markdown. I think LaTeX is quite a special use case that would better fit into a separate app to implement editing and generating a preview of such files.

**Comment by fugohan** [comment]
It would be beneficial to add Mathjax or Katex to Nextcloud Notes.  This would benefit the entire scientific community and would begreat for Nextcloud collectives. Nextcloud collectives can also benefit from this implementation.
