### ISSUE TITLE
Rich Text Mode | Files are renamed when saving

### ISSUE THREAD

**Issue by MoritzDPTV** [nextcloud/notes#1071]
Hello there,

when using the Rich Text Mode in the Notes app, files are renamed after saving according to the first line of the file. Manually renaming the file works, but after another saving it is renamed to the content of the file again. Auto-file-naming should be optional, maybe another tick in the settings would do it.

If you need further information, let me know. Thanks!

Best,
Moritz

## Server
- Notes app version: 4.8.0
- Nextcloud version: 26.0.3
- OS: Ubuntu 20.04.5 LTS
- Web server: Apache
- PHP version: 8.1.18
- Database: MySQL

## Client
- Browser (incl. version): Mozilla Firefox 114.0.2 (64-bit)
- OS: Ubuntu 22.04.1 LTS

**Comment by sapristi** [comment]
This is bothering me as well. This feels like a workaround for the fact that the web-frontend does not have a way to edit a note title, but this prevent integration with other tools.
