### ISSUE TITLE
Scroll Bar Lost on Notes List in Narrow Browser Window

### ISSUE THREAD

**Issue by GuestJim** [nextcloud/notes#1080]
Since the UI recent overhaul (4.8.0 I believe) I cannot scroll through the list of notes unless I maximize my browser. I access my Nextcloud instance via my browser and my preference is to keep my browser at half the screen, making it portrait instead of landscape. Now that I've thought to maximize the window to test, I think I know what is going on; in the narrow view the notes list is focused on but this focused view lacks the scroll bar. If I maximize the window, so it is landscape, I get the complete three-column view and can scroll, but this is not my preferred way to use my browser.

## Steps to reproduce
1. Have a decently long list of notes
    - I've 49 but only 10 are visible in the list, with my current favorites and last-modified sorting
2. Make the browser window narrow/portrait
   - On Windows, drag it against the side of the screen to have it take half the screen. This is what I do with my browser  making it about 1024x1152 (my monitor is 2048x1152)
3. Open the list of notes and attempt to scroll through the list of notes
4. Maximize the browser window and repeat step 3 to notice change in behavior

### Expected behavior
The list of notes can be scrolled through regardless of browser window size

### Actual behavior
Scrolling through the list of notes and its scroll bar are missing when the browser window is narrow/portrait

## Server
- Notes app version: 4.8.1
- Nextcloud version: 25.0.2
- OS: Linux 5.15.79+truenas x86_64
- Web server: nginx/1.23.3 (fpm-fcgi)
- PHP version: 8.1.13
- Database: pgsql PostgreSQL 14.7 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

## Client
Please complete the following information.

- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0
    - more specifically, Waterfox 5.1.9
 - OS: Windows 10

**Comment by juliushaertl** [comment]
Thanks for reporting. I can reproduce this and noticed that in other apps like collectives it works but they have a manual overflow set:

![Screenshot 2023-07-20 at 16 13 53](https://github.com/nextcloud/notes/assets/3404133/2c663e31-a260-4c82-9060-371c1cb312d7)

- [ ] Check if we want to upstream this to the vue components library or propse a fix just in notes

**Comment by amyipdev** [comment]
Was about to report this when I saw this issue existed. Also having it here!

Notes 4.8.1, Hub 27.0.0, Debian 12 Bookworm, php 8.2

**Comment by cscherrNT** [comment]
> I have a similar issue, for me I can't scroll through the note itself when the window is narrow enough. The only way to navigate then is with the arrow keys. Notes 4.8.1, Nextcloud AIO V7.0.0 beta. Both with Firefox and Edge.

I can confirm that I have this behaviour too.

**Comment by GuestJim** [comment]
I see this issue is still marked as open, but as of version 4.9.1, I have the scrollbar again, exactly as desired. I do not know if the fix might have been deployed in an earlier version, but with this new version, it is looking good.
