### ISSUE TITLE
Clear UI for creating notes categories for Nextcloud notes

### ISSUE THREAD

**Issue by Tapio-testauserveri** [nextcloud/notes#1082]
I have been trying to use NextCloud notes running on my Nextcloud instance running on top of my own TrueNAS server. The issue I have been facing is that the category creation button/method is not very clear and not very well documented., and it should be visible from the same screen as creating a new note. 
![image](https://github.com/nextcloud/notes/assets/134807883/c0dab36b-824c-49f3-ac79-bddcec09b2d2)

I would like to see a new button added simular to the create a new note. It could be next to to the create a new note, or it could be placed simularly to the Nextcloud task UI, wherein you have "**Add new lis**t" under the already created categories. 
![image](https://github.com/nextcloud/notes/assets/134807883/255f8ca6-babe-402a-b574-a6403c94cc2d)
For context, the **list** in **tasks** is is simular categorisation to the **categories** in Nextcloud Notes. 

I hope I managed to describe the issue well. Please feel free to contact me if there is any issues or inclarities. I will check this in a couple of days. 

Yours.
Tapio Markkanen

**Comment by joshtrichards** [comment]
Thanks for the feedback. There indeed did seem to be some room for improvement. The category management (and UI in general) was revamped around the same time you sent in this idea.  Closing since that is the old UI.

**Comment by Tapio-testauserveri** [comment]
Hi Josh, thanks for taking the time!
