### ISSUE TITLE
Renaming of notes is not possible anymore

### ISSUE THREAD

**Issue by balvie** [nextcloud/notes#1087]
## Steps to reproduce
1. click new note
2. start typing
3. click on some other note
4. find the note just created being stored with default name ("New note ")

### Expected behaviour
Earlier version had a ... context menu that offered Rename funtion, now this submenu only shows: Add to fav, Details, Delete and Category. See:
![Clipboard01](https://github.com/nextcloud/notes/assets/6725806/6cc1a5b4-c94f-4473-82e3-74f56845de8c)

### Actual behaviour
See above.
Looking at an earlier issue, #1062 , I truly believe that that issue doesn't cover the severity of the issue enough and contains a distracting discussion. (I'd prefer one message at the time.)
Thus this is a bug report that I hope will find attention.
If it only was like before, it would be okay. Thanks for the attention guys.

## Server
Please complete the following information.

- Notes app version: 4.8.1
- Nextcloud version: 26.0.4
- OS: Windows 10
- Web server: Apache
- PHP version: 8.1
- Database: MariaDB

## Client
Please complete the following information.

- Browser (incl. version): 
- OS: Mozilla 115.0.2 (64-bit)

## Log files
Add relevant parts of your `nextcloud.log` and/or your browser's JavaScript console here.

**Comment by juliushaertl** [comment]
To clarify the spec of this issue a bit more:
- Add a rename entry on each note item in the list ([NcActionButton](https://nextcloud-vue-components.netlify.app/#/Components/NcActions?id=ncactionbutton))
- Once clicked exchange it with a [NcActionInput](https://nextcloud-vue-components.netlify.app/#/Components/NcActions?id=ncactioninput) component
- Both options should use the Markdown Pencil icon https://pictogrammers.com/library/mdi/icon/pencil/
- Once the arrow button is clicked it should rename this note on the backend (this is already implemented as a [service method](https://github.com/nextcloud/notes/blob/dca9296a77c0a756712e6507f507b75960f46668/src/NotesService.js#L177-L186))

**Comment by psy0rz** [comment]
yes its very annoying, you can still rename via 'details' and clicking on the title in the details drawer, buts way too much hassle.

**Comment by joshtrichards** [comment]
Fixed in 4099c5321deb4dd36aee7fba995d390a91d0df4a
