### ISSUE TITLE
Add Iotas to wiki?

### ISSUE THREAD

**Issue by cheywood** [nextcloud/notes#1105]
Hello, I'm the maintainer of [Iotas](https://gitlab.gnome.org/World/iotas), a note taking app for Linux mobile and desktop using the API. I thought perhaps you could add an entry in the third party apps list in the wiki? 

eg.
```
### Linux desktop and mobile

- [Iotas](https://gitlab.gnome.org/World/iotas)
  - [Flathub](https://flathub.org/apps/org.gnome.gitlab.cheywood.Iotas)
```

**Comment by juliushaertl** [comment]
Thanks, looks like a neat app, will need to give that a spin as well.

Added to the Wiki :)

**Comment by juliushaertl** [comment]
Just also moved it to the right section for integrating with the API, as I put it in the wrong one before

**Comment by cheywood** [comment]
Thanks Julius!
