### ISSUE TITLE
Synchronization failed

### ISSUE THREAD

**Issue by strk** [nextcloud/notes#1115]
Android app cannot sync anymore, saying:

Provided authentication token does not match or package name is not permitted to perform this action

Full exception message:
https://paste.debian.net/1292970/

Server version: 25.0.10

**Comment by strk** [comment]
Same error when upgrading server to 25.0.12

**Comment by strk** [comment]
Uninstalling the app and re-installing it again fixed the issue for me, beside loosing all local modifications of the notes :(

**Comment by stefan-niedermann** [comment]
The issue template asked you to read the FAQ before opening a new issue.

Pitty that you decided to delete it, it would have explained how to proceed when encountering this error and it also explained the risc of data loss when not backing it up before.

Long story short: Your unsynchronized modifications are lost. Proceed as described in the FAQ (linked in the issue template) to get a working state again.

**Comment by strk** [comment]
Pity a search in the issue tracker did not yeld any result for me

**Comment by strk** [comment]
Btw, I went looking for the FAQ but could not find a link, also I cannot  find it in the issue template

**Comment by strk** [comment]
Found (this was not the correct repository to file the ticket against): https://github.com/nextcloud/notes-android/blob/main/FAQ.md

**Comment by stefan-niedermann** [comment]
Well, what should I say. You are clearly talking about the Notes Android App, aren't you?

So how couldn't you see this line after reading the template a second time?

![Screenshot_20230924-172901_Fennec](https://github.com/nextcloud/notes/assets/4741199/207276bd-c425-4211-8d18-317c37be2690)


Well, let's follow the hint, that we are in the wrong repository here and try opening an issue in the linked, correct repository - but wait! There's also some information when trying to open a new issue:

![Screenshot_20230924-173024_Fennec](https://github.com/nextcloud/notes/assets/4741199/bb551880-ae32-4d8b-bdb3-3d16369e0e8c)

and again, it's in the first bunch of lines, not even need to scroll.

Look, there's [a section in the linked FAQ which explicitly handles the `TokenMismatchException` you posted above](https://github.com/nextcloud/notes-android/blob/main/FAQ.md#tokenmismatchexception)!

It explains that it is not an issue located within Notes or the Notes Android app but it's about the Nextcloud Single Sign On, which means it can possibly affect all 3rd party Nextcloud Android Apps.

And even better, it does explain how to get rid of it, it warns about loosing unsynchronized changes *and* it explains why uninstalling and clearing storage are *not* the same thing.
