### ISSUE TITLE
fix width limitations on a note

### ISSUE THREAD

**Issue by modernNeo** [nextcloud/notes#1128]
Hi, not sure if what I am complaining about is a bug or a feature or if there's some simple toggle that can do what I need and I just can't seem to find it but lately I have been getting somewhat peeved by the width limitation in a note.

To demonstrate what I mean, please take a look at the screenshot below
![Screenshot from 2023-10-10 15-44-55](https://github.com/nextcloud/notes/assets/14242088/a15ccdba-5e17-4b69-bd6d-9a2016da3d45)

I am trying to figure out how/why 2 things are occurring
1. there is a margin imposed such that the text does not take up the whole space it can [the places where I put red arrows are a lot of empty real estate that I really wish could be used to display my note].
2. why the text is centered in the middle.

This can be especially annoying if I have a list and one of my list items is rather long and it ends up taking 2-3 lines in my note when I can see that my monitor is capable of having it all on one line.

## Server
Please complete the following information.

- Notes app version: 4.8.1
- Nextcloud version: nextcloud:27.0.1-apache
- Database: PostgreSQL

**Nextcloud configuration:**

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "27.0.1.2",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "overwriteprotocol": "https",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "maintenance": false
    }
}

```

## Client
Please complete the following information.

- Browser (incl. version): firefox 115.3.1esr
 - OS: Debian

**Comment by stefan-niedermann** [comment]
This has already been discussed *intentively*. Please [read the whole thread](https://github.com/nextcloud/notes/issues/415) which also contains links to relevant upstream issues.
