### ISSUE TITLE
CHANGELOG not maintained

### ISSUE THREAD

**Issue by heinrichmartin** [nextcloud/notes#114]
What where the updates since 1.1.0 doing? Where can I find out as it is not in CHANGELOG?

**Comment by 1337sup3rh4x0r** [comment]
you serious?
you could:
- look at the releases page (https://github.com/nextcloud/notes/releases)
- look at the commits page (https://github.com/nextcloud/notes/commits/master)

**Comment by heinrichmartin** [comment]
No offense intended. Sorry if my input was not verbose enough. Having said that, yes I was confused about the seemingly truncated CHANGELOG file. And I opened this ticket to help others who come here my way:
1. Receive an update notification and want to look up changes.
2. Follow the link to visit web site, developer documentation, or similar. (Unfortunately this is not consistent for all nextcloud apps.)
3. Found no release notes on [Visit website ↗](https://github.com/nextcloud/notes), but spotted CHANGELOG.

Thank you for the links above. I was looking for [release notes](https://github.com/nextcloud/notes/releases) rather than [browsing commits](https://github.com/nextcloud/notes/commits/master). Now, I also found the [link](https://github.com/blog/1547-release-your-software) that would have taken me there from the project homepage.

Having caught up with features of github, my request should be:
Please either remove the misleading CHANGELOG file or add a note about where to find release notes.

Suggested content of such a note:
> Recent release notes are maintained on github only, see https://github.com/nextcloud/notes/releases.
> They are no longer part of the source code.
