### ISSUE TITLE
Support for tables

### ISSUE THREAD

**Issue by ToeiRei** [nextcloud/notes#115]
I'd like to see that built in as I often have to keep track of network documentations which often includes tables (IP/hostname/comment)

**Comment by Rainer-K** [comment]
I would also like to have support of tables. Syntax could be like used by Github and reddit. Might be a challenge to do it with the live-preview, though.

```
First Col | Second Col
--------- | -----------
First cell | Second cell
And so | on
```

**Comment by chris-est** [comment]
Maybe the same syntax as the [Markdown Editor](https://apps.nextcloud.com/apps/files_markdown) can be used ? They support this syntax:
```
| #  | Who   | Where |
|:--:|:------|:-----:|
| 1  | Alice | Earth |
| 2  | Bob   | Mars  |
```

Result:
![markdown_table_rendered](https://user-images.githubusercontent.com/6406802/33803338-f2f638ac-dd8d-11e7-8735-7d8daf731a70.png)

**Comment by jancborchardt** [comment]
We use [SimpleMDE](https://simplemde.com/) as our base, so this has to be done in that software. Unfortunately looking at the repository at https://github.com/sparksuite/simplemde-markdown-editor it does not seem so maintained anymore (ref #204) but do feel free to open an issue there. :)
