### ISSUE TITLE
Titlebar for notes

### ISSUE THREAD

**Issue by mase76** [nextcloud/notes#116]
Hi!
I think, there should be a title bar for each note, from which the filename is generated.
Taking the first line isn't optimal. There are other apps on other machines accessing
the notes. This will always end up in a different filename each time I access the note.
As a workaround for now, I use the first line as title.

**Comment by korelstar** [comment]
Please see owncloud/notes#198. This approach was chosen as part of the app's philosophy. Hence, it's not a workaround to use the first line as title, rather it's a typical way.
