### ISSUE TITLE
Share a note - nothing displayed

### ISSUE THREAD

**Issue by stvogel** [nextcloud/notes#1173]
## Steps to reproduce
1. install recent 4.9.0 version
2. click on "..." in the left bar of a note and choose "Share"
3. on the right side a pane opens, but the pane is completely empty 

### Expected behaviour
I suppose something about "sharing" should appear in the opened right pane.

### Actual behaviour
Tell us what happens instead

### Screenshots
![image](https://github.com/nextcloud/notes/assets/4895281/4e45ddfa-6b01-4ea5-9c5a-d90aad4ec4a5)

## Server
Please complete the following information.

- Notes app version: 4.9.0
- Nextcloud version: 27.1.4
- OS: Linux
- Web server: apache
- PHP version: 8.2
- Database: mysql5.6

## Client
Please complete the following information.

- Browser (incl. version): Chrome 119.0.6045.200 and Edge 119.0.2151.97
 - OS: Win10

**Comment by ByakuraRinne** [comment]
Same here
