### ISSUE TITLE
Notes not showing in webbrowser

### ISSUE THREAD

**Issue by GHBLoos** [nextcloud/notes#1184]
Please make a clear and concise description of what the bug is.

On my desktop PC: When clicking on the notes icon on the top menu, no notes are displayed. Except for the top menu, the screen is empty.
On my laptop: I was working on notes, and I closed the laptop (hibernated it). When I just opened my laptop from hibernation Notes is still working.  Last Note was not yet saved. When I open a second browser window and open Notes, it is also an empty screen. Also after saving the note, the other browser sessies are still showing empty screens.  When leaving the Notes screen on the open browser sessie and navigation to Dashboard, and then back to Notes, Notes is also empty.
So now on all browsers sessions (two computers, multiple brands of browsers), Notes is not showing when clicking the icon. 
When on Dashboard: if I click on new note in the notes section, the new note is not appearing on my screen, but it does on my android device, so it is created.

- Android app works fine. 
- On nextcloud dashboard, the notes are shown normal

I am not sure if there was an update of notes last  night.

## Steps to reproduce
Hard to reproduce, since I'm still having the problem
1. click on the top menu notes icon
2. nothing appears
3. I can't install a previous version of notes. That might give more info.
Might be related to a new update
Might be related to hibernating a computer while working on an note (and note was not yet saved).

### Expected behaviour
Showing the normal screen with notes

### Actual behaviour
Empty screen (just the background with the nexcloud top menu)

### Screenshots
![image](https://github.com/nextcloud/notes/assets/16174035/4cebdb2c-c0f1-4226-910f-9b8776ee1110)

## Server
Please complete the following information.

- Notes app version: 4.9.1
- Nextcloud version:  27.3
- OS: Linux 4.18.0-513.5.1.el8_9.x86_64 x86_64
- Web server: 
- PHP version: 8.2.12
- Database: MySQL  10.3.39

**Nextcloud configuration:**

## Client
Please complete the following information.

- Browser (incl. version): I tried Chrome, Vivaldi and Edge
 - OS:  Windows 10

## Log files
```
[core] Fout: OC\User\NoUserException: Backends provided no user object at <<closure>>

 0. <<closure>>
    OC\Files\Node\Root->getUserFolder()
 1. /var/www/cloud.<DOMAIN>/html/lib/private/Files/Node/LazyFolder.php line 74
    call_user_func_array()
 2. /var/www/cloud.<DOMAIN>/html/lib/private/Files/Node/LazyRoot.php line 40
    OC\Files\Node\LazyFolder->__call()
 3. /var/www/cloud.<DOMAIN>/html/apps/groupfolders/lib/Versions/VersionsBackend.php line 73
    OC\Files\Node\LazyRoot->getUserFolder()
 4. /var/www/cloud.<DOMAIN>/html/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 72
    OCA\GroupFolders\Versions\VersionsBackend->getVersionsForFile()
 5. /var/www/cloud.<DOMAIN>/html/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 59
    OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder()
 6. /var/www/cloud.<DOMAIN>/html/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php line 43
    OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
 7. /var/www/cloud.<DOMAIN>/html/lib/public/BackgroundJob/Job.php line 81
    OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run()
 8. /var/www/cloud.<DOMAIN>/html/lib/public/BackgroundJob/TimedJob.php line 103
    OCP\BackgroundJob\Job->start()
 9. /var/www/cloud.<DOMAIN>/html/lib/public/BackgroundJob/TimedJob.php line 93
    OCP\BackgroundJob\TimedJob->start()
10. /var/www/cloud.<DOMAIN>/html/cron.php line 152
    OCP\BackgroundJob\TimedJob->execute()

at 2023-12-16T10:20:10+00:00
```
(The error below might be because I turned on my laptop.)
```
[index] Fout: TypeError: OCA\Notes\Controller\NotesController::__construct(): Argument #10 ($userId) must be of type string, null given at <<closure>>

0. <<closure>>
   OCA\Notes\Controller\NotesController->__construct()
1. /var/www/cloud.<DOMAIN>/html/lib/private/AppFramework/Utility/SimpleContainer.php line 84
   ReflectionClass->newInstanceArgs()
2. /var/www/cloud.<DOMAIN>/html/lib/private/AppFramework/Utility/SimpleContainer.php line 124
   OC\AppFramework\Utility\SimpleContainer->buildClass()
3. /var/www/cloud.<DOMAIN>/html/lib/private/AppFramework/Utility/SimpleContainer.php line 142
   OC\AppFramework\Utility\SimpleContainer->resolve()
4. /var/www/cloud.<DOMAIN>/html/lib/private/AppFramework/DependencyInjection/DIContainer.php line 494
   OC\AppFramework\Utility\SimpleContainer->query()
5. /var/www/cloud.<DOMAIN>/html/lib/private/AppFramework/DependencyInjection/DIContainer.php line 466
   OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
6. /var/www/cloud.<DOMAIN>/html/lib/private/AppFramework/App.php line 162
   OC\AppFramework\DependencyInjection\DIContainer->query()
7. /var/www/cloud.<DOMAIN>/html/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main()
8. /var/www/cloud.<DOMAIN>/html/lib/base.php line 1068
   OC\Route\Router->match()
9. /var/www/cloud.<DOMAIN>/html/index.php line 36
   OC::handleRequest()

GET /index.php/apps/notes/notes?pruneBefore=1702648912
from 172.20.16.242 at 2023-12-16T11:05:38+00:00
```

**Comment by dl-bone** [comment]
I have exactly the same behaviour as described, without hibernating a computer, but after updating notes.
Tried on Firefox, Opera and Edge on win10.

Notes app version: 4.9.1
Nextcloud version: 27.1.3

**Comment by GHBLoos** [comment]
After upgrading from 27.1.3 to NC 27.1.5 the problem seems solved.
