### ISSUE TITLE
Markdown: New list item makes scrollbar appear until text is put in

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/notes#119]
When you are in a list and press enter to get a new row with dash in front, a scrollbar is shown on the right until you put in text:
![screenshot from 2017-07-27 13-11-01](https://user-images.githubusercontent.com/925062/28667783-3e602752-72cd-11e7-8398-526a9fe0a601.png)

It only disappears when you write. Seems glitchy, happens for me on Firefox. @nextcloud/notes @nextcloud/design any idea?

**Comment by jancborchardt** [comment]
Ah, it seems that while you are in this mode of a new line being there, all rows below are shifted by one. If you click on a row below, the cursor will actually be one row further down, looking very strange. Seems like an issue in the library we use maybe? cc @Henni

**Comment by sellth** [comment]
This bug is very annoying and makes the app completely unusable if you don't know that the empty list item is the cause. It doesn't break if one creates a new sub-list (indented) item by the way.

**Comment by jancborchardt** [comment]
@nextcloud/javascript might be due to the markdown library used?

**Comment by tribut** [comment]
Possibly related: When you open a new list item by pressing enter in the middle of a list, the next bullet point is actually above the currently existing one. This becomes apparent when pressing space a few times, leading to two bullet points on a single line:

![screenshot from 2018-06-05 11-50-53](https://user-images.githubusercontent.com/719105/40968846-07e7e76c-68a6-11e8-8d56-02bc134bc12f.png)

Also, the cursor disappears until some text is added to the new list item.

**Comment by jakobroehrl** [comment]
The problem occurs on Firefox, Chrome is fine.
Please could you fix it? It's pretty irritating.
Thanks a lot!
