### ISSUE TITLE
Ctrl-S should trigger save of note, not open save dialog

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/notes#120]
The »Save website as« dialog is useless in this context. Rather we should do it like in the files_texteditor app, and make Ctrl-S simply force save the note.

**Comment by stefan-niedermann** [comment]
or we provide a download dialog for the current note as a txt or markdown file? maybe additional on ctrl+D?

**Comment by jancborchardt** [comment]
Separate issue for sure. :) Ctrl-S should simply save.

**Comment by jancborchardt** [comment]
Closing as duplicate of #113
