### ISSUE TITLE
Issue with markdown and copying

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/notes#121]
I just had the case that when I wanted to copy some text which had markdown in it (including lists), on paste only a `-` dash appeared. It was impossible to copy the text as whole and I had to copy it in 3 sections.

Maybe an issue with SimpleMDE?

**Comment by jancborchardt** [comment]
@nextcloud/notes any idea? Or does the issue not occur for you?

**Comment by korelstar** [comment]
No, can't reproduce that.

**Comment by jancborchardt** [comment]
Hmm, can’t reproduce it anymore either. :)
