### ISSUE TITLE
Notes incompatible with NC 28

### ISSUE THREAD

**Issue by monperrus** [nextcloud/notes#1253]
Notes has disappeared from my Nextcloud 28.0.x. The UI says it's incompatible.

How to fix that?

Thanks!

**Comment by joshtrichards** [comment]
It's definitely compatible with Server v28.

What version of the app are you seeing offered in the UI?

**Comment by joshtrichards** [comment]
I suppose something in #1193 is another possibility.

**Comment by monperrus** [comment]
yes, seems very much like #1193. After lots of tinkering and refresh for a couple of days, the app reappeared. thanks!
