### ISSUE TITLE
"Uncaught (in promise) TypeError: t is undefined" after updating to nextcloud 28.0.3 and latest notes

### ISSUE THREAD

**Issue by HolgerHees** [nextcloud/notes#1259]
Environment:
- nextcloud 28.0.3
- notes (latest version)
- firefox 124

After updating to the latest version I get the trace at the end (TRACE 1).

After that, the ui is not useable anymore. e.g. if I click on new note, nothing happens with a lot more exceptions.

For me it looks like a timing problem, because it does not happen always.

 (TRACE 1)
```
09:12:53.929 Uncaught (in promise) TypeError: t is undefined
    render editor.js:77
    createEditor editor.js:234
    loadTextEditor NoteRich.vue:89
    fetchData NoteRich.vue:79
    created NoteRich.vue:56
    VueJS 28
editor.js:77:2
    fetchData NoteRich.vue:79
    AsyncFunctionThrow self-hosted:857
    (Async: async)
    created NoteRich.vue:56
    VueJS 69
    init vue-router.esm.js:3005
    forEach self-hosted:203
    init vue-router.esm.js:3004
    updateRoute vue-router.esm.js:2414
    transitionTo vue-router.esm.js:2263
    confirmTransition vue-router.esm.js:2402
    r vue-router.esm.js:2084
    r vue-router.esm.js:2091
    Dt vue-router.esm.js:2095
    confirmTransition vue-router.esm.js:2396
    r vue-router.esm.js:2084
    r vue-router.esm.js:2088
    p vue-router.esm.js:2384
    h vue-router.esm.js:2162
    p vue-router.esm.js:2362
    r vue-router.esm.js:2087
    r vue-router.esm.js:2091
    r vue-router.esm.js:2091
    Dt vue-router.esm.js:2095
    confirmTransition vue-router.esm.js:2392
    transitionTo vue-router.esm.js:2260
    push vue-router.esm.js:2606
    push vue-router.esm.js:3036
    push vue-router.esm.js:3035
    routeToNote App.vue:215
    routeDefault App.vue:194
    loadNotes App.vue:137
    (Async: promise callback)
    loadNotes App.vue:130
    created App.vue:119
    VueJS 17
    <anonym> main.js:12
    <anonym> main.js:16
    <anonym> main.js:16
```

**Comment by HolgerHees** [comment]
here comes a small update.

If I open any other app (like the files app) and open afterwards the notes app, the bug is 100% reproducible

If I reload the notes app by pressing the browser reload button the bug does not happen

**Comment by arnowelzel** [comment]
I can reproduce this with NC 28.0.4 and Notes 4.9.4:

![image](https://github.com/nextcloud/notes/assets/6613614/0e5cad15-6908-4ac9-b021-449768dea641)

**Comment by HolgerHees** [comment]
I created a [fix for it](https://github.com/nextcloud/notes/pull/1264), but have not got any feedback since a month.

@arnowelzel I'm not sure if your bug is the same. The error trace looks different.

**Comment by arnowelzel** [comment]
> I created a [fix for it](https://github.com/nextcloud/notes/pull/1264), but have not got any feedback since a month.
> 
> @arnowelzel I'm not sure if your bug is the same. The error trace looks different.

Thanks for the fix @HolgerHees. Yes you're right, my trace looks different. I just did not realize this in the first place. We'll see.

**Comment by HolgerHees** [comment]
my fix is merged right now and will be available with the next release.
