### ISSUE TITLE
Filerun compatible 

### ISSUE THREAD

**Issue by horphi0815** [nextcloud/notes#1268]
Would be great to have webdav access to filerun.
Access specific notes folder, where all notes are stored like NC

**Comment by stefan-niedermann** [comment]
Notes is not required for WebDAV, everything is basically there. Use the Notes API to detect the base folder of your notes and then you cna use the Open Collaborative Services built in in Nextcloud.

https://github.com/nextcloud/notes/blob/main/docs/api/v1.md
https://docs.nextcloud.com/server/latest/developer_manual/client_apis/OCS/ocs-api-overview.html

Please fill in the issue template the next time, it is there for a reason.
