### ISSUE TITLE
A way to capture elements for the web

### ISSUE THREAD

**Issue by bepolymathe** [nextcloud/notes#127]
Hi,

Thanks for your job. I would like to know if it is expected that one can capture text (in .md or .txt format) from the browser (firefox or chromium like)?
If not, what solutions do you already use? Extensions? External application?
Thank you

**Comment by jancborchardt** [comment]
@bepolymathe sorry for the late reply – you can of course just copy text from websites and manually paste it. If anyone wants to write an extension for it or integrate it into an existing extension, they are very welcome. :)
