### ISSUE TITLE
Sort on Note title and Category

### ISSUE THREAD

**Issue by ericloyd** [nextcloud/notes#1286]
Why does most of Nextcloud think I want to sort by relative date (yesterday, last week, two months ago, etc) instead of by absolute date (2024-04-25, 2024-03-05, 2023-06-05, etc) or by the title of the note?

I'm using Nextcloud Hub 7 (28.0.1) with Notes 4.10.0 and I can see no way to do that.  At least, not in the web interface, which is what I'm interested in using.  I despise Google's Gmail for the same reason - search is great but sometimes you need to sort because you don't know what you're looking for.  Apparently, I can't even reverse-sort on date (and "scroll to the bottom" doesn't count) so there doesn't seem to be any real sorting to speak of anyway.

I also can't see any way to set categories in the web interface, despite there being an "Uncategorized" category to start with.

What am I missing?

**Comment by joshtrichards** [comment]
For sorting enhancement thread, see #613. 

> I also can't see any way to set categories in the web interface, despite there being an "Uncategorized" category to start with.

The 3 dot menu next of each note let's you change categories.
