### ISSUE TITLE
Artifacts in the settings window

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/notes#1289]
After the update from 27.1.x to 28.0.5 I found that there are some exhaustive artefacts of icons in the settings window, see below:

![image](https://github.com/nextcloud/notes/assets/5199030/ed5a16be-5ad6-4c70-8caf-5d38da5fe624)

**Comment by juliushaertl** [comment]
Fixed in 37db99ba4e692f4dcae6eb2b0ded45a5bbfcfd84
