### ISSUE TITLE
Possible bug on Notes app version 4.10.0

### ISSUE THREAD

**Issue by souovan** [nextcloud/notes#1298]
### Steps to reproduce
1. Access Notes application
2. Try to create new or delete an existing one

### Expected behavior 
The application should create and exibihit the new note or delete the existing one

### Actual behavior 
Nothing happens in both cases, making it necessary to forcefully refresh the page to show the change

### Host OS 
Running on:
```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

#### Nextcloud AIO version 
Nextcloud AIO v8.2.0

#### Current channel 
latest

**Comment by Szwendacz99** [comment]
Can confirm, this happens for me as well. You probably should change the issue title to more descriptive of this exact case.

**Comment by fitus85** [comment]
Create works for me, but I can delete a note, it disappears, reload the page or select other note and note is back again.
