### ISSUE TITLE
Offset Error for `#` Chars in Headings

### ISSUE THREAD

**Issue by ocelotsloth** [nextcloud/notes#130]
Markdown provides that you can either use one set of hashes leading a header line, but it also says you can have the same number of hashes trailing.

I don't personally see why one would use this particular feature of the markup language, but to stay in spec it might be worth finding a way to disable the offset for the second set of hashes.

![2017-08-28](https://user-images.githubusercontent.com/9255772/29794112-a2f8f24c-8c14-11e7-8b2f-93c1079c9621.png)

**Comment by korelstar** [comment]
Fixed by @DMuckerman in #208
