### ISSUE TITLE
Disabling URL previews in text files doesn't fully disable the behaviour

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/notes#1307]
When I disable the URL preview setting in the config file, and then paste a URL on an empty line in an .md file, nextCloud still adds additional lines to it and seems to do some processing on the URL despite the disabling.

I don't get the preview, sure, but I don't want it to touch the URL or the formatting AT ALL. I just want it to paste the text _as text_, maybe make it blue and underline as a URL... but _that's it_

As it is now adding a URL adds obnoxious and problematic white space I was hoping to get rid of, and it also does processing that slows me down when I'm pasting a bunch of URLs back to back to back.

So to me this is a bug, can we please have this behaviour improved?

**Comment by juliushaertl** [comment]
This has been addressed with Nextcloud 29 where the URL will be a link by default and the link preview can be switched on case by case, implemented in https://github.com/nextcloud/text/pull/5399

**Comment by BloodyIron** [comment]
> This has been addressed with Nextcloud 29 where the URL will be a link by default and the link preview can be switched on case by case, implemented in [nextcloud/text#5399](https://github.com/nextcloud/text/pull/5399)

Okay that might work better for me. Will I need to change the config file where I previously "disabled" the functionality in it? I'll def have to try this out though, thanks! :D
