### ISSUE TITLE
[Request] Support for basic TeX-like formulas like a_i, x^2

### ISSUE THREAD

**Issue by Rainer-K** [nextcloud/notes#132]
When making notes for studying, I often write short formulas like `e = [e_1, e_2, ... , e_d] in R^d`. It would be nice to have them styled them to subscript and superscript, as this would increase the readability when it gets more complex.

**Comment by jancborchardt** [comment]
We are reliant on the code editor we use for this: [SimpleMDE](https://simplemde.com/). Please open the issue in their repository at https://github.com/sparksuite/simplemde-markdown-editor/issues (which although unfortunately does not seem so maintained anymore :\ )
