### ISSUE TITLE
Icons in settings modal deplaced

### ISSUE THREAD

**Issue by bentuna** [nextcloud/notes#1328]
## Steps to reproduce
1. Open Nextcloud Notes.
2. Open the settings modal by clicking on "Notes settings".
3. See that the icons of the feature items are too far right.

### Expected behaviour
The icons are positiones left of the text.

### Actual behaviour
The icons are under the text.

### Screenshots
![Bildschirmfoto 2024-07-15 um 16 23 41](https://github.com/user-attachments/assets/04ff7637-c82b-4244-b325-7b630469c6c1)

## Server

- Notes app version: 4.10.0
- Nextcloud version: 28.0.7

**Comment by StefInP** [comment]
Same issue for me with : 
- Notes app version: 4.10.0
- Nextcloud version: 29.0.3

**Comment by joshtrichards** [comment]
Fixed in 37db99ba4e692f4dcae6eb2b0ded45a5bbfcfd84
