### ISSUE TITLE
Single line note with Chinese or full shape punctuation breaks Activity app

### ISSUE THREAD

**Issue by outsinre** [nextcloud/notes#133]
Reproduce:

>Nextcloud 12.0.1

1. On the web interface, add a new note that:
   1. Just a single line;
   2. Contains Chinese punctuation (i.e. `，`)
2. Go to Activity app, all activities are gone. Only a circle there.

   ![activity gone](https://i.imgur.com/BalcUgF.png)

   Nextcloud log:

   ```
   "app":"PHP","method":"GET","url":"\/ocs\/v2.php\/apps\/activity\/api\/v2\/activity    \/all?format=json&previews=true&since=0","message":"TypeError: Argument 2 passed to OC\\Activity\\Event::setSubject() must be of the type array, null given
   ```

3. Go Files app - Notes, find the new added note. It does **NOT** have a file extension (neither *\.txt* nor *\.md*).

   Click on the new note, it reports:

   ![internal error](https://i.imgur.com/zJPya7M.png)

     I cannot even delete the note file. It re-appears if I refresh the Files app.
4. Just check the database, *oc_notes_meta* contains 387 rows while Notes app show 390 files.

**Comment by korelstar** [comment]
Ouh, that's bad. Could you please test this with the latest version (from branch `master`) from GitHub? We had a similar problem (see #93) which is already fixed (see #125). However, there is currently no official release containing the fix, yet.

Alternatively, you could do the changes from #125 manually on your installation.

**Comment by outsinre** [comment]
@korelstar Just a reminder, I've just updated the issue context. More useful info was added.

I will try that fix code to see.

**Comment by outsinre** [comment]
@korelstar The #125 do fix the Notes app issue.

Unfortunately, the *broken* Activity cannot be reversed.

**Comment by korelstar** [comment]
Great! You should publish a new release soon due to this bug, @Henni.

@outsinre Please try to
- remove the problematic file manually from the filesystem
- rescan the files using `occ files:scan`
- remove the respective entry from the activity table in the database
