### ISSUE TITLE
Notes not showing in webbrowser. 

### ISSUE THREAD

**Issue by mg1067** [nextcloud/notes#1337]
When i Click on Notes in menubar it does not change to the notes. It is not showing the notes.
But this is only in Webbrowser. In every webrowser I tested. Chrome, Firefox, Chromium, Edge....
I use Nextcloud 29.04.1.

**Comment by stefan-niedermann** [comment]
Please fill out the issue template, it is there for a reason.

**Comment by joshtrichards** [comment]
Closing. Feel free to create a new Issue when you're able to fill out the bug report template.

P.S. Keep in mind this isn't a general technical support channel. If you need help troubleshooting your environment, the community help forum is a good channel for that sort of thing - https://help.nextcloud.com
