### ISSUE TITLE
WYSIWYG view and editor

### ISSUE THREAD

**Issue by eemantsal** [nextcloud/notes#138]
I think that the majority of common mobile devices users don't understand why do they need to learn a markup language instead just selecting some text and tappin some button to format it, like they accustom to do in their text processors or other mobile notes apps, instead of having to deal with all those `*`, `#`, `===`, etc, which seem to them like "yet another geeky and obscure FLOSS thing". It would be also handier and quicker in many cases (doing a couple of quick modifications here and there) even for, more or less, "Markdown literate users".

I want to state clear that **I'm not proposing switching from Markdown** format for the notes **to HTML** at all. I'm convinced that besides the advantages of MD's simplicity and the possibility to edit MD files in almost any digital text write capable thing, MD is potent enough for the needs of at least 95% of users, that only want some basic text formatting, media, principally images, embedding and perhaps chechkboxes for tasks and such. I don't even believe that the vast majority does ever use tables nor code text formatting, which are already present in the MD specifications, so there's no need to go HTML at all, IMHO.
I suggest, **only**, an interface improvement that might make the Nextcloud notes much more accessible to common users and handier in some occasions for those who already know how to compose texts in Markdown. A more graphical interface so users can edit their notes without learning Markdown syntax and can see the results inmediately on a single view, instead of having to switch from a code view to the definitive view and switch back to the code view to continue editing, and then swit... and so on _ad infinitum_.
This should be **optional**, elegible by the user, maybe just tapping a button that enables/disables WYSIWYG mode or some switch in the app's settings... I don't know, I'm not a developer; I'm sure you can think of much better implementations than I do.

There are a lot of web apps that work this way, in WYSIWYG, I mean. See, for example, [Telegra.ph](http://telegra.ph/), [Pen Editor](https://github.com/sofish/pen) or [this plugin for MediumEditor](http://linkesch.com/medium-editor-insert-plugin/). All of them work in Markdown and permit the users to edit the text with floating toolbars and WYSIWYG single view mode with no interface clutter. I repeat that this should be configurable so each user can choose with edition mode do they prefer. I don't try to force happy MD coders to go visual eh? :P I myself prefer plain MD above WYSIWYG, but most of my acquitances don't -and I'm sure most of yours neither ;) -, and that keeps them away from Nextcloud and in the "claws" of Google, Evernote, MS...

**Comment by exekutive** [comment]
I second this.
I'm currently using Quickoffice for Android to edit Nextcloud synced docx files as way of keeping notes.
I would much rather use something simple and lightweight like this app, but the cryptic syntax is the only thing keeping me from doing so. I want to see beautiful, formatted, easy to read text. Not a bunch of symbols.

**Comment by camilasan** [comment]
I think the Notes app should be kept simple.

**Comment by camilasan** [comment]
Maybe this kind of feature could add as optional.
cc @jancborchardt

**Comment by stefan-niedermann** [comment]
I disagree. This has often been discussed and in my opinion this app is for reading / writing, not formatting.

NextNotes might be an alternative that fits the needs better.

**Comment by exekutive** [comment]
According to the author, NextNotes is inactive since Jan '17
https://github.com/janis91/nextnotes/blob/master/README.md

**Comment by jancborchardt** [comment]
Issue for the context-based formatting popover opened at https://github.com/nextcloud/notes/issues/200 - closing this.

**Comment by manuee** [comment]
I know this is an old issue, but it the first that came up when i googled, so adding this info here in case others land here like me.

This issue will most likely be fixed by this: https://github.com/nextcloud/notes/issues/331 :crossed_fingers:
