### ISSUE TITLE
Too much wasted space in list of notes

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/notes#1383]
When using the webGUI for Notes, the left side which lists the notes wastes so much vertical space on presentation. Take a look:

![image](https://github.com/user-attachments/assets/9cb8b3ff-d9bf-43e2-9e8d-a455726f67d6)

The area above and below "Workout notes" and "Groceries" is effectively in total triple the actual space used by the text itself.

This leads to very few items visible on-screen, despite using higher resolution monitors (such as 2560x1440 in my case).

This really is an obnoxious, wasteful, and inefficient design. And I for one would really want to see a lot less of a gap above and below the name of each note in the left list. I'm not saying the gap should be eliminated, and I'm not even sure what I might consider the ideal amount. But maybe half to start?

Also, this is with the latest version as of writing.

Either way, as it stands this really is pretty yucky.

**Comment by user8446** [comment]
In the meantime try the Custom CSS app and reduce it to your liking... I had to do the same with the Deck app

**Comment by BloodyIron** [comment]
Yay thanks!
