### ISSUE TITLE
Add customization of storage path

### ISSUE THREAD

**Issue by opa-rudi** [nextcloud/notes#1398]
It would be nice if you can specify the storage path in the cloud or on local android system.

**Comment by stefan-niedermann** [comment]
# Notes server app

There are <kbd>Settings</kbd> at the bottom left of the Notes app, as in most other apps. Clicking it allows you to adjust the storage path:

![Image](https://github.com/user-attachments/assets/f2cdc94b-b9b0-4763-a115-444df35eb8c3)

# Notes Android
Clicking on your profile avatar in the top right, then click <kbd>Manage accounts</kbd>, tap the ⚙ icon and choose "Set folder" (or similar wording):

![Image](https://github.com/user-attachments/assets/530250fb-43b0-4713-a860-c2b8b0ec5f66)

The *local* storage path can't be adjusted as the Notes Android app does not store the notes as files, but in a database for performance (and other) reasons.

**Comment by opa-rudi** [comment]
Argh. My fault. Thx! :)
