### ISSUE TITLE
App Certificate is not valid.

### ISSUE THREAD

**Issue by namir88** [nextcloud/notes#140]
Hi,
since upgrading my owncloud to 10.0.3.3 there is a problem with the code identity, The correct output is:

- notes
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- App Certificate is not valid.

Can I fix this issue or du you have to do this?

Roman

**Comment by camilasan** [comment]
Do you still have this problem @namir88?

**Comment by namir88** [comment]
Thanks for the reply. I don´t use the notes app since I had the problem. So I don´t know if it´s still exists.

**Comment by jancborchardt** [comment]
Ok, thanks for the update – will close the issue then. :)
