### ISSUE TITLE
Using database  instead of files and directories 

### ISSUE THREAD

**Issue by sircode** [nextcloud/notes#1406]
Is there a reason you are working with files for title and content and directories as "categories" and not simply a database?

**Comment by stefan-niedermann** [comment]
It is a tradeoff that has been discussed way more than once here.

Long story short: A file system avoids vendor lock in, avoids proprietary formats, allows the easiest possible export, requires absolutely no knowledge, ot works with the default Nextcloud desktop sync clients, it ensures interoperability with nearly each editor the user prefers without requiring to implement a specific API or format and a few others.

Drawbacks can be performance (if done wrong), missing features like tags (which may be achieved using frontmatter).

As a blocker for https://github.com/nextcloud/notes/issues/299 there has been mich discussion there.
