### ISSUE TITLE
[Request] Make favorite and delete icon available on hover (not only on active note)

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/notes#142]
Make favorite and delete icon available on hover (not only on active note): 

I think it would be more convenient to make the delete and favorite (or any other actions) icons available on hover (or show them for all notes at all times), so that you don't have to first click on a note in order to delete or favorize it.

**Comment by jancborchardt** [comment]
Yes – while of course it should also still show for the active note, also showing it on hover is a good enhancement.
