### ISSUE TITLE
Feature Request: Easy way to change font

### ISSUE THREAD

**Issue by kpuljek** [nextcloud/notes#143]
After typing out some notes in my native language, Croatian, I noticed that some characters don't work properly in the default font used in notes. (screenshot original.png)

When I change the code (code.png) to something else like Fira Sans, then it looks okay. (fira-sans.png)

Unfortunately, I didn't find a simple way to change the font, I don't want to mess around with code and break something in the future. Any ideas?

![original](https://user-images.githubusercontent.com/9851336/31967792-35a41bb8-b90f-11e7-81da-4f733beee97e.png)

![code](https://user-images.githubusercontent.com/9851336/31967789-33d91fd6-b90f-11e7-8748-88f48377659e.png)

![fira-sans](https://user-images.githubusercontent.com/9851336/31967785-30a5849e-b90f-11e7-89b3-afb1c1c94a92.png)

**Comment by jancborchardt** [comment]
@kpuljek that’s very strange, Open Sans has these letters and it works here:
![screenshot from 2018-06-05 11-29-40](https://user-images.githubusercontent.com/925062/40967616-ca313622-68b3-11e8-83ef-0e73254722d6.png)

Could you clarify which browser you use, and if it works in a different browser or device?

**Comment by jancborchardt** [comment]
Closing because the recent move to SimpleMDE seems to habe fixed this. :)

**Comment by MicNov** [comment]
Hi, this is not fixed. Problem is, that you need to include font with parameter latin-ext, not only base Open Sans. It would be nice to specifiy (in the theme settings) just Google font url in one form input e.g. "https://fonts.googleapis.com/css?family=Roboto&amp;subset=latin-ext" and global font name like "Roboto" in second input. Do it and you'll make a lot of users happier ;-).

**Comment by korelstar** [comment]
That sounds like this is a general Nextcloud issue and not specific to the Notes app. Can you confirm this?

If this is the case, then please open a new issue in the nextcloud/server repository, since we can't fix it from this app.

**Comment by jancborchardt** [comment]
Yup, the core issue is https://github.com/nextcloud/server/issues/11299 – thanks @MicNov @NovaMi for opening! :)

**Comment by alex-milanov** [comment]
Yeah but it would also be good to be able to change the font family (I use FiraCode for some ligatures), colors and background switch etc ...

**Comment by stellarpower** [comment]
I'd like to be able to use a Monospace font - Markdown is meant to be easy to read in both source and rendered views. Nextcloud notes doesn't support tables yet, however, if I generate a table in markdown format, it is sitll pretty legible without being rendered. The problem however, is that the default font isn't monospaced.
![image](https://user-images.githubusercontent.com/5004545/149656571-6822f37d-03bd-4418-af6d-2462db8684e0.png)

I have had to enter the table into a code section, which then makes it not so convenient for scrolling. The current choice makes sense for many users, but I used to use Joplin a lot for taking notes, and for me and anyone using notes a lot for technical work, programming notes, it's certainly a lot easier to edit the sources in a monospace font. Even for general notes, I think it makes life easier if everything lines up nicely whilst you're typing it out. To start with, I think a simple drop-down entry on the toolbar, with a stylised 'f' icon, and offering a limited choice of variations of the main fonr theme (serif, sans, monospace), would be a good way of doing this. To offer support perhaps for arbitrary, enterring a webfont URL would be a good way of enabling this, so the work is client-side.

**Comment by jancborchardt** [comment]
> To offer support perhaps for arbitrary, enterring a webfont URL would be a good way of enabling this, so the work is client-side.

@stellarpower you can already do this using the [Custom CSS app](https://apps.nextcloud.com/apps/theming_customcss). :)
