### ISSUE TITLE
App-Error: Request failed: unacceptable content-type: text/html

### ISSUE THREAD

**Issue by Qixuga** [nextcloud/notes#147]
May be its a but on the API/Server-Site but my Cloundnotes shows always after synchronisation the errormessage of inacceptable content type:

Request failed: unacceptable content-type: text/html

May be i try to overwrite the content typ via htaccess ;-)
Or directly to php-code if i know the suggested one:
`header('Content-type: application/json');`

can you fix it?
thank you very much for your great work!

ps: ups - i knew this wasn't the app repo...

**Comment by korelstar** [comment]
I don't think that's the source of your problem. The app sends the correct content-type header. However, the server sends `text/html` if an unhandled exception happened on the server. Therefore, please check your server's `nextcloud.log` for related log entries and post an excerpt of them, here.

**Comment by jancborchardt** [comment]
Closing because the issue is quite old. If it still happens, feel free to open another issue with the contents of your nextcloud.log. :)

**Comment by Qixuga** [comment]
OK, thank you!
