### ISSUE TITLE
Unable to create note with russian 'х' letter

### ISSUE THREAD

**Issue by blshadow** [nextcloud/notes#149]
For example try to create a note:

> йцукенх

Instead, a note with the text "йцукен?" is created and cannot be removed or modified.

Error message in the log:
> {"reqId":"Wf@UwH8AAAEAADllxGEAAAAS","level":2,"time":"2017-11-05T22:46:24+00:00","remoteAddr":"192.168.0.2","user":"sergey","app":"core","method":"PUT","url":"\/index.php\/apps\/notes\/notes\/111633","message":"normalizing failed for \"\/sergey\/files\/Notes\/\u00d0\u00b9\u00d1\u0086\u00d1\u0083\u00d0\u00ba\u00d0\u00b5\u00d0\u00bd\u00d1.txt\"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/62.0.3202.75 Safari\/537.36","version":"12.0.3.3"}

Nextcloud version: 12.0.3
Notes version: 2.3.1

**Comment by korelstar** [comment]
There was a similar issue (see #93) which was fixed (see #125) but not yet released. Could you please try, if the patch fixes the problem for you?

If not, please try also #138. This fixes problems with 4byte characters and some MySQL installations.

**Comment by blshadow** [comment]
Thanks, #125 fixes the problem.

**Comment by korelstar** [comment]
@Henni please release a bugfix release together with the other to-be-merged PRs.

**Comment by Henni** [comment]
I'll do that during the next weekend.
I'm currently concentrating on the contacts app and this app suffers from it.
