### ISSUE TITLE
RFE: Tomboy import

### ISSUE THREAD

**Issue by MagicFab** [nextcloud/notes#151]
I am migrating a rather large Tomboy account (2K+ notes) to NextCloud and would have liked to have a Tomboy import option.
The [Grauphel](https://apps.owncloud.com/content/show.php/grauphel+-+Tomboy+sync+server?content=166654) extension was used in the ownCloud server we're moving out from, and apparently it would still work on NextCloud. However TomDroid and Grauphel haven't been update for some time now and I'd prefer to move this data to the (native) Notes app in Nextcloud. There is also a dedicated Notes application in F-Droid for this purpose, so I think adding and "Import" functionality in Notes would still be useful.

In Tomboy from a GNU/Linux system, there is and "export to HTML" functionality that produces a directory filled with HTML files (one for each note). Subdirectories are created for each "Notebook" previously created. Notebooks could be imported as Categories.

**Comment by codejp3** [comment]
I just made a topic about integrating NC Notes with XFCE4-Notes. With a little tweaking (such as converting the html files to txt files), you could run a script to take care of the whole thing for you.
https://github.com/nextcloud/notes/issues/152

**Comment by traumschule** [comment]
[Tomboy_NG](https://wiki.gnome.org/Apps/Tomboy) can sync all notes to local folder with the format:
> 13aa53ab-7231-43e4-8a42-584faa190576.note

```
<U+FEFF><?xml version="1.0" encoding="utf-8"?>
<note version="0.3" xmlns:link="http://beatniksoftware.com/tomboy/link" xmlns:size="http://beatniksoftware.com/tomboy/size" xmlns="http://beatniksoftware.com/tomboy">
  <title>2017</title>
  <text xml:space="preserve"><note-content version="0.1">TITLE
...
</note-content></text>
  <last-change-date>2017-10-16T10:27:21.7376260+02:00</last-change-date>
  <last-metadata-change-date>2017-10-16T10:27:21.7512450+02:00</last-metadata-change-date>
  <create-date>2017-10-16T09:05:09.1141360+02:00</create-date>
  <cursor-position>12</cursor-position>
  <selection-bound-position>12</selection-bound-position>
  <width>450</width>
  <height>360</height>
  <x>0</x>
  <y>20</y>
  <open-on-startup>False</open-on-startup>
</note>
```
With the [current rewrite in progress](https://github.com/tomboy-notes/tomboy-ng), it is possible, to integrate a sync with [nextcloud notes](https://github.com/nextcloud/notes)'s [REST API](https://github.com/nextcloud/notes/wiki/API-0.2), [grauphel](https://apps.owncloud.com/content/show.php/grauphel+-+Tomboy+sync+server?content=166654), [tomdroid](https://github.com/tomboy-notes/tomdroid) and [gnote](https://wiki.gnome.org/Apps/Gnote) from the beginning. (Maybe even for [gnome 2.28](https://wiki.gnome.org/ThreePointTwentyseven))

**Comment by jancborchardt** [comment]
Easiest would actually be if Tomboy simply supports exporting all your notes as txt files. Then you could simply move them into the »Notes« folder of your Nextcloud and you’re done. :)

Otherwise there’s the Graphel sync app https://apps.nextcloud.com/apps/grauphel by @cweiske

**Comment by MagicFab** [comment]
Agreed now Grauphel works in NC, thanks for the follow up!
