### ISSUE TITLE
Linux Native Desktop Note Sync - Working Hack & Info (Ubuntu & XFCE4)

### ISSUE THREAD

**Issue by codejp3** [nextcloud/notes#152]
I've really been racking my brain trying to figure out how to sync NC Notes with a native desktop note app. The current options such as QOwnNotes are great for what they are, but they're way too bloated for a simple text notepad. After searching and seeing the abundance of dead-ends everyone was running into with getting native OS note programs to sync with NC, I thought I'd share a quick-n-dirty solution that I came up with, and also post some general info to help you figure out other options for other systems/programs.

NC Handles Notes:
1.) as plain-text files
2.) with a .txt extension
3.) in the NC root /Notes folder
4.) Server handles the changes to files and maniest.xml files (in subfolders)
5.) Only interfaces are the Web interface, or overbloated (for my purposes) alternative note apps.

I'm using Ubuntu with the XFCE desktop environment. After looking for a native OS program that closest matches what NC does and wants/requires, I was pleasantly surprised to find the XFCE has a plugin called XFCE4-Notes that gave the perfect simple note-taking/editing app, and integrated it into the application bar/taskbar.

XFCE4-Notes Handles Notes:
1.) as plain-text files
2.) without any extension
3.) in a hidden local / share session folder
4.) Program handles file changes, asks to reload if external changes (such manual edits) are detected.
5.) Convenient and integrated OS-level interface, and any text editor can access the plain-text files.

Trying to make a bridge between those two, here's what I came up with:

Make a symbolic link from the "Notes" folder NC created for your notes, linked to the location of where the native Note app saves the plain-text entries.
`ln -s /home/username/Nextcloud/Notes /home/username/.local/share/notes/
`

XFCE4-Notes has "groups" of notes that act like categories and each category is assigned a new folder. The above command creates a link called "Notes" to the /home/username/.local/share/notes/ directory, so XFCE4-Notes recognizes a "group" called Notes. The "Notes" "folder" will actually be a symlink to the actual Notes folder of NC that syncs.

That handles the sync'ed Notes between the desktop and the cloud, but there is a problem that NC only recognizes notes (plain-text documents) with a .txt extension, and XFCE4-Notes saves them without any extension. There's also an issue with filenames. NC Notes uses the first word of each note as the file name, and XFCE4-Notes just calls them "Note", "Note 2", "Note 3" and so on. To match what NC is doing, we can do it in a single line command and add a crontab entry to run automatically at a given time interval:
`crontab -e
`

and add the following line (set to run every 5 minutes):
`*/5 * * * * find /home/username/Nextcloud/Notes -type f -not -name "*.*" -not -empty -exec awk 'FNR == 1 { system("mv \"{}\" \"/home/username/Nextcloud/Notes/"$1".txt\"") }' "{}" \;
`
In plain words, the above line says:
Every 5 minutes, 
find any file in the NC Notes dir, 
that does NOT have an extension, 
and is NOT empty (for blank/empty note compatibility in XFCE4-Notes).
For any that are found, 
pull the first word from the file contents,
and rename the file as FIRST_WORD.txt

There's one more issue that I haven't been able to resolve yet -  Illegal filenames with funky characters. I've tried several different ways with awk and sed in the above one-liner command, without success.  It works with illegal filenames (NC doesn't seem to care), but XFCE4-Notes doesn't display the filename if it has non-friendly characters (but it does show the file contents). If anyone has suggestions, I'm open to it. I'll post an update if I come up with a working one-liner for crontab. If all else fails, I may revise the approach and make a sh script, and have cron execute the script instead of the command directly. It'll give me more flexibility with my command to add sanitization much easier. I'd really like a one-liner like I've been trying for though.

Except for the minor illegal filenames issue (only affects the filename displaying within XFCE4-Notes), everything else seems to be working without any problems.

Feel free to use any of this as a starting point for your own native desktop note application syncing with NC. I'd love to hear if anyone has success with other native desktop note apps, or comes up with a better method than mine.

**Comment by BloodyIron** [comment]
Considering Notes as of today is just syncing the Notes folder at the root of your account, just plonk content into that folder when synced to your computer. Why make it harder than that?

**Comment by codejp3** [comment]
Why? 
So that it happens automatically in the background and I never have to plonk anything anywhere. 
Convenience and consistency. That's why.

**Comment by BloodyIron** [comment]
It's already automatic.

**Comment by codejp3** [comment]
Right, but I treat documents like documents and notes like notes.

A document is a specific file with specific content. They're sync'd automatically using NC regular folder sync and may be txt doc or any other file format appropriate for the content. These often have spcific programs associated with the file type and tend to have larger content.

A note is like a post-it sticky note. I use a note program that's integrated into my OS desktop to take notes. They are often only a single word, or a short sentence, or a brief list. Perhaps they end up as a full blown document later which the document syncing above is perfect for, but for quick and useful notes integrated within my active workspace (OS desktop), the NC Notes app has no options or ability to integrate with any desktop program like Tomboy, or XFCENotes, and so on. I'm simply piggybacking off of the NC Notes app folder that you mention automatically syncs. I simply "merged" the NC Notes folder and the dektop notes program folder so that I can use my desktop program for notes, and let NC take care of the background syncing to the cloud. 

I hope that makes more sense?

More complicated, YES. But for someone like me, I use a desktop notes program every day because of how it integrates into my desktop, while I would NEVER use web-based notes program. This is my solution until the NC Notes app integrates with desktop notes programs.

**Comment by jancborchardt** [comment]
For desktop, we simply recommend using the desktop client: https://nextcloud.com/install/#install-clients

For Android, there’s the great Nextcloud Notes app: https://github.com/stefan-niedermann/nextcloud-notes/#nextcloud-notes by @stefan-niedermann and contributors. And you can also view notes simply using the Nextcloud Android app.

For iOS we would love for @phedlund to revive the Nextcloud Notes iOS app! :) But you can also use the Nextcloud iOS app.
