### ISSUE TITLE
When using greek characters as a title, app crashed

### ISSUE THREAD

**Issue by teras** [nextcloud/notes#154]
I was trying to add all of my notes, by hand (copy & paste) through the wen interface. Most (if not all) my notes were written with greek letters. Unfortunately at some point, the system had an error, and now I am unable to add/rename update notes any more.

For some strange reason, the note that was broken should be named `Πουλακίδα` but got trimmed and now it displays `Πο?` with noway to either delete it, rename it or anyhow change it. All others note up to then, had no issues.

I tried to delete all the .txt files from the sync'ed directory, including the offending one, it worked as a file sync, but when I opened the notes app again, this notorious entry appeared again.

What should I do? How can, at least, reset the system and remove this broken ghost entry?

**Comment by korelstar** [comment]
Please see #93 for a similar issue (and the description how to delete that file). This was fixed by #125, but there hasn't been a new release since then.
@Henni Please release the new version!
