### ISSUE TITLE
Ability to undo changes (recovery from backup)

### ISSUE THREAD

**Issue by sosed213** [nextcloud/notes#156]
Often you have to create and view notes on the go. From accidental pressing, extra characters are entered in the notes or the text is erased altogether (yesterday I lost so important an important note). Through the browser, sometimes, after editing, the data is not saved, and sometimes the entire note becomes empty. Especially it happens when you change the first line.

Please make it possible to create daily or weekly backups. Text files take up very little disk space.

Perhaps when opening a note, it will be backed up and stored until the note opens again. This is necessary to return the latest version of the note.

**Comment by jancborchardt** [comment]
Versions of Notes are already created through the files_versions app in Nextcloud. In the 3-dot menu of a note we could simply expose that to roll back to previous versions. :)

cc @nextcloud/designers

**Comment by jancborchardt** [comment]
Actually already reported at https://github.com/nextcloud/notes/issues/144 – closing this as duplicate. :)
