### ISSUE TITLE
Spell check not available through browser or app

### ISSUE THREAD

**Issue by kowalabearhugs** [nextcloud/notes#163]
The app seems be lacking a spell check feature. Additionally, the browser spell check doesn’t seem to be available in the edit window. 

Is it possible to enable either?

**Comment by jancborchardt** [comment]
This seems related to our use of Codemirror. Maybe there is an extra package we need to enable? @nextcloud/notes

**Comment by fazlerabbi37** [comment]
@jancborchardt do this [comment](https://github.com/codemirror/CodeMirror/issues/3356#issuecomment-118171434) help?
