### ISSUE TITLE
Request: Integrate Tagspaces webclipper with Nextcloud Notes

### ISSUE THREAD

**Issue by sunjam** [nextcloud/notes#169]
[Based on Electron, fully open source, works with latest firefox and chrome](https://github.com/tagspaces/browser-extensions), [should be usable as maintainer mentions here](https://github.com/tagspaces/browser-extensions/issues/1). This tool could also benefit [Nextcloud Bookmarks #442 ](https://github.com/nextcloud/bookmarks/issues/442) by allowing one browser extension to create related Nextcloud Notes and Nextcloud Bookmarks.

- Saving complete web pages as HTML and MHTML(chrome only) files
- Saving selected part of a web pages as HTML file
- Saving a screenshot of the visible area of the current tab as PNG file
- Saving a bookmark as URL files

**Comment by jancborchardt** [comment]
We deal with plain text, not with HTML or images. So it seems to best integrate it into the Bookmarks app instead, as has also been reacted to by the maintainer at https://github.com/nextcloud/bookmarks/issues/442#issuecomment-366077131 :)
