### ISSUE TITLE
Request: display comments within Nextcloud Notes as annotations

### ISSUE THREAD

**Issue by sunjam** [nextcloud/notes#170]
My request is for comments on note-files to be viewed as annotations within Nextcloud Notes.  [Issue #776 on Qownnotes](https://github.com/pbek/QOwnNotes/issues/776)

**Comment by sunjam** [comment]
Can Collabora access the Nextcloud Notes directory and comments?  That is very heavy application.

**Comment by jancborchardt** [comment]
Collabora is LibreOffice, online. It works with the Open Document Format, and not plain text or Markdown.

Closing this as wontfix – sorry but we can’t do everything. :)
