### ISSUE TITLE
Add support for Mermaid flowcharts and diagrams like in the Markdown editor

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/notes#174]
Hello,

it would be great if this app could support Mermaid for diagrams and flowcharts like the Markdown editor does: https://github.com/icewind1991/files_markdown#create-graph-using-mermaidjs

Link to the upstream project: https://github.com/knsv/mermaid

**Comment by Larsene** [comment]
What a great idea !!

**Comment by jancborchardt** [comment]
It seems that those flowcharts have a very different text vs graphical representation:
https://github.com/icewind1991/files_markdown#create-graph-using-mermaidjs

Also, it seems a very specialized feature for a _Notes_ app. I don’t think this is something we should work on, sorry. :\ We have very limited resources, and duplicating functionality which already exists in the Markdown app is not something we should spend time on.
