### ISSUE TITLE
Is there an iOS notes app to upload to NextCloud?

### ISSUE THREAD

**Issue by rwat1** [nextcloud/notes#176]
Hi all,

I was wondering if there is an iOS notes app that can upload/integrate with NextCloud Notes app?

**Comment by stefan-niedermann** [comment]
From the Readme.md file (first paragraph): 

> currently, there are notes apps for Android and iOS

https://github.com/owncloud/notes-iOS-App

**Comment by splitt3r** [comment]
The app works very nice and is definitely worth the money 👍

**Comment by stefan-niedermann** [comment]
@rwat1 please feel free to reopen this issue if you have further questions :-)

**Comment by rwat1** [comment]
@stefan-niedermann 

I don't know how to install from GitHub onto my iOS iPhone device

Do I go to the AppStore? What is the name of the app?

**Comment by stefan-niedermann** [comment]
Well, i am not an apple user, but the apl is called "Nextcloud", obviously.... a quick google search shows up with https://itunes.apple.com/de/app/nextcloud/id1125420102?mt=8

I am sure the search on your iPhone App store works as well :)

**Comment by splitt3r** [comment]
I think he means https://itunes.apple.com/de/app/cloudnotes-owncloud-notes/id813973264?mt=8 :grin: does he?

**Comment by rwat1** [comment]
Wow, I never knew you can edit text files inside the "NextCloud app", I always thought I had to pay for a separate app. Thank you Stefan and all!

**Comment by bjo81** [comment]
@splitt3r Well, no. It does not display subdirectories (e.g. as categories) and has no markdown preview. So it's a pity that @stefan-niedermann app is not available for iOS.

**Comment by splitt3r** [comment]
It does display markdown for me :grinning: but you are right it's far behind the Android app.
