### ISSUE TITLE
CSS media query for printing style

### ISSUE THREAD

**Issue by AquaL1te** [nextcloud/notes#179]
At the moment the markdown format is lost when you're just left with txt files. It would be nice if there was an option to convert a Notes document into a PDF or directly call a window to send it to a printer. Thanks!

**Comment by jancborchardt** [comment]
@AquaL1te do you know if such a Markdown-to-PDF library exists, ideally in Javascript (or PHP)? Any help in researching is welcome. :)

**Comment by AquaL1te** [comment]
@jancborchardt, something like [this](https://github.com/alanshaw/markdown-pdf/blob/master/README.md)? There are probably many more, this one was at the top of my Google search.

**Comment by jancborchardt** [comment]
Seems like it requires Node, which we can’t require. Needs to be either PHP or JS. :)

**Comment by AquaL1te** [comment]
What about: https://github.com/nickurt/markdown-pdf

**Comment by jancborchardt** [comment]
@AquaL1te is from 2015, seems unmaintained and says »work in progress«. :\ But thank you for the effort in finding a library! :) That’s the first step.

**Comment by jancborchardt** [comment]
@stefan-niedermann right, that’s a great call! :) Would probably only need few rules to remove the header and notes list from view. :) Setting as good first issue.
