### ISSUE TITLE
Navigation sidebar not accessible on small screens

### ISSUE THREAD

**Issue by korelstar** [nextcloud/notes#18]
On small screens, the navigation sidebar (with the list of notes) is hidden by default. Instead, a Hamburger icon is shown. However, when clicking on this button, nothing happens (NextCloud 10 and ownCloud 9.1; tested with Firefox 45 ESR on Desktop and Android 6 on Mobile). This makes the notes app completely unusable on, e.g., mobile devices.

In the past, a respective issue existed already (owncloud/notes#55), but it was closed in favor of a core issue (owncloud/core#9838) which is still open. However, there was also a pull request (owncloud/notes#61) by @jancborchardt with the intention to fix the issue. But at least for me, the button doesn't work in current `master`.

**Comment by jancborchardt** [comment]
Hmmm, which hackery in the app prevents the button from working? ;) cc @Henni any idea?

**Comment by jancborchardt** [comment]
(Oh and yes, Bernhard said in the past that Snap.js sucks a bit but unless you come up with a better solution for the sidebar we’ll use that. :)
