### ISSUE TITLE
Note file name changes when Android ownCloud Notes app syncs

### ISSUE THREAD

**Issue by camilasan** [nextcloud/notes#180]
How to reproduce:
- I have created a bunch of files with the extension .md years ago...
- I have been using them to take notes in my Desktop
- Today I decided to try the Notes app
- I opened the notes app in the web interface and my .md files were already listed there (even my github recovery codes were there)
- I installed the ownCloud Notes app (v0.13.1) in my phone
- I edited a note in my Android (7.0) phone. 
e.g. the file name of the note is called todo.md as I gave ages ago...and the content starts with '# what is happening here', so that is what I see in the notes list view in my phone.
- Sync (server NC 13)
- Check the file in the browser.
- The file name changed to '# what is happening here' just like the notes list view in my phone.

The problem: I did not expect that my old files would have the name changed. They were files I created, they were not created by the Notes app. And yet, why I can not give my notes a name? I find hard to visualize/find the notes in the list by their contents.

I am not sure if this is a problem here or in the Android app. 
cc @stefan-niedermann

**Comment by camilasan** [comment]
I just renamed my files properly in the app by starting the files with # title. Doesn't feel that bad after doing it. Is there a better way to avoid surprises? Read the documentation before? :)

**Comment by stefan-niedermann** [comment]
This is a server side issue since the android app only uses the API (which does not even allow to change the file extension)

Regards

**Comment by camilasan** [comment]
Thanks for the input @stefan-niedermann. Besides this 'issue', I am really enjoying to use the server and the Android app :)

**Comment by stefan-niedermann** [comment]
References #24
