### ISSUE TITLE
Fit text horizontally

### ISSUE THREAD

**Issue by bszente** [nextcloud/notes#182]
The notes on large (FullHD) screens are auto-wrapped at **47em** leaving a large portion of empty white screen on right side. This is caused by the following line in [notes.css](https://github.com/nextcloud/notes/blob/7e1d827e5c36876132d49fe2156990690458eb99/css/notes.css#L118):

    max-width: 47em;

Please remove this **static width** limitation and enable _fit-to-width_ behavior.

**Comment by elpraga** [comment]
Could this be related to https://github.com/nextcloud/notes/issues/177 ?

**Comment by bszente** [comment]
I don't know if this is related to your issue. Can you please test, if removing this line from CSS fixes the rendering on Android?

**Comment by elpraga** [comment]
I just tried that. It didn't fix my problem. Thanks for your help!
