### ISSUE TITLE
Improve notification of "decryption failed exception"

### ISSUE THREAD

**Issue by KimTheFirst** [nextcloud/notes#186]
Firstly, this error was triggered by myself corrupting one of the files whilst doing something, so the corruption itself is not the issue. 

The issue here is that if this was indeed caused by the corruption of a single file within the notes app, the app now does not function at all. Maybe the file should show with ("decryption failed") or something?

**Comment by KimTheFirst** [comment]
This is because the exception "DecryptionFailedException " is being thrown by the encryption library, and notes is not catching that exception.

It would be possible to catch the exception DecryptionFailedException in notesservice.php and then do something with it. I can see how this might encourage users to ignore what might potentially be a very serious problem, but personally I think perhaps having the app working with errors might be better than having it fail completely.

Line268:
```
    private function getFileById ($folder, $id) {
        $file = $folder->getById($id);
```

**Comment by KimTheFirst** [comment]
I think there are some other potential exceptions too & definitely a few other places they would have to be caught / used.

**Comment by korelstar** [comment]
Thanks for your analysis, @KimTheFirst !

Providing an error message to the frontend would be the best (see https://github.com/nextcloud/notes/pull/184#issuecomment-380893531 for some ideas on how to present error messages), but I think it's fine to start with catching the Exceptions and writing something meaningful to the log. Could you help us with implementing this, @KimTheFirst ? A pull-request is very appreciated :-)

**Comment by jancborchardt** [comment]
Copying over my comment from https://github.com/nextcloud/notes/pull/188#issuecomment-387909164 :)

> can you adjust the style so it is not a modal, but an emptycontent view? Like in Files when you have an empty folder, with a nice icon (icon-edit), a h2 (»Error loading note«) and a short error description.
