### ISSUE TITLE
Add text interaction posibilities in read mode

### ISSUE THREAD

**Issue by godfuture** [nextcloud/notes#189]
To make the notes app work better for shopping lists, do-Tos and so on, we could add the possibility to interact with the interpreted text in read mode. In read mode we do not modify the content, but maybe use the node.

For example: to strike through a pullet point on a list, we could allow the user to select these items.

This feature would not hurt the core function of the read mode, which is I guess displaying the syntax interpreted.

There are many more applicable ways to make us of this feature.

**Comment by stefan-niedermann** [comment]
Nope, just copy it. But i already can tell you that this needs to be done in the RxMarkdown library upstream. There is currently no wy to implement it in the app directly.

See https://github.com/yydcdut/RxMarkdown/issues/40
