### ISSUE TITLE
Remove outdated loading.gif

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/notes#19]
Do we need that gif still? It’s the old look and also core has it with icon-loading since some versions. :)

**Comment by korelstar** [comment]
It's still in use and shown, when a note was changed until auto-saving has completed. But I think that it can be replaced with another version or with a respective icon from core.

**Comment by jancborchardt** [comment]
As talked about with @Henni it’s quite strange we show that every time you type something. It makes the app seem very slow. It should only be shown when saving takes considerably longer than normal.

And yes, when used it should be used from core. Simply use the class `.icon-loading` :)

**Comment by jancborchardt** [comment]
This is fixed since some time, we use the new loading spinner. :)
