### ISSUE TITLE
Use file name instead of first line as title [$20]

### ISSUE THREAD

**Issue by godfuture** [nextcloud/notes#190]
Using the first line as title has the drawback that information is displayed redundant. As space on screen is valuable, on mobile devices even more, it makes sense to expose the title separately from the body and persist it as filename. This way there is no longer redundancy. This still works well with basic text editor and files app syncing to desktop.

**Comment by stefan-niedermann** [comment]
https://github.com/nextcloud/notes/issues/116
https://github.com/owncloud/notes/issues/198

**Comment by godfuture** [comment]
Understood. But I would want to constructively disagree:

- Microsoft and others still know a "title" for their notes. The title is on the very top and underlined.
- Files have names and this app is file based. Why not letting the title to be the file name. In most cases the title is a good summary.
- File name and first line showing totally the same content is also not very reasonable.

To be honest, I guess there is more PRO than CON for it...

**Comment by natrius** [comment]
I do also disagree. A separate field for a Title would be nice, it's always bugging me. Using the title as filename is perfectly fine. :)

**Comment by jancborchardt** [comment]
Especially with the mobile app around and the issues with it:
- Single note widget shows redundant first line
- Changing first line can cause sync issues
- Viewing a note shows the filename already in the header

… I’m thinking again about if it might be a good idea to split first line and file name.

----------------------

We could still handle it exactly like now on note creation: By default the first line you type is used as filename.

But once created, when you change the first line, the note title is not changed. For that you have to use the 3-dot menu in the note list to »Change filename«.


What do you think @nextcloud/notes @Henni @camilasan @stefan-niedermann?

**Comment by korelstar** [comment]
I'm fine with that, although I see other things that would be more important. But if someone implements this for the frontend, I'm willing to change the 3rd-party (`notesapicontroller`) in order to be compatible to both type of apps: using the old style (no separate title) and the new style (separate title).

**Comment by frederiiiic** [comment]
I'm sometimes editing my *.txt files on my computer (NotePad++), sometimes with the web app, and sometimes with the [nextcloud-notes](https://github.com/stefan-niedermann/nextcloud-notes) app. And i'm frequently expériencing some troubles with file names.

**Comment by korelstar** [comment]
@frederiiiic Which kind of troubles do you are talking about?

**Comment by frederiiiic** [comment]
For exemple when i'm changing the first line, the nextcloud app change the name of the file. And if i've changed it on the txt file of my computer, this will be deleted.
I just have to known that but i find this logic weard. Using file name, look more familiar, natural and simple to me, but maybe with differents using it's not...

**Comment by godfuture** [comment]
Maybe we might introduce a slider to decide whether the first line to be interpreted as filename or not?!

**Comment by stefan-niedermann** [comment]
*IMHO*: An option would require to maintain two completely different views. We better should decide for one default view and only provide this.

**Comment by godfuture** [comment]
As this project seems dead (no commits for quite a long time), I want to let you know how I solved it. With two apps, you get close to the Nextcloud nodes app. Install [Denkzettel](https://play.google.com/store/apps/details?id=com.silli.notizen&hl=de) and [Folder Sync](https://play.google.com/store/apps/details?id=dk.tacit.android.foldersync.lite). You have to add your Nextcloud as webdav server and add a sync folder.

With the correct options set, your experience comes close to the Nextcloud solution. Good luck!

**Comment by korelstar** [comment]
Thanks for sharing your experiences :-)

However, this project is far away from being dead. Instead, it undergoes a big modernization, see #290. After that, this issue is one of the issues with higher priority. You can speed this up by increasing the bounty on this, bye the way.

**Comment by godfuture** [comment]
What is the state? Is this still considered for any of the milestones?

**Comment by korelstar** [comment]
You're right, I'm adding this to the next milestone. For the GUI, this will depend on #373 (and therefore on the next release of `nextcloud-vue`); for the third-party API this depends on #311.

**Comment by trevorparsons** [comment]
The main issue for me with the first line of the note being used for the filename is that this very often results in a filename which contains spaces. This is obviously not optimum for when one wants to operate on the file in the command-line interface.

**Comment by srjlover** [comment]
Nextcloud should implement and allows all devs to add the title of notes .. I mean that looks so ugly without title man

**Comment by michaelnew** [comment]
I know it's not much, but I threw another $10 at this. Maybe @godfuture could update the title?

**Comment by korelstar** [comment]
Okay, people. The implementation is finished (see #474), so please test if it is like you expected (checkout the branch `edit-title` and run `make` to compile JavaScript). I will write the documentation for the new API version in the meanwhile.
