### ISSUE TITLE
Checklists

### ISSUE THREAD

**Issue by theel0ja** [nextcloud/notes#191]
Add checklists like this:

- [ ] hello world
- [x] foobar
- [ ] lorem ipsum

Currently, they aren't implemented:
![image](https://user-images.githubusercontent.com/5832930/39147032-3129b532-4741-11e8-8592-b07ef1a7aab4.png)

In the app, they seem to be implemented:

[![](https://lh3.googleusercontent.com/rcZRd5ob_ZbhmwoPkpJtUp1NR5FKTq2jPlB1IBxBYr58-VjHr2hj1HHyOraZJFr4ZeM=w2556-h2632-rw)](https://play.google.com/store/apps/details?id=it.niedermann.owncloud.notes)

**Comment by jancborchardt** [comment]
Closing as duplicate of https://github.com/nextcloud/notes/issues/117, let’s continue there.
