### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by joewashear007** [nextcloud/notes#192]
Great app, I use it all the time. 

What do you think of the idea of having a dark theme? It makes it easier on the eyes 😉

**Comment by stefan-niedermann** [comment]
I think there has been a discussion in one of the other apps where the result basically was like "this should be done in the core so alle apps can take advantage of it".

Aside: The Android client will feature a dark mode in the next version (v0.17.0).

**Comment by jancborchardt** [comment]
Yes, this is something which will be done across Nextcloud. There is no specific coloring done in this app (or at least where there is, there should not be, only using core variables).

Also cc @skjnldsv @juliushaertl regarding theming.

**Comment by skjnldsv** [comment]
I'm pretty sure a dark theme should be done in core and not per app :)
Reference nextcloud/server#1692

**Comment by jancborchardt** [comment]
@skjnldsv yep, that’s why I was saying it will be done across Nextcloud. :) Closing hence.

**Comment by q2apro** [comment]
Hello from 2023 (five years later). 

That's one of the reasons I do not use NC Notes. No dark theme!

**Comment by juliushaertl** [comment]
You might want to give it a try again since both Nextcloud as well as the notes app have a decent dark mode these days ;)
