### ISSUE TITLE
Note "saving failed!"

### ISSUE THREAD

**Issue by Steinardo** [nextcloud/notes#194]
### Steps to reproduce
1. Open or create a note
2. Write something

### Expected behaviour
Note should be saved

### Actual behaviour
Notes show a fault message "saving failed" and new nameless (New note(XX)) are created. When acessing the note.txt via the Nextcloud file browser I can save the note.

### Server configuration

**Operating system**:
Asustor NAS with ADM 3.1.1.RGG1 (linux based)
Kernel 3.4.26

**Web server:**
Apache
Version = 2.4.5

**Database:**
Type: sqlite3
Version: 3.14.1

**PHP version:**
Version: 5.6.30
Memory Limit: 512.0 MB
Max Execution Time: 3600

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 10.0 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**
Yes from ownCloud

**Where did you install Nextcloud from:**
Asustors own App Store

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Homepage is not reachable

RR_INVALID_RESPONSE

**List of activated apps:**

Enabled:
  - activity: 2.3.2
  - calendar: 1.4.1
  - comments: 1.0.0
  - contacts: 1.5.1
  - dav: 1.0.0
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notes: 2.3.2
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.4
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "oco3uhihv22l",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***,
            "192.168.0.125"
        ],
        "datadirectory": "\/volume1\/Web\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/192.168.0.125\/nextcloud",
        "dbtype": "sqlite3",
        "version": "9.1.0.16",
        "logtimezone": "UTC",
        "installed": 1,
        "mail_smtpmode": "php",
        "loglevel": 0,
        "appstore.experimental.enabled": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Webdav on the smartphone

### Client configuration
**Browser:**
Google Chrome Version 66.0.3359.117 (Offizieller Build) (64-Bit)
Safari Version 11.1 (13605.1.33.1.2)

**Operating system:**
macOS High Sierra 10.13.4 (17E199)

#### Web server error log
empty

#### Nextcloud log (data/nextcloud.log)

<Error  PHP Call to undefined method OC\DB\Connection::supports4ByteText() at /volume1/Web/nextcloud/apps/notes/service/notesservice.php#224

#### Browser log
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by korelstar** [comment]
The notes app uses the method `OC\DB\Connection::supports4ByteText()` which seems to be available from Nextcloud 11 upwards, only. We use it to fix a problem with 4-byte-characters.

A workaround would be to do this check only on installations with Nextcloud >= 11. Then, the above mentioned bug will appear again on older installations.

Another option is to drop support for Nextcloud 10, which is also reasonable. However, I think this would kick out ownCloud completely.

**Comment by Steinardo** [comment]
Migrated to Nextcloud 12. Notes work as ist should.
