### ISSUE TITLE
User docs could use an overhaul. [Rant warning: Tiny, and (mostly) constructive rant].

### ISSUE THREAD

**Issue by svein83** [nextcloud/notes#196]
**WOW!** I'm sorry, but if you _don't want_ users, or if you want new users to _give up_, then this is a great way to do it.

I was looking for the manual for the plugin and it's main web-ui. Usage info like formatting and keyboard shortcuts.

This info is **critical** for new users. People who don't search code-repos for key-bindings in source-files for a living (or for fun), will just get confused and pissed-off.

All places where a man-page should exist, there are just links to the [Git-wiki](https://github.com/nextcloud/notes/wiki), the [Git-repo](https://github.com/nextcloud/notes), or the [plugin page](https://apps.nextcloud.com/apps/notes). **All** links I find (where users would look), go to one of those 3 pages.

**None of those 3 pages actually tell a _user_ anything:**
- [Plugin page](https://apps.nextcloud.com/apps/notes): Links to project-repo, and project-wiki on GitHub.
- [Wiki page](https://github.com/nextcloud/notes/wiki):
Just a list of 3 apps on several app-stores, and some API-info for devs.
- [Repo page](https://github.com/nextcloud/notes): A long page with requirements, and a short paragraph says something about supporting Markdown, some more API info, and telling users to go to the project-wiki for more user and developer info.

So this is actually just a giant, useless, and annoying, circle-jerk of hyperlinks to most users! Nothing about **how** text is formatted, not what flavor of MD syntax, and **Not even a hint at where to find the info.** 

MD has no "one technical de-facto standard" except [John Gruber](https://en.wikipedia.org/wiki/John_Gruber)'s own [syntax](https://daringfireball.net/projects/markdown/syntax)-page, and MD has no **real** *keyboard shortcuts standard* specified for for editors.

A user manual has to be available if you want users. If it's just a simple list of named links with short explanations doesn't matter, as long as it takes the guesswork and annoyances away. A faq could be a great way to limit the number of issues submitted too.

**Comment by svein83** [comment]
## Nevermind.
I had a look at the source, and noticed that the text editor is **SimpleMDE**.

### For anyone else looking for this info:
That means the **keyboard shortcuts** are here: [link](https://github.com/sparksuite/simplemde-markdown-editor/blob/master/README.md#keyboard-shortcuts)

And a table with the the supported **syntax** is here: [link](https://simplemde.com/markdown-guide)

**Comment by svein83** [comment]
I'd rather have a help-icon in the web-app. A default note could okay, but
could get deleted, and then someone might get stuck looking for info
again...

Maybe some info on how to sync with PCs on different OSes?

What applications can talk to the API out of box?

Den tor. 10. mai 2018, 10:21 skrev Niedermann IT-Dienstleistungen <
notifications@github.com>:

**Comment by jancborchardt** [comment]
@svein83 a proposal is at https://github.com/nextcloud/notes/issues/200 to introduce a formatting popup which will do away with the need for an intro to Markdown formatting, but simply do it for people.
