### ISSUE TITLE
Weird editor behaviour when using Copy & Paste on text in Markdown syntax

### ISSUE THREAD

**Issue by RotterMartin** [nextcloud/notes#199]
Strange editor behaviour when entering text (in Markdown syntax) and doing copy&paste. Text is pasted to wrong positions, or gets lost, or parts of text can't be selected with cursor any more.
Reproduce: Just enter some text using ## and * syntax, and do some edits, copy & paste, etc.,

**Comment by dest4** [comment]
I experienced the problem when there were empty items in the list.
```
- blah blah
- 
* Where is Bryan ?
```
`* Where is Bryan ?` is *displayed* just below `- blah blah` (2nd line), but is *clickable* and *selectable* at the 3rd line.

The effect can accumulate in a document, making the edition very difficult and confusing.

Workaround: ensure there are no empty items.
