### ISSUE TITLE
Saving a note is very slow

### ISSUE THREAD

**Issue by heyarne** [nextcloud/notes#202]
Hello,
I recently noticed a slowdown of Notes – a very small note (content just "# hello world") takes approximately 4 seconds to save. I used to be able to type and have it saved in < 1 second (never measured but it felt very snappy). Unfortunately I don't know when exactly this issue started to pop up, so I know this isn't the best bug report but I'll try to provide as much information as I can.

System specs:

* Digital Ocean Small Droplet, 1GB RAM
* Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-127-generic x86_64)
* Nextcloud 13.0.2
* Notes 2.3.2

```
$ free -m
              total        used        free      shared  buff/cache   available
Mem:            992         309         112          19         570         486
Swap:          1023         111         912
$ php --version
PHP 7.0.30-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May  2 2018 12:43:14) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.30-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
$ mysql --version
mysql  Ver 15.1 Distrib 10.0.34-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            487M     0  487M   0% /dev
tmpfs           100M  3.0M   97M   3% /run
/dev/vda1        25G  6.7G   17G  29% /
tmpfs           497M     0  497M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           497M     0  497M   0% /sys/fs/cgroup
tmpfs           497M     0  497M   0% /run/shm
/dev/sda         50G   30G   18G  64% /mnt/nextcloud
tmpfs           100M     0  100M   0% /run/user/0
```

```
$ ping my.server.address
PING my.server.address (xxx.xxx.xxx.xxx): 56 data bytes
64 bytes from xxx.xxx.xxx.xxx: icmp_seq=0 ttl=53 time=28.556 ms
64 bytes from xxx.xxx.xxx.xxx: icmp_seq=1 ttl=53 time=26.155 ms
64 bytes from xxx.xxx.xxx.xxx: icmp_seq=2 ttl=53 time=26.245 ms
64 bytes from xxx.xxx.xxx.xxx: icmp_seq=3 ttl=53 time=27.480 ms
64 bytes from xxx.xxx.xxx.xxx: icmp_seq=4 ttl=53 time=26.261 ms
64 bytes from xxx.xxx.xxx.xxx: icmp_seq=5 ttl=53 time=26.797 ms
```

Any idea what might cause this?

**Comment by heyarne** [comment]
Unfortunately I could only test up to `12ba128`, for earlier commits I was getting an update notification. Every commit between `master` and `12ba128` showed the same behavior. The `PUT` request is also considerably slower than all other requests:

![](https://transfer.sh/gvdvs/Screen%20Shot%202018-06-05%20at%2020.39.51.png)

**Comment by jancborchardt** [comment]
@nextcloud/notes @nextcloud/javascript any idea what could cause this?

**Comment by skjnldsv** [comment]
Slow server?
What is your page loading time?
How many cpu cores do you have?

**Comment by heyarne** [comment]
It's the smalles available DigitalOcean droplet; 1 CPU core, 1 25GB SSD for the OS / Nextcloud core and one 50GB SSD for data. I don't know at which frequency the CPU runs. For comparison, uploading a 1,3MB photo takes about twice as long (~8s), while being two orders of magnitude bigger than a note. Isn't saving the note essentially doing the same, storing a text file and writing some metadata?

Load times (avg over 5 tests):
Files:  
* DOMContentLoaded: 1.866 s
* load: 3.76 s
Notes:
* DOMContentLoaded: 0.8 s
* load: 2.15 s

**Comment by skjnldsv** [comment]
Yeah, it's probably coming from this then :/
Have you all performances settings set up? Caching, http2... etc etc?

**Comment by skjnldsv** [comment]
Do you use the contacts app ?

**Comment by heyarne** [comment]
Yes. Full list of apps:
```
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.5
  - dav: 1.4.6
  - encryption: 2.0.0
  - end_to_end_encryption: 1.0.5
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - metadata: 0.6.0
  - news: 12.0.3
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - previewgenerator: 1.0.9
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - deck
  - documents
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - tasks
  - unsplash
  - user_external
  - user_ldap
```

**Comment by skjnldsv** [comment]
What time usually take a contact edit?

**Comment by heyarne** [comment]
Here's a screenshot of multiple edits:
![](https://transfer.sh/nPkb2/Screen%20Shot%202018-06-06%20at%2011.08.14.png)

**Comment by skjnldsv** [comment]
Hum, so it's not coming from the server I guess.

**Comment by heyarne** [comment]
Is there any way for me to profile a request? See how much time is spent in one method? I mean if nothing else I could probably add log requests in the right places, but I don't know anything about the source code of neither Nextcloud nor the Notes app.

**Comment by skjnldsv** [comment]
Clicking the request, you should have a Delay/timing tab where the different waiting states should be displayed :)

**Comment by korelstar** [comment]
You could add some logger calls (see https://docs.nextcloud.com/server/13/developer_manual/app/logging.html) with timestamps it's message in order to debug this. As a start, the method `update(...)` in the file `service/notesservice.php` would be interesting: Please add timestamp logs at the beginning of this method and at the end (directly before `return`). If there is a large difference, then you could add more logger calls at other positions, in order to find the source of this delay.

**Comment by heyarne** [comment]
This is my `update` method:
``` php
    /**
     * Updates a note. Be sure to check the returned note since the title is
     * dynamically generated and filename conflicts are resolved
     * @param int $id the id of the note used to update
     * @param string $content the content which will be written into the note
     * the title is generated from the first line of the content
     * @param int $mtime time of the note modification (optional)
     * @throws NoteDoesNotExistException if note does not exist
     * @return \OCA\Notes\Db\Note the updated note
     */
    public function update ($id, $content, $userId, $category=null, $mtime=0) {
        $this->logger->info('Start of update', ['app' => $this->appName]);
        $notesFolder = $this->getFolderForUser($userId);
        $file = $this->getFileById($notesFolder, $id);
        $this->logger->info('After getFileById', ['app' => $this->appName]); 
        $folder = $file->getParent();
        $title = $this->getSafeTitleFromContent($content);


        // rename/move file with respect to title/category
        // this can fail if access rights are not sufficient or category name is illegal
        try {
            $currentFilePath = $this->root->getFullPath($file->getPath());
            $fileExtension = pathinfo($file->getName(), PATHINFO_EXTENSION);
            $this->logger->info('After setting $fileExtension', ['app' => $this->appName]); 

            // detect (new) folder path based on category name
            if($category===null) {
                $basePath = pathinfo($currentFilePath, PATHINFO_DIRNAME);
            } else {
                $basePath = $notesFolder->getPath();
                if(!empty($category)) {
                    // sanitise path
                    $cats = explode('/', $category);
                    $cats = array_map([$this, 'sanitisePath'], $cats);
                    $cats = array_filter($cats, function($str) { return !empty($str); });
                    $basePath .= '/'.implode('/', $cats);
                }
                $this->getOrCreateFolder($basePath);
                $this->logger->info('After getOrCreateFolder', ['app' => $this->appName]); 
            }

            // assemble new file path
            $newFilePath = $basePath . '/' . $this->generateFileName($folder, $title, $fileExtension, $id);

            // if the current path is not the new path, the file has to be renamed
            if($currentFilePath !== $newFilePath) {
                $file->move($newFilePath);
                $this->logger->info('After $file->move', ['app' => $this->appName]);
            }
        } catch(\OCP\Files\NotPermittedException $e) {
            $this->logger->error('Moving note '.$id.' ('.$title.') to the desired target is not allowed. Please check the note\'s target category ('.$category.').', ['app' => $this->appName]);
        } catch(\Exception $e) {
            $this->logger->error('Moving note '.$id.' ('.$title.') to the desired target has failed with a '.get_class($e).': '.$e->getMessage(), ['app' => $this->appName]);
        }

        $this->logger->info('Before putContent', ['app' => $this->appName]); 
        $file->putContent($content);
        $this->logger->info('After putContent', ['app' => $this->appName]); 

        if($mtime) {
            $file->touch($mtime);
            $this->logger->info('After file->touch', ['app' => $this->appName]); 
        }

        $this->logger->info('End of update', ['app' => $this->appName]);
        return Note::fromFile($file, $notesFolder, $this->getTags($id));
    }
```

and this is the log output I get:

Info | notes | End of update | 2018-06-26T13:09:00+0200
-- | -- | -- | --
Info | notes | After putContent | 2018-06-26T13:09:00+0200
Info | admin_audit | File written to: "/Notes/Disco Disco Fusion Fusion.txt" | 2018-06-26T13:08:55+0200
Info | admin_audit | File updated: "/Notes/Disco Disco Fusion Fusion.txt" | 2018-06-26T13:08:55+0200
Info | notes | Before putContent | 2018-06-26T13:08:55+0200
Info | notes | After setting $fileExtension | 2018-06-26T13:08:55+0200
Info | notes | After getFileById | 2018-06-26T13:08:55+0200
Info | notes | Start of update | 2018-06-26T13:08:55+0200

So something happens after actually writing the file and `putContent` returning. I unfortunately don't have time to investigate this further right now... is it correct that the File object is coming from `lib/private/Files/Node/File.php`?

**Comment by korelstar** [comment]
Any news on this? Is this issue still occurring (please re-test with the latest release)?

**Comment by heyarne** [comment]
After updating to Nextcloud 14.01 / Notes 2.4.2 this seems to have been solved. :) The `POST` / `PUT` requests now take around 150ms for creating or updating a note. I'll close this, thanks!
