### ISSUE TITLE
Meta-Issue: Created some milestones

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/notes#205]
Just as a meta-discussion-issue :) – you might have seen we now have some milestones:
https://github.com/nextcloud/notes/milestones

It's to roughly prioritize the issues a bit better. I went through all issues, closed a lot of invalid ones, tagged them and also put them in the milestones according to either if they are more of a **fix/issue** (to be focused on first) or a **feature/enhancement** (second priority), and then of course all other issues outside of milestones (low priority, or whenever someone picks it up).

Feedback on this is very welcome @nextcloud/notes @korelstar @Henni @camilasan @stefan-niedermann :)

**Comment by korelstar** [comment]
Thanks for you efforts, @jancborchardt !  👍 

I think it's a good starting point. Hoping, that we will find more time and/or become more people to work on those issues.

**Comment by korelstar** [comment]
We have done much work in the meanwhile, so I think we can close this issue (which is more an information than an issue). The milestones are still alive ...

**Comment by jancborchardt** [comment]
Seems that there’s 2 different models now though? https://github.com/nextcloud/notes/milestones one with version numbers, and one with M1, M2? Better to stick with just one approach. :)

**Comment by korelstar** [comment]
Yeah you're right. I think your milestones were too optimistic. My milestones with version numbers reflect what I really plan to do and what is realistic to realize (small steps).

I would remove your old milestones then.

**Comment by jancborchardt** [comment]
@korelstar cool! I agree semantic versioning milestones are much better for organization. :+1:
