### ISSUE TITLE
Export Notes

### ISSUE THREAD

**Issue by 8sd** [nextcloud/notes#209]
I have many notes written in Markdown. Sometimes I need to have them as PDF, currently I use some online markdown to pdf render service.

I'd love to do this inside of Nextcloud it self.

**Comment by stefan-niedermann** [comment]
Hi, please read the recent comments at this issue: https://github.com/nextcloud/notes/issues/179

Might that be a solution?

**Comment by 8sd** [comment]
Yes, I think so.
If not, I will reopen the issue in due time.

**Comment by Mte90** [comment]
I saw that now print styles are supported but not everyone use Chrome that include the pdf exporter.
It is possible to add a button that let to download a pdf?

**Comment by stefan-niedermann** [comment]
Firefox supports exporting as a PDF file, too. Alrernatively you can installl any pdf printer e.g. [PDF Creator](https://www.chip.de/downloads/PDFCreator_13009777.html)

**Comment by Mte90** [comment]
You are right also Firefox support printing as pdf...😅
