### ISSUE TITLE
Search function shows results only after restarting screen

### ISSUE THREAD

**Issue by danjde** [nextcloud/notes#212]
Hi Friends!
I know that this issues seems very funny, but it's real!
I'm using "CyanogenMod 12.1-20150518-UNOFFICIAL-s3ve3g" (without GAPS) on Samsung GT-I9301I,
if I perform a term search, something moves quickly, but then all the notes appear on the screen. I just wait 30 seconds (the timeout time of the display) and at the display resuming appears the list of files correctly filtered by the search term.
Same behavior manually locking and unlocking the display.

I don't aspect a solution for me around this issue, only notify you. 
If you want more info tell me.

I will certainly be updating the firmware in a few months and I will let you know around this issue..

Many thanks!

Davide

**Comment by stefan-niedermann** [comment]
Hey, do you mean the android app? If so, please reopen the issue in https://github.com/stefan-niedermann/nextcloud-notes because this repo is only for the server part / web app :)

Regards

**Comment by danjde** [comment]
Hoops! Sorry! :-)
Thanks again!

Ciao!

**Comment by stefan-niedermann** [comment]
No problem :) You're welcome.
