### ISSUE TITLE
Enable Travis-CI (again)

### ISSUE THREAD

**Issue by korelstar** [nextcloud/notes#217]
We had some problems with Travis, and we were not able so solve them (see #52). Therefore, I've proposed to disable Travis until we solve these problems (see #136).

Today, I found some issues in our app's code and fixed them (see #215 and #216). However, these problems should have been found earlier, if we had Travis still enabled: these issues can be detected using `xmllint` resp. `occ app:check-code`. However, the unsolved problems mentioned above are in the test cases using `phpunit`.

Therefore, I propose to re-enable Travis for this repository. Then I will update the `.travis.yml` in order to execute some basic tests without the phpunit test cases. I think, this should work and would be helpful.

@Henni @MorrisJobke

**Comment by MorrisJobke** [comment]
Done.

**Comment by korelstar** [comment]
Jippie, thanks! We're on again ... :-)
