### ISSUE TITLE
Crash when selecting

### ISSUE THREAD

**Issue by SqueeZen** [nextcloud/notes#224]
Hello,

For several version of this great app, when I make a long press to select text, the two cursors appear at the beginning of the note. When I want to extend the selection, the application systematically crashes (Unfortunately, "Notes" Has Stopped ...)

I'm using a Xperia Z3C (D5803) with the latest official ROM available (Android 6.0.1).

Thank you in advance and have a good summer!

**Comment by stefan-niedermann** [comment]
Hi, may i ask whether you are talking about the android app or the web app?

**Comment by SqueeZen** [comment]
Oops, sorry, problem occurs on Android only.

**Comment by stefan-niedermann** [comment]
please reopen the issue at stefan-niedermann/nextcloud-notes/issues thx :)
