### ISSUE TITLE
Add edit/preview toggle

### ISSUE THREAD

**Issue by phsc84** [nextcloud/notes#23]
Sometimes you just want to read notes. Then it is more convenient if you can read it as formatted text without the whole markdown "noise".

The current implementation (simplemde branch, not yet merged) always shows the edit mode. This way I don't get why I need the Notes app. Because this is more or less the same as editing the notes with the default Nextcloud texteditor.

**Comment by phsc** [comment]
Related to the pull request "Switch editor from mdedit to simplemde" #22

**Comment by stefan-niedermann** [comment]
Just for information: Android client will do the exact same thing: https://github.com/stefan-niedermann/OwnCloud-Notes/issues/155

**Comment by jancborchardt** [comment]
There could be a separate »reading« view, yes. But the edit mode should always be the default.

cc @Henni @korelstar what do you think? Something next to the fullscreen button maybe.

**Comment by Henni** [comment]
👍 
@jancborchardt that's also where I would have placed that action.

**Comment by phsc** [comment]
Great! Would be happy to have that feature.

**Comment by korelstar** [comment]
> But the edit mode should always be the default.

Yes, and I think it would be useful if the current mode (edit or preview) is kept active when loading another note -- until it is changed manually.

> Something next to the fullscreen button maybe.

Definitely together with other buttons, and placing it next to the fullscreen button sounds really reasonable, since both buttons affect the representation of the note.

However, in the near future, it's likely to integrate more settings per note, e.g. a setting for the category of the note (#8). This is just meant as a hint to include this in our thoughts.

**Comment by jancborchardt** [comment]
> Yes, and I think it would be useful if the current mode (edit or preview) is kept active when loading another note -- until it is changed manually.

@korelstar I’d rather say that if at all, this should be remembered on a per-note basis. You might have some notes you’re only reading, and several notes you only edit.

We need to focus on that this is a Notes app, and edit mode also includes viewing anyway, but viewing mode does not include editing. So edit mode is always the choice in case of doubt.

**Comment by patrikx3** [comment]
please up for like github write/preview editor

**Comment by patrikx3** [comment]
https://simplemde.com/

**Comment by jancborchardt** [comment]
The [Markdown Editor](https://apps.nextcloud.com/apps/files_markdown) app has this functionality: Editing view, Split view, or only Preview.

Maybe @icewind1991 can help with adding a preview mode here? Basically it’s also what happens when you share a Markdown file.

**Comment by korelstar** [comment]
Please have a look at #315 for an implementation of this.
