### ISSUE TITLE
apps/notes/notes loads too slow

### ISSUE THREAD

**Issue by AykutCevik** [nextcloud/notes#232]
Hello,

I noticed that the call /apps/notes/notes takes up to 2.9 seconds to return the data for 25 notes.
I think it is related to https://github.com/nextcloud/notes/blob/master/controller/notesapicontroller.php#L79

Is there anything we can do to speed up the delivery of the notes list?

Thank you for the great work!

**Comment by AykutCevik** [comment]
@korelstar I meant the web-app, sorry for the wrong link. The route is `apps/notes/notes`.

**Comment by korelstar** [comment]
Please have a look at #233. Does this solves your problem?

**Comment by korelstar** [comment]
I just merged my changes to `master` and will publish a new release with this, soon.
Please re-open or open a new issue if loading the list of notes is still too slow.

**Comment by AykutCevik** [comment]
@korelstar wow, that was fast! Didn't have the time to look into your PR earlier, sorry.
I've updated the Notes app to the latest version and it works flawlessly. Got really fast now, thank you for the fix!
Keep up the great work.
