### ISSUE TITLE
Last modified note open when note URL is used to open note

### ISSUE THREAD

**Issue by fazlerabbi37** [nextcloud/notes#236]
Last modified note open when note URL is pasted in the address bar or 'open link in new tab' is used to open note.

### Step to reproduce:
1. Open note
2. The last modified note opens, let's say it is X.
3. Click and open an another note, say it is called Y.
4. Copy the URL from the URL bar and paste the URL to a new page.
5. From the previous page, right click on Y from the left side panel and select open link in new tab.

### Expected behavior:
In both case on step 4 and 5, note Y should be open.

### Actual behavior:
In both case on step 4 and 5, note X opens.

**Comment by korelstar** [comment]
Thanks for reporting! This bug will be fixed in the next release.
