### ISSUE TITLE
Failed integrity check

### ISSUE THREAD

**Issue by jurgenhaas** [nextcloud/notes#237]
The last version 2.4.0 fails the integrity check with lots of extra files in the `l10n` directory and also `templates/note.php.orig` and `js/app/controllers/notecontroller.js.orig`.

Can this be corrected?

**Comment by jurgenhaas** [comment]
Just realized that the `.orig` files have been part of the [2.3.2](https://github.com/nextcloud/notes/releases/download/v2.3.2/notes.tar.gz) release file and that's where they came from.

**Comment by korelstar** [comment]
Thanks for the feedback. Strange, that those files where part of the old release.

I close this issue now, since it affects an old version.
