### ISSUE TITLE
Enable fast copy and paste (middle-click on Linux)

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/notes#244]
When using Linux/Unix, you can copy and paste just with select and middle click; this is very fast, requires less key presses (less RSI risk) and particularly good for moving text to/from console apps. Is it possible to enable this behaviour in the editor?

**Comment by Eszartek** [comment]
This issue makes using notes much more tedious than it should have to be, it reminds me of using Windows :)

**Comment by korelstar** [comment]
It is not intended that this feature from the operating system is not available. Unfortunately, I have no idea how to fix this. This may come from the used editor (SimpleMDE) and may be related to #163.

Any ideas how to fix this are welcome!

**Comment by putt1ck** [comment]
Maybe some hints here (linked from https://github.com/sparksuite/simplemde-markdown-editor/issues/583)

**Comment by korelstar** [comment]
It looks like pasting text using the middle-click works now. However, copy-on-select works on Chromium but does not work on Firefox (see https://bugzilla.mozilla.org/show_bug.cgi?id=1593761). Since it's a known-bug in Firefox and not in this app, I'm closing this issue for now.
