### ISSUE TITLE
Unwanted strings at Transifex

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/notes#245]
Since today there are four strings at Transifex which should not be there:

1.  https://www.transifex.com/nextcloud/nextcloud/translate/#de/notes/151126248
https://github.com/nextcloud/notes/blob/718908a6c74ec9129f2238700d9306dd09a3f5ac/js/vendor/lodash/vendor/underscore/test/utility.js#L147
1. https://www.transifex.com/nextcloud/nextcloud/translate/#de/notes/151126247
https://github.com/nextcloud/notes/blob/718908a6c74ec9129f2238700d9306dd09a3f5ac/js/vendor/lodash/test/test.js#L2333
1. https://www.transifex.com/nextcloud/nextcloud/translate/#de/notes/151126246
https://github.com/nextcloud/notes/blob/718908a6c74ec9129f2238700d9306dd09a3f5ac/js/vendor/lodash/test/test.js#L10300
1. https://www.transifex.com/nextcloud/nextcloud/translate/#de/notes/151126249
https://github.com/nextcloud/notes/blob/718908a6c74ec9129f2238700d9306dd09a3f5ac/js/vendor/lodash/test/test.js#L20972

@MorrisJobke Any ideas for this one?

**Comment by korelstar** [comment]
This is due to the update of JavaScript dependencies in #222. Since these are only files from unit tests: can I instruct bower to not include those test files?

**Comment by MorrisJobke** [comment]
> can I instruct bower to not include those test files?

Usually this is defined by the package owner in the `package.json` or `.npmignore`: https://stackoverflow.com/a/25125870/520507

So either you do a PR against those upstream repos. The other far easier way would be to put them into the `.gitignore` in this repo and remove them from the source as well. That's what we do in our repos (server & apps) as well. 

For example: 
https://github.com/nextcloud/3rdparty/blob/master/.gitignore#L34-L39

**Comment by korelstar** [comment]
Thanks, that's a good idea. I will use `.gitignore`, too.
