### ISSUE TITLE
Ability to search notes

### ISSUE THREAD

**Issue by affanse** [nextcloud/notes#25]
Hi dev, it is nice to have a search function for notes. I have plenty of notes, which is no problem searching in android. But the problem is when I use Internet Browser from Windows I have to search all the notes, it kinda dizzy.. :)

**Comment by korelstar** [comment]
Yes, that would be nice.

Just for reference: owncloud/notes#176 is a similar issue in the old repository

**Comment by phsc** [comment]
And just as a side note: https://github.com/janis91/nextnotes already supports searching.
As I already wrote in another thread: It would be supercool to have one well-maintained notes app!
=> https://github.com/janis91/nextnotes/issues/39

**Comment by monperrus** [comment]
I notice that Ctrl-F binds to search over all notes. Is there a way to only search in the current note?
Thanks!
