### ISSUE TITLE
Title underlined with "=" doesn't get rendered in edit view

### ISSUE THREAD

**Issue by nsrosenqvist** [nextcloud/notes#259]
Markdown allows two different syntaxes for titles, one is by a single hash, and the other is by "underlining" the line by creating a line of equal signs underneath. The second method currently doesn't render the above text as a title, only the line itself.

**Comment by n1try** [comment]
Actually seems to be part of the Markdown spec: https://spec.commonmark.org/0.28/#setext-headings

But I can't think of a nice way to use this in the "hybrid" / combined editor + rendered view.

**Comment by korelstar** [comment]
Looks like this is fixed now:

![Screenshot](https://user-images.githubusercontent.com/6277619/58315257-83113e80-7e11-11e9-9aba-1b8fbdea304e.png)
