### ISSUE TITLE
Support showing notes by most recently modified first

### ISSUE THREAD

**Issue by nsrosenqvist** [nextcloud/notes#260]
This is a feature request to add the option to sort the sidebar by last modified time, so that recently modified files are at the top.

**Comment by n1try** [comment]
Isn't that the case anyway? In my case, when I edit a note, it swaps up to the very top of the list, which makes sense, because of https://github.com/nextcloud/notes/blob/94f45599f0a38128fb67fff9e5674941ff1e7d59/templates/main.php#L49

**Comment by nsrosenqvist** [comment]
You are right, sorry my bad.
