### ISSUE TITLE
[Bug] Android Widget, click + for new note, hit back, create empty note - breaks desktop sync

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/notes#263]
I use notes very regularly both on my desktop, laptop and my phone.

I have the note list widget on my android phone, and just now I hit the "+" button by mistake, then hit back to cancel, and it created a "new note" that was empty. Then my desktop sync client could not complete sync since it was empty.

Pretty sure this is a bug.

**Comment by stefan-niedermann** [comment]
Please reopen this issue in https://github.com/stefan-niedermann/nextcloud-notes/issues
