### ISSUE TITLE
Search (Ctrl+F) trap for searching files (rather than text) is not useful

### ISSUE THREAD

**Issue by AquaL1te** [nextcloud/notes#268]
There is a trap in Notes for Ctrl+F which does not allow text searches in a file, it then searches for files. This is not ideal or useful. Please introduce a different trap for this, e.g. Ctrl+Shift+F, please don't break regular browser workflows.

**Comment by korelstar** [comment]
Sounds reasonable.
However, this is done by the Nextcloud server and not by the app itself. Does anybody know if we can deactivate this in this app?

**Comment by marcelklehr** [comment]
@korelstar It should be deactivated by default, so I assume there is some code that sets this up in this app.

**Comment by korelstar** [comment]
No, I don't think that we activate the shortcut manually. Instead, it's activated by the Nextcloud core when providing a search using the search API:
https://github.com/nextcloud/server/blob/master/core/search/js/search.js#L124

An option would be to add an option to the search API, that doesn't add the listener when the option is set.

**Comment by stefan-niedermann** [comment]
I think pressing ctrl f a second time opens the browser default search, can someone confirm this?

**Comment by AquaL1te** [comment]
@stefan-niedermann that indeed works! I guess it can be closed then.
