### ISSUE TITLE
Formatting issue when `<` (&lt;) present

### ISSUE THREAD

**Issue by shtrom** [nextcloud/notes#271]
Adding an `<` in a the text of a note seems to break the formatting of subsequent text.

See screenshot:
<img width="638" alt="screen shot 2018-11-21 at 15 40 15" src="https://user-images.githubusercontent.com/160280/48819458-240c3780-eda4-11e8-9117-ebcacf28dfff.png">

For reference, this is the text used:
```
# Nextcloud note formatting issue

## A

All good here
* and here
* and here

## B

Here too
* and here
* But... if a<b

## C

Is all messed-up
* here too
* Now close the tag >
* Woohoo?

## D

Not quite, we still have the indent...
```

**Comment by korelstar** [comment]
Looks like `<b ...>` is interpreted as HTML tag by the used SimpleMDE library. It doesn't look like this can be deactivated. A workaround could be to put your formula `a<b` into backticks: `\`a<b\``

**Comment by shtrom** [comment]
Ah, yep.

![nextcloud-notes](https://user-images.githubusercontent.com/160280/48824034-20ce7700-edb7-11e8-8dad-59f0aada4ccf.gif)

Sounds like it could be a duplicate of #201 then.
