### ISSUE TITLE
2.5.1 broken with PostgreSQL

### ISSUE THREAD

**Issue by shibotto** [nextcloud/notes#278]
After updating to 2.5.1 I get this error:
```Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT quote_ident(r.conname) as conname, pg_catalog.pg_get_constraintdef(r.oid, true) as condef FROM pg_catalog.pg_constraint r WHERE r.conrelid = ( SELECT c.oid FROM pg_catalog.pg_class c, pg_catalog.pg_namespace n WHERE n.nspname NOT IN ('pg_catalog', 'information_schema', 'pg_toast') AND c.relname = 'oc_phonetrack_sessions' AND n.nspname = ANY(string_to_array((select replace(replace(setting,'"$user"',user),' ','') from pg_catalog.pg_settings where name = 'search_path'),',')) AND n.oid = c.relnamespace ) AND r.contype = 'f'': SQLSTATE[21000]: Cardinality violation: 7 ERROR: more than one row returned by a subquery used as an expression```
Reverting to 2.5.0 seems to solve the issue. 3 days ago I migrated from MariaDB using pgloader, so I'm not excluding the problem is on my end (I just don't know what to look for).

**Comment by shibotto** [comment]
Nope, I messed with my installation a bit more and my DB seem to be the problem. Sorry for the fuss.

**Comment by colttt** [comment]
@shibotto how did you solve the problem? I've the same issue
