### ISSUE TITLE
Full-screen mode: scrolling not possible

### ISSUE THREAD

**Issue by korelstar** [nextcloud/notes#279]
In full-screen mode (use button on the lower right to toggle mode), there is no possibility to scroll a larger note. This applies to all browsers, I've tested (Firefox, Chrome, Edge).

I think this worked in the past, maybe it was introduced by Nextcloud server (I've tested with 14 and 15RC1, only).

**Comment by xxKeith20xx** [comment]
In full-screen mode, there is no ability to scroll. Replicated on Nextcloud 15.04.
