### ISSUE TITLE
[Bug] "Saving failed" on Groceries.txt (just this specific one)

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/notes#280]
Suddenly out of nowhere the notes App won't let me save anything for my "Groceries.txt" file. Other notes work just fine, so I think it's specific to this and may be some form of file locking gone wrong.

I've tried:
1. Updating the OS and all packages, including rebooting
2. Updating Apps to 2.5.1 on nextCloud
3. Removing the "Groceries.txt" file and remaking it many different ways (mobile, web interface, at file level)
4. Triggering an OCC file rescan on all users

Whenever I edit the file, it often makes a "Groceries (2).txt" with the changes, but never lets me save "Groceries.txt".

This happened this week, can't recall exactly when.

Please help! I'm out of ideas :(

nextCloud 13.0.2 is the version running, and I haven't updated it recently.

**Comment by korelstar** [comment]
Hmm. Immediately, I have no idea, why this could happen. Hence, I'm asking some questions, may be we can find something ...

- So you can't edit the `Groceries.txt` anymore from the notes app. Are you able to edit this file from the files app with the default text editor?
- Are you able to continue to work on the new `Groceries (2).txt`?
- Are there any special characters in the note? (Maybe by accident?)
- Do you edit the file `Groceries.txt` from other devices? E.g., syncing with desktop or mobile app
- Is there something relevant in your nextcloud logs (i.e. the file `data/nextcloud.log` or through the web-interface)? Have a special look at the time range where the file `Groceries (2).txt` was created.
- Do you plan to update to Nextcloud 14? Maybe this helps?

**Comment by BloodyIron** [comment]
1. When I go in via the web interface for notes, I try to type stuff into the "Groceries.txt" file, and hit ctrl + s to save, bottom of the interface says "Saving failed"
2. When I try to edit the "Groceries.txt" file at the filesystem level I can, but when I then get into the Notes app, it seems to dupe the file to "Groceries (2).txt"
3. "Groceries (2).txt" I can edit and save, and other notes seem to be editable just fine
4. The note is just a simple list of groceries, no special characters, and each time I have regenerated the file in testing I just typed alpha-numeric stuff (asdf etc), nothing special.
5. I use the Notes app on mif you're writing the swatch file, if you could also write out the RGB values beside each that'd be appreciated, since my monitors have inconsistent colour from one to the nexty android to work against my notes files, I've used it regularly for different notes, and it also can edit other notes just fine, just not this one specific file any more.
6. I've re-created the file on-disk several times now, and restarted the service. I didn't check logs, but I have tried several ways to clear up any possible file locks, as this looks like a file locking issue or something of that ilk.
7. I actually had lost track of the NC14 release hah! So yeah I'll probably do that today.

**Comment by korelstar** [comment]
Please check the Nextcloud logs for the time when the file was duplicated. Without this information we can't help.

However, you can try to change the title of that note (e.g. "Grocery list") and continue working on that file.

Finally, please update to the latest release of all software components.

**Comment by BloodyIron** [comment]
Okay so I can't explain it, but suddenly I can now actually edit and save "Groceries.txt" on both my Android device, web interface, and such. The changes reflect on both, and I'm not seeing the file duplication.

I'm not sure what more to say on that :O

**Comment by korelstar** [comment]
I'm happy to hear that the problem doesn't happen anymore! :-)

Let's close this issue then.
