### ISSUE TITLE
Notes and Nextcloud GlobalSiteSelector

### ISSUE THREAD

**Issue by riggs498** [nextcloud/notes#281]
I just upgraded to 14.0.4. I am not able to use the notes app anymore. I get logged in errors. Is the Notes App enabled? Been working great until now.

**Comment by korelstar** [comment]
Are you talking about the Android app? Please try open the notes app using the web interface, then. Does this work? Are there any related entries in the log file (e.g. `data/nextcloud.log`)?

**Comment by riggs498** [comment]
Here is what my phone shows. And the server log.

**Comment by riggs498** [comment]
Yes the web interface works. Here is another screen shot for you on login.

**Comment by korelstar** [comment]
@riggs498
Please upload your image and log file attachments directly on the Github's website and not as e-mail attachment. Otherwise we can't see them.
Do have activated two-factor author, too?

@smartysmart34
Does it work when you (temporarily) deactivate two-factor author?

**Comment by riggs498** [comment]
No. I have tried it on 3 other phones and tablets. No good.

**Comment by riggs498** [comment]
I dont use two - factor auth. To much of a hassle mobile.

**Comment by riggs498** [comment]
![screenshot_20181205-094612_gmail](https://user-images.githubusercontent.com/15127431/49536277-1ec6e680-f894-11e8-9c8e-627b575ae78d.jpg)
![screenshot_20181205-094939_chrome](https://user-images.githubusercontent.com/15127431/49536288-25555e00-f894-11e8-8f07-70360501ee3d.jpg)
![screenshot_20181205-100423_notes](https://user-images.githubusercontent.com/15127431/49536300-2a1a1200-f894-11e8-9f0c-7f44d37bd81e.jpg)

**Comment by smartysmart34** [comment]
Hi, I did try with another user credential that does not use 2F-Auth. No
success though :-(

Regards,
Martin


Am 05.12.18 um 18:33 schrieb korelstar:

**Comment by korelstar** [comment]
@smartysmart34 What's in your logs?

The logs from @riggs498 say:
"no app in context"
"remote logout request failed: Key may not be empty"

I'm not sure if this is really related.

**Comment by riggs498** [comment]
Everytime i try and access notes. That is the error that comes up.

**Comment by korelstar** [comment]
@riggs498 
I found the error message you've posted ("remote logout request failed") in the repository of the app "globalsiteselector" (see https://github.com/nextcloud/globalsiteselector/blob/2fd3f4f6b0c4ae1ccf222818b8dc950a43e384d6/lib/Controller/MasterController.php#L99).

Do you use that app? Please deactivate that app (temporarily) and try again.

**Comment by korelstar** [comment]
Any news on this?

**Comment by riggs498** [comment]
Sorry been busy.

Yes, you have to leave global selector turned off. I am kind of afraid. I
really want to learn how to use global selector. I will try and figure it
out and see if when i get the slelector working.

**Comment by korelstar** [comment]
Thanks for the feedback. I have a theory on this: The Android app doesn't follow HTTP redirects, but GlobalSiteSelector uses redirects in order to redirect to the actual server. This may be solved by implementing https://github.com/stefan-niedermann/nextcloud-notes/issues/418, but I don't know exactly.

So, what's your actual configuration:
- Do you try to connect to a master server or a slave server?
- Is the user account on the server you are connecting?
- Does it work if you connect to the other server?

**Comment by korelstar** [comment]
Closing due to missing feedback. Since this affects the Android app, please open an issue there, if the Problem still occurs.
