### ISSUE TITLE
when selecting text, the App navigation bar opens

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/notes#282]
Hey,
here are the steps to reproduce:
- open a note in browser, resize the window so that the sidebar automatically hides
- mark two lines of text with the mouse, starting in the beginning of a line and dragging bottom-right to the end of the line
- the sidebar opens and the text you wanted to select is not completely selected

workaround: start selecting text at the bottom right corner and drag upwards and to the left.

this is a little annoying because I do this quite a lot and everytime it doesn't work. With every other text/app I use, I can select text from top left to bottom right no problem.

notes app  2.5.1
nextcloud 13.0.1
firefox 64.0

**Comment by korelstar** [comment]
I was able to reproduce this. That's indeed weird and should be fixed.
