### ISSUE TITLE
Notes for Groups (sharing to other users)

### ISSUE THREAD

**Issue by cradermacher** [nextcloud/notes#285]
Hi,

is it possible to use Notes with Groups?
All notes should be visible and editable  for the Group

Regards
Christian

**Comment by stefan-niedermann** [comment]
The notes are all stored as files in the `Notes`-Folder. You should at least be able to share single files, though i do not know if one can place a shared file in his/her own `Notes`-folder so it can be used with the Notes-App.... :question:

**Comment by cradermacher** [comment]
Hallo,

 

vielen Dank für die super schnelle Rückmeldung.

Man kann über die Einstellungen in den Notizen einen Ordner definieren, der unterhalb eines geteilten Ordners liegt. Wenn dies alle in den Einstellungen ändern liegen die Notizen in einem Bereich für die Gruppe, und können von allen gelesen und bearbeitet werden.

 

Funktioniert also perfekt. Vielen Dank.

 

Gruß

Christian Radermacher

 

---------------------------------------------------------------------------
Christian Radermacher
Fastlingerring 155

85716 Unterschleißheim

Tel: +49 89 32627750
Mobil: +49 170 9997555
Mail: christian@radermachers.net

 

 

Von: Niedermann IT-Dienstleistungen <notifications@github.com>
Antworten an: nextcloud/notes <reply@reply.github.com>
Datum: Mittwoch, 19. Dezember 2018 um 16:52
An: nextcloud/notes <notes@noreply.github.com>
Cc: cradermacher <christian@radermachers.net>, Author <author@noreply.github.com>
Betreff: Re: [nextcloud/notes] Notes for Groups (#285)

 

The notes are all stored as files in the Notes-Folder. You should at least be able to share single files, though i do not know if one can place a shared file in his/her own Notes-folder so it can be used with the Notes-App.... ❓

**Comment by korelstar** [comment]
No, the default folder is always `Notes`. Another way would be to share a folder inside the notes folder to your group and let every user move that shared folder from their root directory to their notes folder. That's the way I'm using notes in order to have both: a shared folder and my own notes.

However, a valid enhancement of the app is to make this more easy. I thought we had already an issue for that, but I can't find it.

**Comment by TruputiGalvotas** [comment]
I would be willing to take on this issue with some mentoring/guidance from nextcloud team.

**Comment by korelstar** [comment]
Yay, that would be so great! I think we have two cases that should be realized: sharing a single note and sharing a category (i.e. a folder). Therefore, we have the following steps to be done:

### Backend
- add new attributes to `lib/Db/Note.php` which determine if the note is shared by the current user (and to which users) or if it is shared by another user (and by whom)
- fill these attributes using the share API: https://docs.nextcloud.com/server/stable/developer_manual/api/OCP/Share/index.html
- create and implement `lib/Service/ShareService.php` with methods for sharing/unsharing files or directories to other users (and, after sharing, move these to the other user's notes directory) using the share API
- extend `lib/Controller/NotesController.php` with methods for sharing/unsharing notes using `ShareService`
- create `lib/Controller/CategoryController.php` with methods for listing all categories and respective share info as well as sharing/unsharing categories using `ShareService`

### Frontend
- add new action for sharing/unsharing of notes and categories in app navigation
- provide frontend for selecting users or groups (maybe there is a common design element that can be used, e.g. app sidebar).

### Contribute
Please note that we are moving the frontend from AngularJS to VueJS (see #290). Therefore, please use the branch `vue` as base for development and create pull requests for that branch.

You can start with small steps and concentrate on a single step from the above list only, e.g.  the changes in `lib/Db/Note.php`.

**Comment by korelstar** [comment]
Please note also this related issue: #135 (Deletion of single shared note is not possible). That should be fixed by implementing the steps above.

We have also another issue about sharing, but there is the focus on making a note public available: #38. I think we should keep this independently.

**Comment by jakobroehrl** [comment]
Ich würde Sharing gerne einbauen.

**Comment by cryptoquick** [comment]
This feature would be nice, because Nextcloud Text isn't letting users I share notes with edit the note in an editor or viewer, it just wants them to download the note.

**Comment by kirmaha** [comment]
Interrested in this feature too, with read-only option on group sharing for whole categorie and sub-categories.

**Comment by kojid0** [comment]
Since [nextcloud deck](https://github.com/nextcloud/deck) has the option to share decks with other users, can't this part of code  be included into nextcloud notes?

**Comment by korelstar** [comment]
@kojid0 : I don't think so, because deck has a database backend and notes uses files. Therefore, sharing a note should be equivalent to sharing this file.

**Comment by d4nyl0** [comment]
Currently when you share a note or Notes folder (category), it goes to other users' Root.

I think it should be easier to move that object (single note or folder) directly under "Notes" of all other users.
When only one note is shared, if it belongs to a category, I'm not sure if it's cleaner to create that category for all other users or ignore it.

**Comment by juliushaertl** [comment]
Sharing has been implemmented through file shares changing the target to the notes folder with #1146
