### ISSUE TITLE
Overview of supported Markdown syntax

### ISSUE THREAD

**Issue by Tuxyso** [nextcloud/notes#287]
I use notes App 2.5.1 on a nextcloud 14 installation. 

Is there an overview which Markdown syntax is supported? During my tests it seems to me that only a small subset of Markdown is supported. A "factsheet" for supported Markdown syntax would be appreciated.

Best wishes,
Tuxyso

**Comment by korelstar** [comment]
No, we haven't such a thing yet. There was a related issue (#196) but we still have not a proper user-documentation. There are some ideas on improving this, such as a "default note" with some introduction (see https://github.com/nextcloud/notes/issues/196#issuecomment-387986729 and #14) and a "Context-based formatting popover" (see #200).

Another aspect is, that the actual supported syntax depends on the editor we use. Here, it is important, that we plan to switch to another editor (see #204).

Nevertheless, we have to do something for a better usability. :+1:

**Comment by Wadera** [comment]
Can we integrate Notes with Markdown Editor? 
https://apps.nextcloud.com/apps/files_markdown

**Comment by cangeeq** [comment]
It wouldn't, but at least the rendering would more likely be consistent if the supported syntax was common to both.

Right now it seems like markdown notes render better in Files view than Notes in the web client, but that could just be personal based on the syntax used in the markdown files I have.

**Comment by iSpeeX** [comment]
Hello,
I can say that @cangeeq is right, I tried to use Markdown Editor, thinking about an automated integration in the Notes app, but unfortunately...
The app is good, but way too simple : no tags, no "real editor", no preview pane...

At least, the support avec the nextcloud app "Markdown Editor" (it's an optionnal install after all) would be GREAT, don't know if it's hard to make but.... Kepp up the great work !

**Comment by newhinton** [comment]
I have some ideas to bring some of the more "hidden" features to users. Disclaimer: I don't know if my ideas are 'the nextcloud way of doing it'


Generally, there is the existing introduction  screen. I think it is not really remarkable, and does not leave a lasting impression.

My idea would be to introduce an actual popup, just like the nextcloud-first-run wizard. This Popup contains some quick information, just like the current introduction screen (except more 'modern' and colorful, maybe add some pictures)

It also contains a link to my main idea: the in-app-wiki.
This would either be "hidden" in the lower left settings, or directly above it (like Deleted Files in the nextcloud-files-app)

This wiki contains a more thorough overview about the app. Shortcuts, features, the apps, Tips and tricks.

It could either be a popup, just like the intro, or a dedicated page as the introduction is now. Please comment on how you think this would look best, and i will eventually take a shot at implementing something like this!

**Comment by stefan-niedermann** [comment]
> in-app-wiki [...] would either be [...] in the lower left settings

Actually not a bad idea at all - we do have a <kbd>Formatting</kbd> section in the Android apps sidebar right above the <kbd>Settings</kbd> section, too 🙂
