### ISSUE TITLE
Search-filter for notes list doesn't use the notes' contents [$20]

### ISSUE THREAD

**Issue by korelstar** [nextcloud/notes#288]
Due to the speed optimization in #233, the content of the notes is not loaded anymore when loading the notes list. This is still a good decision, but as a consequence filtering notes using a keyword (resp. search string) doesn't "search" in the notes' contents - since filtering is performed on the client. Currently, filtering uses metadata such as the note's title, path, and category, only.

In order to (re-)introduce filtering by notes' contents, we have to implement a server-side search. Of course, the search should be performed asynchronously and has to cope with network errors, users who type faster than the network connection etc. (you know that stuff).

**Comment by doc75** [comment]
This feature is really important to ensure Notes is usable.
Can't we imagine to integrate something like https://lunrjs.com/
It requires only to generate the index on server side and then to serve the index when search is launched (size of the index would be from 110s of KB for a resaonable number of notres)

Not sure if this is realistic or not.

**Comment by g-work** [comment]
I like the simple UI of the note app, but with hundreds of notes, it is nearly impossible to find the one you're looking for by only searching the title. Unfortunately I'm not able to provide code myself, but i posted a bounty on it - perhaps there are more of you, who are interested in a solution and want to join?

**Comment by fajabird** [comment]
The deck app provides a indexer plugin, can't that be used? Indexed Fulltextsearch should be supported.
