### ISSUE TITLE
Add the Notes app to the Nextcloud App Store

### ISSUE THREAD

**Issue by phsc** [nextcloud/notes#29]
We should add the Notes app to the Nextcloud App Store.
=> https://apps.nextcloud.com/

**Comment by schiessle** [comment]
Would be great if we could have it in the app store, Nextcloud 11 is already almost released.

cc @BernhardPosselt @Henni @jancborchardt

**Comment by Henni** [comment]
I'm working on it. Should soon be done.

**Comment by Henni** [comment]
Should work now!
Would love to hear a few positiv reviews, just to be sure the signing worked out well for Nextcloud 10 and 11.

**Comment by phsc** [comment]
The new app store is only available for Nextcloud 11. Nextcloud 10 still points to the ownCloud app store.
Therefore, I cannot test it right now (I have to perform the update first).

**Comment by BernhardPosselt** [comment]
You can also use the store with 9 and 10 FYI check the app store docs

**Comment by korelstar** [comment]
@Henni
- Screenshot is missing (most of the other apps have one and you could use the one from `README.md`).
- Description is missing (providing some more info (e.g. the file backend, markdown parsing) would be also nice for use in `README.md`).
- How do I check the signing in Nextcloud 10? Do you mean the verification of file authenticity (`hashes` in `appinfo/signature.json`) or signing of a whole release (I think `signature`/`certificate` in `appinfo/signature.json`)? It seems that both are not verified in Nextcloud 10 (I manipulated the data and got no error). I "installed" the app from the new store by downloading and unzipping `notes.tar.gz` manually.

@BernhardPosselt Which documentation do you mean? I only found a developer documentation, but no information about using the store with Nextcloud 9 and 10.

**Comment by Henni** [comment]
@korelstar first two issues can be solved by editing the info.xml. I'll probably do this tomorrow at the Munich Meetup.
Installing the app in nextcloud 10 is possible by configuring your instance to use the nextcloud app store. That way the signature should be checked (AFAIK).
But I'm probably happy with the signature working on Nextcloud 11, as this is the first version which enabled the app store by default.

**Comment by BernhardPosselt** [comment]
http://nextcloudappstore.readthedocs.io/en/latest/restapi.html#legacy-api

**Comment by korelstar** [comment]
Thanks for the hint, I got it finally. However, it's hard to proof if the signature was checked. One would have to setup an own app store instance with a manipulated app.

**Comment by korelstar** [comment]
@Henni
Could you please update the Notes app in the app store, so that all our nice enhancements of the `appinfo/info.xml` take effect. Afterwards, this issue can clearly be closed.

**Comment by Henni** [comment]
@korelstar give me a day or two 😉

**Comment by korelstar** [comment]
Hooray :tada:: 2.2.0 is released (thanks @Henni) and the app-store entry now provides all necessary information: https://apps.nextcloud.com/apps/notes
Therefore, I'm closing this issue.

**Comment by jancborchardt** [comment]
PARTY HARD! :dancer: :man_dancing:
