### ISSUE TITLE
Ability to join files likes screenshots or photos

### ISSUE THREAD

**Issue by tclavier** [nextcloud/notes#294]
As a user I want to attach some files to my notes. For exemple, I wrote a markdown note, and I want to add a photo. I can choose a photo in my nextcloud gallery or upload a new one. After that I see the markdown IMG link in my note.

**Comment by korelstar** [comment]
Duplicate of #74

**Comment by korelstar** [comment]
Please feel free to increase the bounty on #74. :-)
