### ISSUE TITLE
Lost / missing note: File error: (name_of_note.txt) File not found at path: File not found

### ISSUE THREAD

**Issue by axelsimon** [nextcloud/notes#297]
Hi,
(not reporting using the [issue template](https://raw.githubusercontent.com/nextcloud/server/master/issue_template.md) as it missing (404)).

I just realised Nextcloud Notes has lost one of my notes. The note itself was created a few months back. When clicking on the note, the following error appears at the top of the Nextcloud web interface:
> File error: (name_of_note.txt) File not found at path: File not found

I immediately checked the filesystem and indeed, the note had disappeared from the Notes directory.
I then checked the deleted files in the Nextcloud web interface, but was greeted with
>No deleted files
You will be able to recover deleted files from here

Not good.

However, a `find /path/to/nextcloud/ -iname "*name_of_note*"` showed the note was in the deleted files, at `/path/to/nextcloud/user/files_trashbin/files/name_of_note.txt.d1541270989`
This s good :wink: 

So 2 issues:

1.  I didn't voluntarily delete this note, that I am sure. So either there was a severe bug in Notes, or the Android Nextcloud Notes app deleted them. Since that happened to me in the past, possibly by swiping the note away without really realising it, I've been careful when using the app now. There is nothing in the logs about deleting the note. The logs go back to early December.
Looking at the file system level:
```
ls -alh /path/to/nextcloud/user/files_versions/Notes/name_of_note.txt.*
-rw-r--r-- 1 www-data www-data 574 Oct 18 23:53 '/path/to/nextcloud/user/files_versions/Notes/name_of_note.txt.v1538042778'
-rw-r--r-- 1 www-data www-data 631 Oct 20 15:23 '/path/to/nextcloud/user/files_versions/Notes/name_of_note.txt.v1539899611'
```
and
```
ls -alh /path/to/nextcloud/user/files_trashbin/files/name_of_note.txt.*
-rw-r--r-- 1 www-data www-data 631 Oct 18 23:53 '/path/to/nextcloud/user/files_trashbin/files/name_of_note.txt.d1541270989'
```
This is weird in itself, It appears the note was created on Oct 18 and deleted on Oct 18, but updated on Oct 20. Furthermore, the deleted note's content is the same as the Oct 20 note, even though it looks like the note was deleted on Oct 18 (if the creation date of the note in `files_trashbin` is to be believed).

2. The deleted note is not easily recoverable (ie: using the Nextcloud interface rather than file system level commands).

I'm happy to report further info, however given the logs don't go back that far, not sure what I'll be able to provide :/ 

This is Nextcloud 15.0.4.0 on Debian 10 (buster/sid, well buster with bits of sid in, I know, I know…) with nginx 1.14.2.
Looking at the updater log, Netxcloud was v 14.0.1.1 when the note disappeared.

Thanks!

**Comment by axelsimon** [comment]
Question: is it safe to simply copy the latest version of the note back to its initial filename in `/path/to/nextcloud/user/files/Notes/name_of_note.txt`?
Or is there a better way to recover the note?

**Comment by korelstar** [comment]
Puh, it's unlikely that the Notes app has lost that file, because it only deletes a file if someone gives the command to do so. On the other hand, I hope, that the Nextcloud server itself typically doesn't lose any files. Hence, I hope that you accidentally deleted that file by yourself. But we can't reproduce this with the information provided. :-/

However, in order to recover a file from backup, the notes app doesn't require any special steps. You recover the file the same way, like you recover any file in your Nextcloud:
1. copy the file from backup to its original place
2. run the command `php occ files:scan USERNAME` (replace USERNAME with your username) in the root directory of you Nextcloud installation

**Comment by axelsimon** [comment]
Thanks for your reply. I can see your point about how it's unlikely the Notes app lost my file. It's a bit hard to know where to report this, as my user experience is that a file I was expecting to be there had disappeared. I wish I had seen the file had disappeared earlier, I could have maybe got something useful out of the logs.

Thanks for your advice, `occ` is scannnig my files right now.

It does leave us with point #2 however: if the file was deleted, and is in files_trashbin, why is not recoverable directly from Nextcloud? This issue is likely to be in a nextcloud/server issue I think though.

**Comment by korelstar** [comment]
Great to hear, that you were able to recover that file!

However, I think we can't help here anymore from the notes app perspective. The filesystem was obviously out of sync with the Nextcloud database. This is an issue for `nextcloud/server` or of your server.
