### ISSUE TITLE
Android: Error Message when Notes App is disabled

### ISSUE THREAD

**Issue by kaefert** [nextcloud/notes#301]
When the Notes App is disabled on the Nextcloud Server (for example because someone installed an update and forgot to re-enable non standard apps afterwards)

The Android Notes App displays this error Message when trying to sync:

`org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONArray`

Could this maybe be changed  to something more easily interpretable? Thank you!

(see also: https://help.nextcloud.com/t/nextcloud-notes-android-app-error-message/50206 )

**Comment by korelstar** [comment]
Yes, I agree. But this has to be solved in the Android app. Please check for existing issues (I think there was one) and create a new one if needed over there: https://github.com/stefan-niedermann/nextcloud-notes
