### ISSUE TITLE
Provide release notes in CHANGELOG.md

### ISSUE THREAD

**Issue by pm-pm** [nextcloud/notes#304]
Do you have any release note files?
It would be helpful to read more about the new version.
Thanks.

**Comment by korelstar** [comment]
Please have a look at https://github.com/nextcloud/notes/releases . Is this what you mean?

**Comment by korelstar** [comment]
What we could do is to move/copy the information from these [Github Releases](https://github.com/nextcloud/notes/releases) to a `CHANGELOG.md` file. Then, the appstore would show this information, see https://nextcloudappstore.readthedocs.io/en/latest/developer.html#changelog

This is easy to realize but would take some time (I think it's useful to migrate former versions, too). Therefore, any help is very appreciated.

**Comment by pm-pm** [comment]
> 
> 
> Please have a look at https://github.com/nextcloud/notes/releases . Is this what you mean?

Yes. This is what i am looking for. :)
I did not see that, because i update inside my nextcloud instance from nextcloud app store. (Magic and automatic) 👍 .  On the first page of github there is also no changelog.md.

Thanks for the hint to look at "[file download place](https://github.com/nextcloud/notes/releases)" and the implementation of CHANGELOG.md. :-)

**Comment by stefan-niedermann** [comment]
Maybe a link on the README.md to the changelog is enough? So we could avoid to duplicate the information every time.

**Comment by pm-pm** [comment]
Or a CHANGELOG.md with (only) a link to the changelog information. ;-)
Because when i am looking for changelog information i do not look inside readme documents.

**Comment by korelstar** [comment]
The link from `README.md` is indeed a good thing. I've just added this: https://github.com/nextcloud/notes/commit/f4ecc45d6f9540abe88e73d8518e4d0115f8536c

However, I still think that a *correct* `CHANGELOG.md` would be nice. [Other](https://github.com/nextcloud/contacts/blob/master/CHANGELOG.md) [apps](https://github.com/nextcloud/calendar/blob/master/CHANGELOG.md) [have](https://github.com/nextcloud/tasks/blob/master/CHANGELOG.md) [it](https://github.com/nextcloud/mail/blob/master/CHANGELOG.md), [too](https://github.com/nextcloud/deck/blob/master/CHANGELOG.md) - and it's [the official way to do it](https://nextcloudappstore.readthedocs.io/en/latest/developer.html#changelog). But this has low priority for me.
