### ISSUE TITLE
New note error

### ISSUE THREAD

**Issue by Lenny5Aces** [nextcloud/notes#307]
**Steps to reproduce**
Synchronize with server

**Expected behaviour**
don't create empty new notes

**Actual behaviour**
an empty new note is created every time the app synchronizes with the server. So opening the app and going into 3 notes means 4 empty new notes ("New note", "New note (2)", "New note (3)" and "New note (4)") are created.

**Server configuration**
Raspberry Pi 3 Model B Rev 1.2
Raspbian GNU/Linux 8 (jessie)
Kernel 4.9.78-v7+

**Web server:**
Apache
Version 2.4.10

**Database:**
mysql
Version 14.14 Distrib 5.5.62

**PHP version:**
Version: 5.6.40+dfsg-0+deb8u2

**Nextcloud version:**
Owncloud 10.1.1.1

I know it's a Nextcloud-app. Nevertheless, it used to work with my Owncloud installation just fine until some point (unfortunately I can't exactly tell to which one, since I didn't use it for a while)

**Comment by korelstar** [comment]
Sorry, in the meantime, the differences between ownCloud and Nextcloud are to big. We can't ensure compatibility to ownCloud anymore.

If you want to fix this by your own, please have a look at your ownCloud log files. But as far as I remember, we use a function, that doesn't exist in ownCloud, now. I think it was something about database internationalization.

**Comment by Lenny5Aces** [comment]
Ok, thanks for your reply!
