### ISSUE TITLE
Checkboxes cannot be "checked" on mobile with tapping

### ISSUE THREAD

**Issue by gradinaruvasile** [nextcloud/notes#309]
The checkboxes are not "clickable" on mobile in view mode.

**Comment by stefan-niedermann** [comment]
Do you mean in browser or in android app?

**Comment by gradinaruvasile** [comment]
The mobile app.

**Comment by korelstar** [comment]
Please see https://github.com/stefan-niedermann/nextcloud-notes/issues/451
