### ISSUE TITLE
Update notes webview

### ISSUE THREAD

**Issue by thecyberd3m0n** [nextcloud/notes#310]
**Is your feature request related to a problem? Please describe.**
When I'll change note on mobile, same note on desktop will not update. I need to refresh the website

**Describe the solution you'd like**
Javascript part of app should constantly update opened note. I would set it to 5 seconds, but we could make this an option.

**Describe alternatives you've considered**
Using OnlyOffice or file editor on opened note from filesystem

**Additional context**
Wife shares shopping list, and she wants to add something. She shares note with me, I want webapp to keep in sync with opened note.

**Comment by stefan-niedermann** [comment]
As far as i know: Nextcloud Text supports synchronous editing of multiple users, and so should the vue-component.

I think this issue is obsolete once https://github.com/nextcloud/notes/issues/331 has been fixed.
