### ISSUE TITLE
Notes not working since the update to 3.0

### ISSUE THREAD

**Issue by mundschenk-at** [nextcloud/notes#322]
**Describe the bug**
Since updating to 3.0.0, Notes does not work anymore because the JS and CSS files don't work with Nextcloud's nginx configuration (security headers).

**To Reproduce**
1. Go to 'Notes'
2. See error

**Expected behavior**
The Notes templates should be parsed by the provided JS.

**Screenshots**
![image](https://user-images.githubusercontent.com/6943905/59550249-b191bd80-8f68-11e9-845d-4eb09d7b2991.png)

**Server (please complete the following information):**
- Notes app version: 3.0.0
- Nextcloud version:  16.0.1
- OS: FreeBSD
- Web server: Nginx
- PHP version: 7.3.6
- Database: MariaDB

**Client (please complete the following information):**
 - Browser (incl. version): Safari 12.1.1, Firefox 67.0
 - OS: macOS 10.14.5

**Log files**
```
[Error] Did not parse stylesheet at '<root>/apps/notes/js/vendor/simplemde/dist/simplemde.min.css?v=272f0a04-3' because non CSS MIME types are not allowed in strict mode.
[Error] Refused to execute <root>/apps/notes/js/vendor/angular/angular.min.js?v=817b143f-3 as script because "X-Content-Type: nosniff" was given and its Content-Type is not a script MIME type.
[Error] Refused to execute <root>/apps/notes/js/vendor/angular-route/angular-route.min.js?v=817b143f-3 as script because "X-Content-Type: nosniff" was given and its Content-Type is not a script MIME type.
[Error] Refused to execute <root>/apps/notes/js/vendor/restangular/dist/restangular.min.js?v=817b143f-3 as script because "X-Content-Type: nosniff" was given and its Content-Type is not a script MIME type.
[Error] Refused to execute <root>/apps/notes/js/vendor/simplemde/dist/simplemde.min.js?v=817b143f-3 as script because "X-Content-Type: nosniff" was given and its Content-Type is not a script MIME type.
[Error] Refused to execute <root>/apps/notes/js/public/app.min.js?v=817b143f-3 as script because "X-Content-Type: nosniff" was given and its Content-Type is not a script MIME type.
```

**Comment by korelstar** [comment]
Please try to reload your webserver/php-fpm (or similar). It looks like your using still the old files. It's likely that those are in some caches.

**Comment by mundschenk-at** [comment]
Ah, sorry, I thought I already tried that. Looks like I did not.
