### ISSUE TITLE
Add subcategories (documentation)

### ISSUE THREAD

**Issue by petitminion** [nextcloud/notes#324]
Could be usefull to give the possibility to create sub-directories. Like notes -> categorie 1 -> subcategorie

**Comment by korelstar** [comment]
You can create sub-categories (subdirectories) by using `/` as delimiter between parent category and subcategory (e.g. `parent/sub`). Since this is not well documented, I will add a info button with this hint in the sidebar. Hence, I leave this issue open for now.
