### ISSUE TITLE
Checkbox Support In Preview Mode

### ISSUE THREAD

**Issue by tnyeanderson** [nextcloud/notes#325]
THANK YOU EVERYONE FOR THE HARD WORK ON 3.0!

**Describe the bug**
Checkboxes are not rendered properly in Preview mode

**To Reproduce**
Create a note with checkboxes
```
- [ ] One
- [x] Two
```
Go to preview mode

**Expected behavior**
We should see this (essentially):
```
<ul>
  <li>
    <input type="checkbox" disabled>
    <label>One</label>
  </li>
  <li>
    <input type="checkbox" disabled checked>
    <label>Two</label>
  </li>
</ul>
```

Instead we see this (essentially):
```
<ul>
  <li>[ ] One</li>
  <li>[x] Two</li>
</ul>
```

**Server (please complete the following information):**
- Notes app version: 3.0.0
- Nextcloud version: 16

**Comment by tnyeanderson** [comment]
Looks like we just have to add this plugin!

https://github.com/mcecot/markdown-it-checkbox

**Comment by korelstar** [comment]
Yes, I think that's it. Just hadn't the time / prior to look at this plugin. Could you write a PR on this? That would be cool :-)

**Comment by tnyeanderson** [comment]
I'll get to work on it. Should have one ready by the end of the week if time allows!

**Comment by tnyeanderson** [comment]
We need [this issue](https://github.com/mcecot/markdown-it-checkbox/issues/6) to get fixed before we implement here. Otherwise the checkboxes will be clickable which should not be possible in preview mode. There are a couple pull requests open at the moment for this issue, but I'm not sure when they will be accepted. The last activity was 4 years ago.

We will also need [this one](https://github.com/mcecot/markdown-it-checkbox/issues/11) fixed because our syntax includes a hyphen. That *might* be fixed by [this](https://github.com/mcecot/markdown-it-checkbox/pull/15), but that PR could cause rendering weirdness as well.

It's not looking good at the moment...

**Comment by tnyeanderson** [comment]
I'm curious why we chose to use Markdown-It and not the built-in `previewRender` config option in EasyMDE. Seems like an unnecessary library when the functionality is already there in the editor library...

**Comment by korelstar** [comment]
Thanks for your research! :+1: 
I've implemented the preview mode using `markdown-it`, because the [Nextcloud Markdown-Editor](https://apps.nextcloud.com/apps/files_markdown) uses markdown-it, too. And that editor was often referenced in the issues, here. But I'm fine with switching to `marked` (this is what EasyMDE uses), if the result look similar.

**Comment by tnyeanderson** [comment]
We should definitely be using EasyMDE's preview functionality for this. See #329

**Comment by sciurius** [comment]
A year has gone by... NC onderwent three major releases. Notes went from 3.0.0 to 3.6.0... Any progress here?
Since I make extensive use of checkboxes this issue is quite annoying.

**Comment by korelstar** [comment]
No, I've focused on other features and on fixing bugs. Would be glad if you could contribute a PR on this!

**Comment by AI-ien** [comment]
This have been open for over two years. Will it be ever fixed?

**Comment by stefan-niedermann** [comment]
@AI-ien am pretty sure the maintainer of the Notes server app will happily review your Pull Request. Otherwise you will have to wait until somebody picks up this issue. This is getting harder of course everytime when a potential contributor has to scroll through a history of "i want to have this too"-comments which add no new information to an issue.

**Comment by newhinton** [comment]
@tnyeanderson Why do we need the checkbox not be clickable in preview mode? to me it seems like a feature to be able to quickly tick off a checkbox, even without switching to edit-mode. The android app handles it this way and i think it's quite useful!

**Comment by tnyeanderson** [comment]
@newhinton I said that because I believe preview mode should not be able to change the content. That's what edit mode is for. The checkbox is easy to quickly tick off in edit mode, so if you want to make changes, use edit mode. In my mind, once I click "Preview" I should no longer be able to make changes to the note... I can't change any other aspect of the note in preview mode, so I shouldn't be able to check a box either.

**Comment by sciurius** [comment]
IMHO preview mode is just another way of looking at the content. It is a view where the markup is processed, as opposed to edit mode where the markup is shown and you can edit content **and** markup.

It is generally accepted that you can toggle checkboxes in view mode.

**Comment by tnyeanderson** [comment]
I'm not opposed to either way. I just figured it would be an outlier, as its the only thing you can edit in preview mode.

If I click print preview on a word document, I can't change the text from within a preview.

It's not intuitive to me, but like I said it doesn't really make a difference from my end. I only ever use edit mode anyway.

**Comment by AI-ien** [comment]
> @newhinton I said that because I believe preview mode should not be able to change the content. That's what edit mode is for. The checkbox is easy to quickly tick off in edit mode, so if you want to make changes, use edit mode. In my mind, once I click "Preview" I should no longer be able to make changes to the note... I can't change any other aspect of the note in preview mode, so I shouldn't be able to check a box either.

Then by this logic we all should browse web pages in HTML code and render page only when viewing. But seriously, in preview mode all the md code is rendered except checkboxes that makes it look broken. Also, then by your logic you should not render links, because in view mode user should not be able to interact, links should work only in edit mode, no?!

From user perspective this is a bad design in my opinion. Having to switch to edit mode just to be able to check a box does not make any sense. I haven't seen any md editor who does that. Even the built in Nextcloud [mark down](https://apps.nextcloud.com/apps/files_markdown) does it right. 

What I see there are three ways how to make it better, first and simplest is just to reverse checkbox rendering, second, make basic md code render as you type, trigger with space, tab or enter, then you wont even need edit or view modes, something what [typora](https://typora.io/) does, or as a last resort at least you could add an opt-in setting for users to be able to toggle it on or off.

**Comment by AI-ien** [comment]
> I'm not opposed to either way. I just figured it would be an outlier, as its the _only_ thing you can edit in preview mode.
> 
> If I click print preview on a word document, I can't change the text from within the preview.
> 
> It's not intuitive to me, but like I said it doesn't really make a difference from my end. I only ever use edit mode anyway.

When you type in word document you don't see all the xml code document generates, for example, you bold a font. Just saying.

**Comment by newhinton** [comment]
I know, this is getting a bit offtopic and maybe we shoukd open a seperate issue for it, but is there any reason we should not use the same markdown editor as https://github.com/nextcloud/text? It seems to solve some issues on behaviour, and also makes the ux more consistent across nextcloud

the markdown only-mode could still exist, the viewmode would then be a wysiwyg-mode

**Comment by stefan-niedermann** [comment]
@newhinton there already is an issue for that (even pinned) and it contains the reasons why this did not happen yet: https://github.com/nextcloud/notes/issues/331#issuecomment-751512413

**Comment by tnyeanderson** [comment]
> Then by this logic we all should browse web pages in HTML code and render page only when viewing. But seriously, in preview mode all the md code is rendered except checkboxes that makes it look broken. Also, then by your logic you should not render links, because in view mode user should not be able to interact, links should work only in edit mode, no?!

This is a pretty weird thing to say given my clearly stated position. *Of course* the checkboxes should be rendered correctly in preview mode (hey wait that's what *this issue I created* is about!) And "by my logic" links should *of course* be rendered and clickable, just not EDITABLE. You know, kind of like how I clearly explained in my post using analogies to print preview as well as referencing how current preview mode works (bUt bY mY LoGiC wE ShOuLdN't ReNdEr LiStS--no. Lists are currently rendered, just not editable. That's been my clear point through all of this.) It seems like you're just trying to be rude, which is a weird flex.

> From user perspective this is a bad design in my opinion. Having to switch to edit mode just to be able to check a box does not make any sense. I haven't seen any md editor who does that. Even the built in Nextcloud mark down does it right.

The only problem I have with this is not with the UX, it's with *consistency*. Checkboxes would be the ONLY editable part of a preview. That's why it's off-putting and unintuitive to me.

> make basic md code render as you type, trigger with space, tab or enter, then you wont even need edit or view modes

This is basically how the current edit mode works. Markdown is (essentially) rendered, including headers and clickable checkboxes and links, but you can also easily see and edit the markdown source. No preview mode needed. Like I said, I don't even use preview mode, because I see no point to it. I get nice enough rendering in edit mode *and I can edit my notes* so that's the only mode that is useful for me. It's also why I've stated that I don't really care what happens with preview mode in the end because it doesn't fit into my use case whatsoever.

> When you type in word document you don't see all the xml code document generates, for example, you bold a font. Just saying.

Same statement as above, same rude tone and weird flex from you. I think we can all share our ideas here without getting smart.

Honestly though, this issue has been open for two years. I opened it after *being the one to implement working checkboxes in edit mode* and I opened it not for me, but for other people who might use preview mode. I'm probably not going to be the one to implement this. So you go ahead and implement it however you want, and either way it won't matter a bit to me.

**Comment by sciurius** [comment]
It's all about customer expectations and experience. AFAIK, almost all existing tools allow toggling checkboxes. Even if the reasoning is right ("Checkboxes would be the ONLY editable part of a preview.") this is, indeed an exception.

**Comment by tnyeanderson** [comment]
Completely agreed, it's about expectations. I'm not tuned into expectations here (as I don't use this type of mode in any context/editor, not just nextcloud)... So if it is the case that users expect to be able to click checkboxes in a preview mode such as this, while simultaneously NOT being able to add further list items without switching back to edit mode, then I think that is absolutely what should be implemented :)
