### ISSUE TITLE
more sorting options

### ISSUE THREAD

**Issue by Iowaba** [nextcloud/notes#327]
**Issue #298**
The app has two type of notes lists: All notes, sorted by last modified date (default view for quickly finding recent notes) Notes in a specific category, sorted by title (stable view to find a known note at the same position again).

**It would be good** if you could choose the order (A-Z or Z-A) in the categories. Because I would like to take a part of my notes also by date of creation, in the sense of a diary. Since this sorting does not exist, I could start the first line of my notes with YYYY.MM.DD. If I wanted the latest note in the first place, I would have to be able to sort by Z-A as well.

**Comment by skjnldsv** [comment]
Yes, it's always good to have multiple sorting options as long as the ui doesn't get crowded :)
Sorting headers are a nice feature for simple sorting options (do not overcomplicate things): last update, title... But if we don't display the creation date, then adding one more column for that is maybe not ideal :thinking:

**Comment by Iowaba** [comment]
I think this is a misunderstanding of my bad English. Because I would not want another column, just simply the possibility to list in the categories the notes-titles sorted either "sort from A-Z" or "sort from Z-A".

**Comment by skjnldsv** [comment]
No no, your English is very good :)
But my comment is more generally speaking. In case that was something tha came into our mind for the creation date sorting ;)

**Comment by jancborchardt** [comment]
This seems to be a duplicate of **Sort by Title #298** where @korelstar already gave reasoning. :)

And I agree: Sorting alphabetically by title makes little sense for notes as the beginning letter of a note has little bearing on its content. There is a special case for you where you start with a date, but if we accomodate every little edge-case then we need to maintain all these options and this takes away resources from other things. :) Hope that explains it.

If you use the notes like a diary as you say, then if you don’t modify them after that date, the current "sort by most recently edited" should work for you, no?

**Comment by Iowaba** [comment]
Thank you very much for answering my request. This is an misunderstanding. My request is not a duplicate of #298, it is an extension to it. That's why, in my introductory part, I referred to question # 298. The example of the diary served only as an indication. Basically, with a high number of notes, it is advantageous to be able to sort them according to A-Z and Z-A. Regarding to your resources for far more important concerns and open-source projects, I can understand that. I thank you for your precious time in all your valuable open-source projects.

**Comment by jancborchardt** [comment]
@Iowaba thank you for your understanding and your nice comment! :)

Actually there might be something for you, as we recently released "Nextcloud Text": https://github.com/nextcloud/text

As you can use that from anywhere in the Files app, you can sort the folder alphabetically (or reverse) and there you go. :)
