### ISSUE TITLE
Use EasyMDE for Preview

### ISSUE THREAD

**Issue by tnyeanderson** [nextcloud/notes#329]
I took a look; we should definitely be using EasyMDE's preview functionality instead of Markdown-It. It supports checkboxes out of the box and prevents us from requiring another library. Here's what EasyMDE **does not** support that Markdown-It does:

- Emojis
- Blockquotes
- Images (displayed as block instead of inline, larger size
- Sub/Superscript
- Inserted text
- Marked text
- Footnotes
- Definition lists
- Custom Containers

Since we don't support these features anyway, making the switch makes sense.

Some useful notes for implementation:
Check if we are in preview mode: `easyMDE.isPreviewActive();`
Toggle preview mode: `easyMDE.togglePreview()`

This should be easy to implement. Then we can get rid of Markdown-It, AND have checkboxes available in preview mode :)

**Comment by korelstar** [comment]
This will be obsolete due to #331. Did you already did some implementation on this or can we safely close this issue, @tnyeanderson?

**Comment by tnyeanderson** [comment]
You're absolutely right. Closing.
