### ISSUE TITLE
Ugly code blocks printing since v3.0.0

### ISSUE THREAD

**Issue by Salokyn** [nextcloud/notes#338]
**Describe the bug**
Since v3.0.0, code blocks are not well rendered (at least on Chrome)

**To Reproduce**
1. Open a note
2. Insert a code block

ex:
>\```sh
>cd $HOME
>echo "alias ll='ls -l'" >> .bashrc
>\```
>

Or with lines beggining with 4 spaces

4. See spaces between lines

**Expected behavior**
There should not be spaces between lines inside a code block

**Screenshots**
https://privatebin.net/?dc65941fb7bc8cb5#D8vbGaBtE1oBYJJLaLEjXM4HYeaNJKbeEGxw9RakSWPk

**Server (please complete the following information):**
- Notes app version: 3.0.0
- Nextcloud version: 16
- OS: Debian 9
- Web server: nginx
- PHP version: 7.3
- Database: mariadb 10.3

**Client (please complete the following information):**
 - Browser (incl. version): Chrome 75
 - OS: Windows

**Comment by korelstar** [comment]
I was able to reproduce this on Chromium. The issue doesn't appear in Firefox, Edge or IE. I will provide a fix immediately.
