### ISSUE TITLE
Deleting a note doesn't remove the text

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/notes#342]
**Describe the bug**
The UI (right side of the app, where you write text - not the left sidebar with the list of notes) doesnt update when deleting a note. When you delete a note, the written text stays there. If you update the text, the left sidebar will try to catch on and update/save what you typed but since the note has already been deleted, an error comes up: "Updating note 9400 has failed. See JavaScript console for details."

**To Reproduce**
1 NEW NOTE
2 Start typing
3 Left sidebar - MENU -> DELETE NOTE
4 What you typed in 2) stays on screen, type some more text and the app will attempt to update the deleted note, unsuccessfully. Stream of errors will be shown.

**Expected behavior**
When you delete a note, the text must disappear.

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/36133540/61169831-f60d7a80-a561-11e9-8433-b90a8920d158.png)

**Server (please complete the following information):**
- Notes app version: 3.0
- Nextcloud version: 15

**Client (please complete the following information):**
 - Browser (incl. version): chrome 75.0
 - OS: w10

**Comment by korelstar** [comment]
I think we have to introduce a "deleting" state, in which the editor is disabled. When I find some free time, I will implement this.
