### ISSUE TITLE
Preformatted text is rendered incorrectly

### ISSUE THREAD

**Issue by taikedz** [nextcloud/notes#349]
**Describe the bug**

When a markdown codeblock is used like

    ```yaml
    data:
      moredata:
    ```

it simply renders as

> `data:`
>
> `moredata:`

when viewed in the Nextcloud Notes browser view.

## Environment

* Firefox 67.0.4
* Ubuntu 18.04

**To Reproduce**

* Create a new note
* Start a code block with "\`\`\`", and add some preformatted text
* See that it does not render a preformatted block, but a series of preformatted paragraph-lines
* Inspect the raw file data to see that it is potentially correct

**Expected behavior**

The same type of rendering as here on Github (example above)

**Screenshots**

![nextcloud_notes_yaml](https://user-images.githubusercontent.com/231984/62147056-9d263c00-b2ee-11e9-8ae3-68516860abe3.png)

**Server (please complete the following information):**
- Notes app version: 3.0.1 (just updated)
- Nextcloud version: 16.0.3
- OS: Ubuntu 16.04 server
- Web server: Apache2
- PHP version: PHP7
- Database: MySQL

**Client (please complete the following information):**
 - Browser (incl. version): Firefox 64
 - OS: Ubuntu 18.04

**Log files**

(none relevant?)

**Comment by korelstar** [comment]
I can reproduce this issue. It looks that this was introduced with #321 and not fixed by #340.

Currently, I can't see a fix for this issue other than reverting #321 and #340. Then, we will lose the nice looking code block style, but with realizing #331, we will have it back again. So I think, this is fine for now.

**Comment by taikedz** [comment]
Looking forward to getting this in. Thanks! :tada:
