### ISSUE TITLE
Allow to set notes title via the API

### ISSUE THREAD

**Issue by milohr** [nextcloud/notes#351]
When using the API to create a new note, according to the documentation, the title field is not available. If I, however, set a value to the title field, it is ignored and instead, it picks the first line fo the content as the title. 

It would be better that the endpoint to create the notes would take the title field as a parameter

I'm working on a third-party app to integrate with it, it works on phones with plasma mobile, android and also on desktop.
https://invent.kde.org/kde/buho

**Comment by stefan-niedermann** [comment]
Dup of #190 and #289 and #55 and #24.

Please see especially last comment in #289

Thank you

**Comment by stefan-niedermann** [comment]
app looks nice btw :)

**Comment by stefan-niedermann** [comment]
@korelstar maybe we can mention it in the wiki: https://github.com/nextcloud/notes/wiki
