### ISSUE TITLE
Default note view in preview mode

### ISSUE THREAD

**Issue by probastaller** [nextcloud/notes#352]
**Describe the solution you'd like**
I would like, if possible, to open the already written notes in preview formatted mode instead of edit mode. Or if it is not massive desirable, the option to chose default view in the settings would be great. In preview mode, links are clickable and text is cleaner and easier to read.

Thanks for your time :)

**Comment by zaphodus** [comment]
It would be improve usability

**Comment by frauhottelmann** [comment]
It woul increase the readability of the notes that already exist. The android app has a setting for this as well.

**Comment by goofus** [comment]
Why is this closed? Does the option exist now?

**Comment by goofus** [comment]
That's exactly the feature I am missing. Please add an option to open existing Notes in View Mode!

**Comment by korelstar** [comment]
After realizing #331, there is no differentiation between edit mode and preview mode anymore - there will be only one single mode. Hence, this setting would just be relevant for a short period of time.

**Comment by manfredu** [comment]
> After realizing #331, there is no differentiation between edit mode and preview mode anymore - there will be only one single mode. Hence, this setting would just be relevant for a short period of time.

This does makes sense to me. Is there an estimation when #331 will be realized?

**Comment by korelstar** [comment]
No, sorry. We hadn't enough free time for this, yet.

I would accept a PR for a default view mode setting as interim solution, though.

**Comment by Baptistou** [comment]
> After realizing #331, there is no differentiation between edit mode and preview mode anymore - there will be only one single mode. Hence, this setting would just be relevant for a short period of time.

There are still some differences between the two modes :
- Line endings are rendered in edit mode but preview mode requires 2 consecutive line endings to end a paragraph.
- Markdown Tables are rendered in preview mode but not in edit mode.
- Preview mode prevents you to modify a note accidentally.

Therefore, a default setting is still relevant.

**Comment by arkadym** [comment]
> After realizing #331, there is no differentiation between edit mode and preview mode anymore - there will be only one single mode. Hence, this setting would just be relevant for a short period of time.

Yes, it is cool one, but still is not exaclty what we are discussing here, i still prefer able to see notes in preview mode by default.
Btw, #331 is missing tables support feature.

**Comment by Fuseteam** [comment]
this would a nice setting, where should one look to add the settings? how does one test?

**Comment by korelstar** [comment]
I think the following steps have to be done:

- PHP backend: add new setting `viewMode` in [`NotesService`](https://github.com/nextcloud/notes/blob/master/lib/Service/SettingsService.php) (like the existing setting `fileSuffix`, use values `edit` und `preview`)
- JS frontend settings: add drop-down for changing that setting in [`AppSettings`](https://github.com/nextcloud/notes/blob/master/src/components/AppSettings.vue)
- JS frontend note: load setting from store in [`Note`](https://github.com/nextcloud/notes/blob/master/src/components/Note.vue) and process it.

Unfortunately, we currently have no GUI tests, but syntax and code style checks (run `make lint`).

**Comment by Fuseteam** [comment]
Cool thanks for explaining, with test i mean more in the sense of seeing the changes i made

**Comment by korelstar** [comment]
I'm not sure if I understand you correctly. You will have to run `make build-js` and replace the notes app for in your Nextcloud installation. Then, if you chose the setting `view`, notes should open directly in preview mode, otherwise the behavior should like before.

**Comment by Fuseteam** [comment]
ah build with make build-js and replace it in nextcloud, thanks that's what i wanted to know

**Comment by Baptistou** [comment]
For those interested in this default setting and waiting for it to be implemented, I use the following workaround script with [JSLoader](https://apps.nextcloud.com/apps/jsloader).
When Notes app loads a page, this script triggers `CTRL + /` and thus switches to preview mode.

```javascript
document.addEventListener("DOMNodeInserted",function(event){
    if(event.relatedNode.matches(".app-notes #app-content-vue"))
        document.dispatchEvent(new KeyboardEvent("keydown",{"key": "/","ctrlKey": true}));
});
```

**Comment by korelstar** [comment]
Implementation is in #747, please have a look 😃
