### ISSUE TITLE
Add padding to table cells

### ISSUE THREAD

**Issue by CodeAlDente** [nextcloud/notes#355]
**Is your feature request related to a problem? Please describe.**
In reference to #115 tables are supported now. When I add them to a note and take a look at the preview, there is no padding inside the cells. This results in a difficult readability as you can not tell where the content of a cell starts and where it ends.

**Input**:
```
| First head   | Second head  | Third head   |
|--------------|--------------|--------------|
| ABC123456789 | DEF123456789 | GHI123456789 |
| JKL123456789 | MNO123456789 | PQR123456789 |
| STU123456789 | VWX123456789 | YZ123456789  |
```

**Output**:
![1566896755-001](https://user-images.githubusercontent.com/10899559/63757601-aa692300-c8ba-11e9-8c39-dc14f3b97e5a.png)

**Describe the solution you'd like**
Padding must be applied to the cells.

**Describe alternatives you've considered**
In addition to that it would be nice to apply `font-weight: bold` to thead to differ them from the tbody. Also the tables width should be set to 100% to make use of the whole space.

**Additional context**
See above.

**Comment by korelstar** [comment]
Yes, we could adjust the style for the preview mode. How about that?

![Screenshot](https://user-images.githubusercontent.com/6277619/63885346-784de300-c9d8-11e9-8a01-3944871fa835.png)

- [x] `th` is bold
- [x] `th` and `td` has `1em` padding
- [ ] table width is still auto, since 100% doesn't make sense in most cases

**Comment by CodeAlDente** [comment]
Looks much better. What about 1.5em? Just to be sure.

**Comment by korelstar** [comment]
I'm fine with that, see #362
