### ISSUE TITLE
When the notes are in full screen, the wording of reduction is incorrect

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/notes#365]
I noticed that when I put the notes in full screen the words Full Screen does not change to make the screen smaller, or it returns to the window but remains as always "full screen" and not "shrink the screen" obviously I speak of the Italian language I do not know the others. I enclose Screenshot

![Immagine](https://user-images.githubusercontent.com/35575744/64410591-a774ec00-d08b-11e9-84e1-2448c3908cf9.png)

**Comment by korelstar** [comment]
You're right, currently the label doesn't change. The plan is to visualize the state of this action (enabled/disabled). However, this isn't supported yet. Please see https://github.com/nextcloud/nextcloud-vue/issues/425 for a discussion on how to improve this. My plan is to wait for a fix over there.

**Comment by skjnldsv** [comment]
> The plan is to visualize the state of this action (enabled/disabled)

Wait, why don't you just change the wording and the icon?
#425 have nothing to do with that? It's about feedback on hover/focus/active :)

**Comment by korelstar** [comment]
Oh yes, the referenced issue is exactly about this problem! When the proposal ( https://github.com/nextcloud/nextcloud-vue/issues/425#issuecomment-527914136 ) is implemented, the full-screen action will appear with a blue bar when active (hover is in gray then!). There is no need to change text and icon anymore, since the activated state is indicated by other means.

But if you see a high priority for this, we could implement an intermediate fix by using another text and icon. Which one do you suggest?

**Comment by skjnldsv** [comment]
I think it's a not a proper ux. What happens if you click on it again when it's full screen?

**Comment by korelstar** [comment]
The action is not active anymore (and full screen is deactivated). This is typical behavior in UI elements. Please have a look on my explanations in https://github.com/nextcloud/nextcloud-vue/issues/425#issuecomment-499891410 and the following remarks by @jancborchardt

**Comment by skjnldsv** [comment]
If your click is deactivating the fullscreen, then it's not an active state you're looking for, but a toggle. It's confusing, the button should instead just say "disable full screen" or similar. :)

We don't use an active state anywhere else on nextcloud, either this is a setting that is on/off, then we use a checkbox, or this is a state, and therefore we have a toggle with different icons and text :)

**Comment by korelstar** [comment]
Okay, then I had an misunderstanding of this.

So, when I want to use a checkbox, I can't use an icon?

Then, I think the best would be to use a toggle different icons and text. Which one do you suggest for this? "Disable fullscreen"? Which icon?

**Comment by skjnldsv** [comment]
Well, this is my view of this, but I might be wrong :)
Using a checkbox is for a setting or a config. Changing the icon is for a state change.

![dev skjnldsv com_apps_files__dir=_ (1)](https://user-images.githubusercontent.com/14975046/64763647-bdc5f080-d540-11e9-97f4-0e8885159220.png)
![dev skjnldsv com_apps_files__dir=_ (2)](https://user-images.githubusercontent.com/14975046/64763634-b868a600-d540-11e9-96f3-e908bb9dc61e.png)

What do you think of that? cc @jancborchardt
