### ISSUE TITLE
Enhancements and new Features

### ISSUE THREAD

**Issue by janis91** [nextcloud/notes#37]
Hi, my first review of the official notes app is done and I want to summarize it a little from my point of view:

1. Missing feature: tagging
2. Problem with Sharing
3. (more in the future) Sharing with externals

1: For me it would be a big enhancement. If you are able to tag your notes and you have a search for it available, it would be much easier to oversee a large amount of notes. 
The tagging feature could be a big advantage for some users.

2: In two cases the storing of the notes within the files app is a problem in case of sharing the notes with others:

- User 1 has already been using the notes app and now gets the "Notes" folder shared by User 2. This will result in a "Notes (2)" folder which will not be recognized by the app.
- User 1 only wants to share a specific note with User 2. The note will be displayed in the root directory of User 2 and will not be recognized by the app either.

IMHO this is not the behaviour a typical end user would expect, if it wants to share a specific note or all notes (the folder) to another user, which is also using the app.

3: Another point is the cloud as a paradgim: as a user you maybe would expect to have the ability of sharing your notes to external parties. This is actually possible via the files app, but wouldn't it be nicer to display these notes within the notes app itself? (just a prospect)

**Comment by JSoko** [comment]
No opinions on this detailed review?

For me as a user, it would be great to have a powerfull notes-app under Nextcloud.

**Comment by korelstar** [comment]
These are definitely good points.

ad 1.: Would you insist on tags or are categories fine as well? We have a discussion on this (see #8) and such a feature is definitely on the agenda.

ad 2.: I'm looking forward to such a feature, too. The easiest way to improve this situation, would be to finish #6 and then share sub-directories. However, sharing should be possible directly from the notes app -- in my point of view. But this could be implemented afterwards.

ad 3.: I think this idea is now adopted in #38.

Finally, I think your demanded features are definitely on the agenda of this notes app (maybe @Henni as the current "leader" can confirm this). So if your participation depends on putting these features on the agenda of this app (see https://github.com/janis91/nextnotes/issues/39#issuecomment-270637799), I say: welcome on board! :smiley:

**Comment by gsantner** [comment]
Just my 2 cents:
> 2: In two cases the storing of the notes within the files app is a problem in case of sharing the notes with others:
> 
>     User 1 has already been using the notes app and now gets the "Notes" folder shared by User 2. This will result in a "Notes (2)" folder which will not be recognized by the app.
>     User 1 only wants to share a specific note with User 2. The note will be displayed in the root directory of User 2 and will not be recognized by the app either.
> 

I, as a user would still like to have an **easy** access to the notes everywhere, and don't have to open the WebUI for them. Usually I edit them with just a plain note editor on my computer, and don't have an specific Note app on my phone, I would still prefer to be able to retrieve/edit/modify them in plain without any hassles, and still be synchronized. 
I don't know how I would solve this with the pointed sharing stuff, but for the local part I would still prefer to be able to edit them without any additional software.

**Comment by korelstar** [comment]
@gsantner 
Do you worry about the functionality of the notes app or about the functionality of synchronizing files with Nextcloud in general?
The sharing API of Nextcloud is quite transparent, so your WebDAV client only see files and directories, which then can be edited with any editor of your choice. It is very likely, that any sharing functionality of the notes app will be realized using this sharing API. Therefore, I don't see any problems for your use-case.

**Comment by korelstar** [comment]
@janis91 
> User 1 only wants to share a specific note with User 2. The note will be displayed in the root directory of User 2 and will not be recognized by the app either.

Workaround: Rename your shared file `shared-file.txt` to `Notes/shared-file.txt`. Then you can edit the shared file with the notes app!
However, this should indeed be optimized for the users.

**Comment by gsantner** [comment]
@korelstar About the notes app. The nextcloud sync file algorithm itself shouldn't (and cannot I think) be touched by anything else than the core&files app.
Yeah, it's just about that I can still use gedit/vim/nano/whatever to edit (at least my own) notes at desktop.

**Comment by sunjam** [comment]
I’d like to be able to share notes with:

- other users on my local instance
- [federated circles](https://apps.nextcloud.com/apps/circles) of remote users
- attach to tasks
- attach to calendar events
- attach to contacts
- attach to files
- attach to gallery
- attach to Bookmarks
- attach to Nextcloud Talk conversations.
- attach to admin and personal settings
- attach to one time password generation so I remember specifics of what the password is for.
- [Circles descriptions issue #167](https://github.com/nextcloud/circles/issues/167)
- share with a public url as though it were a file or just html
- share with a url and add a one time password that can be given to multiple users
    
It’d be great to be able to add Comments support to Notes
- allow other federated users to comment on notes you’ve shared.
- allow unauthenticated users to comment on notes
- Allow any of these comments to be visible within the Notes app.
    
Collaborative Tag support would be really helpful if Notes did expand to all of the different Nextcloud apps above.  Tags could also make it easier to search through notes, and perhaps they would be treated as “categories” inside the app.

**Comment by jancborchardt** [comment]
This issue has too many individual topics in it. As @korelstar already referenced above, the relevant issues are:

- #8 for categorization
- #38 for sharing notes

So I’m closing this one. In the future, please open separate issues for each topic. :)
