### ISSUE TITLE
CTRL+C not working

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/notes#378]
Title says it all.

Reproduce:
1 New note
2 Put some text
3 CTRL+C
4 try pasting somewhere, nothing will be pasted

Nextcloud 15; Notes 3.0.2, Firefox 69 (Chrome is working)

**Comment by korelstar** [comment]
I'm not sure if I understand you correctly. Do you want to copy the whole note or the selected part of the note? The latter works for me (open note, press CTRL+A to select all, then press CTRL+C to copy). Please be more precise and provide more information about your environment (e.g. client operating system).

**Comment by pilsnerbeer** [comment]
Nothing works - not selecting a piece of text or all. I was sure to disable any plugins on my browser beforehand but likely there must be some bad configuration as I just tried it on my other PC and it worked. The client OS is Windows 10. I will close this issue as it seems the bug can't be reproduced on your side.
