### ISSUE TITLE
Add Markdown table support in edit mode

### ISSUE THREAD

**Issue by drosan-dev** [nextcloud/notes#379]
can you make markdown tables mapping in edit mode?

**Comment by korelstar** [comment]
The currently used library doesn't support this and even the to be integrated editor from Nextcloud Text (see #331) doesn't have this feature. But a feature request also exists over there: https://github.com/nextcloud/text/issues/114

So let's wait until these two issues have been implemented.

**Comment by PatrickHuetter** [comment]
This would be a huge improvement. The main thing we're missing in the nextcloud markdown editor (and in collectives) are tables.

**Comment by stefan-niedermann** [comment]
@PatrickHuetter Collectives uses https://github.com/nextcloud/text/ as editor.

**Comment by ktprograms** [comment]
Hi, I think I may have thought of a way to edit tables in a html `textarea`, inspired by emacs org mode tables.

You can try it out by opening https://ktprograms.codeberg.page/table_editor_html/@master/, the instructions are at the top of that page.

You can leave feedback on the [issues page for my repo](https://codeberg.org/ktprograms/table_editor_html/issues), or on this issue thread.

Thanks!

**Comment by joshtrichards** [comment]
Markdown Tables are now fully supported.
