### ISSUE TITLE
Show number of characters and size of note file

### ISSUE THREAD

**Issue by CodeAlDente** [nextcloud/notes#382]
**Describe the solution you'd like**
There is already a counter that shows the number of words in a note. It would be great to also show the number of characters and the size of the file in a human readable way.

**Comment by stefan-niedermann** [comment]
What's your use case? What do you expect by this information and how do you use the information?

I thinkt his is some very technical info that most users do not care about.

**Comment by CodeAlDente** [comment]
Well, why do people need the counter for words then? There is a use case for that and an additional counter would perfectly go along with that. Same for the file size. I'm rather more interested in the amount of characters than in words tbh.

**Comment by stefan-niedermann** [comment]
cc @jancborchardt

**Comment by jancborchardt** [comment]
> Well, why do people need the counter for words then?

Cause this is a very common thing for writing of any kind like in academia, reporting, etc.

What we could do is show a character count on hover of the word count. But file size is so negligible for Notes files, we don’t need to bother including that.

**Comment by CodeAlDente** [comment]
Okay, that would be nice. Maybe it is possible to get the file size of the note through the API of Nextcloud? In my case I need to submit reports with a certain amount of characters and a max file size of 5 KB. So it would be great to have that information inside the note so I do not have to look it up every time.

**Comment by jancborchardt** [comment]
The character count seems to match up pretty well with the byte / KB count, no? 5 KB is very roughly 5000 characters. If there’s a character count on hover of the word count, and you have a certain amount of characters as limit, then that’s that.

**Comment by CodeAlDente** [comment]
If you only use latin characters. In my case I'm also using cyrillic characters which take a bit more space. But you are right, it would be a good idea to determine the size based on the amount of characters. Even though I'd like to see that information inside the note through the API. Just to save time on that as it might not be that huge benefit for everyone.

**Comment by stefan-niedermann** [comment]
If you need it via API: The notes are stored as usual files, have you tried to access the size-information via the WebDAV API of the Nextcloud files app?

**Comment by korelstar** [comment]
@jancborchardt 
> What we could do is show a character count on hover of the word count. But file size is so negligible for Notes files, we don’t need to bother including that.

`@nextcloud/vue` doesn't let us define a hover, here. What about showing both things directly? E.g., `3 words / 16 characters`

**Comment by jancborchardt** [comment]
> What about showing both things directly? E.g., `3 words / 16 characters`

Sure, sounds good. Let’s use a simple comma though:

> 3 words, 16 characters
