### ISSUE TITLE
Add some screenshots for the app store

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/notes#40]
Linking https://github.com/nextcloud/appstore/issues/403

Please also provide a small-thumbnail, see https://nextcloudappstore.readthedocs.io/en/latest/developer.html#info-xml for more information

**Comment by korelstar** [comment]
For the screenshot, there is already a PR: #34. I think it is ready for being merged now, hm? @Henni
However, the small-thumbnail is still missing.
