### ISSUE TITLE
Allow resync index of note

### ISSUE THREAD

**Issue by murlock** [nextcloud/notes#402]
**Describe the bug**

I've launch one of my internal tool that concat files (and remove them) to another filer  in `notes` directory.

The old files are still shown in Notes web interface and new one is of course missing.  

**To Reproduce**
1. Go to `{nextcloud_data}/{user}/fies/Notes`
2. Launch `cat http*.md > links.md; rm http*.md` 

**Expected behavior**

Of course, I've misunderstood how Notes App was managing notes but I didn't found a way
to force synchronize files and index.

I've written a script to fix unwanted entries using API https://gist.github.com/murlock/88f33776731b917fc1cfc3711def92f4

**Server:**
- Notes app version: `3.0.3`
- Nextcloud version: ` 16.0.5`
- OS:  `Ubuntu 19.04
- Web server: `nginx/1.15.9` 
- PHP version: `7.2.24-0ubuntu0.19.04.1`
- Database: `mysql  Ver 14.14 Distrib 5.7.27`

**Log files**
Add relevant parts of your `nextcloud.log` and/or your browser's JavaScript console here.
```
{
  "reqId": "tuf4viC3Ot2MnzTHqSf6",
  "level": 3,
  "time": "2019-10-30T20:24:03+00:00",
  "remoteAddr": "XXXX:YYYY:ZZZ:AAAA:BBBB:CCCC:DDDD:EEEE",
  "user": "XXXX",
  "app": "PHP",
  "method": "GET",
  "url": "/apps/notes/notes/480936",
  "message": "file_get_contents(/home/opt/nextcloud_data/murlock/files/Notes/httpXXX.txt: failed to open stream: No such file or directory at /home/opt/nextcloud/lib/private/Files/Storage/Local.php#217",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0",
  "version": "16.0.5.1"
}

```

**Comment by stefan-niedermann** [comment]
Have you tried occ:scan command?

**Comment by korelstar** [comment]
What you describe is not specific to the notes app. If you change files directly in the file system, you always have to resync them with your Nextcloud. In order to do this, you have to execute`php occ files:scan {username}` in your Nextcloud installation directory on your server.

**Comment by murlock** [comment]
Thanks
I've forgot to try `php occ files:scan {username}/files/Notes` !
