### ISSUE TITLE
feature request - save/sync button

### ISSUE THREAD

**Issue by xxKeith20xx** [nextcloud/notes#411]
**Is your feature request related to a problem? Please describe.**
Going between computers and my phone, sometimes I run into sync issues due to the previous client not syncing as soon as I expect it to. 

**Describe the solution you'd like**
Some kind of sync/save button would be nice to ensure the work I've done is saved.

**Describe alternatives you've considered**
knowing the exact way to trigger the sync or how long it takes

**Additional context**
Also using nextcloud notes android app

follow-up to https://github.com/nextcloud/notes/issues/300

**Comment by korelstar** [comment]
What is the exact problem? a) changing notes in the web app doesn't save that note to the server; or b) changed notes from other devices are not shown in the web app?

for a): If this happens, there is a connection problem. But this should be shown with a red exclamation mark. Furthermore, unsynced notes are shown with an asterisk behind the note's title in the app navigation.

for b): This is not implemented, yet. Currently, you have to reload the notes app. My plan was to implement reloading the notes list in one of the next releases. But a full sync of the current note during editing requires #331. This will still take some time.

**Comment by xxKeith20xx** [comment]
I think the main issue is when making changes on mobile actually. I've noticed the notes web app saves almost immediately but the mobile app I'm pulling to refresh/sync to be sure.  <3
