### ISSUE TITLE
Display problem when in preview mode / click hyperlink problem when in editing mode

### ISSUE THREAD

**Issue by Blockligne** [nextcloud/notes#428]
Hi all, 
The hyper links don't show on my browser when in preview mode
![image](https://user-images.githubusercontent.com/58459583/71715284-395ded00-2e11-11ea-9941-11ee325f719c.png)

The hyperlinks are not clickable when in editing mode.
![image](https://user-images.githubusercontent.com/58459583/71715331-54c8f800-2e11-11ea-84ad-977d10924100.png)

**Comment by korelstar** [comment]
Please give more information about your environment, since I can't reproduce this issue. All information from the issue template could be helpful:

**Server (please complete the following information):**
- Notes app version: 
- Nextcloud version: 
- OS: 
- Web server: 
- PHP version: 
- Database: (irrelevant here)

**Client (please complete the following information):**
 - Browser (incl. version): 
 - OS: 

----

Do you use a custom theme or changed the colors on your Nextcloud instance?

**Comment by Blockligne** [comment]
After a quick check, you were right, the color of the header in the global display parameters of Nextcloud was #FFFFF (plain white), which on a white backgroud did not show. 
![image](https://user-images.githubusercontent.com/58459583/71821072-6ae4eb80-3091-11ea-85fa-015499a1076a.png)

This means a the hyperlink display setting should be set appart from the global color of the header in order not to be affected by color change in  the nextcloud environnement. (the other apps don't behave the same way - Deck for instance).

Thanks for your help

**Comment by korelstar** [comment]
Deck and Tasks use the default link color, which is `--color-main-text` which is light gray by default, and set opacity to 0.5 and add an underline. Notes leaves opacity and text-decoration untouched but sets the color to `--color-main-text` which can be white if the admin defined this.

@jancborchardt What do you suggest? Should we use the (colorless) style from the Deck app? Is there another color we could use?

**Comment by jancborchardt** [comment]
Theming color only influences the `primary` color, not `--color-main-text`, so the issue has to come from somewhere else?

cc @juliushaertl 

------

The "links are not clickable in preview mode" is a separate issue and yes, that should of course work. :)

**Comment by korelstar** [comment]
Sorry, there was an error in my comment. The notes app uses `--color-primary` for links in preview mode. So, again: @jancborchardt What do you suggest? Should we use the (colorless) style from the Deck app? Is there another color we could use?

**Comment by jancborchardt** [comment]
If you use primary that’s fine, but then you have to use `var(--color-primary-element)`. This basically is the same as `var(--color-primary)`, but when the theming color is so that the contrast with the background is too low, it doesn’t go lighter and stays at a grey. :)

**Comment by Blockligne** [comment]
This seems perfect. Thank you all for trying to resolve this issue.
Happy new year and long live NextCloud !

Le 13/01/2020 à 23:49, Jan-Christoph Borchardt a écrit :
