### ISSUE TITLE
Fetching notes has failed. See JavaScript console for details.

### ISSUE THREAD

**Issue by alcir** [nextcloud/notes#429]
**Describe the bug**
Notes display a blank screen with a little "!" on the left and "Fetching notes has failed. See JavaScript console for details.✖" on top right.

**To Reproduce**
1. Click on 'Notes'

**Server (please complete the following information):**
- Notes app version: 3.1.1
- Nextcloud version: Nextcloud 17.0.2
- OS: Ubuntu 18.04.3
- Web server: Nginx 1.17.7
- PHP version: 7.3.13
- Database: Mariadb 10.4.11

**Client (please complete the following information):**
 - Browser (incl. version): Firefox 71
 - OS: Fedora 31

**Log files**
Browser's JavaScript console:

Error: "Request failed with status code 500"
    exports https://server.com/apps/notes/js/notes.js?v=c181ac3f-0:946
    exports https://server.com/apps/notes/js/notes.js?v=c181ac3f-0:960
    onreadystatechange https://server.com/apps/notes/js/notes.js?v=c181ac3f-0:946
    fetchNotes https://server.com/apps/notes/js/notes.js?v=c181ac3f-0:972

https://server.com/apps/notes/js/notes.js <--- this is reachable

**Comment by korelstar** [comment]
That's strange. The notes app doesn't add that `?v=c181ac3f-0` part and I haven't seen that the Nextcloud server add it neither.

Nevertheless, such a request should not fail on your web server (I tested with apache and also with Nginx). Hence, please have a look at your web server configuration and logs. The reason for a status code 500 should be explained in your web server's log file. What's logged there?

**Comment by szaimen** [comment]
I think I have the same error. maybe this is because my home folder is not writeable?
This is the first time I open the app and /files/userid/notes is not there and cannot be created.
A few versions it was then possible to go into notes settings to define the path. Afterwards everything worked. But not now.

**Comment by szaimen** [comment]
here are screenshot:
![image](https://user-images.githubusercontent.com/42591237/73259042-39120100-41c7-11ea-9922-24ef4b9d77c2.png)
![image](https://user-images.githubusercontent.com/42591237/73259101-5050ee80-41c7-11ea-8e25-f51ae114cd1f.png)

**Comment by korelstar** [comment]
@szaimen I think your problem is the same like in #436. I'm working on a fix for this.
