### ISSUE TITLE
Search is not where expected

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/notes#43]
Hi @Henni ,
i recently updated the app and was happy to see the search functionality.
Though i didn't expect it in the left sidebar but in the top right corner next to the user name where it is in the files, contacts and calendar app, too.

So this is a request to move it to the well-known place :)

PS.: Works great! :)

cc @nextcloud/designers

**Comment by DirkR** [comment]
Hi @stefan-niedermann,
look at the "search function" as a filter: it filters the list of articles matching the search pattern in note title as well as body. Thus that's the correct place.

We might discuss, if the glass icon is the best icon for this job (=field). I would prefer a funnel. And one could argue, that the input field is somewhat hidden thanks to the "flat" design. A really visible input field might be better/more helpful. But the place is correct (IMHO).

**Comment by Henni** [comment]
@jancborchardt would love to have your feedback on this, as we talked about this a while ago.

**Comment by Bugsbane** [comment]
> it filters the list of articles matching the search pattern in note title as well as body.

I would expect that most users would think of this as "Search" and thus look for it with the traditional search icon and UI location, as the original poster did on this issue.

**Comment by eppfel** [comment]
..and even if we provide full-text search later, the main use-case is finding the right note.

**Comment by jancborchardt** [comment]
So, thinking about this it seems that uniformity with the other apps is more important than the value of experimenting with a new position for the search.

That’s a separate topic though still. With other considerations like accessibility on mobile – if it’s in the top of the sidebar, searching will be difficult to access and require a two-step process, if it’s discovered at all. Unlike the top right spot which people are used to from Android and also iOS to a certain extent.

So @Henni if you agree then the sensible solution might be to use the normal search field position after all.

**Comment by splitt3r** [comment]
Related to this it would be nice if the "Add note" button would look the same as the "Add contact" button.

![add_note](https://cloud.githubusercontent.com/assets/1869584/22699145/ea818cbc-ed56-11e6-9843-87d2a4c4405e.png)

**Comment by stefan-niedermann** [comment]
@jancborchardt @camilasan and i discussed this topic again in a design review at the hackweek and we came to the conclusion that even if it is technically *filtering* and not *searching* (what i do not aggree), the input should be on the top right position.

**Comment by skjnldsv** [comment]
@stefan-niedermann I'll introduce a new standard for the search button soon :)

**Comment by jancborchardt** [comment]
@skjnldsv anything we could implement here already? :)

Or could we fix it even without that new standard @nextcloud/notes?

**Comment by skjnldsv** [comment]
@jancborchardt Actually, there is already a standard for the search, so it might fit the needs of the notes app already :)
The lack of documentation is unfortunate though :/

The only work will be to make the standard 'standardized' enough so our new vue apps can work with it

**Comment by jancborchardt** [comment]
@skjnldsv as this app is still in Angular, it would be awesome to get some pointers on how to use the standard way of searching in the Notes app for the time being. :)

**Comment by skjnldsv** [comment]
Look at the JavaScript file that handle the search in server!
Lots of comments it seems ;)

**Comment by korelstar** [comment]
Nextcloud 14 will introduce a complete new search, see nextcloud/server#9912. However, as far as I can see, this will not be backwards-compatible. How to proceed?

The easiest way would be to
- implement new search, but activate it only if the server runs on Nextcloud 14 (how to check this?), and
- remove our search field in the Navigation (since we don't want to implement two searches)

This means, however, that users on Nextcloud 13 or older can't use the search. How do other apps cope with this?

**Comment by skjnldsv** [comment]
@korelstar Apps will need to set their min-version of nextcloud to 14.
The search standard is just a hook so that anyone can use it though. So the differences between a search in 13 and 14 are not that big and search still needs to be managed internally by apps. :)

**Comment by korelstar** [comment]
I don't think that we should exclude Nextcloud 13 and older just due to the search. Isn't there a possibility to check the current version and execute the app's search code on Nextcloud 14 upwards, only?
