### ISSUE TITLE
Store notes in CalDAV/VJOURNAL -> (closed)#197

### ISSUE THREAD

**Issue by peedy2495** [nextcloud/notes#432]
Sorry, but this feature is really wanted ...

Meaning of a PIM is to work under one hood.
Well, it's strange to tell users to use this feature here and the other feature there.
An then ... they tell u're silly to "set up a system" such this "experimental Cloud" and last: Hey dude, Google and M$ can do this and u won't. Aehm, why u're using Linux?

Sorry, again. But welcome to my life ...

**Comment by stefan-niedermann** [comment]
I could imagine additional apis to the outside like a wrapper / mapper if this is something that @korelstar wants to implement.

Alternatively one could write an additional serverside nextcloud app which uses the same storage backend.

We are not microsoft neither google, we do not have the budget neither the time. But we have a huge community and the project develops from the people who want features and are willing to contribute. If noone contributes, the pain is not high enough for the users to have a free solution 🤷

To push this forward, @peedy2495 maybe you want to maintain one of the proposed solutions or start a new new project / pull request where volunteers could contribute? 🚀 Or, if you are not a coder, put a bounty on this to motivate other volunteers?

**Comment by korelstar** [comment]
Hmmm. #197 was about to store the notes in a CalDAV/VJOURNAL backend instead of the filesystem. I still think that we shouldn't add multiple storage backends to the notes app.

The proposal by @stefan-niedermann is about providing a new API, so that clients could use the CalDAV/VJOURNAL API in order to access notes stored in the filesystem. This sounds interesting, but I don't know if this is what @peedy2495 intended. Honestly, the issue description is really hard to understand. So please be more precise in a technical way what this issue is really about (more than just the title and some general complaining).

**Comment by stefan-niedermann** [comment]
@peedy2495 please clarify what exactly you mean.

**Comment by peedy2495** [comment]
Most open source PIMs like evolution, kontact, etc are using dav-sources for notes, only.
As the title of this issue describes: a dav source to use notes over all platforms is needed.

**Comment by peedy2495** [comment]
... explicitly a CalDAV/VJOURNAL-source is reqested.

**Comment by stefan-niedermann** [comment]
So your intention is either
- that **3rd-party clients** are able to **access** Notes via `CalDAV` / `VJOURNAL API` or
- that the **server-app** just **stores** the notes in the `CalDAV` / `VJOURNAL`

Based on [your comment ](https://github.com/nextcloud/notes/issues/432#issuecomment-575983130) i guess you want the first one. In this case: See [my comment](https://github.com/nextcloud/notes/issues/432#issuecomment-571195135).

---

Are you using Google translate or any other translation tool? It is really very hard to understand what you are trying to tell us.

**Comment by peedy2495** [comment]
[lang=DE-de]
Entschuldigen Sie, dass mein syntaktisch/grammatikalisches Unvermögen Ihre Auffassungsgabe übersteigt.
Sie können dieses Issue schließen.
Vielen Dank für Ihre Zeit, wie auch die gezeigte Hingabe.
In Indien hätte man Sie hierfür sicher heilig gesprochen.
[lang=default]

[COMMUNICATION CLOSED]

**Comment by korelstar** [comment]
Okay, no problem.
