### ISSUE TITLE
Return HTTP Status 507 when storage is full

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/notes#438]
See https://github.com/stefan-niedermann/nextcloud-notes/issues/679

Currently `HTTP Status code 500` is returned. It would be much better if the clients could display an appropriate error message **why** the sync failed :)

**Comment by stefan-niedermann** [comment]
Great! I assume, `3.1.2` will ship this improvement?

**Comment by korelstar** [comment]
Yep, see milestone :wink:

I think I will release it in the next few days (want to wait for Transifex translations for new error messages on web frontend).

**Comment by stefan-niedermann** [comment]
Nice, i will await the final release. Then i am able to test it on my testing instance without messing around with direct deployments from the git repository :wink:
