### ISSUE TITLE
Discussion: Style 'add note' as button

### ISSUE THREAD

**Issue by Henni** [nextcloud/notes#44]
Should we style the 'add note' action like a button? This would align notes to other apps like contacts:
![](https://cloud.githubusercontent.com/assets/6277619/19726700/745d175c-9b8c-11e6-8f78-d12336c9b7ee.jpg)

see also:
https://github.com/nextcloud/notes/pull/42#discussion_r94250427

cc @nextcloud/designers

**Comment by skjnldsv** [comment]
Yes, we should aim to uniform designs :)

**Comment by MariusBluem** [comment]
👍

**Comment by jancborchardt** [comment]
I agree with this, yes. It makes the primary action clearer and we do this in Contacts & Mail as well. (And to some extent in Files and Calendar)

**Comment by Henni** [comment]
Looks like we currently don't have a `.primary-button` style in core.
I think we should change that so that we can reuse it in contacts, mail and here in notes.

**Comment by skjnldsv** [comment]
I completely agree.
Should be in apps.scss. A `#app-navigation > .primary-button-container > button.primary-button`?

- Mail has its button inside a div
- Contacts has it inside a custom element (which a class can be easily applied)
- Calendar has 3 buttons (previous, month and next) maybe we should uniform the `.primary-button-container` with some flexbox to be compatible with that too?

**Comment by Henni** [comment]
I would ignore calendar and just define a simple primary button.

A wrapper element like `.primary-button-container ` shouldn't be necessary. And maybe we should even remove #app-navigation to allow primary buttons in the app-content.

Also: Do we only want button or also input[type=button]?

**Comment by skjnldsv** [comment]
Since every app is using a wrapper, it could be useful to think twice about it.
I agree with you, this isn't necessary, but I like the idea of a unified buttonS wrapper wich include calendar.

**Comment by jancborchardt** [comment]
We do have `.primary` though, as used by the log in button and the main button of the file picker, and in the Calendar app for event saving, and in Mail for send and reply button. :) So that should be used.

**Comment by jancborchardt** [comment]
This is fixed, we now have a nice button there. :)

**Comment by jancborchardt** [comment]
Thanks to @andreasjacobsen93 who fixed it in https://github.com/nextcloud/notes/pull/108 ;)
