### ISSUE TITLE
Problems with adding or switching the category of a note

### ISSUE THREAD

**Issue by Popyllol** [nextcloud/notes#440]
Version:
- notes: 3.1.1

occ status:
  - installed: true
  - version: 17.0.2.1
  - versionstring: 17.0.2
  - edition: 

As documented in [#413](https://github.com/nextcloud/notes/issues/413) there is a triple dot when I hover over the note and I get a menu

![Screenshot from 2020-01-28 13-54-58](https://user-images.githubusercontent.com/8819927/73265780-e0963000-41d5-11ea-8cbd-8e2309bcac95.png)

But there is no drop down menu and when I click on "Pflanzen" in my screenshot the menu simply disappears and nothing else happens.

Can you give me any hint how to fix this?
Do you need further data?

Greetings,
   Lars

**Comment by korelstar** [comment]
Hey Lars,

that's the wrong three-dot-menu. You have to open the note, click on the three-dot-button in the top-right corner and then click on details:

![grafik](https://user-images.githubusercontent.com/6277619/73577129-663b0980-447c-11ea-9d15-1906f679f2e3.png)

Now, the sidebar opens and you can go ahead as instructed in https://github.com/nextcloud/notes/issues/413#issuecomment-565708455 .

Yes, we have to improve the workflow. ;-)

**Comment by korelstar** [comment]
Does this solve your issue?

**Comment by Popyllol** [comment]
Pefrect! Thank you for clarification!
