### ISSUE TITLE
Mobile code block text wrap

### ISSUE THREAD

**Issue by maxtimbo** [nextcloud/notes#445]
**Is your feature request related to a problem? Please describe.**
When I use markdown to ` \`code here \` ` the text doesn't wrap while in preview mode in profile view. This is very frustrating since sometimes, I'm not sure if I have made a mistake.

**Describe the solution you'd like**
text wrap inline code blocks

**Describe alternatives you've considered**
none

**Additional context**

**Comment by korelstar** [comment]
Thanks for reporting this issue! It will be fixed in the next release.
