### ISSUE TITLE
notes filename with iso compliant date

### ISSUE THREAD

**Issue by dk87** [nextcloud/notes#45]
Hi,

maybe an enhancement. The filename of one single note prefixed with an ISO compliant time (YYYY-MM-DD) stamp e.g.

2016-01-06_myawesomenote.txt

also in combination with filname-based tagging #37 (e.g. see tagspaces).

**Comment by camilasan** [comment]
Not sure if this makes sense since the file name is the first line in the note.
@jancborchardt ?

**Comment by jancborchardt** [comment]
This will make the note name totally technical and not very readable.

Remember they are still normal files, and will also be opened with other apps. Especially in mobile apps (like our own Nextcloud apps) the prepended date would make the actual title hide in ellipsis.

And yeah, combined with also that the title is the first line as @camilasan mentioned.

Sorry but this isn't something we'll do.

**Comment by dk87** [comment]
Can totally live with that. I`m not using this app anymore. But a great thank you for your response after this long period of time.

**Comment by jancborchardt** [comment]
@dk87 sure, you're welcome! :) Sorry it sometimes takes a bit longer, some apps like this are purely done in free time or by volunteers. :)
