### ISSUE TITLE
First-run client links can be mistaken for regular text

### ISSUE THREAD

**Issue by strugee** [nextcloud/notes#453]
**Is your feature request related to a problem? Please describe.**

When opening the Notes app for the first time, it's not clear that the "Android app" and "iOS app" links are, well, links.

**Describe the solution you'd like**

These should be blue and maybe underlined as is usual for links on the web to help users figure this out. 

**Describe alternatives you've considered**

We could also change them into the "Get it on Google Play"/"Available on the App Store" graphic badges.

**Comment by korelstar** [comment]
I think using these badges is a good idea.

**Comment by strugee** [comment]
Labeling as good first issue since this seems pretty trivial. @korelstar does that seem right to you?

**Comment by korelstar** [comment]
I'm fine with that too. Do you want to provide a PR?

**Comment by strugee** [comment]
I think I'll leave it for someone who could learn more from it ;)

At least for the time being.
