### ISSUE TITLE
Return appropriate HTTP statuscode on OCA\Notes\Service\NoteDoesNotExistException

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/notes#454]
Currently `HTTP 500` is returned from the server, in case that a client wants to `PUT` a locally modified note which does no more exist on the server.

Some potential candidates:
- `412 Precondition Failed` The server does not meet one of the preconditions that the requester put on the request header fields.
- `409 Conflict` Indicates that the request could not be processed because of conflict in the current state of the resource, such as an edit conflict between multiple simultaneous updates.
- `404 Not Found` The requested resource could not be found but may be available in the future. Subsequent requests by the client are permissible.
- `400 Bad Request` The server cannot or will not process the request due to an apparent client error

The candy on the ice cream would be a `410 Gone` if the file is in the trashbin.

**Comment by korelstar** [comment]
Good point. I think we should use 404.
