### ISSUE TITLE
"Enabled" apps not showing when Notes app is installed

### ISSUE THREAD

**Issue by avalx** [nextcloud/notes#46]
Hi!

I just installed the latest version (2.1.1) of the Notes app (via git pull) on my ownCloud server 9.1.3 and now I don't see the apps list on the server anymore: I click on the App button and no "Enabled" apps are shown - only the "loading circle" is running for ever. If I click other items (Not enabled, Multimedia, ...) the apps are visible with all the information. On the other hand all the apps, even Notes, seem to be working OK.

If I manually delete the Notes app everything works fine and I see also all the Enabled applications. I've cheked the log but there is not much in it:

`Error	PHP	Array to string conversion at /var/www/html/owncloud/settings/Controller/AppSettingsController.php#203	2017-01-06T12:45:04+00:00
Error	PHP	Array to string conversion at /var/www/html/owncloud/settings/Controller/AppSettingsController.php#202	2017-01-06T12:45:04+00:00
Error	PHP	Array to string conversion at /var/www/html/owncloud/settings/Controller/AppSettingsController.php#202	2017-01-06T12:45:04+00:00`

Any ideas what might be the problem?

**Comment by 9Mad-Max5** [comment]
Same here ownCloud 8.2.11 stable

**Comment by camilasan** [comment]
@avalx @9Mad-Max5  Have you updated to the latest version of the app? Do you still have this problem?

**Comment by 9Mad-Max5** [comment]
Sadly I wasn't able to fix the issue.
So I just used an older version. 

But actually i changed to nextcloud.

**Comment by jancborchardt** [comment]
@9Mad-Max5 @avalx can you try with the latest version of Nextcloud and the app, and also provide relevant content of server log, nextcloud.log, Browser console or screenshots? :) That would really help us to fix this issue.

**Comment by jancborchardt** [comment]
Also cc @skjnldsv regarding the app list

**Comment by avalx** [comment]
I'm now using latest Nextcloud and this issue is not present anymore.

**Comment by jancborchardt** [comment]
Thank you for letting us know @avalx! :) Closing the issue then.
