### ISSUE TITLE
After Upgrade to NC18 all notes are empty / new notes can't be created

### ISSUE THREAD

**Issue by florie1706** [nextcloud/notes#460]
Hi,

I don't know if it was because of the upgrade from nc17 to nc18 because I just realised it now. NC is running on a lunux docker with the official image nc:18-apache.

All old notes are there, but they just appear empty. New notes can't be created, there is an error message: **Creating the new note failed. See JavaScript Console for details.**

I do not know what that means:

`Error: "Request failed with status code 500"
    exports https://foo.bar/custom_apps/notes/js/notes.js?v=04707f84-1:967
    exports https://foo.bar/custom_apps/notes/js/notes.js?v=04707f84-1:974
    onreadystatechange
https://foo.bar/custom_apps/notes/js/notes.js?v=04707f84-1:967
notes.js:986:318980
    createNote https://foo.bar/custom_apps/notes/js/notes.js?v=04707f84-1:986`

WHat can I do that Notes will work again? ANd hopefully get my old notes back?

Thanks

**Comment by korelstar** [comment]
Please use the issue template and provide more information about your environment (version of the notes app and information from `nextcloud.log` are very important in this case!).

**Server (please complete the following information):**
- Notes app version: 
- Nextcloud version: 
- OS: 
- Web server: 
- PHP version: 
- Database: 

**Client (please complete the following information):**
 - Browser (incl. version): 
 - OS: 

**Log files**
Add relevant parts of your `nextcloud.log` and/or your browser's JavaScript console here.

**Comment by stefan-niedermann** [comment]
Also: Can you access them with the Files app? Are they visible or are they not available there anymore? (In case you can access them, you should do a backup while this issue is analyzed)

**Comment by Benance** [comment]
Hello
Same symptoms on my instance since the nextcloud notes upgrade to 3.1.4
Here are my instance specs:

Server:

    Notes app version: 3.1.4
    Nextcloud version: 15
    OS: Raspbian 9
    Web server: nginx
    PHP version: 7.0.33
    Database: mariadb

Client (please complete the following information):

    Browser (incl. version): firefox 68.4.2 ESR
    OS: Windows 10 1909

Here are the javascript console errors:
Error: "Request failed with status code 500"
    exports https://my_domain.com/cloud/apps/notes/js/notes.js?v=9b947893-0:967
    exports https://my_domain.com/cloud/apps/notes/js/notes.js?v=9b947893-0:974
    onreadystatechange https://my_domain.com/cloud/apps/notes/js/notes.js?v=9b947893-0:967
notes.js:986:319113

**Comment by korelstar** [comment]
> Request failed with status code 500

That means, that something has failed on the server. More information can be found in the Nextcloud server log. This can be accessed in the filesystem (`data/nextcloud.log`) or directly over Nextcloud (as Nextcloud administrator in "Settings" -> "Logging").

Please have a look over there an provide us all entries from the notes app. Please understand that it's not possible to find the problem source without this information.

**Comment by florie1706** [comment]
I have checked the file-system and on every of my seven users there is just the cache subfolder. All other subfolders are gone. So that is the reason why I did not see the notes and could not create new ones. I was transfering a backup of the files-folders to the user accounts and now everything is working again. Maybe that is not a notes problem but nc-server.

**Comment by Benance** [comment]
ok so here is the notes-relative logs in the nexcloud.log when I try to create a new note:
`"time":"2020-02-10T13:11:24+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"my_user","app":"index","method":"POST","url":"\/cloud\/index.php\/apps\/notes\/notes","message":{"Exception":"TypeError","Message":"Return value of OCA\\Notes\\Service\\NoteUtil::ensureSufficientStorage() must be an instance of OCA\\Notes\\Service\\void, none returned","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/apps\/notes\/lib\/Service\/NotesService.php","line":129,"function":"ensureSufficientStorage","class":"OCA\\Notes\\Service\\NoteUtil","type":"->","args":[{"__class__":"OC\\Files\\Node\\Folder"},1]},{"file":"\/var\/www\/nextcloud\/apps\/notes\/lib\/Controller\/NotesController.php","line":129,"function":"create","class":"OCA\\Notes\\Service\\NotesService","type":"->","args":["my_user"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"create","class":"OCA\\Notes\\Controller\\NotesController","type":"->","args":["",null]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Notes\\Controller\\NotesController"},"create"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Notes\\Controller\\NotesController"},"create"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Notes\\Controller\\NotesController","create",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"notes.notes.create"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"notes.notes.create"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"notes.notes.create"}]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/notes\/notes"]},{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/apps\/notes\/lib\/Service\/NoteUtil.php","Line":232,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":"15.0.14.1"}

`
Thnaks a lot for your support

**Comment by korelstar** [comment]
@florie1706 good to hear that it is working for you again.

@Benance Thanks for the log! It looks like we are using a PHP feature that is available from PHP 7.1+ only, but you are using 7.0 which is out support for about a year! Please upgrade your system as soon as possible! Nextcloud 15 is out of support, too!

**Comment by korelstar** [comment]
@Benance You can try to fix this issue by removing `: void` from the end of the line
https://github.com/nextcloud/notes/blob/3.1.4/lib/Service/NoteUtil.php#L226

**Comment by gnouts** [comment]
Hi,
I am in the same config as @Benance  : NC15, PHP7.0 (I'm stuck with this config because my distribution is slow to migrate to Debian Buster with PHP7.1+)

So @korelstar,  removing `: void` fixed the issue for me. Thanks :)

I guess you won't provide a proper fix for this as it concerns an unmaintained php version ?

**Comment by Benance** [comment]
Same config as @gnouts here: my nextcloud instance is running on a [yunohost server](https://yunohost.org/#/) which isn't compatible yet with debian 10.
@korelstar thanks for the fix. My Nextcloud notes app works again!

**Comment by korelstar** [comment]
I will provide a release with this fix soon. But this will be definitely the last release that is supporting Nextcloud 15 and PHP 7.0. Sorry for that, but we have to manage the few resources.

**Comment by korelstar** [comment]
fixed in v3.1.5
