### ISSUE TITLE
Desktop app?

### ISSUE THREAD

**Issue by acloudadmin** [nextcloud/notes#464]
Hi there.

First, thank you so much for your work on the app. I use it all the time, especially on my phone (an Android). It's fast and reliable and I'm happy to say it means I've said goodbye forever to Google Keep.

My suggestion: a desktop app that, with a click of the taskbar, would give me a dedicated Notes window similar to the Android app.

Would make a great app even better. Thanks again!

**Comment by stefan-niedermann** [comment]
Have you tried QOwnNotes?

**Comment by acloudadmin** [comment]
Thanks for the suggestion. Just set it up and it's OK. Bit overpowered for
my needs -- what I love about Notes is how simple it is -- but it is the
kind of desktop app I was looking for.



613-710-6743

Proud member of the Toronto Free-Net! Join us at torfree.net

**Comment by stefan-niedermann** [comment]
Glad to hear :) I am not aware of any other desktop app, but once https://github.com/nextcloud/notes/issues/306 has been finished, the webapp as a progressive web app might be a solution.

A third solution could be running the android app within bluestck

**Comment by stefan-niedermann** [comment]
@korelstar do you know whether QOwnNotes uses the Notes REST-API? In this case we could add it to the [Wiki](https://github.com/nextcloud/notes/wiki#3rd-party-clients).

**Comment by korelstar** [comment]
I think so, but @pbek should confirm this.

**Comment by pbek** [comment]
> @korelstar do you know whether QOwnNotes uses the Notes REST-API? In this case we could add it to the Wiki.

QON doesn't do any note syncing. The Nextcloud sync client syncs the note files.

see: https://www.qownnotes.org/Knowledge-base/Why-isn-t-QOwnNotesAPI-syncing-my-notes

**Comment by pbek** [comment]
But if the question was if QON was made to work with Nextcloud and Nextcloud Notes, the answer is yes. QON works with the note file naming conventions of Nextcloud notes and is also able to access note versions and the trash directly from the Nextcloud server as well as sharing notes, everything directly from inside QON. QON also supports Nextcloud text and you can also manage your Nextcloud tasks with it. Plus you can import your Nextcloud bookmarks and there is an Evernote importer. :grin:

**Comment by acloudadmin** [comment]
Hi again. I can definitely see how this app could be very useful for me. But I think I'm missing something conceptually.

I'm inferring from the "Setup Notes Dialogue" that QON can read and write the note files straight to server storage. Is that correct? If so, wouldn't any syncing questions be moot?

I'd much prefer that ability -- to have QON read and write directly to the files themselves. (I'd like to see changes propogated as quickly as possible to the notes I see on my phone -- I'm often using computer and phone in tandem for lots of things and waiting for the desktop nextcloud client to scan my 25,000+ files for changes is just too slow)

But my problem is that the "Path on your nextcloud/owncloud" isn't working for me. When I click on the folder icon, it seems to be trying to read my server folders but then reports back "no more folders were found in the current folder" and I'm left with a blank window.

Here's what the log reports: 

"QNetworkReply error 204 from url https://aaacloud.ddns.net/remote.php/webdav/: " "Host requires authentication"
[Feb 15 08:49:26] [debug]: Reply from ownCloud webdav

Any thoughts on how I can get this working properly?

Thanks!

**Comment by korelstar** [comment]
@acloudadmin Please discuss QOwnNotes specific problems in the appropriate repository: https://github.com/pbek/QOwnNotes

@pbek How does your Nextcloud Text support work? Did you integrate the Text editor in the desktop app or did you implement the protocol on your own?

**Comment by pbek** [comment]
@acloudadmin, about syncing, please read https://github.com/pbek/QOwnNotes/issues/1624
about your issue: please report issues in the issue tracker: https://github.com/pbek/QOwnNotes/issues

@korelstar, no and no. It just supports markdown files created by Nextcloud text and it can also show a preview of Nextcloud text's embedded images (see https://github.com/pbek/QOwnNotes/issues/1226)
