### ISSUE TITLE
API did not work

### ISSUE THREAD

**Issue by rvs75** [nextcloud/notes#471]
**Describe the bug**
We use this url to fetch notes: https://username:pass@my.example.com/cloud/remote.php/webdav/index.php/apps/notes/api/v0.2/notes. After an update of nextcloud to 16.0.8 we got an 404 error page. If we test https://my.example.com/cloud/index.php/apps/notes/api/v0.2/notes we got an error 500.

**To Reproduce**
1. Go to 'https://my.example.com/cloud/index.php/apps/notes/api/v0.2/notes'

**Expected behavior**
Go the list of notes for this user.

**Screenshots**

**Server (please complete the following information):**
- Notes app version: 3.1.5
- Nextcloud version: 16.0.8.1
- OS: Ubuntu 18.04.1 LTS
- Web server: Apache2
- PHP version: 7.2.12
- Database: mysql 10.3.9

**Client (please complete the following information):**
 - Browser (incl. version): Chromw 79.0.3945.130
 - OS: Windows 10

**Log files**
[index] Error: TypeError: Argument 1 passed to OC\Authentication\Token\Manager::getToken() must be of the type string, null given, called in /var/www/vhosts/default/cloud/lib/private/User/Session.php on line 493 at <<closure>>

 0. /var/www/vhosts/default/cloud/lib/private/User/Session.php line 493
    OC\Authentication\Token\Manager->getToken("*** sensitive parameters replaced ***")
 1. /var/www/vhosts/default/cloud/lib/private/User/Session.php line 411
    OC\User\Session->isTokenPassword("*** sensitive parameters replaced ***")
 2. /var/www/vhosts/default/cloud/lib/private/AppFramework/Middleware/Security/CORSMiddleware.php line 93
    OC\User\Session->logClientIn("*** sensitive parameters replaced ***")
 3. /var/www/vhosts/default/cloud/lib/private/AppFramework/Middleware/MiddlewareDispatcher.php line 95
    OC\AppFramework\Middleware\Security\CORSMiddleware->beforeController(OCA\Notes\Contro ... {}, "index")
 4. /var/www/vhosts/default/cloud/lib/private/AppFramework/Http/Dispatcher.php line 98
    OC\AppFramework\Middleware\MiddlewareDispatcher->beforeController(OCA\Notes\Contro ... {}, "index")
 5. /var/www/vhosts/default/cloud/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Notes\Contro ... {}, "index")
 6. /var/www/vhosts/default/cloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Notes\\Con ... r", "index", OC\AppFramework\ ... {}, {_route: "notes.notes_api.index"})
 7. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "notes.notes_api.index"})
 8. /var/www/vhosts/default/cloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "notes.notes_api.index"})
 9. /var/www/vhosts/default/cloud/lib/base.php line 972
    OC\Route\Router->match("/apps/notes/api/v0.2/notes")
10. /var/www/vhosts/default/cloud/index.php line 45
    OC::handleRequest()

GET /cloud/apps/notes/api/v0.2/notes
from 95.222.29.66 at 2020-02-21T09:18:49+00:00

**Comment by korelstar** [comment]
This API is not meant to be used in the browser. You can use, e.g., `curl` for testing purposes:

`curl https://username:password@my.example.com/cloud/index.php/apps/notes/api/v0.2/notes`

Does this work for you?

**Comment by rvs75** [comment]
Yes, this works.

**Comment by rvs75** [comment]
So, I think we can close this ticket.
