### ISSUE TITLE
Bad translations

### ISSUE THREAD

**Issue by korelstar** [nextcloud/notes#473]
From time to time, some people add translations on Transifex which don't suffice my quality approaches. This is not the fault of those people, I think it's because they don't know the actual context of the strings (e.g. a much too long translation for a button label).

However, most often I can update that translation on my own on Transifex. But from time to time, other people do a review on those strings. Then, they are locked and I can't update the translation anymore.

Therefore I would like to ask @rakekniven @jancborchardt @MorrisJobke , if

- I can get the credentials to edit reviewed translations on Transifex, or if
- reviewing on the notes resource on Transifex can be disabled.

I really would like to improve small things, but it's annoying if this is not possible even if I'm the maintainer of this app.

**Comment by rakekniven** [comment]
For sure you can be a reviewer.
Are you asking for a specific language? It is not possible for all languages, that would be different role.
Will answer you more in detail tomorrow.

**Comment by korelstar** [comment]
Thanks, `de` and `de_DE` is sufficient for me :-)

**Comment by rakekniven** [comment]
Good morning, 

just added you as reviewer for both languages.

btw. Hoffentlich habe ich Dir nicht zuviele schlechte Übersetzungen bescherrt ;-)

**Comment by korelstar** [comment]
Thanks!

(Nein, die Übersetzungen, mit denen ich nicht zufrieden war, kommen i.d.R. von einem anderen Benutzer ;-) )

**Comment by rakekniven** [comment]
German: Habe gerade mal die beiden Resourcen komplett einem Review unterzogen und ich fand die Qualität gut.

**Comment by jancborchardt** [comment]
Thank you both! :)
