### ISSUE TITLE
Small images in preview

### ISSUE THREAD

**Issue by Weiming-Hu** [nextcloud/notes#482]
**Describe the bug**
I'm using version 3.2.0 and my preview of inserted images looks like below.

![Screen Shot 2020-03-19 at 10 41 48 AM](https://user-images.githubusercontent.com/16421338/77079669-bfc8aa80-69ce-11ea-894b-efaf01d38329.png)

I remember the preview images used to be larger than just thumbnails. I don't know how to enlarge the size of the image. At this point, it is hard to see clearly what's in the image. Is there a way to enlarge the size of the image?

Thank you

**To Reproduce**
1. User version 3.2.0
2. Insert an image to a markdown file

**Expected behavior**
Images used to be bigger and clearer.

**Server (please complete the following information):**
- Notes app version: 3.2.0
- Nextcloud version: 18.0.2
- OS: Raspian
- PHP version: 7.3.14 
- Database: mysql 10.3.22

**Client (please complete the following information):**
 - Browser (incl. version): Firefox 74.0 (64 bit)
 - OS: Mac OS Mojave

**Comment by korelstar** [comment]
Currently, we don't support images officially. There is another open issue which is about the image support in general (#74). Therefore, I close this in favor of the other issue.

**Comment by rosacola** [comment]
So if I understand it correctly, we cannot change the size of the image right?

**Comment by korelstar** [comment]
I'm not sure what are we talking about. The notes app doesn't support images officially, but the preview engine ([markdown-it](https://markdown-it.github.io/)) does. Therefore, you can use the following syntax for inserting images:

```
![Image Description](https://www.example.com/path-to-image)
```
In preview mode, the image is shown in its original size. Does this help?

**Comment by Weiming-Hu** [comment]
I'm sorry for the confusion. This is what my note looks like.

![Screen Shot 2020-05-18 at 9 22 11 AM](https://user-images.githubusercontent.com/16421338/82218076-52ab9580-98e9-11ea-88ba-87a31d0c7b8f.png)

I'm afraid that I didn't find a `preview` button. Could you help me find it?

My issue is that the image used to be shown much bigger. Now, it almost seems like it is only showing the thumbnail.

Thank you

**Comment by korelstar** [comment]
The screenshot does not show the Notes app. It looks like the Nextcloud Text app: https://github.com/nextcloud/text

**Comment by Weiming-Hu** [comment]
I'm really sorry about this. Apparently I made a mistake. Please feel free to delete this issue.
