### ISSUE TITLE
Selected text not visible in dark theme

### ISSUE THREAD

**Issue by drikqlis** [nextcloud/notes#484]
**Describe the bug**
When selecting text in edit mode in note when the dark theme is turned on the text is not visible. The problem is not present in preview mode. 

**To Reproduce**
1. Turn on the dark theme.
2. Create new note and write something.
3. Try to select text in edit mode.

**Expected behavior**
The text should be visible when selected.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/19647553/78367527-885b2000-75c2-11ea-9b4e-862d1be58647.png)

**Server (please complete the following information):**
- Notes app version: 3.2.0
- Nextcloud version: 18.0.3
- OS: Ubuntu 18.0.4 LTS
- Web server: apache2
- PHP version: 7.3.15
- Database: MariaDB

**Client (please complete the following information):**
 - Browser (incl. version): Firefox 74.0
 - OS: Windows 10 1909

**Comment by korelstar** [comment]
Thanks for reporting this issue. It will be fixed in the next release.
