### ISSUE TITLE
Create widgets for dashboard app

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/notes#487]
**Is your feature request related to a problem? Please describe.**

For a better integration with the Nextcloud ecosystem it would be great if there were some widgets for the dashboard app.

**Describe the solution you'd like**

- 📓 List of most recent notes with a quick way to open them in the Notes-App
- ⭐ List of favorite notes
- ✍️ Direct note widget of a note of choice for quick note taking

**Describe alternatives you've considered**
No integration

**Additional context**

There is an issue with ideas of possible integrations for the dashboard app: https://github.com/nextcloud/dashboard/issues/39#issuecomment-405362971

**Comment by korelstar** [comment]
Do people use the dashboard app? I have the impression that app development has been discontinued.

**Comment by stefan-niedermann** [comment]
legitimate question.

**Comment by stefan-niedermann** [comment]
Let's ask @daita @tuxedo-rb as the ones who contributed most to the `dashboards` app and @MorrisJobke @skjnldsv from Nextcloud whether they can tell us something about the current state of the `dashboards`-app?

It looks indeed dead and i'm not sure whether or not it's worth the effort.

**Comment by skjnldsv** [comment]
Better ping @juliushaertl & @jancborchardt ;)

**Comment by tuxedo-rb** [comment]
Hello, our company does no longer use the Dashboard App (i got a bit forced to work on it).
Dunno, if i find time/motivation to work on a widget in my free time.
At home i'm a slacker. :blush:

**Comment by jancborchardt** [comment]
The super flexible iGoogle-like dashboard is not something we’ll continue, however we’re looking into a more organized approach. Showing recently edited notes in a column and the ability to (in the first step) navigate to them and (in a second step) be able to open them right in that dashboard could be part of that. cc @juliushaertl for the details.

**Comment by korelstar** [comment]
Will this be based on the existing dashboard app or a new one? Because I tend to close this issue then until the new variant is available.

**Comment by jancborchardt** [comment]
@juliushaertl will have to comment for specifics but most likely it will _not_ be based on that.

**Comment by juliushaertl** [comment]
Yes, the existing dashboard app has a quite complex API and our new attempt will simplify both the UI and the API for integrating apps a lot. I'm currently wrapping up the first version of the server API for 20.

**Comment by korelstar** [comment]
Okay, then I'm closing this issue (since it's about the old dashboard app) and we can open a new issue when the new API is finished.
