### ISSUE TITLE
Allow scrolling past the note end

### ISSUE THREAD

**Issue by SuperSandro2000** [nextcloud/notes#493]
**Is your feature request related to a problem? Please describe.**

I am writing longer notes and if they reach the bottom of my screen I would like to scroll up a bit so that my writing area is in the middle of my screen again.

**Describe the solution you'd like**
Allow scrolling notes further up when they are longer than on screen height.

**Describe alternatives you've considered**
Adding many blank lines at the end of long notes.

**Additional context**

**Comment by korelstar** [comment]
This could be easily done by adding a margin-bottom of e.g. `50vh` (or `30vh` which looks better) to the editor `div`. However, it feels a little bit strange, since the scrollbar is not at the bottom, even if I'm at the bottom of the note.

What do you think @jancborchardt ?

**Comment by stefan-niedermann** [comment]
Wouldn't work a `paading-bottom`? This way the scrollbar should reach to the end (not tested)

**Comment by korelstar** [comment]
Sorry, I think my description was ambiguous. The scrollbar still fills the full viewport height. But if I'm at the end of the note, the scrollbar position will not be at the end of the bar. That's not a technical problem, rather it is inherent to the feature request.

**Comment by jancborchardt** [comment]
Agree with @SuperSandro2000 – we do the same in the Files list actually and for the Mail app as well. :) It’s much nicer than having the end of the content always hanging down towards the bottom of the screen.

**Comment by korelstar** [comment]
As far as I can see, you are using a height of 250px for the summary line. Therefore, a `margin-bottom` of 200px should be sufficient. Do you agree, @jancborchardt ?

![Mockup](https://user-images.githubusercontent.com/6277619/83661836-0342b600-a5c7-11ea-8027-103d44a6d77c.png)

**Comment by jancborchardt** [comment]
I'd probably go for something like `30vh` so it adjusts based on viewport. What do you think?
