### ISSUE TITLE
More alert about 2FA consequences

### ISSUE THREAD

**Issue by CATER-COM** [nextcloud/notes#497]
When you activate 2FA external app like thunderbird can't connect anymore with basic password. It's quite normal from a security point of view. The problem is that's not clear before you launch your calendar or contact syncing app and you see it doesn't work anymore

Over the activate cas of a 2FA system, a red warning should inform you that you MUST use an app password before activating the 2FA system. Especially if the system is using an app on exetrnal device like Notification. In the same idea it should warn you to creat and save backup code before you be locked outside you account.  

Just an enhancement that could save frustrating time ;)

Edit : it look like the Android apps credentials aren't compromised by the 2FA activation so you shoud not be locked outside ;-)

**Comment by korelstar** [comment]
Thanks for sharing your experiences. However, I don't know how we can fix this. Shouldn't this be part of the Nextcloud server, since you have to activate 2FA from there :question: 
The notes app doesn't have an option to activate 2FA, so we can't add a warning!

**Comment by CATER-COM** [comment]
@korelstar sorry it's a mistake this issue was for nextcloud server. I don't why I wrote it there :-(

**Comment by korelstar** [comment]
No Problem :-)
