### ISSUE TITLE
Configure Travis for this Repository

### ISSUE THREAD

**Issue by korelstar** [nextcloud/notes#5]
Automated testing seems not to be activated in this repository.

**Comment by Henni** [comment]
Who do I have to bribe to set up Travis for this repo? Maybe @MorrisJobke ?

**Comment by MorrisJobke** [comment]
Done

**Comment by MorrisJobke** [comment]
I only enabled PR based triggers. If you need them also for branches just ping me.

**Comment by Henni** [comment]
@MorrisJobke Awesome thanks!
