### ISSUE TITLE
3rd party API: enable compression

### ISSUE THREAD

**Issue by korelstar** [nextcloud/notes#50]
In order to speed up synchronization with mobile devices (mobile connections often are slow and unreliable) it would be advantageous if the connection would be automatically compressed. Depending on the value of the HTTP header `Accept-Encoding` sent by the client (Android is sending this automatically), the response should be compressed and the respective header `Content-Encoding` should be activated.

As far as I can see, the ownCloud/Nextcloud App Framework does not provide any support for this. Is this really true? If yes, then we would have to implement it on our own. This is not a big deal, but requires to pick the `Accept-Encoding` into pieces. As an alternative one could try to use features from the web server. However, for Apache it wouldn't be straight forward, because a `.htaccess` file in this app would not apply to requests to the API (they go over `index.php` from nextcloud/server). Therefore, I'm not sure which solution would be best. Any ideas?

**Comment by jancborchardt** [comment]
Any idea about this @nextcloud/notes? Or @MorrisJobke @rullzer?

**Comment by korelstar** [comment]
Will be fixed by Nextcloud 20, see https://github.com/nextcloud/server/pull/20270
