### ISSUE TITLE
Desktop client

### ISSUE THREAD

**Issue by emmjam** [nextcloud/notes#501]
Please consider creating desktop versions of the client ?
This would provide a nice backup from my work laptop to my Nextcloud server, to be picked up later on my mobile whilst discussing with someone else. I know I could use the browser, but thats just horrible. Something like Notes on the Mac would be fantastic

**Comment by stefan-niedermann** [comment]
Have you tried [QOwnNotes](https://www.qownnotes.org/)?

**Comment by emmjam** [comment]
I had not. Thanks for this, will try it immediately !
