### ISSUE TITLE
Allow empty directories to be selected as categories

### ISSUE THREAD

**Issue by joeySeal** [nextcloud/notes#504]
For example
If I create a child directory inside of /Notes that does not contain a *.md file the notes app will not allow me to select it as a category. There are situations where I might create a new directory(category) from my desktop and put other file types in it and would like to use it as a notes category as well.

**Comment by korelstar** [comment]
Please see https://github.com/nextcloud/notes/issues/413#issuecomment-565708455 for an instruction on how to use a new category. Notes will use the existing folder, if you type its name into the category field. Does this work for you?

**Comment by joeySeal** [comment]
@korelstar yes that works but it seems like an unnecessary extra step

**Comment by korelstar** [comment]
Which part of that is "unnecessary extra" for you - compared to assigning an existing category?

**Comment by joeySeal** [comment]
See attached screenshot, unless I am overlooking something. I would have to type out the entire path if I want to use an existing directory which contains no *.md files
![category](https://user-images.githubusercontent.com/2881557/81211812-f0c26600-8fa1-11ea-93c8-028d8c455347.gif)

**Comment by korelstar** [comment]
I see. I think we really can improve that and show also empty directories in auto-completion.
