### ISSUE TITLE
Pos1 and End key behavior

### ISSUE THREAD

**Issue by maurerle** [nextcloud/notes#508]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I use the Pos1 Key or End Key while writing notes in the Nextcloud Notes app ;)
It always jumps to the beginning after the last line break instead of the first position of the current visible line (or last positon for End)

**Describe the solution you'd like**
Just like VSCode or Notepad++ is doing it (with enabled word wrap/automatic line break):
Pressing once jumps to beginning/end of visible line
Pressing twice jumps to beginning/end of current paragraph.

**Describe alternatives you've considered**
I understand that the current behavior is due to how Markdown works and maybe it is done intentionally like this. I hope that I am not the only one who would like this change and that there isn't somebody who formed a workflow around the current behavior.

**Comment by korelstar** [comment]
This behavior is from the used editor library `EasyMDE`. You can reproduce this on their [online demo site](https://easymde.tk/).

Please open an issue in their repository and link it from here. Thanks!
