### ISSUE TITLE
API: get all notes of a specific category

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/notes#510]
**Is your feature request related to a problem? Please describe.**
I want to implement https://github.com/woefe/ShoppingList/issues/17
The app shoppingList should store its lists as notes with category "shoppingList".
Therefore it would be great to extend API with 
GET /notes/{category}

**Describe the solution you'd like**
Get all notes from one desired category

**Describe alternatives you've considered**
Getting all notes and filtering notes

**Comment by korelstar** [comment]
Sound reasonable. I will extend the API with such a new endpoint. However, `GET /notes/{category}` is ambiguous, since we already have `GET /notes/{id}`. Categories named by a number will conflict, then. Therefore, I think I will use `GET /notes/by-category/{category}`.

**Comment by stefan-niedermann** [comment]
or `/notes/categories/{category}`?

**Comment by korelstar** [comment]
Another question is: should the result include notes from the exact category only or also notes from sub-categories?

Example: Note 1 has category `recipes` and Note 2 has category `recipes/cakes`.
Should a query for `recipes` include both notes or only Note 1?

**Comment by stefan-niedermann** [comment]
i would *expect* that all notes from subcategories are included, though i know that the use case of @tobiasKaminsky only needs notes from the main category. Maybe an optional query parameter `?includeSubcategories=true`?

**Comment by korelstar** [comment]
It looks like the "correct" way for such a filter on the list of notes is to add a query, I.e. `GET notes?category=X`. So I will use this approach.

Regarding my last question, I think I will only implement the behavior that is needed, for now. So if I understand correctly, this is an exact category match (do not include subcategories). Is this correct, @tobiasKaminsky ?

**Comment by korelstar** [comment]
See  #518 for a first implementation. Please check if this is sufficient for you.

**Comment by tobiasKaminsky** [comment]
> Regarding my last question, I think I will only implement the behavior that is needed, for now. So if I understand correctly, this is an exact category match (do not include subcategories). Is this correct, @tobiasKaminsky ?

Yes, for now I do not "need" subcategories.
Thanks for helping out so fast!
