### ISSUE TITLE
Exception when upgrading from 3.2.0 to 3.5.0

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/notes#534]
**Describe the bug**
1. Installed `3.2.0` from GitHub
2. upgraded to `3.5.0` via web interface
3. after update i get the following exception:

```
  | Doctrine\DBAL\Exception\InvalidFieldNameException: An  exception occurred while executing 'INSERT INTO `oc_notes_meta`  (`user_id`, `file_id`, `last_update`, `file_etag`, `content_etag`,  `etag`) VALUES(?, ?, ?, ?, ?, ?)' with params ["stefan", 63408,  1591521704, "03d903ef48b4a813da22c3819fe87d1b",  "0ffe40b05e6243839c583f101df564f2", "ee66978acc4f63065f91e04ec0d8df34"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'file_etag' in  'field list'
-- | --

```
Might there be a missing migration script or so? Ping me if you need more information...

**Screenshots**
![grafik](https://user-images.githubusercontent.com/4741199/83965179-0d5c0180-a8b2-11ea-8e82-d158b79a89e4.png)

**Server (please complete the following information):**
- Notes app version: 3.2.0 -> 3.5.0
- Nextcloud version: 18.0.5
- OS: Linux
- Web server: Apache
- PHP version: 7.3
- Database: Don't know

**Client (please complete the following information):**
Each rest client requesting → `GET /index.php/apps/notes/api/v1/notes`

**Comment by stefan-niedermann** [comment]
I have fixed the issue meanwhile for me (by manually creating the columns directly in the database). So if you cannot reproduce it, you can simply close this issue @korelstar 

But it might be worth a look whether or not a migration-script is missing or wrong.

**Comment by korelstar** [comment]
Thanks for reporting this. Can you please post the output of the following SQL query on your Nextcloud database?
```sql
SELECT * FROM oc_migrations WHERE app='notes'
```

**Comment by stefan-niedermann** [comment]
| app | version |
| --- | --- |
| notes | 3005Date20200528204430 |
| notes | 3005Date20200528204431 |

This might be the solution.

I had installed the Notes app regulary and updated it for a long time.

Then i removed all the files and copied the old files from `3.2.0` via FTP and to make sure that everything works fine i also dropped the table `oc_notes_meta`. I didn't think about entries being present in other tables.

So when i upgraded from `3.2.0` back to `3.5.0` the database probably wasn't updated correctly because there already have been entries in `oc_migrations`.

This all sounds very reasonable to me.

**Comment by szmurlor** [comment]
Just for the future refence, the same issue was described here #551 with explanation how to rerun the missing migrations, located in folder: `nextcloud/apps/notes/lib/Migration`

In my case (NC 17.08) I just created the missing columns in mysql with commands and worked fine:

```
ALTER TABLE oc_notes_meta ADD COLUMN content_etag varchar(32);
ALTER TABLE oc_notes_meta ADD COLUMN file_etag varchar(40);
```
