### ISSUE TITLE
3.5.0 violates not-null constraint

### ISSUE THREAD

**Issue by cvandesande** [nextcloud/notes#535]
**Describe the bug**
Updated to 3.5.0 via occ app:update --all results in a broken notes install.

Opening the notes apps results in this message:
```
The notes folder is not accessible: An exception occurred while executing 'INSERT INTO "oc_notes_meta" ("user_id", "file_id", "last_update", "etag") VALUES(?, ?, ?, ?)' with params ["cvandesande", 1250349, 1591527378, "592b0ded3befc748129fd3aa87e21b65"]: SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "content_etag" violates not-null constraint DETAIL: Failing row contains (5, 1250349, cvandesande, 1591527378, 592b0ded3befc748129fd3aa87e21b65, null, null).
```
A similar message is displayed in the Postgres logs:
```
ERROR:  null value in column "content_etag" violates not-null constraint
DETAIL:  Failing row contains (7, 1250349, cvandesande, 1591527429, 592b0ded3befc748129fd3aa87e21b65, null, null).
18553] STATEMENT:  INSERT INTO "oc_notes_meta" ("user_id", "file_id", "last_update", "etag") VALUES($1, $2, $3, $4)
```
**To Reproduce**
1. Use Postgres DB
2. Update notes to 3.5.0

**Expected behavior**
Working notes after uprgade

**Screenshots**
![ksnip_20200607-115848](https://user-images.githubusercontent.com/24499582/83967082-531ac900-a8b6-11ea-93f8-ddcda35559b7.png)

**Server (please complete the following information):**
- Notes app version:  3.5.0
- Nextcloud version: 18.0.5
- OS: Docker
- Web server:  Nginx
- PHP version: 7.4.6
- Database: PostgreSQL

**Comment by sonicnkt** [comment]
Im Facing a similiar issue. 
Notes App stopped working after updating to 3.5.0

Im always getting the following error in the Androiud app
`"Request failed with status code 500" `

The WebApp shows only this message:

```
Fehler
true

Bitte wähle einen geeigneten Verzeichnispfad in den Einstellungen (unten links).
```
But i dont have access to the Settings Button.

Checked nextcloud logs and the issue was a single note .txt file. As i didn't need it anymore anyway i removed it and everything worked fine after that again. 
I can get a copy of the file from old backups if it helps investigating the problem.
Here are the nextcloud logs pointing me in the right direction:

```
[notes] Error: TypeError: Return value of OCA\Notes\Service\Note::getContent() must be of the type string, bool returned at <<closure>>

 0. /var/www/html/custom_apps/notes/lib/Service/MetaService.php line 157
    OCA\Notes\Service\Note->getContent()
 1. /var/www/html/custom_apps/notes/lib/Service/MetaService.php line 141
    OCA\Notes\Service\MetaService->generateContentEtag("*** sensitive parameter replaced ***")
 2. /var/www/html/custom_apps/notes/lib/Service/MetaService.php line 120
    OCA\Notes\Service\MetaService->updateIfNeeded("*** sensitive parameters replaced ***")
 3. /var/www/html/custom_apps/notes/lib/Service/MetaService.php line 80
    OCA\Notes\Service\MetaService->createMeta("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 4. /var/www/html/custom_apps/notes/lib/Controller/NotesController.php line 74
    OCA\Notes\Service\MetaService->updateAll("*** sensitive parameters replaced ***")
 5. /var/www/html/custom_apps/notes/lib/Controller/Helper.php line 32
    OCA\Notes\Controller\NotesController->OCA\Notes\Controller\{closure}("*** sensitive parameters replaced ***")
 6. /var/www/html/custom_apps/notes/lib/Controller/NotesController.php line 110
    OCA\Notes\Controller\Helper->handleErrorResponse(Closure {})
 7. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Notes\Controller\NotesController->index(0)
 8. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Notes\Controller\NotesController {}, "index")
 9. /var/www/html/lib/private/AppFramework/App.php line 125
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Notes\Controller\NotesController {}, "index")
10. /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Notes\\Controller\\NotesController", "index", OC\AppFramework\ ... {}, {_route: "notes.notes.index"})
11. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "notes.notes.index"})
12. /var/www/html/lib/private/Route/Router.php line 299
    call_user_func(OC\AppFramework\ ... {}, {_route: "notes.notes.index"})
13. /var/www/html/lib/base.php line 1008
    OC\Route\Router->match("/apps/notes/notes")
14. /var/www/html/index.php line 38
    OC::handleRequest()

GET /apps/notes/notes
from 192.168.1.1 by USERNAME at 2020-06-07T16:52:42+02:00

[PHP] Error: file_get_contents(/var/www/html/data/USERNAME/files/Notes/PROBLEMFILE.txt): failed to open stream: No such file or directory at /var/www/html/lib/private/Files/Storage/Local.php#218

```

**Comment by korelstar** [comment]
Thanks for reporting these issues. I think the cause for these two is different.

@cvandesande: do you use php-fpm or something similar? Please restart php-fpm as well as your webserver and then test again. Sadly, php-fpm often uses a cached version of the PHP files. I don't know how to fix this, since it's not a problem of the notes app.

@sonicnkt: It looks like Nextcloud wasn't able to read that note file. Is there something special about that file? However, I will have to add some error handling here, in order to not break things when a single note can't be read.

**Comment by cvandesande** [comment]
@korelstar You're right! Restarting php-fpm and nginx have solved the issue. Sorry I should have tried that before reporting.  I will close this. Thank you!

**Comment by korelstar** [comment]
@cvandesande Glad to hear that! Which [memory caching](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html) configuration do you use?

**Comment by sonicnkt** [comment]
> 
> @sonicnkt: It looks like Nextcloud wasn't able to read that note file. Is there something special about that file? However, I will have to add some error handling here, in order to not break things when a single note can't be read.

I just browsed my last backup and the file was not available in there which is weird. It was on my windows 10 system which is using the sync client but i deleted it as i said. My guess ist that the file was corrupted on my server  and did not  sync correctly or be backed up in the past. After deleting it on my system the broken file remains were removed on the server.

**Comment by korelstar** [comment]
@sonicnkt Thanks for your analysis. I think, the issue was caused by the corrupt file, too. This means, that this is not caused by the Notes app.

**Comment by sonicnkt** [comment]
@korelstar 
No problem, a way for notes to ignore those files and maybe report them in a dialog would be great tho. Especially if you are an enduser and dont have access to the logs and all that.

**Comment by cvandesande** [comment]
> @cvandesande Glad to hear that! Which [memory caching](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html) configuration do you use?

@korelstar I'm using redis for everything:
```
  'filelocking.enabled' => 'true',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
```

**Comment by cvandesande** [comment]
@korelstar Thanks for following up. Here's my whole ini file
```
  nextcloud.ini: |
    #PHP memlimit
    memory_limit = 512M
    #Nextcloud Opcache
    opcache.enable=1
    opcache.interned_strings_buffer=8
    opcache.max_accelerated_files=10000
    opcache.memory_consumption=128
    opcache.save_comments=1
    opcache.revalidate_freq=1
    opcache.validate_timestamps=0
    opcache.fast_shutdown=1
    #APCU
    apc.enabled=1
    apc.enable_cli=1
    apc.shm_size=128M
    apc.ttl=7200
    #PostgresSQL
    pgsql.allow_persistent = On
    pgsql.auto_reset_persistent = Off
    pgsql.max_persistent = -1
    pgsql.max_links = -1
    pgsql.ignore_notice = 0
    pgsql.log_notice = 0
    log_level = info
```
As you can see  opcache.validate_timestamps was 0. I'll change it to 1. Also I'll set opcache.revalidate_freq to 0 and see how it goes.

**Comment by korelstar** [comment]
@cvandesande Thanks, please open a new issue if this happens again.
