### ISSUE TITLE
Add API endpoint to query Notes app version

### ISSUE THREAD

**Issue by phedlund** [nextcloud/notes#537]
Please add an API endpoint like: GET `/notes/version`

with response
```
{
    "version": "3.5.0"
}
```

**Comment by stefan-niedermann** [comment]
Do you really want the Notes version or the APi version? May i ask for what purpose? Do you display the server version in the iOS app?

**Comment by phedlund** [comment]
I want the app version to
- Display in the client UI
- Verify that users are on the version they say they are

But sure, it would be convenient to include the API version also in the same response.

(FYI, for comparison, the News app has this feature in their API)

**Comment by stefan-niedermann** [comment]
> Verify that users are on the version they say they are

Relatable, i do the same at the Deck app. Never trust a user :smiling_imp:

**Comment by korelstar** [comment]
I suggest to add the app version to the Nextcloud capabilities endpoint, since it's an app meta information. Is this okay?

But I'm also fine with adding a HTTP header containing that information to every response. However, I don't think that this is needed.

**Comment by phedlund** [comment]
> I suggest to add the app version to the Nextcloud capabilities endpoint

Sure, that would work. Thanks.

**Comment by stefan-niedermann** [comment]
@phedlund by the way please note that the `capabilities`-endpoint supports ETags beginning with Nextcloud 19.
