### ISSUE TITLE
Undo deletion

### ISSUE THREAD

**Issue by claell** [nextcloud/notes#54]
Currently it is pretty easy to delete a note accidentally. A confirmation question would avoid this.

**Comment by stefan-niedermann** [comment]
Better than a confirmation would be an undo function (a message at the top of the app that hides after ~5 sec.)

**Comment by claell** [comment]
I think it can be discussed, whether this is really better than a question.
Personally I never liked the approach of an undo function, I prefer preventing an unwanted action rather than offering an option to revert it later.

However this approach is used on many other sites and might be easier to integrate into the current UI.

**Comment by korelstar** [comment]
In addition, @jancborchardt considered to put the delete button in a *3-dot-menu*, see #38. This would reduce the likelihood to hit the button by accident.

**Comment by jancborchardt** [comment]
We should definitely go with undo, as is also planned for the server and other apps. See the main issue at https://github.com/nextcloud/server/issues/3216 and cc @ChristophWurst who worked on an implementation.

**Comment by Perelandra0x309** [comment]
+1 on being able to disable deletion by the left/right swipe, or present a confirmation before doing the delete.  At least you can log into the server and restore a deleted note but it would be best to prevent unintentional deletes in the first place.

**Comment by korelstar** [comment]
@Perelandra0x309 This app doesn't provide deletion by swiping. Do you mean the Android app? In this case please see stefan-niedermann/nextcloud-notes#144 and stefan-niedermann/nextcloud-notes#158

**Comment by Perelandra0x309** [comment]
Oh sorry yes you are right I was doing this in the Android app.

**Comment by waeltken** [comment]
I just deleted a set of notes by accident...

**Comment by jancborchardt** [comment]
@waeltken can you provide further info? If it was in the Android app, please see @korelstar's comment above.

**Comment by korelstar** [comment]
There is a CSS style for implementing this, available since NC12:
![Animation of Undo](https://docs.nextcloud.com/server/13/developer_manual/_images/navigation-undo.gif)
https://docs.nextcloud.com/server/13/developer_manual/design/navigation.html#undo-entry

**Comment by rodrigoaguilera** [comment]
I just hit this issue with a key combination.

I was undoing the edits I made on a note and I realized that my last CTRL+Z returned the whole note to a "new" status. 

Is this related or should I file a new issue?

**Comment by korelstar** [comment]
@rodrigoaguilera 
That sounds like intended behavior: if you create a note, write some text and then press CTRL+Z (undo) multiple times, the note will be empty at some point. That's a feature from your browser. However, typically the browser provides CTRL+Y for redo the changes for which you've done an undo before. At least Firefox has this key command.

If you think that this is a problem of the notes app, please open a new issue, where we can discuss this. This issue is about deleting the whole note which is different.

**Comment by korelstar** [comment]
Depends on https://github.com/nextcloud/nextcloud-vue/issues/470
