### ISSUE TITLE
Don’t use bountysource anymore!

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/notes#547]
Bountysource decided to update their Terms of service today:

> 2.13 Bounty Time-Out.
> If no Solution is accepted within two years after a Bounty is posted, then the Bounty will be withdrawn and the amount posted for the Bounty will be retained by Bountysource. For Bounties posted before June 30, 2018, the Backer may redeploy their Bounty to a new Issue by contacting support@bountysource.com before July 1, 2020. If the Backer does not redeploy their Bounty by the deadline, the Bounty will be withdrawn and the amount posted for the Bounty will be retained by Bountysource.

Also check the discussion at: https://help.nextcloud.com/t/stay-away-from-bountysource/84943

**Comment by korelstar** [comment]
Ouh, that's bad. Unfortunately, I also wasn't aware of the "inactivity fee", so I lost all my money I earned. Damn.

@jospoortvliet Please deactivate the bountysource integration for this repository.

**Comment by stefan-niedermann** [comment]
@jospoortvliet is on vacation for the next two weeks as far as i know.

There are a few issues in this repository which have bounties on them. Maybe you should post something there @korelstar ?

**Comment by korelstar** [comment]
Since the new Terms of Service were withdrawn, I think we have won some time. I will wait for @jospoortvliet 's comeback then, since this is his part and his bot is still active.

**Comment by elsiehupp** [comment]
> @stefan-niedermann Please read the pinned issue "[Don’t use bountysource anymore! ](https://github.com/nextcloud/notes/issues/547)". @korelstar maybe you should remove the bounty sums from the issue titles.

I saw this pinned Issue before contributing to a bounty, but I didn't click through to it, and I subsequently forgot about it. Should someone maybe go through and edit the `<bountysource-plugin>` section in each Issue to explain the situation? I mean, I have write access to do so myself, but I don't want to step on your toes here... @korelstar suggested removing the sections entirely, but it does seem useful to leave up references to the bounties that still exist.

P.S. I deleted my off-topic comments on the other Issue (which I'm deliberately not pinging), so you can delete your response there, too, if you'd like. (I can edit out this paragraph from this comment shortly.)

**Comment by korelstar** [comment]
I don't know. The bountysource integration was done by @jospoortvliet and [I asked him to remove it](https://github.com/nextcloud/notes/issues/547#issuecomment-678656362) but I got no answer :disappointed: 

I really don't like the current situation, but I can't speak for the Nextcloud organization, which is responsible for this stuff. Maybe they can give an official advise.
