### ISSUE TITLE
Note renaming from within app

### ISSUE THREAD

**Issue by claell** [nextcloud/notes#55]
Yesterday I installed this app and created some test notes. What was very disappointing to me is that one cannot rename a note from inside the app, but has to do it in the Notes folder. This is not very intuitive.

**Comment by korelstar** [comment]
It's a key feature of this app, that filenames are derived from the first line of the note. This happens every time you change the note using this app, so the filename will change back to the content of the first line, regardless you've changed the filename in the filesystem before.

The advantage is, that you are not struggling with filenames -- you aren't even confronted with files and you can concentrate on your note. Nevertheless, this approach still produces meaningful filenames for people who want to work with the files directly.

I don't think that this behavior will be basically changed in future. However, you can always change the filename indirectly, by changing the first line of the note accordingly.

**Comment by claell** [comment]
I already thought something like that and tried it, but it did not work for me:
![bildschirmfoto vom 2017-01-22 22-15-12](https://cloud.githubusercontent.com/assets/6171135/22186096/7208ba8e-e0f0-11e6-93b5-80478377ac6f.png)

**Comment by Henni** [comment]
@claell if that is the case we have to take a look at this.
I'm currently working on a few new test cases so I might be able to find out how this happens.

We might come back to you if we need further info.

**Comment by korelstar** [comment]
Please check if there is an empty line before your first line with `Test`.

Unfortunately, the current editor starts in the second line. This will be improved when we switch to the new editor (work in progress). For now, you have to remove that empty line manually.

**Comment by claell** [comment]
@korelstar You are right, that caused the problem.

Not very intuitive, so I hope this get fixed soon.

**Comment by scottalanmiller** [comment]
No matter what text I put in a note, it calls itself New Note.  Renaming it doesn't help, it changes itself back.

**Comment by korelstar** [comment]
@scottalanmiller Please check if your text is in the **first** line of the note. In the [screenshots](https://mangolassi.it/topic/12938/how-do-you-rename-a-note-in-nextcloud/24) I can see an empty line before the text. Please remove that line and test again.

**Comment by leoboiko** [comment]
I wish it would ignore all empty lines (or whitespace-only lines) and name the note based on the first *non-empty* line.

**Comment by korelstar** [comment]
This is already implemented (see #88) and will be part of the next release.

**Comment by ak1n** [comment]
The automatic renaming makes this app useless to me. I have many notes in different formats including markdown, odt, and txt. When I open once of my markdown notes to edit it they get immediately renamed to a filename I do not want the file renamed to. Otherwise this app seems like it would be very useful. Can the automatic naming be only applied to newly created files?
