### ISSUE TITLE
Handle read only files correctly

### ISSUE THREAD

**Issue by 1ndeed** [nextcloud/notes#564]
When opening and editing a `-rwxrwxrwx` file, everything is fine.
When opening a `-rwxr-xr-x `(owned by a user other than www-data), everything is fine.
But when editing a `-rwxr-xr-x `(owned by a user other than www-data), you can input the first few words(which doesn't actually get inputted into the file). Then you can not see any content but `File could not be loaded. Please check your internet connection.[Retry]`

Maybe check if a file is writable before opening a file? Because I have some files that are too important to lose. I can't risk making it 777.

**Comment by korelstar** [comment]
I'm not sure if your use case is officially supported by Nextcloud. But since there are other scenarios where files can be read only, we should indeed handle those cases better. Therefore: :+1:
