### ISSUE TITLE
NextCloud Notes being locked constantly

### ISSUE THREAD

**Issue by hardwareadictos** [nextcloud/notes#568]
**Describe the bug**
When editing notes on browser, i get a message telling "Note is being locked", having to wait for some seconds till the system recognizes the note again:

**To Reproduce**
Just create a new note, the message appears rear some seconds of writting.

**Expected behavior**
Work without this message interruptions

**Screenshots**
![image](https://user-images.githubusercontent.com/20403906/87221652-ec357780-c36d-11ea-88d3-1c37550fef9c.png)

Directory isn't accessible (note path) is locked, please choose a valid route on Configuration.

**Server (please complete the following information):**
- Notes app version: 3.6.0
- Nextcloud version: 19.0.0
- OS: linuxserver.io docker container (Linux 4.19.118-v7l+ armv7l) --> alpine 3.12
- Web server: nginx version: nginx/1.18.0
- PHP version: 7.3.18
- Database: mysql 10.1.44

**Client (please complete the following information):**
 - Browser (incl. version): Firefox 78.0.2, happens also on Chrome 83 and Chromium, previous versions also.
 - OS: Linux (tested on Fedora 32 and Arch Linux) and Windows 10.

**Comment by korelstar** [comment]
I did some improvements related to error handling in #573. Therefore, I hope this problem will be fixed in the next release (v3.6.1)
