### ISSUE TITLE
Setting to choose notes folder

### ISSUE THREAD

**Issue by iacchi** [nextcloud/notes#57]
Hi,
I'm in a situation where my hosting provider (DreamHost) is ok with me installing Nextcloud on my space but doesn't want me to store personal files in said space. That's why I put all my files in a connected GDrive space (or similar). The Notes application create a Notes folder in my root folder and puts all the notes in there, which is a potential breach of my contract with the hosting provider.
I was wondering if it's possible to create a setting entry in the personal preferences to allow users to choose the folder where they want the notes saved, so that I can e.g. move it to the GDrive space or others.

**Comment by BloodyIron** [comment]
I really would like to have the folder that Notes are stored in configurable. Please!

**Comment by jancborchardt** [comment]
Considering the amount of people who are requesting this, maybe it’s good to have a setting for this. The default would of course stay "Notes", but we could have a bottom left settings area with a simple folder picker.

Then when you connect the Android Notes app, ideally the server/API could broadcast the folder which was chosen. That way it’s all still seamless. What do you think @nextcloud/notes @stefan-niedermann?

**Comment by korelstar** [comment]
I vote for it!

Just a hint: for #24, we need this "bottom left settings area", too.

**Comment by BloodyIron** [comment]
Just to be explicit here, I think this preference should be perhaps either Per-User setting, or Server-Wide (for environments that want to enforce consistency).

Now that I've switched to using Notes, it's super duper handy! Glad to see this is moving along :)

**Comment by jancborchardt** [comment]
1. First step: user setting
2. Second step maybe in the future: admin setting

Contributions are very welcome, and we accept donations via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F46751022&utm_medium=issues&utm_source=github). :rocket:

**Comment by korelstar** [comment]
fixed in #207 by @danielmorlock . Thanks!
