### ISSUE TITLE
3 dot menu hidden behind sidebar

### ISSUE THREAD

**Issue by mw80** [nextcloud/notes#570]
In case there is an app active which provides a sidebar (e.g. XMPP chat) the 3 dot menu is hidden behind the sidebar.
To use the menu it is required to always collapse the sidebar first.

**Screenshots**
![Capture2](https://user-images.githubusercontent.com/19948946/87280098-0b5d1200-c4f2-11ea-96c4-69ff5ef72beb.PNG)

**Server (please complete the following information):**
- Notes app version: 3.6.0
- Nextcloud version: 19
- OS: 
- Web server: 
- PHP version: 
- Database: 

**Client (please complete the following information):**
 - Browser (incl. version): Seems to be all browsers are affected
 - OS: 

**Log files**
Add relevant parts of your `nextcloud.log` and/or your browser's JavaScript console here.

**Comment by korelstar** [comment]
Hmm. It looks like that app just adds a layer on top of what is already shown. Therefore, I can't see how we can prevent this in the notes app. As far as I understand this approach, the developers of that app are aware of the problem that important things from other apps can be covered - and for this purpose, they provide a functionality for collapsing the chat sidebar. Hence, everything looks fine for me.

If you are not happy with this behavior, I think you should discuss this with the developers of the XMPP chat app. I can't see, what we can do, here. :confused:

**Comment by mw80** [comment]
I can confirm. Also other apps are affected. I will open an issue for the xmpp chat app. Thanks!
