### ISSUE TITLE
Notes app keeps loading

### ISSUE THREAD

**Issue by ejmroberge** [nextcloud/notes#583]
I wanted to change the folder path to store the notes in Settings and after I typed "/" I clicked on my file browser to note the path. It then seems to have saved this way and now notes just keeps loading.

I tried:

1. Disable/Enable.
2. Remove/Download and Enable.
3. Reboot of the server.

**Comment by korelstar** [comment]
Closing due to missing feedback. Please re-open using the issue template, if the problem still occurs.
