### ISSUE TITLE
Reading notes from filesystem has failed

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/notes#590]
**Describe the bug**
The following error is displayed when opening the app. I have tried reinstalling Notes to no avail. Android app also not working. All notes are in /Notes directory and are accessible from web via Files.

![Screenshot_1](https://user-images.githubusercontent.com/36133540/90987457-7129c880-e58b-11ea-92c4-68f9bd836ee5.png)

**To Reproduce**
1. Open notes

**Server (please complete the following information):**
- Notes app version: 3.6.2
- Nextcloud version: 19snap3
- OS: ubuntu 20

**Client (please complete the following information):**
 - Browser (incl. version): brave/firefox latest
 - OS: win, android

**Log files**
Add relevant parts of your `nextcloud.log` and/or your browser's JavaScript console here.

{"reqId":"WtXz8SnoVKaGcDwz4iaG","level":3,"time":"2020-08-23T21:47:07+02:00","remoteAddr":"162.158.94.165","user":"miro","app":"notes","method":"GET","url":"/index.php/apps/notes/notes","message":{"Exception":"Exception","Message":"Can't read file content.","Code":0,"Trace":[{"file":"/var/snap/nextcloud/22653/nextcloud/extra-apps/notes/lib/Service/MetaService.php","line":159,"function":"getContent","class":"OCA\\Notes\\Service\\Note","type":"->","args":[]},{"file":"/var/snap/nextcloud/22653/nextcloud/extra-apps/notes/lib/Service/Util.php","line":11,"function":"OCA\\Notes\\Service\\{closure}","class":"OCA\\Notes\\Service\\MetaService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/snap/nextcloud/22653/nextcloud/extra-apps/notes/lib/Service/MetaService.php","line":160,"function":"retryIfLocked","class":"OCA\\Notes\\Service\\Util","type":"::","args":[{"__class__":"Closure"},3]},{"file":"/var/snap/nextcloud/22653/nextcloud/extra-apps/notes/lib/Service/MetaService.php","line":142,"function":"generateContentEtag","class":"OCA\\Notes\\Service\\MetaService","type":"->","args":["*** sensitive parameter replaced ***"]},{"file":"/var/snap/nextcloud/22653/nextcloud/extra-apps/notes/lib/Service/MetaService.php","line":121,"function":"updateIfNeeded","class":"OCA\\Notes\\Service\\MetaService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/snap/nextcloud/22653/nextcloud/extra-apps/notes/lib/Service/MetaService.php","line":81,"function":"createMeta","class":"OCA\\Notes\\Service\\MetaService","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/snap/nextcloud/22653/nextcloud/extra-apps/notes/lib/Controller/NotesController.php","line":54,"function":"updateAll","class":"OCA\\Notes\\Service\\MetaService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/snap/nextcloud/22653/nextcloud/extra-apps/notes/lib/Controller/NotesController.php","line":89,"function":"getNotesAndCategories","class":"OCA\\Notes\\Controller\\NotesController","type":"->","args":["*** sensitive parameter replaced ***",0]},{"file":"/var/snap/nextcloud/22653/nextcloud/extra-apps/notes/lib/Service/Util.php","line":11,"function":"OCA\\Notes\\Controller\\{closure}","class":"OCA\\Notes\\Controller\\NotesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/snap/nextcloud/22653/nextcloud/extra-apps/notes/lib/Controller/Helper.php","line":51,"function":"retryIfLocked","class":"OCA\\Notes\\Service\\Util","type":"::","args":[{"__class__":"Closure"}]},{"file":"/var/snap/nextcloud/22653/nextcloud/extra-apps/notes/lib/Controller/NotesController.php","line":113,"function":"handleErrorResponse","class":"OCA\\Notes\\Controller\\Helper","type":"->","args":[{"__class__":"Closure"}]},{"file":"/snap/nextcloud/22653/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"index","class":"OCA\\Notes\\Controller\\NotesController","type":"->","args":[0]},{"file":"/snap/nextcloud/22653/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Notes\\Controller\\NotesController"},"index"]},{"file":"/snap/nextcloud/22653/htdocs/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Notes\\Controller\\NotesController"},"index"]},{"file":"/snap/nextcloud/22653/htdocs/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Notes\\Controller\\NotesController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"notes.notes.index"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"notes.notes.index"}]},{"file":"/snap/nextcloud/22653/htdocs/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"notes.notes.index"}]},{"file":"/snap/nextcloud/22653/htdocs/lib/base.php","line":1007,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/notes/notes"]},{"file":"/snap/nextcloud/22653/htdocs/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/snap/nextcloud/22653/nextcloud/extra-apps/notes/lib/Service/Note.php","Line":45,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36","version":"19.0.1.1"}

**Comment by pilsnerbeer** [comment]
Android app started working after reinstalling but web still same

**Comment by pilsnerbeer** [comment]
I have resolved the issue by restoring server backup. Cause unknown, but it had something to do with reverting & then upgrading the snap. I have no access to the broken version anymore so Im closing this

**Comment by korelstar** [comment]
Glad to hear you that you could fix the problem. However, I'm not happy, that a single erroneous file can break the whole app. Therefore, I've implemented an improved error handling for such a situation, see #593.
