### ISSUE TITLE
Missing API on web info

### ISSUE THREAD

**Issue by sciurius** [nextcloud/notes#595]
**Describe the bug**
The web info reads "Furthermore, a separate allows for an easy integration into third-party apps...".

The words "REST API" are missing.
![scrot20200825124810](https://user-images.githubusercontent.com/1118804/91165811-a0e2e880-e6d1-11ea-94b8-de591719dd6c.png)

**Comment by stefan-niedermann** [comment]
Where did you make the screenshot? The word `Rest-API` is there, but it is linked. See https://github.com/nextcloud/notes/blob/master/README.md

**Comment by sciurius** [comment]
![scrot20200825162816](https://user-images.githubusercontent.com/1118804/91187091-12ca2a80-e6f0-11ea-9dfc-e37836d7bb83.png)

**Comment by korelstar** [comment]
We have other links in that description and those are working. The difference is, that we use a relative path here, since the description is from [`README.md`](https://github.com/nextcloud/notes/blob/master/README.md). I will fix this.

**Comment by korelstar** [comment]
Fixed in https://github.com/nextcloud/notes/commit/0ff5ab1483102a8230cfb04349611c29db4ed52a, will be part of the next release.
