### ISSUE TITLE
Notes web app no longer working after upgrading to NC v20

### ISSUE THREAD

**Issue by aproposnix** [nextcloud/notes#596]
### Steps to reproduce
1. Upgrade to NC v20
2. Open the Notes web app

### Expected behaviour
I would expect that when I open the app I would see my notes like I normally do. 

### Actual behaviour
I only see a white screen with spining orbs. 
I have tried on both Firefox and Chrome with the same result. 

Note:  I can still work with notes on the mobile app. 

## Server configuration detail

**Operating system:** Linux 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64

**Webserver:** Apache/2.4.41 (Ubuntu) (apache2handler)

**Database:** mysql 10.3.22

**PHP version:** 

7.4.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, apc, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 20.0.0 Beta 1 - 20.0.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** updater

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.0
 - admin_audit: 1.10.0
 - bookmarks: 3.3.4
 - calendar: 2.0.3
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.3.0
 - contactsinteraction: 1.1.0
 - dav: 1.16.0
 - deck: 1.0.5
 - documentserver_community: 0.1.7
 - federatedfilesharing: 1.10.1
 - federation: 1.10.1
 - files: 1.15.0
 - files_pdfviewer: 2.0.O
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.0
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - gpxpod: 4.2.2
 - issuetemplate: 0.6.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - mail: 1.4.1
 - metadata: 0.12.0
 - news: 14.1.11
 - nextbackup: 20.4.0
 - nextcloud_announcements: 1.9.0
 - notes: 3.6.3
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - onlyoffice: 4.3.0
 - password_policy: 1.10.1
 - photos: 1.2.0
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - riotchat: 0.6.4
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - support: 1.3.0
 - survey_client: 1.8.0
 - suspicious_login: 3.1.0
 - systemtags: 1.10.0
 - tasks: 0.13.3
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_status: 0.0.2
 - viewer: 1.4.0
 - workflowengine: 2.2.0
Disabled:
 - apporder
 - audioplayer
 - bruteforcesettings
 - camerarawpreviews
 - dashboard
 - drawio
 - duplicatefinder
 - encryption
 - epubreader
 - event_update_notification
 - external
 - files_external
 - files_markdown
 - firstrunwizard
 - forms
 - guests
 - impersonate
 - maps
 - music
 - occweb
 - phonetrack
 - previewgenerator
 - rainloop
 - recommendations
 - richdocuments
 - richdocumentscode
 - spreed
 - user_ldap
 - weather_status

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "aproposnix.dyndns.org"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "20.0.0.3",
    "overwrite.cli.url": "https:\/\/aproposnix.dyndns.org\/",
    "Overwriteprotocol": "https",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "app_install_overwrite": [
        "social",
        "dashboard",
        "occweb",
        "issuetemplate",
        "suspicious_login",
        "calendar",
        "onlyoffice",
        "documentserver_community",
        "news",
        "riotchat",
        "contacts"
    ],
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_sendmailmode": "smtp",
    "updater.release.channel": "beta",
    "theme": "",
    "loglevel": 2,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0

**Operating system:** Ubuntu 20.04

**Browser Console Error**
Not sure this is usefuul, but I see this when I try loading the page. It's the only error message. 

>vue.runtime.esm.js:1888 TypeError: OCA.Search is not a constructor
    at o.created (App.vue:131)
    at Ue (vue.runtime.esm.js:1854)
    at Xt (vue.runtime.esm.js:4219)
    at o.e._init (vue.runtime.esm.js:5008)
    at new o (vue.runtime.esm.js:5154)
    at vue.runtime.esm.js:3283
    at init (vue.runtime.esm.js:3114)
    at vue.runtime.esm.js:5978
    at d (vue.runtime.esm.js:5925)
    at wn.__patch__ (vue.runtime.esm.js:6516)

![Selection_112](https://user-images.githubusercontent.com/6204273/91170212-86dfe080-e6a6-11ea-9061-39d5e6efed1c.png)

**Comment by korelstar** [comment]
Unfortunately, NC20 removed the old search without being compatible to NC19. I realized this yesterday :disappointed: 

See also https://github.com/nextcloud/notes/issues/288#issuecomment-678656220

I will try to provide a new release as fast as possible, but there are many breaking changes in NC20, see also #587.
