### ISSUE TITLE
Update ownCloud appstore

### ISSUE THREAD

**Issue by korelstar** [nextcloud/notes#61]
@Henni 
I don't know if it's intended, but the ownCloud appstore offers an [old version of the notes app](https://apps.owncloud.com/content/show.php/Notes?content=174554). I propose to update the entry continuously, because this could attract people to use this app and some of them could contribute to it -- and we are happy with every help, we get. :smiley: 

(E.g., the [tasks app](https://apps.owncloud.com/content/show.php/Tasks?content=164356) has updated the ownCloud appstore entry although its repository has moved to Nextcloud.)

**Comment by sergeydi** [comment]
I am working on Note app now. And I think it will be ready during next two weeks. If you are interested, you can participate in the testing.

**Comment by korelstar** [comment]
@sergeydi 
What do you mean? Are you working on an existing app (which one?) or are you writing a new one?

**Comment by sergeydi** [comment]
I am writing a new one. I think that during next two weeks I will upload first version on GitHUB.

**Comment by korelstar** [comment]
Why do you do that? Is there a need for *just another* notes app out there?
It would be cool, if we could bundle all power in order to create one great app instead of many similar apps.

You are very welcome to contribute to this app!

**Comment by sergeydi** [comment]
Sorry its my mistake, I am working in iOS version of notes app. I think that when you are talking appstore, you mean Apple AppStore...

**Comment by korelstar** [comment]
Ah, okay. No, this issue is about the **ownCloud** appstore.

But I think there is already an iOS client for the Notes app: CloudNotes
https://itunes.apple.com/us/app/cloudnotes-owncloud-notes/id813973264?ls=1&mt=8
https://github.com/owncloud/notes-iOS-App

Did you had a look at that app? Maybe you can contribute there?

**Comment by sergeydi** [comment]
Thank you. I will look at this version.

**Comment by camilasan** [comment]
This is definitely an old issue :)
https://apps.nextcloud.com/apps/notes
