### ISSUE TITLE
[Feature proposal] standalone applications for Mac, Windows, Linux

### ISSUE THREAD

**Issue by ralxxx** [nextcloud/notes#615]
**Is your feature request related to a problem? Please describe.**
I am using notes on my mobile as well as on my desktop computer. What frustrates me is that on my computer it that fact that here is no stand-alone application for non mobile devices (Win/Mac/Linux). The usability is so much higher when using similar services with stand-alone services.

**Describe the solution you'd like**
Stand-alone applications for Windows-Mac-Linux.  

**Describe alternatives you've considered**
Simplenote (https://simplenote.com/) offers a webbrowser-based service as well as on iOS, Android as well as on Mac, Windows, Linux. The software is Open Source. Only downside is the fact that it is not clear where personal data is saved. 

**Additional context**
--

**Comment by stefan-niedermann** [comment]
You can use [QOwnNotes](https://www.qownnotes.org/) which is capable of syncing with Nextcloud Notes 🙂
