### ISSUE TITLE
Add support for Wiki links

### ISSUE THREAD

**Issue by Nebucatnetzer** [nextcloud/notes#616]
There a currently a lot of note taking applications getting made which are inspired by the Zettelkasten method.
A lot of those apps started adopting the wiki link format to link notes together. `[[Note Name]]`
I'm currently using Obsidian.md on the desktop to work with my notes but on the go I'm using Nextcloud Notes.
Therefore I have a lot of notes with links to each other but the links aren't working in the Android application or the web application.

**Describe the solution you'd like**
Add support for the Wiki link, link format. So that one can use:
`[[Note Name]]` to link to a file
and
`[[Note Name#Heading]]` to link to a heading.

**Comment by stefan-niedermann** [comment]
Since we plan to migrate to [Nextcloud Text](https://github.com/nextcloud/notes/issues/331) as markdown renderer in the future, i vote against adding new syntax support which is not supported by Nextcloud Text at this time.

**Comment by Nebucatnetzer** [comment]
I don't have problem with opening an issue about this on the Nextcloud Text project.

Sep 26, 2020 17:47:38 Niedermann IT-Dienstleistungen <notifications@github.com>:

**Comment by stefan-niedermann** [comment]
@Nebucatnetzer if @korelstar (maintainer of this repo) agrees, i think this would make more sense for a consistent feature set across all Nextcloud apps which use markdown.

**Comment by Nebucatnetzer** [comment]
I created the issue at Nextcloud Text but will keep this issue here open as well at least until we have a response from upstream.

**Comment by korelstar** [comment]
I agree with @stefan-niedermann, but we can leave this open until we finished switching to Text

**Comment by newhinton** [comment]
So, is switching to nextcloud text even an option? The current issues with their implementation would be a dealbreaker for me. 

Also it seems this wouldn't be too hard to implement, so i'd give it a try

**Comment by korelstar** [comment]
You're right, switching to Nextcloud Text is currently not an option due to the critical issues (see #652).

However, I'm still against introducing a new non-Markdown syntax.
