### ISSUE TITLE
Not working with nncli

### ISSUE THREAD

**Issue by klundry** [nextcloud/notes#618]
Is nncli no longer supported? The latest release is over a year old at this point and I think the api may have moved on. Is there any way to get nncli to talk to the latest version of Notes or is there another cli client?

```
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //cloud.cyberbot.space/index.php/apps/notes/api/v0.2/notes?exclude=content (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f283798dc40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2020-09-29 23:51:51,706 [DEBUG] ERROR: Failed to get note list from server
2020-09-29 23:51:51,707 [DEBUG] Full sync completed
2020-09-29 23:52:06,707 [DEBUG] Starting full sync
2020-09-29 23:52:06,708 [DEBUG] REQUEST: https://https://'my server address'/index.php/apps/notes/api/v0.2/notes?exclude=content
2020-09-29 23:52:06,711 [DEBUG] Starting new HTTPS connection (1): https:443
2020-09-29 23:52:06,717 [ERROR] request error
```

**Comment by stefan-niedermann** [comment]
To be honest, i wasn't even aware that there was a command line interface 😄.

You should ask the developer of the cli: https://www.danielmoch.com/ - there are plenty contact information on his website.

If the project is still alive, we can add it to the [list of known 3rd party clients](https://github.com/nextcloud/notes/wiki#3rd-party-clients) in our wiki.

**Comment by korelstar** [comment]
I'm sorry, but we can't provide support for third-party clients. Please contact the developer of your client.

That said, according to the logs, it looks like you may use a wrong URL. The client tries to connect to a host named `https`, the full URL seems to bee `https://https://'my server address'/index.php/apps/notes/api/v0.2/notes?exclude=content`  which obviously can't work. Please check your configuration and/or command line parameter!

In general, nncli uses the deprecated API version 0.2, but this should still work with the lates Notes (server) app.

**Comment by klundry** [comment]
> I'm sorry, but we can't provide support for third-party clients. Please contact the developer of your client.
> 
> That said, according to the logs, it looks like you may use a wrong URL. The client tries to connect to a host named `https`, the full URL seems to bee `https://https://'my server address'/index.php/apps/notes/api/v0.2/notes?exclude=content` which obviously can't work. Please check your configuration and/or command line parameter!
> 
> In general, nncli uses the deprecated API version 0.2, but this should still work with the lates Notes (server) app.

I wasn't expecting any support for the client. Was just hoping to find out if it was worth messing with or if there was no chance of it working anymore..which I suppose is kind of like asking for support so my apologies. Thank you for the reply though as it helped me get it working! The config file only wants the domain and not the "https://" part as it adds it again. I hadn't noticed that initially. 

Anyways, it does work and it is pretty great as a simple command line notes client! Hopefully it continues to work because i really like it. Cheers.

**Comment by klundry** [comment]
Oh, I also just noticed that nncli is actually linked to in the first paragraph of the Notes Readme, although the link is broken because the url doesn't exist anymore. Might be a good idea to remove it if its too outdated to promote in the Readme or fix the link to point to https://nncli.org.
