### ISSUE TITLE
RestAPI doesn't work

### ISSUE THREAD

**Issue by DMinsky** [nextcloud/notes#62]
Looks like RestAPI doesn't work on my server. I can easy access notes with web interface with these urls:
https://mydomain.com/nextcloud/index.php/apps/notes/
https://mydomain.com/nextcloud/index.php/apps/notes/#/
But when I try to open 
_https://mydomain.com/nextcloud/index.php/apps/notes/api/v0.2/_
in my browser it just redirect me to 
https://mydomain.com/nextcloud/index.php/apps/files/?dir=/&fileid=29

p.s. nextcloud-notes android client also doesn't want to login.

**Comment by korelstar** [comment]
The redirect is normal. Please try https://mydomain.com/nextcloud/index.php/apps/notes/api/v0.2/notes instead and use `curl` in order to test if the API works correctly:
`curl https://mydomain.com/nextcloud/index.php/apps/notes/api/v0.2/notes -u YOURUSERNAME`

**Comment by DMinsky** [comment]
Oh, looks like there is an issue with my reverse proxy setup. With curl I get 504 Gateway Time-out if I do request through reverse proxy. But when I do request directly to server with nextcloud I get {"message":"CORS requires basic auth"}  Is this what expected on _index.php/apps/notes/api/v0.2/notes -u YOURUSERNAME_ request?

**Comment by DMinsky** [comment]
p.s. seems like all this is related to overall nextcloud 11 performance (https://github.com/nextcloud/server/issues/2272) just because increasing of timeouts on nginx helped.
