### ISSUE TITLE
HTTP 500 error in Dashboard

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/notes#620]
After entering Dashboard, I get an HTTP 500 error.

![obraz](https://user-images.githubusercontent.com/47037905/95583612-b2434280-0a3c-11eb-881f-4515fe43b82f.png)

**Server (please complete the following information):**
- Notes app version: 4.0.0
- Nextcloud version: 20.0.0
- PHP version: 7.3.16

**Log files**
Add relevant parts of your `nextcloud.log` and/or your browser's JavaScript console here.
```
Exception: 

    /home/xxx/public_html/cloud/lib/private/AppFramework/Http/Dispatcher.php - line 123:

    OCP\AppFramework\Http\JSONResponse->render()

    /home/xxx/public_html/cloud/lib/private/AppFramework/App.php - line 152:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Notes\Co ... {}, "dashboard")

    /home/xxx/public_html/cloud/lib/private/Route/Router.php - line 308:

    OC\AppFramework\App::main("OCA\\Notes\ ... r", "dashboard", OC\AppFramew ... {}, { action: nu ... "})

    /home/xxx/public_html/cloud/lib/base.php - line 1009:

    OC\Route\Router->match("/apps/notes/notes/dashboard")

    /home/xxx/public_html/cloud/index.php - line 37:

    OC::handleRequest()
```

**Comment by korelstar** [comment]
Hmm, honestly I have no idea which could cause this exception. The log excerpt is not very meaningful. :-(

Could you please try to restart your webserver and php-fpm (if used)? Sometimes this helps with strange issues.

Does the notes app itself work?

Does anybody else have such a problem?

**Comment by Santobert** [comment]
> Does anybody else have such a problem?

I have this issue as well. Latest Nextcloud in Docker with nginx reverse proxy. Nothing special besides that.

**Comment by Valdnet** [comment]
> Does the notes app itself work?

The application is working fine.

**Comment by korelstar** [comment]
I tried to reproduce this issue with docker, but I failed. Can you please provide more information about your setup? A step-by-step guide on how to setup the problematic environment would be nice.

Are there any special notes in your account? Does this happen to every account on that server?

Maybe somebody can find a more meaningful log with an exception message and without shortened strings?

**Comment by Santobert** [comment]
The error doen't show up in the docker logs. 
There are some JS Errors:
```javascript
Uncaught TypeError: OCA.Files.DetailTabView is undefined
    <anonymous> https://cloud.tobhaase.de/js/activity/activity-sidebar.js?v=d547ee66-96:603
    <anonymous> https://cloud.tobhaase.de/js/activity/activity-sidebar.js?v=d547ee66-96:803
activity-sidebar.js:603:24

Uncaught TypeError: n.Files.DetailTabView is undefined
    <anonymous> commentstabview.js:21
    <anonymous> commentstabview.js:756
    Webpack 3
commentstabview.js:21:23

Uncaught TypeError: OCA.Files.DetailTabView is undefined
    <anonymous> versionstabview.js:18
    Webpack 3
versionstabview.js:18:7

Error: Request failed with status code 500
    exports createError.js:16
    exports settle.js:17
    onreadystatechange xhr.js:69
NotesService.js:55:11
    A NotesService.js:55

Uncaught (in promise) Error: Request failed with status code 500
    exports createError.js:16
    exports settle.js:17
    onreadystatechange xhr.js:69
createError.js:16:14
```

And there is another error, that shows up in the server logs:
```
[index] Error: Exception: null at <<closure>>

0. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 123
   OCP\AppFramework\Http\JSONResponse->render()
1. /var/www/html/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Notes\Controller\NotesController {}, "dashboard")
2. /var/www/html/lib/private/Route/Router.php line 308
   OC\AppFramework\App::main("OCA\\Notes\\Controller\\NotesController", "dashboard", OC\AppFramework\ ... {}, {action: null,_r ... "})
3. /var/www/html/lib/base.php line 1009
   OC\Route\Router->match("/apps/notes/notes/dashboard")
4. /var/www/html/index.php line 37
   OC::handleRequest()

GET /apps/notes/notes/dashboard
from 217.238.238.100 by tobhaase at 2020-10-26T06:42:58+00:00
```

I hope this helps, since I can't provide a detailed step-by-step guide how to reproduce this error.

**Comment by Santobert** [comment]
It looks like this issue is listed twice: https://github.com/nextcloud/server/issues/23241

**Comment by korelstar** [comment]
Thanks, but I'm still not sure what's the problem's source. It could be something related to the notes character set, because JSON rendering seems to fail. But I still wasn't able to reproduce. Therefore, please answer some more questions:

- does this happen even if you have no notes in your account? (for testing purposes you could temporarily change the notes path to an empty folder)
- what language have your notes / do the notes contain some/many (?) multi-byte/non-ASCII characters?
- does the issue happen for anybody in a non-Docker setup?

**Comment by Santobert** [comment]
Wow that's it. Some of my notes contained square meters (²). After I had removed the small 2, the error was gone.

**Comment by D-side** [comment]
This issue occurs when 100th (!) character is multi-byte in UTF-8, be it a Russian letter, a ² or whatever else multibyte.

Create a note with this text to reproduce the issue (and make sure to set the title to something different):

```
So if I provide a sufficient amount of English text to invoke truncation, does anything nasty occur¿
```

And that seems to be because **excerpt generation** uses `substr` which for multi-byte encodings may stop mid-character, producing invalid UTF-8 which causes some breakage inside. I don't know my way around PHP very well, but [it sounds like using `mb_substr` + `"utf-8"` instead may fix this](https://stackoverflow.com/q/9087502/).

https://github.com/nextcloud/notes/blob/937c08754bdd984a0a8eb85b0bb9b0008f004586/lib/Service/Note.php#L57-L71

**Comment by bentolor** [comment]
Thanks, @D-side ! 

I can confirm this is the issue & fixes it, @korelstar ! I'm a german user and had this issue for quite some time. With the hint of D-side I just went inside the docker container an hot-patched the given lines by simply replacing the two `substr` instances with `mb_substr` calls. and it immediately started to work.

![image](https://user-images.githubusercontent.com/588260/99897671-c1541c00-2c9b-11eb-98b9-acd45a50d3e1.png)

I'm a total PHP noob and not sure to the full extent about the "100" and the strange magic codes appended. If it helps I can provide a MR with the change.

**Comment by bentolor** [comment]
On looking on the [PHP API documentation](https://www.php.net/manual/en/function.mb-substr.php) it seems by first modification is wrong and I should use ` $excerpt = mb_substr($excerpt, $length, NULL, "utf-8");` instead. (Not sure: Does PHP sth. like named arguments?)

I created a pull request https://github.com/nextcloud/notes/pull/630 for everybodies convenience
