### ISSUE TITLE
Opening a note via Dashboard

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/notes#622]
**To Reproduce**

1. Create a new note.
2. Go to the Dashboard app.
3. Click on the created note to open it.

The note opens in a **new browser window** if you open it through the Dashboard.
In my opinion, it should open in the same browser window.

**Server (please complete the following information):**
- Notes app version: 4.0.0
- Nextcloud version: 20.0.0

**Client (please complete the following information):**
 - Browser (incl. version): Firefox 81.0.2

**Comment by korelstar** [comment]
This is enforced by the Nextcloud framework, see: https://github.com/nextcloud/nextcloud-vue-dashboard/blob/v1.0.1/src/DashboardWidgetItem.vue#L164

I think the idea is that users should be able to leave their dashboard open the whole session. Maybe @juliushaertl can tell the real rationale?

**Comment by juliushaertl** [comment]
@jancborchardt Argued for this during our discussions when writing the first widgets, but I don't remember the exact reasoning. Maybe he can clarify that again.

**Comment by korelstar** [comment]
ping @jancborchardt

**Comment by korelstar** [comment]
Although we are still waiting for the exact reason for this behavior, we nevertheless won't be able to change it in this app. If this is important to you, @Valdnet, please open a new issue in [nextcloud-vue-dashboard](https://github.com/nextcloud/nextcloud-vue-dashboard).
