### ISSUE TITLE
Formatting toolbar disappears when a note is more than a screen height in length

### ISSUE THREAD

**Issue by rca** [nextcloud/notes#624]
**Describe the bug**
Once a note is more than a screen height in length, the formatting toolbar at the top of the page disappears and it becomes harder to format the document as one is typing.

**To Reproduce**
1. create a note with the `.md` extension
2. write a lot of text so that there is more text than fits on the screen
3. go to the bottom of the text
4. notice that the toolbar that used to be on the top of the screen disappears and is no longer available.

**Expected behavior**
I'd expect the toolbar to be visible in order to continue using it.

**Screenshots**
Here is a long note when the cursor is within the first screenful of text; notice the formatting toolbar is visible
<img width="1792" alt="Screen Shot 2020-10-30 at 10 43 01 PM" src="https://user-images.githubusercontent.com/53537/97769454-a1e52b80-1b01-11eb-9b66-558aee416ece.png">

Once the page is scrolled past the first screenful of text, the toolbar disappears:
<img width="1792" alt="Screen Shot 2020-10-30 at 10 43 21 PM" src="https://user-images.githubusercontent.com/53537/97769468-c50fdb00-1b01-11eb-80a4-6071e1d4ef64.png">

**Server (please complete the following information):**
- Notes app version: 4.0.0
- Nextcloud version: 20.0.1
- OS: Linux (using [linuxserver.io nextcloud container](https://hub.docker.com/r/linuxserver/nextcloud))
- Web server: nginx

```
apk info nginx
nginx-1.18.0-r1 description:
HTTP and reverse proxy server (stable version)
```

- PHP version: 

```
$ php --version
PHP 7.3.23 (cli) (built: Oct  1 2020 14:34:47) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.23, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.23, Copyright (c) 1999-2018, by Zend Technologies
```

- Database: sqlite

**Client (please complete the following information):**
 - Browser (incl. version): Safari 14.0
 - OS: MacOS 10.15.7

**Log files**
N/A

**Comment by stefan-niedermann** [comment]
Your screenshots do not show the Notes app ([compare to the Notes app](https://github.com/nextcloud/notes/) but they show the [Nextcloud Text](https://github.com/nextcloud/text) app.

It seems like you have opened your note from within the Files app instead of explicitely opening the Notes app first.

Please reopen your issue [here](https://github.com/nextcloud/text/issues/new?labels=bug&template=Bug_report.md).
