### ISSUE TITLE
Quick create new collaborative note button

### ISSUE THREAD

**Issue by raphaelbastide** [nextcloud/notes#628]
**Is your feature request related to a problem? Please describe.**
Notes, together with the “share” and “allow editing” option makes good alternatives to collaborative pads such as etherpad. Those useful collaborative document often has to be created quickly, and by users without expertise. Currently, creating a collaborative text file suggest that the user:

- Knows the path where the text files are stored
- Know / has the right to create a new file
- Know how to make it sharable
- Know how to change the rights to “allow editing” 

Those 4 steps require a documentation, that I think we can avoid with an easier solution.

**Describe the solution you'd like**

A simple page, accessible via a menu button, allowing users and external users (depending on the settings) to add a new collaborative note.

**Describe alternatives you've considered**
Instead of patching the Note app, this can be another dedicated nextcloud app.

**Additional context**

![pad](https://user-images.githubusercontent.com/193122/99371394-23d5a280-28bf-11eb-939d-e0de8fa0a34b.png)

If another solution can solve this need, please let me know about it, I am simply not aware of its existence.

**Comment by stefan-niedermann** [comment]
> If another solution can solve this need, please let me know about it

- Regarding sharing: Yes: [Share a single note / publish](https://github.com/nextcloud/notes/issues/38)
- Regarding collaboration: Yes, it is even pinned: [Integrate Nextcloud Text](https://github.com/nextcloud/notes/issues/331):
  > This is a new rich text editor [...] providing collaborative editing. 

Closing this as duplicate therefore :slightly_smiling_face:

**Comment by raphaelbastide** [comment]
My feature request doesn’t ask a note to be shared and collaborative. I am currently able to do that. My feature request ask quick access to a new collaborative note. In this sense, those are not duplicates. But your answer makes me realize I already use Nextcloud text for collaboration. I should maybe suggest my feature request there.

**Comment by stefan-niedermann** [comment]
> I am currently able to do that.
> I already use Nextcloud text for collaboration

Correct, the Notes app does simply not yet support it. What you actually are doing (outside of the Notes app), is to open a text or markdown file from the Files app with the [Nextcloud Text](https://github.com/nextcloud/text/) editor.

So yeah - wait for the two issues to be resolved, then we can talk about how to integrate some kind of Quick access button - and in the meantime you maybe want to open a feature request [in the Nextcloud Text repository](https://github.com/nextcloud/text/issues/new?labels=enhancement&template=Feature_request.md). (Personally i think a separate app which hooks on the `+` button of the Files app and provides some kind automatism for the wanted steps would be a better approach).

**Comment by raphaelbastide** [comment]
> Personally i think a separate app which hooks on the + button of the Files app and provides some kind automatism for the wanted steps would be a better approach

Yes, I am beginning to think that too! I will see if my skills allow me to make an app myself… Thank you anyway.

**Comment by stefan-niedermann** [comment]
Would be cool if you can keep us updated! It might be interesting once the linked issues are solved :slightly_smiling_face:
