### ISSUE TITLE
extension .md as default for every new user

### ISSUE THREAD

**Issue by markushub** [nextcloud/notes#629]
**Is your feature request related to a problem? Please describe.**
Open notes files on pc - opens it in normal text viewer as normal text because of the extension .txt (no markdown format)

**Describe the solution you'd like**
Option to set .md for markdown as default extension for all new user

**Describe alternatives you've considered**
notify every new user to manually set .md as default

**Additional context**
I know the setting in option in the bottom left of the Web UI, but it is only for one (current) user

**Comment by Baptistou** [comment]
As a workaround, I use the OCC command line to apply this default setting to new users :

```shell
occ user:setting username notes settings '{"fileSuffix":".md","notesPath":"Notes"}'
```

**Comment by pat-githubber** [comment]
Hi @Baptistou, I would love to implement your solution in my nextcloud but I am nooby and I am not able to understand how I can make the command `occ` work on my machine. I tried to understand the [documentation](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html) without success. I receive `occ: command not found`

I would be glad about any help!

I run Nextcloud 22.2.3 on a RaspberryPi installed from [OwnYourBits](https://ownyourbits.com/nextcloudpi/).

**Comment by Baptistou** [comment]
Hi @pat-githubber, you need PHP in order to launch `occ`.

> `occ` is in the `nextcloud/` directory; for example `/var/www/nextcloud` on Ubuntu Linux. `occ` is a PHP script. You must run it as your HTTP user to ensure that the correct permissions are maintained on your Nextcloud files and directories.

Depending on your machine, you can define an alias as below :
`alias occ='sudo -u www-data /usr/bin/php7.4 /path/to/nextcloud/occ'`

**Comment by daeavelwyn** [comment]
I put a thumbup 👍 , As Notes use default markdown syntax, it would be really great that wd could define .md as default file format.

BTW, I love this app, simple and very efficient, thanks a lot guys for your hard work on it !
