### ISSUE TITLE
Note open in two windows leads to lost data

### ISSUE THREAD

**Issue by brortao** [nextcloud/notes#63]
I ran into a problem earlier when I had this app open in two separate browser windows. I typed a lot of data into one of these, and there was a spinner going constantly in the corner. Refreshing the page caused everything I had typed to be lost - it had not been saved, hence the spinner.

I looked at my logs and as far as I can tell, the app was unable to save the note because it was (or had been) opened in another window:

    OCP\Lock\LockedException: "Notes/my_note.txt" is locked

Is the app supposed to continually retry saving in a case like this? If so, it doesn't seem like it happened here. Another potential solution would be to save unsynced data locally - this would also be useful if the connection drops.

I tried reproducing this, but I was unable to. I'm not sure exactly what caused the note to be locked, but I'm posting this to see if others have run into the same issue.

**Comment by jancborchardt** [comment]
Any idea @nextcloud/notes?

**Comment by Henni** [comment]
I believe the locking issue occurred before. I'll have to dig into this.

**Comment by GLLM** [comment]
Hi all !
Since yetserday, I'm getting locks on files as well ... 
The only thing I did since it started was revoke the access the Andoird Notes app had on  my nextcloud instance ...

> OCP\Lock\LockedException: "Notes/MyFileName.txt" is locked
> 
>     /home/my_own_path/www/nextcloud/lib/private/Files/View.php - line 2018: OC\Files\View->lockPath('/MyUserName/file...', 1, false)
>     /home/my_own_path/www/nextcloud/lib/private/Files/View.php - line 1122: OC\Files\View->lockFile('/MyUserName/file...', 1)
>     /home/my_own_path/www/nextcloud/lib/private/Files/View.php - line 580: OC\Files\View->basicOperation('file_get_conten...', '/MyUserName/file...', Array)
>     /home/my_own_path/www/nextcloud/lib/private/Files/Node/File.php - line 51: OC\Files\View->file_get_contents('/MyUserName/file...')
>     /home/my_own_path/www/nextcloud/apps/notes/db/note.php - line 57: OC\Files\Node\File->getContent()
>     /home/my_own_path/www/nextcloud/apps/notes/service/notesservice.php - line 84: OCA\Notes\Db\Note fromFile(Object(OC\Files\Node\File), Object(OC\Files\Node\Folder), Array)
>     /home/my_own_path/www/nextcloud/apps/notes/controller/pagecontroller.php - line 64: OCA\Notes\Service\NotesService->get(164146, 'MyUserName')
>     [internal function] OCA\Notes\Controller\PageController->index()
>     /home/my_own_path/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
>     /home/my_own_path/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Notes\Controller\PageController), 'index')
>     /home/my_own_path/www/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Notes\Controller\PageController), 'index')
>     /home/my_own_path/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Notes\\Contr...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
>     [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
>     /home/my_own_path/www/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
>     /home/my_own_path/www/nextcloud/lib/base.php - line 1004: OC\Route\Router->match('/apps/notes/')
>     /home/my_own_path/www/nextcloud/index.php - line 48: OC handleRequest()
>     {main}

**Comment by jancborchardt** [comment]
Let’s continue in the discussion on concurrent editing at #56
