### ISSUE TITLE
Popover menu runs off-screen

### ISSUE THREAD

**Issue by bencomp** [nextcloud/notes#646]
**Describe the bug**
When I edit a note in Firefox, both on Windows and MacOS, and want to change the note's category, I click the three-dot menu and see that the popover is partially positioned outside the visible screen.

Looking at screenshots in #413, I understand this may not affect all users.

**To Reproduce**
1. Open Notes app in web interface
2. Click the menu button in the editing interface
3. See only part of the menu

**Expected behavior**
I expect the popover menu to stay within my visible screen area.

**Screenshots**
![Popover menu goes off-screen](https://user-images.githubusercontent.com/1303898/101983748-4b7d1800-3c7d-11eb-800f-32d2a009ba99.png)

**Server (please complete the following information):**
- Notes app version: 3.6.4
- Nextcloud version: 19.0.5
- OS: Ubuntu 18 LTS
- Web server: Apache in Nextcloud Docker container `nextcloud:19-apache`
- PHP version: As provided in Docker
- Database: Docker image `mariadb:10.3`

**Client (please complete the following information):**
 - Browser (incl. version): Firefox 81.0.1, Firefox 83
 - OS: Windows 7 / MacOS 10.15.7

**Log files**
I don't see relevant log messages in the web console. Using the Inspector, I do notice that `translate: translate3d(…, …, …)` causes the popover menu to move to its position – maybe adjusting the parameters would solve this issue.

**Comment by stefan-niedermann** [comment]
cc @skjnldsv

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/nextcloud-vue/issues/1384

**Comment by korelstar** [comment]
Does this also happen with the latest version (i.e. 4.0.1) of the Notes app?
