### ISSUE TITLE
Responsive template of shared notes

### ISSUE THREAD

**Issue by broslavski** [nextcloud/notes#648]
Shared notes are displayed beyond the screen on on smartphone resolutions. They should be responsive and fully adapt to the resolution of any screen.

**Comment by stefan-niedermann** [comment]
Please fill out the complete issue template with screenshots, steps to reproduce and software versions.

**Comment by broslavski** [comment]
I think the problem is due to the fact that there is no styling for responsiveness of multiline code block such as this:
```
if (isAwesome){
  return true
}
```
Examples:
- [iPhone X](https://share.getcloudapp.com/YEuQBPeN)
- [iPhone 6/7/8 Plus](https://share.getcloudapp.com/X6u088rQ)

**Comment by stefan-niedermann** [comment]
Those screenshots are not from the Nextcloud Notes app but from [Nextcloud Text](https://github.com/nextcloud/text/) which will be opened when you are clicking on a text document in the files app.

Next time please use the issue template, it is there for a reason.
