### ISSUE TITLE
Rendering bugs on PC app

### ISSUE THREAD

**Issue by roipoussiere** [nextcloud/notes#65]
- **Type**: bug
- Platform: PC

There are several rendering bugs when looking a note from the PC app. All the following text is correctly rendered on the Android app.

```
#A: Title without space after the `#`

>>> B: multiple citation

**`C: Some code in bold`**

*`D: Some code in italic`*

- E: A nested
    - list

```

But this is what I got on the PC app:

![](http://i.imgur.com/TihwnQ2.png)

**Comment by rushsteve1** [comment]
A `#` without a space after is not supposed to become header ([according to commonmark](http://spec.commonmark.org/0.27/#atx-headings))

**Comment by roipoussiere** [comment]
I just note the inconsistency between the web app and the Android app. If a `#` without a space is not supposed to be a header, so the Android app should not render `#foo` as a header.

**Comment by camilasan** [comment]
Do you still have this problem @roipoussiere?

**Comment by roipoussiere** [comment]
Sorry, I don't use this app anymore. Maybe someone else can answer?

**Comment by jancborchardt** [comment]
The libraries we use on web and Android are different so there might be some inconsistencies, but yeah ideally they are low.

But yeah, if you don’t use the app anymore then I’ll close the issue. :)
