### ISSUE TITLE
File revisions

### ISSUE THREAD

**Issue by muety** [nextcloud/notes#664]
Hi all! I'm using Nextcloud Notes for quite a while now and I am very happy with it. However, I just found that for every note, a lot of revisions are saved in `file_revisions`, sometimes for than 100 or so.

My concern might not even be related to Notes, but to Nextcloud in general, but I'd like to know if and how I configure this versioning behavior and clean things up a bit. Any ideas?

**Comment by korelstar** [comment]
This is part of the Nextcloud server and can be configured. Please have a look at the administration manual: https://docs.nextcloud.com/server/20/admin_manual/configuration_files/file_versioning.html
