### ISSUE TITLE
Colors and pin note

### ISSUE THREAD

**Issue by talesam** [nextcloud/notes#666]
I use Keep a lot and I'm migrating to Notes with my personal Nextcloud server, something that I miss that helps a lot visually is being able to color notes to identify them in a simpler way and you can fix them at the top.

**Comment by stefan-niedermann** [comment]
"Pinning" notes at the top is already possible: Just mark a note as favorite (click the ⭐ icon) and it will get sorted to the top automatically.

For colors see https://github.com/nextcloud/notes/issues/10
