### ISSUE TITLE
Enumeration not parsed properly when number is bold

### ISSUE THREAD

**Issue by muety** [nextcloud/notes#668]
Consider this Markdown snippet:

```markdown
**1.** Foo
**2.** Bar
```
It gets rendered as:

**1.** Foo **2.** Bar

The enumeration is not being interpreted as such, however, in my opinion, it should be.

**Comment by stefan-niedermann** [comment]
I'm afraid that this is no valid markdown according to the [commonmark specification](https://spec.commonmark.org/).

**Comment by muety** [comment]
Never mind, I was confused. Obviously, it should be:

```markdown
* **1.** Foo
* **2.** Bar
```
