### ISSUE TITLE
note can not be entered in Chinese!

### ISSUE THREAD

**Issue by tianmotrue** [nextcloud/notes#67]
Note can not be entered in Chinese. But the note in owncloud can be entered in Chinese. Is this a bug? Or note in nextcloud does not support double-byte text?Is there a plan to solve this problem?

**Comment by korelstar** [comment]
Nextcloud as well as the notes app use UTF-8. Hence, Chinese *should* be no problem. What is *exactly* the problem? Please give more details and have a look at the [issue template](https://github.com/nextcloud/notes/blob/master/CONTRIBUTING.md).

**Comment by korelstar** [comment]
Oh, I just see that there is already a respective issue: #59. Please continue there.
