### ISSUE TITLE
"Cancel" save should not delete changes to note

### ISSUE THREAD

**Issue by ab0oo** [nextcloud/notes#682]
This morning, I made several changes to a note, then wanted to switch to another note.  I got the modal popup that says "You have made changes to this note  -- Do you want to save them" with the choices "Cancel" or "Save Changes".
I saw that I needed to fix a typo in the note I'd edited, and hit cancel, at which time Notes removed all my edits and took me to the second Note.
It's probably better design to make a third choice, or make it abundantly clear what's going to happen:  Abandon Changes, Cancel (i.e. stop this action, return to the last state), or Save Changes.
Fortunately, I didn't lose a LOT of work, but I could see how that could be dangerous and frustrating to someone that made a lot of changes.
Thanks for considering this.
John Gorkos

**Comment by stefan-niedermann** [comment]
Are you sure that you are referring to this Notes app? I wasn't even aware that there is such a confirmation dialog.
This Notes app is supposed to save on the fly automatically in the background.

**Comment by ab0oo** [comment]
How embarrassing.  Wrong app.  I'm using the Nextcloud Notes for Mac app.  Apologies.  I'll go do some remedial google training now.
