### ISSUE TITLE
Notes isn't visible to users that aren't assigned to group user

### ISSUE THREAD

**Issue by lepool** [nextcloud/notes#684]
I don't know if that are intentionally set. 

## Steps to reproduce
1. create new user
2. verify that new user aren't 'assigned to group "user"
3. verify notes isn't visible on dashboard to new created user

### Expected behaviour
Notes App should be visible to all users

### Actual behaviour
Notes are visible only users assigned to group "user"

## Server

- Notes app version: 4.0.2
- Nextcloud version: 20.0.8
- OS: debian buster
- Web server: apache2 
- PHP version: 7.3.27-1~deb10u1
- Database: mysql 8.0.23

## Client
Please complete the following information.

- Browser (incl. version):  some browsers like firefox , chrome
 - OS: linux , windows

**Comment by korelstar** [comment]
What do you do exactly expect? Is it about the dashboard or the apps list (Nextcloud's top bar)? Could you please provide a screenshot?

**Comment by lepool** [comment]
Here the screenshot of the Nextcloud's top bar : 
the first one if the user aren't assigned to group users
the second one if the user is assigned to group users

![Bildschirmfoto von »2021-03-03 10-45-08«](https://user-images.githubusercontent.com/32035706/109787211-47262280-7c0e-11eb-8cb3-c190f314b247.png)
![Bildschirmfoto von »2021-03-03 10-46-35«](https://user-images.githubusercontent.com/32035706/109787227-4a211300-7c0e-11eb-9a2b-4320422e9c74.png)

you can see that the icon for notes in the first case aren't visible

**Comment by korelstar** [comment]
That's strange. As far as I know, there is no special "users" group in Nextcloud. There is definitely no special handling in the notes app for such a group.

Do you use any other app that influences the top bar, e.g. AppOrder or something similar? Maybe you can list all apps that you have installed?

**Comment by lepool** [comment]
Yes, i have apporder installed, but there are no difference if i deactivate it.

I have corrected the following comment https://github.com/nextcloud/notes/issues/684#issuecomment-789586445

not "users" but "user"

**Comment by lepool** [comment]
here a list of my apps : 

Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - audioplayer: 3.1.0
  - audioplayer_editor: 0.3.0
  - bookmarks: 4.1.0
  - calendar: 2.1.3
  - checksum: 1.1.1
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - dav: 1.16.2
  - deck: 1.2.4
  - emlviewer: 0.0.21
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_downloadactivity: 1.9.0
  - files_external: 1.11.1
  - files_markdown: 2.3.2
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - firstrunwizard: 2.9.0
  - keeweb: 0.6.5
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.9.1
  - maps: 0.1.8
  - metadata: 0.13.0
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.3
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - radio: 1.0.2
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.6
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - terms_of_service: 1.6.1
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_ldap: 1.10.2
  - user_status: 1.0.1
  - viewer: 1.4.0
  - workflowengine: 2.2.0
Disabled:
  - bruteforcesettings
  - dashboard
  - encryption
  - files_videoplayer
  - music
  - video_converter
  - weather_status

**Comment by korelstar** [comment]
Okay, it looks like Nextcloud has a setting for limiting apps to specific groups. Maybe you have activated this setting by accident?

Here is an instruction on how to change this setting: https://github.com/nextcloud/server/issues/25411#issuecomment-786293469

**Comment by lepool** [comment]
Yes !  Tthanks. I don't know if it was a accidentally settings .
