### ISSUE TITLE
Move API documentation Opem-API / Swagger

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/notes#698]
The REST-API is curreny [documented with Markdown](https://github.com/nextcloud/notes/tree/master/docs/api).

I propose to rewrite it in `.yaml` using Open-API / Swagger. This way clients as well as the server could generate some code from it. Changing data types will result in a breaking build pipeline for the clients (-> They will immediately get notified if there is a breaking change). Another benefit is that the machine readable format allows the generation of a fancy graphical documentation.

@korelstar what do you think about it? Might this be a thing for you? Do you know Open-API already? Do you think it might be useful for the server part, too?

**Comment by korelstar** [comment]
I was already aware of that specification, but I didn't recognized the advantage for me. Now, that you are talking about, I found out that it can be used together with a validator and phpunit for testing the API. That would be an enhancement. However, I still don't think that code generation would help me for the server-side.

How would you use it, if we would realize an OpenAPI documentation?

**Comment by stefan-niedermann** [comment]
> Do you know if this is somewhere used in the Nextcloud context?

I am not aware of it being used in the Nextcloud context yet, but it would be an enhancement for sure.

> How would you use it, if we would realize an OpenAPI documentation?

It's just a theory so far, but ideally i could generate the models (What today is `CloudNote`) and the endpoints (What today is `NotesClient` respectively `NotesClientV1` / `NotesClientV02`).

The main benefit from my point of few is to get notified at build time when the API or the model has changed to avoid mistakes.

However i do not insist in any way to fulfill this issue and i am not sure how big the benefits are in the real world. But on the other hand: What do we have to lose? We can generate a fancy documentation and if we don't use it further, it is at least machine readable - if we find ways to utilize it for clients or server: the better! :smiley:

**Comment by korelstar** [comment]
> What do we have to lose?

Much of our free time ;-)

Besides this, the Open api specification has three disadvantages:

- According to the specification, you can only define endpoints with concrete server names. If you ommit the respective section, this means that the endpoint URL is relative to the API YAML file. => Technically, this is not correct for Nextcloud: it would be relative to github.com)
- The specification does not support API minor versions. We would have to specify the latest minor version and define all attributes that were introduced as optional. The actual minor version would be named textual in the description. This is not as clear to the reader as the current docs.
- For a human-readable documentation, this approach requires some code generation on every change of the YAML file. But where to place the result? It's HTML/CSS/JS, so it can't be shown from within the repository like the current documentation. I fear that we would have to use a new service for this (is GitHub pages sufficient?). This will produce some efforts. Maybe you or someone else have an idea on this?

**Comment by stefan-niedermann** [comment]
:man_shrugging: valid points

**Comment by korelstar** [comment]
Yes, but my intention was not to block this. Maybe at some time, some of us or someone else has time and motivation to realize a good solution. So let's keep it in our minds ...
