### ISSUE TITLE
question: is there a client for osx?

### ISSUE THREAD

**Issue by tessus** [nextcloud/notes#70]
Are you aware of a client on OSX to sync the notes?

**Comment by tessus** [comment]
The reason why I ask is the following: I'm currently using local text files which I sync with the nextcloud sync client. But this is rather messy. Especially, if you have many notes and want to search and organize them.
People I know use evernote, but I do not trust public cloud services, thus I do not use it. But evernote has fantastic features and I can see this app becoming a substitute for evernote.

**Comment by korelstar** [comment]
There is/was such an app, but it wasn't updated since a long time. I don't know, if it works or is useful (I don't use OS X): http://peterandlinda.com/cloudnotes/ (https://github.com/owncloud/notes-OSX-App)

**Comment by tessus** [comment]
Thanks for the info. I think I tried the app before and I had a few problems: no search, no images (only plain text), data was exclusively kept in the database.

**Comment by ank0m** [comment]
@tessus Yes there is a client for MacOS it's called QOwnNotes [http://www.qownnotes.org](url).

**Comment by tessus** [comment]
@ank0m thanks. this looks very nice. 

I just hope that the server app will support images in the future. Usually I don't need images in my notes, but sometimes a picture says more than a thousand words. I will open a feature request in a new issue.
