### ISSUE TITLE
Browser extension

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/notes#706]
Hi!

Are any kind of browser extension (Google Chrome and/or Firefox), which allow to save pieces of information to Notes? Like it is organised with Pocket or Google Keep? Additionally, this browser extension may show the links to current notes. Here is an example of Google Keep extension:
https://chrome.google.com/webstore/detail/google-keep-chrome-extens/lpcaedmchfhocbbapmcbpinfpgnhiddi?hl=en

**Comment by stefan-niedermann** [comment]
Unfortunately i am not aware of any. If someone finds one (or starts a project :rocket:) a note would be nice so we can add it to the [known 3rd-party clients](https://github.com/nextcloud/notes/wiki) of the wiki :slightly_smiling_face:

**Comment by danieljweinberg** [comment]
I was looking for the same thing, and I so far have settled on QOwnNotes ([github](https://github.com/pbek/QOwnNotes)), which is a desktop notes program that syncs with Nextcloud, and has a Web Clipper and Bookmarks extension. 

The extension only works if you're browsing on the same computer QOwnNotes is running on. Then on a website, you can select text, right-click, and save to QOwnNotes. There is a workaround to Clip on other desktops, but it involves some creative networking which I discussed with the creator [here](https://github.com/pbek/QOwnNotes/issues/2098). This solution doesn't work with mobile browsers, however.

**Comment by korelstar** [comment]
I'm closing this, since the question was answered and implementing a browser extension for the notes app is out of scope of this project. That would be a new project.
