### ISSUE TITLE
No support for nested * lists

### ISSUE THREAD

**Issue by benyanke** [nextcloud/notes#71]
Expected: 
* item 1
  * item 2

Displays as:

* item 1
* item 2

**Comment by g33kdad** [comment]
I am also experiencing this behaviour in Notes v 2.2.0

**Comment by Henni** [comment]
might be fixed now that #22 is merged. I'd love to hear feedback :)

**Comment by g33kdad** [comment]
I just installed it yesterday. Have you merged since then?

M

**Comment by Henni** [comment]
Just a few minutes ago and it isn't updated in the App store yet.

**Comment by g33kdad** [comment]
Cool. I'll keep looking for the update.

M

**Comment by adsworth** [comment]
This seems to work now, but only if you change list markers.
