### ISSUE TITLE
Set consistent tab size across editors

### ISSUE THREAD

**Issue by Baptistou** [nextcloud/notes#714]
**Is your feature request related to a problem? Please describe.**
Nextcloud editors have inconsistent behaviour regarding to tab character.
[Plain Text](https://apps.nextcloud.com/apps/files_texteditor) tab size is 4
[Rich Text](https://github.com/nextcloud/text) tab size is 8
[Notes](https://apps.nextcloud.com/apps/notes) tab size is 2

**Describe the solution you'd like**
Because text files can be edited in different ways, with Plain Text app, Rich Text app, Notes app, or on desktop with for example Notepad++. Most desktop editors, IDEs, and also [Codemirror have a default tab size of 4 spaces](https://codemirror.net/doc/manual.html#option_tabSize), which I think is used in Nextcloud?
Please consider to unify tab size across Nextcloud editors in order to have a consistent display of text files.

**Describe alternatives you've considered**
It is possible to change this behaviour on Rich Text app with [Custom CSS](https://apps.nextcloud.com/apps/theming_customcss). I didn't find any solution for Notes app.
```css
#viewer .editor__content { tab-size: 4; }
```

Related Issue : https://github.com/nextcloud/text/issues/1591

**Comment by korelstar** [comment]
I second this request. I will change the notes app's tab size to 4 in the next step, because I think that's the best common value. But I'm watching the ticket in the Text repository and if there will be an agreement to another value, I will adopt it here, too.
