### ISSUE TITLE
three dots menu not accessible when scrolling down

### ISSUE THREAD

**Issue by prokler** [nextcloud/notes#716]
When you write a note and you are not on top of the page anymore, then click the three dots menu, it will pop up north of the three dots and is therefore not accessible anymore. 

## Steps to reproduce

1. Write a note long enough to get a scrollbar.
2. Scroll down.
3. Click the three dots.

### Expected behaviour

The menu should pop up south of the three dots, so it's accessible.

### Actual behaviour

Menu pops up north of the three dots and is therefor not accessible because it's hidden under the main menu.

### Screenshots

![Bildschirmfoto zu 2021-05-18 03-31-23](https://user-images.githubusercontent.com/40594647/118546118-14f67c80-b78a-11eb-9dba-fd9372fe4ff8.png)

## Server

- Notes app version: 4.0.4
- Nextcloud version: 21.0.1
- OS: Ubuntu 20.04
- Web server: apache2
- PHP version: 7.4.3
- Database: mysql 10.3.29

## Client

- Browser (incl. version): Firefox 88.0.1 (64-Bit)
 - OS: Ubuntu mate 20.04

**Comment by korelstar** [comment]
This is an old bug of `nextcloud-vue` and `server`, see https://github.com/nextcloud/nextcloud-vue/issues/1384. I thought, we have fixed it :-/
