### ISSUE TITLE
On creating a new note I get Note is locked error

### ISSUE THREAD

**Issue by NielBuys** [nextcloud/notes#730]
I press on the "+ New note" button top left. Then a new note is created for me. As before I type the first line that I know would become the title of the file. Press enter to type the rest but then I get error "Updating title for note 888 has failed Note is locked" see screenshots. I also see errors in the console I took screenshots of that also. Not sure when it stopped working I always used it the same way.

## Steps to reproduce
1. Create new note.
2. Type in first line for title.
3. Type in rest of the lines. Stop typing for save to happen. Then error come up.
4. If I refresh my browser. Everything I typed is saved. The file name on left is just still New note. And no error messages.
5. I am able to rename the file on the left menu that works. And I can normally work without errors on existing files no errors. 

### Expected behaviour
Create note without error.

### Actual behaviour
See above fault scenario

### Screenshots
![Screenshot from 2021-06-24 21-34-25](https://user-images.githubusercontent.com/8427483/123323062-502c5e00-d535-11eb-85b6-3d1471638194.png)
![Screenshot from 2021-06-24 21-37-23](https://user-images.githubusercontent.com/8427483/123323073-528eb800-d535-11eb-80f1-686a0ef4bc70.png)

## Server
Please complete the following information.

- Notes app version: 4.0.4
- Nextcloud version: 21.0.2
- OS: Ubunut 20.04
- Web server: Apache
- PHP version: 7.4
- Database: Mysql 8.0.25

**Nextcloud configuration:**

<details>
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "buyshome.ddns.net",
            "bh.ncomp.co.za"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.2.1",
        "overwrite.cli.url": "https:\/\/bh.ncomp.co.za\/bcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "ZA",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "hsts",
            "twofactor_email",
            "twofactor_admin"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
```
</details>

## Client
Please complete the following information.

- Browser (incl. version): Chrome v91.0.4472 and also Firefox v89.0.1 (Firefox is my normal browser but screenshots is for Chrome. Chrome have less messages in console.)
 - OS: Ubuntu 20.04

## Log files
Add relevant parts of your `nextcloud.log` and/or your browser's JavaScript console here.
I took a screenshot of the console. I haven't researched how to get the logs if you need it can you give me the steps.

**Comment by korelstar** [comment]
Thanks for your report. Could you please have a look at your Nextcloud server log (`nextcloud.log`)? There should be detailed log entries for those errors. Please post this part of the log, here.

**Comment by NielBuys** [comment]
Here is log hope this is all the rest looks like background job stuff.
`{"reqId":"yIvX5Pcp3DcTLozIKDaW","level":3,"time":"2021-06-28T07:14:11+00:00","remoteAddr":"154.70.211.42","user":"nielbuys","app":"notes","method":"PUT","url":"/bcloud/index.php/apps/notes/notes/104138/autotitle","message":{"Exception":"OCP\\Lock\\LockedException","Message":"\"Notes/New note.md\" is locked","Code":0,"Trace":[{"file":"/var/www/html/bcloud/lib/private/Files/View.php","line":800,"function":"changeLock","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/html/bcloud/lib/private/Files/Node/Node.php","line":448,"function":"rename","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/html/bcloud/apps/notes/lib/Service/Note.php","line":152,"function":"move","class":"OC\\Files\\Node\\Node","type":"->"},{"file":"/var/www/html/bcloud/apps/notes/lib/Service/Note.php","line":128,"function":"setTitleCategory","class":"OCA\\Notes\\Service\\Note","type":"->"},{"file":"/var/www/html/bcloud/apps/notes/lib/Controller/NotesController.php","line":232,"function":"setTitle","class":"OCA\\Notes\\Service\\Note","type":"->"},{"file":"/var/www/html/bcloud/apps/notes/lib/Service/Util.php","line":28,"function":"OCA\\Notes\\Controller\\{closure}","class":"OCA\\Notes\\Controller\\NotesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/bcloud/apps/notes/lib/Controller/Helper.php","line":48,"function":"retryIfLocked","class":"OCA\\Notes\\Service\\Util","type":"::"},{"file":"/var/www/html/bcloud/apps/notes/lib/Controller/NotesController.php","line":235,"function":"handleErrorResponse","class":"OCA\\Notes\\Controller\\Helper","type":"->"},{"file":"/var/www/html/bcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"autotitle","class":"OCA\\Notes\\Controller\\NotesController","type":"->"},{"file":"/var/www/html/bcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/bcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/bcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/bcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/bcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/bcloud/lib/private/Files/View.php","Line":2008,"Previous":{"Exception":"OCP\\Lock\\LockedException","Message":"\"files/145c001e73902ff806a4b9924b77d3dc\" is locked","Code":0,"Trace":[{"file":"/var/www/html/bcloud/lib/private/Files/Storage/Common.php","line":816,"function":"changeLock","class":"OC\\Lock\\DBLockingProvider","type":"->"},{"file":"/var/www/html/bcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":614,"function":"changeLock","class":"OC\\Files\\Storage\\Common","type":"->"},{"file":"/var/www/html/bcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":614,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/var/www/html/bcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":614,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/var/www/html/bcloud/lib/private/Files/View.php","line":2002,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/var/www/html/bcloud/lib/private/Files/View.php","line":800,"function":"changeLock","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/html/bcloud/lib/private/Files/Node/Node.php","line":448,"function":"rename","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/html/bcloud/apps/notes/lib/Service/Note.php","line":152,"function":"move","class":"OC\\Files\\Node\\Node","type":"->"},{"file":"/var/www/html/bcloud/apps/notes/lib/Service/Note.php","line":128,"function":"setTitleCategory","class":"OCA\\Notes\\Service\\Note","type":"->"},{"file":"/var/www/html/bcloud/apps/notes/lib/Controller/NotesController.php","line":232,"function":"setTitle","class":"OCA\\Notes\\Service\\Note","type":"->"},{"file":"/var/www/html/bcloud/apps/notes/lib/Service/Util.php","line":28,"function":"OCA\\Notes\\Controller\\{closure}","class":"OCA\\Notes\\Controller\\NotesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/bcloud/apps/notes/lib/Controller/Helper.php","line":48,"function":"retryIfLocked","class":"OCA\\Notes\\Service\\Util","type":"::"},{"file":"/var/www/html/bcloud/apps/notes/lib/Controller/NotesController.php","line":235,"function":"handleErrorResponse","class":"OCA\\Notes\\Controller\\Helper","type":"->"},{"file":"/var/www/html/bcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"autotitle","class":"OCA\\Notes\\Controller\\NotesController","type":"->"},{"file":"/var/www/html/bcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/bcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/bcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/bcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/bcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/bcloud/lib/private/Lock/DBLockingProvider.php","Line":263},"CustomMessage":"Controller failed with OCP\\Lock\\LockedException"},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0","version":"21.0.2.1"}`

**Comment by korelstar** [comment]
This problem should not happen anymore in the new release v4.1.1. Please test :smiley:

**Comment by NielBuys** [comment]
Thanks I don't see the error anymore.
