### ISSUE TITLE
Widget doesn't display tabulations

### ISSUE THREAD

**Issue by fl0rianB** [nextcloud/notes#737]
The widget of the android app doesn't  display tabulations when using ballot box

## Steps to reproduce
1. Create a widget showing a single note
2. Copy/past this text in a new note
`# Test

- [ ] a 
    - [ ] aa
    - [ ] ab 
- [ ] b
    - [ ] ba
    - [ ] bb
        - [ ] bba

- a
    - aa
    - ab
- b
    - ba
    - bb
        - bba`
3. observe the result in the widget (https://acloud10.zaclys.com/index.php/s/aC8JrxCSiGSiKKW)

### Expected behaviour
The widget should display balot box with indentation, like buleted lists.

### Actual behaviour
The widget display balot box/task lists without indentation.

### Screenshots
https://acloud10.zaclys.com/index.php/s/aC8JrxCSiGSiKKW

## Server
Please complete the following information.

- Notes app version: 3.4.11

**Comment by stefan-niedermann** [comment]
Hey @fl0rianB 

this repository is for the Notes server app only.

For the Android app please use [this repository](https://github.com/stefan-niedermann/nextcloud-notes/issues) in the future.

I opened a new issue [here](https://github.com/stefan-niedermann/nextcloud-notes/issues/1294) for you. Thanks for the report 🙂.
