### ISSUE TITLE
Default view (EDIT/PREVIEW)

### ISSUE THREAD

**Issue by fredbcode** [nextcloud/notes#749]
**Is your feature request related to a problem? Please describe.**
In Nextcloud the default mode is edit, In almost part of my time I'm just using view, so I must click on preview to see the documents without the markdow entries 

**Describe the solution you'd like**
Add an option to switch the default mode to EDIT/PREVIEW

**Comment by stefan-niedermann** [comment]
Please use the :mag: **search function** before opening new issues.

Duplicate of https://github.com/nextcloud/notes/issues/352
