### ISSUE TITLE
E/S server error android client

### ISSUE THREAD

**Issue by adamsson6** [nextcloud/notes#75]
Hi, i just setup a new nextcloud server, and im' getting a problem with the note app.
When I add notes 1 by 1 it looks to be worling, but when i try to copy all my text notes in the folder (700 files), the nextcloud notes web interface shows empty folder, and the android app don't connect anymore, sending an error, in french : "Détails de connexion incorrects: URL/ Serveur a des erreurs".

May be it's due to a wrong filename or a bgi quantity of notes ?

Thank you for your help, and thank you for your job.

**Comment by korelstar** [comment]
> May be it's due to a wrong filename or a bgi quantity of notes ?

Please test this by going on stepwise. We would be happy to have some more data from you (e.g. filename or number of notes which breaks the app).

See also: stefan-niedermann/nextcloud-notes#125

**Comment by adamsson6** [comment]
Hi ! I ve made some more advanced tests, syncing modification after modification.
It's not a question of number of notes.

And i found that it was in the content of some files, i don't know why, nor which characters create the problem, but it's it.

For example : file addressnumber2.txt contains " word1, word2, blabla..."
I removed step by step "word1" and syncing "word2" and syncing, etc, , and i found that some "random" parts of the text create the bug, and the web client and android client notes don't sync with the server anymore.
If I remove the file which make problem, the sync works again.
It does not depend on the lenght of the text because the error happened with one long text and one very short.

May be it's a problem of encoding, some of the text files are very old and i can't remember with which editor i created them.
I tried one thing : copy the content of the problematic text file to a new one, and save it. And the sync works !!

So i compared the 2 files in an hexa editor, and i found that the encoding was different, and some weird characters were present in problematic files, like (in hexa) 0D 0A 0D 0A                                                 ....

I think the problem come from here ! so now i'm gonna clean my notes but I don't understand why Qownnotes is able to read these weird notes and not Nextcloud note app...

I hope these information could help ! Thank you !


I hope this can help.

**Comment by adamsson6** [comment]
UPDATE : Cleaning notes finished. I had only 2 files which were causing the crash, i rewrited them in a new file and it's ok. 
Now the app is working with android, web interface, and qownnotes on linux. Thank you !

**Comment by korelstar** [comment]
Thanks for the detailed analysis of this issue. Good, that you were able to fix it for you.

Just for the protocol: I think it's the same issue like in #73.

**Comment by gringo1er** [comment]
Hello
I have that king of error, with a nextcloud server installed on Ubuntu 17.04, apache, php7 and mysql server.

SSL certificates are officials, and not "let's encrypt" version (provided by our domain name provider and certified by Comodo)

When I use the clone nextcloud installed on a synology nas, I don't have that kind of trouble.

The real message is, in french, "Détail de connexion incorrect erreur d'E/S"
