### ISSUE TITLE
Adding timestamp inside a note / templating a note

### ISSUE THREAD

**Issue by AlfredEVOL** [nextcloud/notes#752]
it would be great if the notes had a header with the timestamp.
i use one on my pc with the header being "_$(date +"%Y-%b-%d-%R")_"

Or it would also be good if there were templates(user defined) for notes , tho things like date might require some work

**Comment by korelstar** [comment]
I don't get exactly what do you mean. Which header do you reference to? Should this be physically in the notes file or should this be just shown in the web frontend? Which date do you mean?

**Comment by AlfredEVOL** [comment]
i currently make a notes with the script
the first line is a timestamp of when it was created , i.e `$(date +"%Y-%b-%d-%R"`

also , i have some notes which i copy from a template .
So yes , like the date would bein the notes.txt file / or i guess it would be easier to use user-defined templates the user can choose from when creating a new note

**Comment by AlfredEVOL** [comment]
_2021-Aug-25-18:31_
***
An example note from a template i use

**Comment by korelstar** [comment]
Sorry, but templates are out of scope of this simple "distraction-free" notes app. Everybody who wants to add a date into the note can just write it down there.
