### ISSUE TITLE
Notes Version 4.11 does not show up in Browser

### ISSUE THREAD

**Issue by minibootsmann** [nextcloud/notes#756]
Please make a clear and concise description of what the bug is. Please note, that issues with the Android app have to be reported under https://github.com/stefan-niedermann/nextcloud-notes/issues and issues with Nextcloud's Text app have to be reported under https://github.com/nextcloud/text/issues .

## Steps to reproduce
1. Open Nextcloud page in Browser
2. Log in
3. Open Notes app

### Expected behaviour
Stored Notes should appear

### Actual behaviour
Notes App throws an error : "Fehler | true | Für Details siehe Protokolldatei des Nextcloud-Servers."
Translated: "Error | true | For Details look at the protocol file of the nextcloud server."

Another message pops up: "Laden der Notizen fehlgeschlagen. Siehe JavaScript-Konsole und Server-Protokoll für Details."
Translated: "Loading of notes failed. Look at JavaScript-Console and server-protocol for Details."

## Server
Please complete the following information.

- Notes app version: 4.11
- Nextcloud version: 21.0.4
- OS: Debian Buster
- Web server: Apache 2
- PHP version: 7.4
- Database: MariaDB

**Nextcloud configuration:**

<details>
{
    "system": {
        "debug": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "familie-robben.de",
            "wolke9.familie-robben.de",
            "45.85.216.54",
            "wolke9.fritz.box"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.4.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "logtimezone": "UTC",
        "log_type": "file",
        "loglevel": 0,
        "logdateformat": "F d, Y H:i:s",
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "appstore.experimental.enabled": true,
        "filelocking.enabled": true,
        "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
        "overwrite.cli.url": "https:\/\/wolke9.fritz.box",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mysql.utf8mb4": true,
        "app_install_overwrite": [
            "calendar"
        ],
        "mail_sendmailmode": "smtp",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "DE"
    }
}
</details>

## Client
Please complete the following information.

- Browser (incl. version):  Vivaldi 4.1.2369.21 (Stable channel) stable (64-Bit)
 - OS: SuSE Linux Leap 15.3

## Log files
Extract from javascript console:

```
(anonymous) @ notes-main.js:1
notes-main.js:1 TypeError: e is not iterable
    at updateNotes (notes-main.js:1)
    at Array.<anonymous> (main.js:12)
    at u.dispatch (main.js:12)
    at u.dispatch (main.js:12)
    at notes-main.js:1
```

**Comment by korelstar** [comment]
Please check the Nextcloud server's log file (nextcloud.log) for errors from the notes app. There should be more information on why loading the notes has failed.

**Comment by minibootsmann** [comment]
Strange,

as I tried to reproduce the issue again today, everything was fine again. No Java error, notes are shown as expected. 

So I will close this issue, thanks to all for reading this!
