### ISSUE TITLE
Implement emoji picker

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/notes#763]
**Is your feature request related to a problem? Please describe.**
It is not easy to enter emojis. I currently rely on emoji picker browser extensions.

**Describe the solution you'd like**
Similar to `xed` / `gedit` it would be great if <kbd>Ctrl</kbd> + <kbd>.</kbd> could open an emoji picker, maybe with a little search field.

**Describe alternatives you've considered**
A dedicated button, maybe next to the three dots menu. I didn't like the idea because it is visual noise which can be avoided.

**Additional context**
![grafik](https://user-images.githubusercontent.com/4741199/137578522-4c804c6c-33a6-40b8-9a9c-a42f97951ae8.png)

**Comment by JonnyTischbein** [comment]
Can this be considered as solved, because the richtext editor provides this function ?

![Screenshot from 2023-03-25 10-15-01](https://user-images.githubusercontent.com/10757520/227708453-4a22a380-7365-456a-978f-ef78fd401e3f.png)
