### ISSUE TITLE
Allow option to hide/reveal checked items in a list

### ISSUE THREAD

**Issue by gadgetguy08** [nextcloud/notes#765]
**Is your feature request related to a problem? Please describe.**
Unrelated to problem.

**Describe the solution you'd like**
Have the ability to hide (and re-reveal) checked items from a checklist. For example, you may have a shopping list which you check off items as you get them (or don't need). It would be helpful to have those hidden by option, so you can just see what is needed. Similarly with a list of tasks to hide when individual tasks are complete.

**Describe alternatives you've considered**
Checked items are grayed out and struck through, but remain as clutter in large lists.

**Additional context**

**Comment by korelstar** [comment]
Sorry, but I won't implement this. The focus of this app is taking notes and not managing lists. I see the motivation of this, but I think this should be realized in a separate Nextcloud List app.

**Comment by stefan-niedermann** [comment]
Let me propose the [Deck](https://apps.nextcloud.com/apps/deck) and [Tasks](https://apps.nextcloud.com/apps/tasks) apps for advanced task management.
