### ISSUE TITLE
Two simple suggestions to implement

### ISSUE THREAD

**Issue by talesam** [nextcloud/notes#770]
I use Notes a lot every day and noticed a lack of two features that I think are simple to implement. One of them is to create subfolders to store the notes, so far it is only possible to create a main folder to "store" the notes.

The second feature is the option to share with a user from the Nextcloud server itself and create a public share link for sharing with

**Comment by stefan-niedermann** [comment]
> One of them is to create subfolders to store the notes, so far it is only possible to create a main folder to "store" the notes.

Just use `/` to generate subfolders like `main/sub`, the Notes app will automatically recognize it and create subfolders. Of course contributions for a better UX are welcome, mäybe you have some concrete ideas and want to start a Pull Reauest?

> share with a user from the Nextcloud server itself and create a public share link for sharing with

Duplicatw of https://github.com/nextcloud/notes/issues/38 - as a workaround just share the note (or category) from the files app.
