### ISSUE TITLE
Let the user choose the Nextcloud Files root folder to memorize notes

### ISSUE THREAD

**Issue by SamuXzX** [nextcloud/notes#771]
## Is your feature request related to a problem?
I make extensive use of .md files to store informations across my Nextcloud instance, not only in the Notes folder, which lets me use the Nextcloud Notes interface to read them. I ususally manage them with my desktop text editor and file manager, having the files synced with my laptop, but if I was to access Nextcloud from the browser I'd obliged to navigate between the files with the Files app and modify them with the Nextcloud Text app.

Addittionally, having categorized my files in different scopes and needing some notes regarding these scopes, the folder structure of Files and the category structure of Notes becomes redundant, unless I put every folder I use for my scope into the Notes folder. At the moment, I find my files well divided in folders but their relative notes are in a completely differente folder with its own redundant structure, so that I must navigate between two folders or Nextcloud Apps at the same moment.

## Describe the solution you'd like
I find that being able to use the Notes app interface, which is much simpler than the Files app one, could be a great way to manage those .md files.
This would also filter out all the files that aren't .md files, so diminishing the noise for someone who works with these .md files like me. Given that the Notes app doesn't show the empty folders (or those folders which doesn't contain .md files), even having lots of folders in the Files app should not be a problem.

This would solve my second problem, as I could use the Files structure as the Notes' app category structure and finding my notes from the Notes app also in the right folder in the Files app. In this way I could read my notes even when I'm simply navigating the files in my folders. 

## Describe alternatives you've considered
A possible alternative is putting every file in the Notes folder, but this is obviously uncomfortable.

Another possibility is this issue: [ Allow to include multiple folders from separate locations #670 ](https://github.com/nextcloud/notes/issues/670). We could select the folders where we store the .md files and the Notes app would show them to us.

**Comment by korelstar** [comment]
Did you try to set the notes path to the root folder `/` ? This should fix your problem, since the notes app then uses all notes files from every folder.

**Comment by SamuXzX** [comment]
I tried with "/", but it fell back to the previous setting (Notes). I'll try again today

**Comment by Discostu36** [comment]
> I tried with "/", but it fell back to the previous setting ("Notes"). I'll try again today

I tried it today and it didn't work. I would also like this feature for the reasons that you have stated. It does not make sense for my workflow to have notes and files in separate folder structures because the notes are often in relation to the files.

Nextcloud 21.0.7
Nextcloud Notes 4.2.0
