### ISSUE TITLE
text with Colors 

### ISSUE THREAD

**Issue by Cellophile** [nextcloud/notes#777]
Hello, 
I know that markdown isn't done to offer entire possibilities like html.
But I think that permit to put some colorations to the texts will be great : I've installed Nextcloud for an association with many people with mental disabilities, and colors will help them a lot.

Is it possible to imagine some codes to propose that ?
something like that : 
- This is *red*{: style='color: red'}. 
- This is [red]red[/red].
- This is _r_red_r_. 
...

We can see on the web that many installations with markdown editors let us use colors attributions with css, but in nextcloud, impossible. It may be a future upgrade ?

Best regards,

**Comment by stefan-niedermann** [comment]
The Notes app aims to support the [`commonmark` language specification](https://spec.commonmark.org/current/).

The spec does not contain any of the suggested markers, i therefore recommend to not add any of the mentioned proprietary markers.

The possibility of colored text is indirectly mentioned in example [`172`](https://spec.commonmark.org/0.30/#example-172) and [`176`](https://spec.commonmark.org/0.30/#example-176) of version `0.30` (= latest at time writing) of the specification by using a HTML `style` tag with CSS instructions. While the sample implementation does color the text as expected, i wasn't able to find a requirement in the specification that the CSS instructions *must* be applied to the markdown document when rendered.

Current behavior:

| Implenentation | Edit | Preview |
| --- | --- | --- |
| Notes Server | Syntax highlighting for the `style` tag, not processed | `style` is displayed as normal text, not processed |
| Notes Android | `style` tag is displayed with different text color, not processed | `style` tag is invisible, not processed |
| `commonmark` samples | `style` tag is displayed as normal text, not processed | `style` tag is invisible, instructions are processed and applied |

My personal opinion: Styling with HTML tags is ridiculous complex and on a very high level (examples are only available tag wise, so no possibility to just color a single word?). I strongly disagree with implementing non standardized features, though and will not do so in the Notes Android app.

**Comment by korelstar** [comment]
I agree with @stefan-niedermann . We don't want to introduce propietary markup. Although markdown/commonmark is limited in it's expression abilities, it is sufficient for the main goal of this app: distraction-free notes taking. It's not a full word processing software.
