### ISSUE TITLE
DB constraint violations since update to 4.2.0

### ISSUE THREAD

**Issue by noplanman** [nextcloud/notes#778]
## Steps to reproduce
1. Update Nextcloud Notes to 4.2.0
2. Try to sync with Nextcloud Notes Android app
3. See flooding of the logs with warning mentioned below (1 error for every note, total 1600+)

### Expected behaviour
Seamless update with no warnings written to log.

### Actual behaviour
Sync with the Android app seemed to get stuck and NC logs were filling up with warnings.

## Server
Using Docker image, version 22.2.0

- Notes app version: 4.2.0
- Nextcloud version: 22.2.0
- Host OS: Debian Buster
- Web server: Apache
- PHP version: 8.0.11
- Database: MariaDB 10.6

**Nextcloud configuration:**

<details>
```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "top.secret"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/top.secret\/",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "22.2.0.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "updater.release.channel": "stable",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "mysql.utf8mb4": true,
        "mail_sendmailmode": "smtp",
        "app_install_overwrite_": [
            "calendar",
            "keeweb",
            "spreed",
            "social",
            "spreedme",
            "twofactor_gateway",
            "twofactor_totp"
        ],
        "trashbin_retention_obligation": "auto, D",
        "encryption.key_storage_migrated": false,
        "app_install_overwrite": [
            "twofactor_gateway"
        ],
        "default_phone_region": "CH"
    }
}
```
</details>

## Client
[Nextcloud Notes](https://github.com/stefan-niedermann/nextcloud-notes) app for Android

## Log files
`OC\DB\Exceptions\DbalException: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '12652-noplanman' for key 'notes_meta_file_user_index'`

**Comment by korelstar** [comment]
What do you mean by "flooding"? Can you quantify this? Please tell me more about you clients (Android, web, ...) and please use the issue template!

**Comment by noplanman** [comment]
Hi @korelstar, so sorry for not using the issue template, my mobile client didn't load it so I didn't know there was one.
Have updated it now!

By "flooding" i meant that it gave me that error for every note i have (1600+).

I use the "[Nextcloud Notes](https://github.com/stefan-niedermann/nextcloud-notes)" app for Android, so it may have been that app causing it. There was also a seemingly endless loading screen after the update to 4.2.0 of the Notes package.

It seems to have normalised now, so may have been a temporary thing. Still not sure what has caused it though, but all working well again now and sync is up to date and flowy.

Feel free to close off if this is a one-off and nobody else has had this.

**Comment by korelstar** [comment]
Okay, thanks for you feedback. I will think about on how we can improve this. But just to be clear to all people who see this log entry: it's not an error, but it's just an information.

**Comment by korelstar** [comment]
In #835, I finally improve the logging for this scenario. With the next release, there will be two grouping warnings in the log: "Database failed inserting Meta objects for *x* times." and "Database failed inserting Meta objects for all *x* notes. If this happens consistently, there is a problem with your database.". If you see the latter in your log, we should dig into this.
