### ISSUE TITLE
Unable to delete notes

### ISSUE THREAD

**Issue by JonathanCrouse** [nextcloud/notes#78]
I am on NextCloud 11.0.2 after migrating from OwnCloud.  I am able to create new notes and edit existing notes but the delete button on the site does not do anything.  If I attempt to delete using the app on my phone, the note will reappear after I refresh the app screen.  I can manually delete them from the Notes folder in files.  Thanks.

**Comment by Perfect-Solutions-Web-Services** [comment]
That's a heck of a workaround. If you install QOwnNotes on your Gnu-Linux box you can delete, rename and create new notes, and the deleted ones wont magically re-appear. I assume it would work on Windows and Mac too.

**Comment by Henni** [comment]
I can't reproduce this and need a bit more information.
Do you see anything inside your logfiles or the browser console?

**Comment by JonathanCrouse** [comment]
Logged in today to pull some logs but it now appears to be deleting fine.   I successfully deleted a note, from my phone, that was previously created.  I then created a new note and deleted it from the browser and viceversa.  Perhaps networking issues the day of the problem?  I think this can be marked as closed though.
