### ISSUE TITLE
Widget font-weight and text-shadow

### ISSUE THREAD

**Issue by SamuXzX** [nextcloud/notes#780]
**Is your feature request related to a problem? Please describe.**
As you can see in the screencast below, the tasks' widget (the second one) is a lot less visible than other widgets (for example the first one) when I entirely remove the background.

**Describe the solution you'd like**
Apart from increasing the background opacity, which entirely makes the personalization options useless, you could add an option to make the text bolder (at the moment we can only make it proportionally bigger) and to add a shadow, so that it's more visible without background.

**Describe alternatives you've considered**
I'm sorry, I don't have any. Do you?

**Additional context**
![screen-20211115-091535](https://user-images.githubusercontent.com/30182251/141749182-894a488d-eccd-414c-84e4-eecc1a9f4b1f.gif)

**Comment by stefan-niedermann** [comment]
Wrong repository buddy.
1. This is the Notes Server repository
2. The Notes Android app repository is [here](https://github.com/stefan-niedermann/nextcloud-notes/)
3. I (as developer of the Notes Android app) have never seen this "tasks" widget you are talking about. It is for sure not from the Notes Android app, so i guess you are completely wrong here....

**Comment by SamuXzX** [comment]
I completely missed the right repository, I was talking about another app... I'm sorry.
