### ISSUE TITLE
Configure Categories & Ordering

### ISSUE THREAD

**Issue by ulph0** [nextcloud/notes#783]
Ok, will start this as suggested :) I'm always frustrated when ... i open Notes online and the left column shows my notes ordered by Time they are created. That's completely useless for me, since i am not using my notes as a diary.

I would like to
- have the opportunity to order "all notes" alphabetically
- have the opportunity to configure the "start view" for the left column so that it either starts with alphabetically or 
  chronologically ordered notes, or with a view which shows all categories and a link to show the uncategorized notes, 
  in a folded or unfolded view, as the user likes it.

Nothing to add besides that i am also very interested in an advanced notes app like obsidian. Would be great if Notes could face into that direction ...

**Comment by tuxick** [comment]
There's the (paid) Android App "Nextcloud Notes" i considered worth the money

**Comment by korelstar** [comment]
I agree that the current navigation is not the best. There are already plans to improve this: please see #413 (especially https://github.com/nextcloud/notes/issues/413#issuecomment-569600608 for how it could look like) and #613 for an existing issue regarding ordering. Since we have already enough issues about these topics, I will close this new one. But this does not mean, we don't want to implement it.

**Comment by ulph0** [comment]
> There's the (paid) Android App "Nextcloud Notes" i considered worth the money

I don't really see the point of this comment. A bit off-topic, isn't it? OK if you want off-topic: I am using and loving that app and Notes itself for several years now. But maybe that time is over. Meanwhile NC has its own simple but great Markdown Editor so that you even can use the normal Nextcloud app as a Note Editor. And that notes are sharable as editable files with links and anything, nearly tlike an etherpad. On the other Hand there are advanced Note-Apps like obsidian. I will be happy if notes would catch up a bit.
