### ISSUE TITLE
Markdown formating not working in Notes - 

### ISSUE THREAD

**Issue by wgregori** [nextcloud/notes#79]
I'm running Nextcloud 11.0.2.  I have enabled Markdown and Notes, however, there is no difference with in my Notes window regardless whether Markdown is enabled or not.  Does Notes make use of the Markdown plugin?  .

Running on Ubuntu 16.04 with Nginx.
Wayne

**Comment by wgregori** [comment]
Problem solved!  My misunderstanding about the Markdown app... The Markdown app works with the Text Editor app and has nothing to do with the Notes app. (or so it appears).
Thanks,
Wayne

**Comment by korelstar** [comment]
Yes, this app is independent from other editor apps. You run other editors by opening a respective file in the files app. This app provides a special interface which shows only the notes and brings its own editor.
