### ISSUE TITLE
have an automatic backup

### ISSUE THREAD

**Issue by NESC1US** [nextcloud/notes#794]
**Is your feature request related to a problem? Please describe.**
i used notes for something important, but its too easy to delete everything (just by hitting ctrl+z on just opened existing note) i would really appreciate some backup mechanism which would actually allow to undo recent changes..

**Describe the solution you'd like**
maybe create a copy of the file when opening existing note?

**Describe alternatives you've considered**
i made an automatic backup script

**Comment by korelstar** [comment]
Notes are stored as files in your Nextcloud server. By default, Nextcloud already saves old versions of files. You can go to the files app and restore an older version of your note's file. Beside that, making backups is mandatory and should be done centrally for the whole Nextcloud installation, not just for the notes app. Therefore, I don't think that there should be a separate backup mechanism for the notes app.

Regarding the CTRL+Z issue, this is already documented (but unfortunately not yet fixed) in #308.
