### ISSUE TITLE
Checkboxes not formatted correctly

### ISSUE THREAD

**Issue by gwfHegel** [nextcloud/notes#797]
Checkboxes are not properly formated in edit and preview mode. This is only happening in the web version, the notes app works as expected. 

## Steps to reproduce
1. Add new note.
2. Type "- [ ] Item" or "- [x] Item" in edit mode. 
3. Switch to preview mode.

### Expected behaviour
Edit mode should just show "- [ ]" unformatted.
In preview mode "- [ ]" should be shown as a checkbox. 

### Actual behaviour
In edit mode only the brackets "[ ]" are formatted as a checkbox, while the dash "-" is still there (unformatted). 
In preview mode it's the other way around. "-" is formated as bullet item while "[ ]" is shown as unformatted. 

### Screenshots
The first Screenshot is showing edit mode while the second one is preview mode. 

Edit mode
![NC Notes Bug1](https://user-images.githubusercontent.com/81383391/147291808-1dbaaa70-911f-4a32-bce2-74458b8a94da.jpg)

Preview mode
![NC Notes Bug2](https://user-images.githubusercontent.com/81383391/147290940-22463a9b-7a28-49a5-a522-dc3c78ee04f8.jpg)

## Server
I am using Hetzner's storage share solution. 

- Notes app version: 4.2.0
- Nextcloud version: 22.2.3
- OS: Linux 5.4.0-80-generic x86_64
- Web server: ?
- PHP version: 7.4.25
- Database: mysql 10.3.32

## Client

- Browser (incl. version): Firefox 95.0.2
 - OS: Windows 10 21H2/ Windows 11

**Comment by stefan-niedermann** [comment]
Will be fixed in `4.3.0`: https://github.com/nextcloud/notes/issues/325
