### ISSUE TITLE
Inconsistent handling of newline between web browser version of notes and android app

### ISSUE THREAD

**Issue by Szwendacz99** [nextcloud/notes#801]
I was not sure if this is a bug for web app or for android app, or even if this is bug at all, so I decided to make issue here.

 
## Steps to reproduce
1. write two lines containting multiple words in new note using newline character (enter) as line separator
2. save it in web browser app and switch to preview mode to see they are **not** split in two lines
3. open the same note in preview mode in android app and see that there are two lines

### Expected behaviour
Both apps should show the same markdown formatting.

### Actual behaviour
Newline formatting handling differ. 

## Server
Please complete the following information.

- Notes app version: 4.3.0
- Android app version: 3.4.18
- Nextcloud version: 22.2.3

## Client
Please complete the following information.

- Browser (incl. version): Vivaldi 5.0.2497.35 (Stable channel) stable (64-bit)
 - OS: Linux

**Comment by stefan-niedermann** [comment]
The Notes server (and Android app) aim to be compatible to the [commonmark](https://commonmark.org/) language standard.

The Notes **server app** has the **correct** behaviour in terms of the specification to *not* break the lines, but only break them if there is either a blank line between them *or* two <kbd>Space</kbd> characters *or* a <kbd>\\</kbd> at the end of the first line[¹](https://spec.commonmark.org/0.30/#hard-line-break).

However this feels not natural and is hard to explain to new markdown users. The Notes Android app therefore decided explicitly to deviate at this (and only this) point from the standard and breaks the line implicitly (even if there are not two <kbd>Space</kbd> characters at the end of a line).

I do not plan to revert those changes of the Notes Android app, but I agree that the handling should be consistent. I therefore would like to invite @korelstar to change the Notes server app at this point. :slightly_smiling_face:

**Comment by korelstar** [comment]
Looks like `markdown-it` (the package we use for the preview) has the option `breaks` which does this. I will think again about this.
