### ISSUE TITLE
Error with position of "add/edit link - file" button on selected text when note is scrolled down

### ISSUE THREAD

**Issue by ImaCrea** [nextcloud/notes#804]
## Steps to reproduce
1. scroll down in your note
2. select some text

### Expected behaviour
I should be able to see the contextual button "add link / file"

### Actual behaviour
I can't see it, unless I scroll back up which is not usable. (many users here think the feature is just gone. it's only eventually by chance that one can't notice it can be found upper)

### Screenshots

https://user-images.githubusercontent.com/764332/149632336-e600eb6b-e4c5-465c-b4c9-7dfeb60567e1.mov

## Server
Please complete the following information.

- Notes app version: 4.2
- Nextcloud version: 21.0.7

## Client
Please complete the following information.

- Browser (incl. version):  Firefox 96
 - OS: MacOS Mojave

**Comment by korelstar** [comment]
The Notes app does not have such a button. That's the Nextcloud Text app you're talking about. Please have a look at the Text app GitHub repository.

**Comment by ImaCrea** [comment]
> The Notes app does not have such a button. That's the Nextcloud Text app you're talking about. Please have a look at the Text app GitHub repository.

Sorry for the mismatch!
