### ISSUE TITLE
Unable to save note

### ISSUE THREAD

**Issue by droidus** [nextcloud/notes#805]
## Steps to reproduce
1. Modify an existing note

### Expected behaviour
Note should automatically save

### Actual behaviour
Saving note 409 has failed. HTTP 500 (OCP\Files\GenericFileException)

## Server
Please complete the following information.

- Notes app version: 4.3.0
- Nextcloud version: 22.2.3
- OS: Ubuntu 20.04
running as a snap.

## Client
Please complete the following information.

- Browser (incl. version): 
 - OS: Firefox 96.0

**Comment by korelstar** [comment]
Please have a look at the server logs and search for relevant entries. There should be some information on this Exception.

**Comment by droidus** [comment]
`{"reqId":"R717Qqnt0WSb3YVOkTCH","level":3,"time":"2022-01-20T17:00:01+00:00","remoteAddr":"<ip>","user":"<username>","app":"PHP","method":"PUT","url":"/index.php/apps/notes/notes/408","message":"file_put_contents(/var/snap/nextcloud/common/nextcloud/data/<username>/files/Notes/links.txt): Failed to open stream: Permission denied at /snap/nextcloud/28713/htdocs/lib/private/Files/Storage/Local.php#282","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0","version":"22.2.3.0","exception":{"Exception":"Error","Message":"file_put_contents(/var/snap/nextcloud/common/nextcloud/data/<username>/files/Notes/links.txt): Failed to open stream: Permission denied at /snap/nextcloud/28713/htdocs/lib/private/Files/Storage/Local.php#282","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/snap/nextcloud/28713/htdocs/lib/private/Files/Storage/Local.php","line":282,"function":"file_put_contents"},{"file":"/snap/nextcloud/28713/htdocs/lib/private/Files/Storage/Wrapper/Wrapper.php","line":258,"function":"file_put_contents","class":"OC\\Files\\Storage\\Local","type":"->"},{"file":"/snap/nextcloud/28713/htdocs/lib/private/Files/View.php","line":1169,"function":"file_put_contents","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/snap/nextcloud/28713/htdocs/lib/private/Files/View.php","line":706,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/snap/nextcloud/28713/htdocs/lib/private/Files/Node/File.php","line":71,"function":"file_put_contents","class":"OC\\Files\\View","type":"->"},{"file":"/var/snap/nextcloud/28713/nextcloud/extra-apps/notes/lib/Service/Note.php","line":171,"function":"putContent","class":"OC\\Files\\Node\\File","type":"->"},{"file":"/var/snap/nextcloud/28713/nextcloud/extra-apps/notes/lib/Controller/NotesController.php","line":226,"function":"setContent","class":"OCA\\Notes\\Service\\Note","type":"->"},{"file":"/var/snap/nextcloud/28713/nextcloud/extra-apps/notes/lib/Service/Util.php","line":28,"function":"OCA\\Notes\\Controller\\{closure}","class":"OCA\\Notes\\Controller\\NotesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/snap/nextcloud/28713/nextcloud/extra-apps/notes/lib/Controller/Helper.php","line":145,"function":"retryIfLocked","class":"OCA\\Notes\\Service\\Util","type":"::"},{"file":"/var/snap/nextcloud/28713/nextcloud/extra-apps/notes/lib/Controller/NotesController.php","line":228,"function":"handleErrorResponse","class":"OCA\\Notes\\Controller\\Helper","type":"->"},{"file":"/snap/nextcloud/28713/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"update","class":"OCA\\Notes\\Controller\\NotesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/28713/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/snap/nextcloud/28713/htdocs/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/snap/nextcloud/28713/htdocs/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/snap/nextcloud/28713/htdocs/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/snap/nextcloud/28713/htdocs/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/snap/nextcloud/28713/htdocs/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
`

**Comment by korelstar** [comment]
The important one is this: `file_put_contents(/var/snap/nextcloud/common/nextcloud/data/<username>/files/Notes/links.txt): Failed to open stream: Permission denied`. Please check the file's permissions in the filesystem. Looks like your webserver does not have the permission to open that file. Maybe, there is a malconfiguration of your server?
