### ISSUE TITLE
External API for custom file extensions

### ISSUE THREAD

**Issue by korelstar** [nextcloud/notes#818]
#795 has introduced the possibility to define custom file extensions for note's files. Internally, the setting `fileSuffix` is set to `custom` and the new setting `customSuffix` is set to the custom file suffix (e.g. `.org` or `.markdown`). This change also affects the external API for third-party apps. We can chose between two alternative ways for changing this API.

@nextcloud/notes @stefan-niedermann : which one do you prefer as a third-party app developer?

### Alternative 1: pass-through
The settings endpoint of the external API will reflect these changes directly, i.e. a new setting `customSuffix` will be introduced and the existing setting `fileSuffix` can have the new value `custom`.

### Alternative 2: encapsulate
The settings endpoint of the external API will still have the settings `notesPath` and `fileSuffix` - no new setting `customSuffix`. Instead, the existing setting `fileSuffix` can have arbitrary values (i.e., besides `.txt` and `.md` it can have e.g. `.org` or `.markdown`).

**Comment by stefan-niedermann** [comment]
Personally i'd prefer alternative two. I'll have to make some adjustments on my side though, as currently a user can only choose from a list of predefined values yet.
