### ISSUE TITLE
Notes not updated in nextcloud app store

### ISSUE THREAD

**Issue by pschopen** [nextcloud/notes#822]
I just wanted to install nextcloud notes on my nextcloud 23 via the nextcloud app store. However, the latest version there was for nextcloud 21. Can one update the version that's available there?

**Comment by korelstar** [comment]
Please provide more information about the problem and your environment (please use the issue template!). The latest notes app version is 4.3.0 and that version is published for all current Nextcloud server versions (20-23). See [Nextcloud app store](https://apps.nextcloud.com/apps/notes):

![Screenshot App Store](https://user-images.githubusercontent.com/6277619/154834627-0b7d65ad-cbd8-4640-83df-4bc869c51b95.png)

**Comment by pschopen** [comment]
<img width="455" alt="grafik" src="https://user-images.githubusercontent.com/65334274/154837745-37875460-bb8d-488e-83b6-8ef6a870f2b0.png">
Details

<img width="455" alt="grafik" src="https://user-images.githubusercontent.com/65334274/154837748-288997d4-157f-49c8-86ae-a81b6ef7d4b0.png">
Changelog

Inside my nextcloud installation version 4.3.0 is not available; running nextcloud 23

**Comment by korelstar** [comment]
Again: please use the issue template and provide more information about your installation! We need this information in order to help!

Additional questions: are you able to update other apps? Please have a look at https://apps.nextcloud.com/ for current versions of other apps.

**Comment by pschopen** [comment]
## Steps to reproduce
1. Go to Apps
2. Search for Notes
3. Click on Notes

### Expected behaviour
Nextcloud should offer Version 4.3.0 to download

### Actual behaviour
Nextcloud offers Version 3.5.1

### Screenshots
See above

## Server

- Notes app version: None 
- Nextcloud version: 23
- Database: Maria DB

**Nextcloud configuration:**

## Client
Please complete the following information.

- Browser (incl. version): Firefox 97.0.1 (64-Bit)
- OS: Mac OS Monterey 12.1

**Comment by korelstar** [comment]
Which PHP version do you use? Which operating system and web server?

**Comment by pschopen** [comment]
Linux 5.16.9-arch1-1 x86_64

PHP 8.1.3

**Comment by korelstar** [comment]
Ah, okay. PHP 8.1 isn't supported yet. Neither by Nextcloud server 23, nor by the current notes app version. It will be supported in the next release.
