### ISSUE TITLE
where are the actual files?

### ISSUE THREAD

**Issue by patrikx3** [nextcloud/notes#83]
Hi!

How are you?

Just a simple question. Where can I find the actual md files? Like for backup it? Or export?
Thanks so much!

**Comment by MariusBluem** [comment]
> How are you?

Nice that you ask 🙈 We are currently preparing the upcoming Nextcloud 12.0 release, which will include a lot of new features and optimizations 💪 That said, I think we are fine 😅☀️ 

> Just a simple question. Where can I find the actual md files? Like for backup it? Or export?

The notes are stored as `.txt` in the **Notes** folder of your Nextcloud 😅 Its that simple 😉
