### ISSUE TITLE
Notes files not showing in iOS Files app if in a category

### ISSUE THREAD

**Issue by kevindurb** [nextcloud/notes#836]
Ive just started using the notes app and the official nextcloud ios app has an integration with the iOS Files app to show your nextcloud files. Im wanting to use an app called "pretext" to exit my notes on my iPhone but ive noticed that if the note is in a category I can see the category as a sub directory of my notes directory in the iOS Files app but the category directory looks empty. If i use the nextcloud app or web interface i can see all my notes in the category sub directory.

## Steps to reproduce
1. have the iOS nextcloud app installed with the advanced setting "Disabled Files App integration" set to its default of "off"
2. create a note in a category from the nextcloud web interface
3. open the iOS Files app and navigate to "nextcloud" > your notes directory > your category name

### Expected behaviour
category directory should contain .txt and .md files of notes created in notes app

### Actual behaviour
category directory is empty

## Server
- Notes app version: 4.3.1
- Nextcloud version: 23.0.0
- OS: Ubuntu 20.04.4
- Web server: official docker container
- PHP version: official docker container
- Database: postgres 13

## Client
- Browser (incl. version): Firefox 98
- OS: iOS 15.3

**Comment by kevindurb** [comment]
sorry just updated the description. I got expected and actual swapped 🤦🏻

**Comment by stefan-niedermann** [comment]
This is the repository of the Notes **server** app. Would you kind moving this issue to the repository of the Notes iOS client you are using?

**Comment by kevindurb** [comment]
I'm not using an iOS client, I'm trying to view the notes as just the raw files they are from the iOS Files app

**Comment by stefan-niedermann** [comment]
I still don't get the connection to the notes server app - you said the note files are available in the web interface, so they are *there* - isn't it an issue of the iOS Files app then if it doesn't show them?

Do other sync client shpw the note files, for example the desktop sync client?

**Comment by kevindurb** [comment]
I actually havent tried the desktop sync. I could totally see this just being a nextcloud iOS app issue tho. But the only thing that lead me down this route is that my notes directory is the only directory acting weird. Ive got other files nested in various levels of directories and all those show fine but only specifically the category directories for notes dont show the contents

**Comment by korelstar** [comment]
@kevindurb Could you please confirm that the note's file is in the correct sub directory on the server (using the Nextcloud web frontend's file app)?

**Comment by kevindurb** [comment]
Yes i can confirm the notes show up correctly in the sub dirs they should via nextcloud web and even the nextcloud ios app but specifically in the iOS Files app i cant see them, i can see the directories for the top level notes dir and the sub directories for categories but i cant see the notes files themselves.

**Comment by korelstar** [comment]
Thanks for this clarification. In this case, @stefan-niedermann is right and there is nothing that we can do in the Notes app, because it looks like the Notes app works correctly (files appear in the correct directory). Please open an issue for the iOS app.
