### ISSUE TITLE
Invalid Hash since 23.0.3 update

### ISSUE THREAD

**Issue by waielbi** [nextcloud/notes#837]
Hello,
since the nextcloud 23.0.3 update, there's a warning on the admin page : « Some files have not passed the integrity check... »

> Technical information
> =====================
> The following list covers which files have failed the integrity check. Please read
> the previous linked documentation to learn more about the errors and how to fix
> them.
> 
> Results
> =======
> - notes
> 	- INVALID_HASH
> 		- js/notes-main.js.map
> - appid
> 	- EXCEPTION
> 		- Exception
> 		- App not found
> 
> Raw output
> ==========
> Array
> (
>     [notes] => Array
>         (
>             [INVALID_HASH] => Array
>                 (
>                     [js/notes-main.js.map] => Array
>                         (
>                             [expected] => a43e8ef3134191232a7e1c851a1d37762844f5049fdf623aaa56da9c2663d7387ad761073f17ca16a9a299577c1ccc680e30315666c316c16a2138be36a1f301
>                             [current] => 468a75bc50eac007f1160a49e19dc5139658df7049b4195066b25341567214cc30c0c2210bbf0c53bf92ad422683da27e2c37744729e41c897ca628e1ba0435e
>                         )
>                 )
>         )
> 
>     [appid] => Array
>         (
>             [EXCEPTION] => Array
>                 (
>                     [class] => Exception
>                     [message] => App not found
>                 )
>         )
> )

I tried to ununstall / reinstall Notes, the warning is still here

## Steps to reproduce
1. install Notes
2. Update 23.0.2 to 23.0.3

### Expected behaviour
no warning

### Actual behaviour
the warnig

## Server
Please complete the following information.

- Notes app version: 4.3.1
- Nextcloud version: 23.0.3
- OS: ubuntu-20.04.3-live-server up to date
- Web server: apache 2
- PHP version: 7.4.3, 512 MB
- Database: mysql, 10.3.34

**Nextcloud configuration:**

## Client
Please complete the following information.

- Browser (incl. version): firefox
 - OS: ubuntu 20.04.04

## Log files
Add relevant parts of your `nextcloud.log` and/or your browser's JavaScript console here.

**Comment by korelstar** [comment]
Please try to restart your web service and PHP-FPM (if used). In most cases, the server has still some files in it's cache.

**Comment by korelstar** [comment]
Closing due to missing feedback. I assume that restarting the server has fixed the issue.

**Comment by waielbi** [comment]
Thank you. In fact it was Ubuntu witch was down due to a crashed update. restarted blocked it with initramfs pro même i clould'nt solve (SSD). I recovered the files from the disk ans the calendars from thunderbird by exporting the ICS.
I quit auto-hosting, i took a Zaclys plan for  a Nextcloud...

Le 16 avril 2022 05:08:55 UTC, korelstar ***@***.***> a écrit :
>Closed #837.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/notes/issues/837#event-6442975073
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
YLB / ***@***.***
https://waielbi.net
