### ISSUE TITLE
Word counter doesn’t need to show anything when note is empty

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/notes#84]
When you click into a new empty note, the word counter on the bottom left shows »0«. That’s unnecessary. :)

If there are no words, simply don’t show anything in there, just like we don’t show any number in the sidebar of Mail or News if there are 0 unread entries.

**Comment by andreasjacobsen93** [comment]
Did a PR. :-)

**Comment by jancborchardt** [comment]
Cool work all around @andreasjacobsen93! Hope to see you at the Nextcloud conference in Berlin! :)
