### ISSUE TITLE
right Sidebar permanent open

### ISSUE THREAD

**Issue by saddy123** [nextcloud/notes#845]
Hey, 

many thanks for this cool app, I really like the implementation.

I miss only one thing and this would be an option to always show the details sidebar on the Desktop version.

**Comment by korelstar** [comment]
Which app version do you use? Since version 4.2.0, the sidebar already stays open when switching to another note. What do you want in addition to this?

Please be more precise, use the issue template (!) and provide screenshots about what do you exactly mean.

**Comment by korelstar** [comment]
Closed due to missing feedback.
