### ISSUE TITLE
nextcloud notes doesn't sync NotPermittedException

### ISSUE THREAD

**Issue by BBGamingNL** [nextcloud/notes#855]
i have a nextcloud docker and would like to use the app but i get steet sync error

nextcloud Version : 24.0.0
nextcloud Notes : 4.3.1

[notes] Fout: OCP\Files\NotPermittedException:  at <<closure>>

 0. /var/www/html/custom_apps/notes/lib/Service/NotesService.php line 121
    OC\Files\Node\File->delete()
 1. /var/www/html/custom_apps/notes/lib/Controller/NotesApiController.php line 221
    OCA\Notes\Service\NotesService->delete("BB", 875)
 2. /var/www/html/custom_apps/notes/lib/Service/Util.php line 28
    OCA\Notes\Controller\NotesApiController->OCA\Notes\Controller\{closure}("*** sensitive parameters replaced ***")
 3. /var/www/html/custom_apps/notes/lib/Controller/Helper.php line 145
    OCA\Notes\Service\Util::retryIfLocked(Closure {})
 4. /var/www/html/custom_apps/notes/lib/Controller/NotesApiController.php line 223
    OCA\Notes\Controller\Helper->handleErrorResponse(Closure {})
 5. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 225
    OCA\Notes\Controller\NotesApiController->destroy(875)
 6. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Notes\Contro ... {}, "destroy")
 7. /var/www/html/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Notes\Contro ... {}, "destroy")
 8. /var/www/html/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main("OCA\\Notes\\Con ... r", "destroy", OC\AppFramework\ ... {}, {apiVersion: "v1 ... "})
 9. /var/www/html/lib/base.php line 1023
    OC\Route\Router->match("/apps/notes/api/v1/notes/875")
10. /var/www/html/index.php line 36
    OC::handleRequest()

DELETE /index.php/apps/notes/api/v1/notes/875?
by BB at 2022-05-14T07:28:18+00:00

**Comment by korelstar** [comment]
`NotPermittedException` means that your Nextcloud user does not have the permission to delete the file with id `875`. It looks like you tried to delete a note using a third-party app, but your user is not allowed to do this.

Please check if you are able to delete that file using the Nextcloud files app. I assume that this will not work, too. Therefore, you should check your Nextcloud configuration. Maybe the Nextcloud's data directory is not correctly set up?

**Comment by BBGamingNL** [comment]
> `NotPermittedException` means that your Nextcloud user does not have the permission to delete the file with id `875`. It looks like you tried to delete a note using a third-party app, but your user is not allowed to do this.
> 
> Please check if you are able to delete that file using the Nextcloud files app. I assume that this will not work, too. Therefore, you should check your Nextcloud configuration. Maybe the Nextcloud's data directory is not correctly set up?

Know where the error is. I recently reinstalled my cloud and backed up my files. and when i put them back changed the rwx to data $userfile location just sudo chmod and then i set it to 774 and it just does it again
