### ISSUE TITLE
Double Click action in View mode

### ISSUE THREAD

**Issue by newhinton** [nextcloud/notes#857]
It could be good if a note would switch to editing mode if a user double clicks the view.

I am willing to implement this, this ticket is more a discussion if that is something that would actually make the ui better.

**Comment by stefan-niedermann** [comment]
I have concerns about the double click action. It is not discoverably nor accessible and maybe there are better solutions like permanently showing the toggle button in combination with a keyboard shortcut.

cc @nextcloud/designers @jancborchardt @nimishavijay

**Comment by newhinton** [comment]
I agree with the keyboard shortcut, i will check if there is one and if not, i will add one. Also this will never be the only toggle, there is the button in the trhee-dot menu.

@stefan-niedermann what exactly do youn mean with accessible?  Does this 'dubplicate' method need anything?

**Comment by korelstar** [comment]
There is already a keyboard shortcut for switching between view mode and edit mode: `CTRL + /` , see https://github.com/nextcloud/notes/pull/556 and the discussion on https://github.com/nextcloud/notes/issues/505

**Comment by newhinton** [comment]
@korelstar I think i have an idea. We could implement a "First Use"-Popup that explains some of the features that we provide. Similar to what nextcloud shows users they log in the first time. As a second step we could also implement an 'in-app'-wiki, similar to how nextcloud/passwords does it. Should i open a new issue for this or is this an unwanted feature?

**Comment by korelstar** [comment]
We have already a welcome screen, see https://github.com/nextcloud/notes/issues/14#issuecomment-489298524 . But I think we should not add every detail there. Instead, an in-app info page with more details could be helpful. We had already some issues regarding this, e.g. #287 and #196. However, the discussion was not very constructive, yet. Maybe you can add some ideas on how to integrate the desired information into the app in the open issue? (The solution should respect how other Nextcloud apps do it, of course)

**Comment by korelstar** [comment]
I tried the PR #859, and I agree with @raimund-schluessler.

However, I must say that it's confusing when double clicking on a long note after scrolling down. Currently, the editor mode starts from the top. I think, the use case when double clicking on the text is to start editing at this position. Would it be possible to move (roughly) at the position that I had in view mode?

By the way: when switching from edit mode to view mode, the (rough) position is kept.

**Comment by korelstar** [comment]
From https://github.com/stefan-niedermann/nextcloud-notes/issues/1519#issuecomment-1140499223 :
> Double tapping usually triggers on Android a "Select word" action and it also interfers with checkboxes.

"Select a word" is also triggered on web browsers. It is true, that this feature request conflicts with the browser's default behavior. Maybe we should indeed use another shortcut. Maybe the keyboard shortcut `CTRL + /` is enough?

**Comment by korelstar** [comment]
Okay, I finally think we should not introduce this, since double clicking text has another meaning in browsers (see https://github.com/stefan-niedermann/nextcloud-notes/issues/1519#issuecomment-1167072504).
