### ISSUE TITLE
Allow Checkbox to be toggled in viewmode

### ISSUE THREAD

**Issue by newhinton** [nextcloud/notes#858]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when i cant quickly change a checkbox

**Describe the solution you'd like**
Changeable checkboxes in viewmode.

**Describe alternatives you've considered**
a clear and concise description of any alternative solutions or features you've considered
No changes to the viewmode

**Additional context**
I am willing to implement this together with #857

**Comment by newhinton** [comment]
I have already started implementing this, though i still need to figure out how to update the markdown after i changed the checkbox

**Comment by Jerome-Herbinet** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when i cant quickly change a checkbox
> 
> **Describe the solution you'd like** Changeable checkboxes in viewmode.
> 
> **Describe alternatives you've considered** a clear and concise description of any alternative solutions or features you've considered No changes to the viewmode
> 
> **Additional context** I am willing to implement this together with #857
Hi @newhinton, 
**I totally agree with what you are pointing out.** 
Besides, it would be so much more consistent with the Android application that has been allowing it for a long time. In my smartphone app, I can check or uncheck the checkboxes when in view mode.
I hope your PR will be accepted and pushed into production as soon as possible 😊
Best regards,
Jérôme
