### ISSUE TITLE
android app won't connect to NC server until open NC sync app one time.......

### ISSUE THREAD

**Issue by dd88w** [nextcloud/notes#868]
Please make a clear and concise description of what the bug is. Please note, that issues with the Android app have to be reported under https://github.com/stefan-niedermann/nextcloud-notes/issues and issues with Nextcloud's Text app have to be reported under https://github.com/nextcloud/text/issues .

## Steps to reproduce
1.open android note app, and it will try to connect NC server,and it keeps on  trying and failed.
2.open the andorid NC sync app version 3.20.0, get into a random server folder make sure it sync sth sucess.
3.go back open android note app, and its connected to NC server sucessfully, and syned already......

### Expected behaviour
the notes app  should connect to NC server independelly

### Actual behaviour
without openning the NC sync app, the note app won't able to connect at all.

## Server
Please complete the following information.

- Notes app version: 3.4.19
- Nextcloud version: 24.0.1
- OS: debian 11
- Web server: nginx/1.14.2
- PHP version: PHP 8.1.5
- Database: mariadb  Ver 15.1

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            ""***REMOVED SENSITIVE VALUE***""
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.1.1",
        "overwrite.cli.url": "https:\/\/"***REMOVED SENSITIVE VALUE***"\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filesystem_check_changes": true,
        "default_phone_region": "cn",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "maintenance": false,
        "loglevel": 2
    }
}

## Client
Please complete the following information.

- Browser (incl. version): chrome 93.0.4577.62
 - OS: harmony OS 2.0.0

## Log files
Add relevant parts of your `nextcloud.log` and/or your browser's JavaScript console here.

**Comment by stefan-niedermann** [comment]
Dear @dd88w 

please try to clear the storage of **both** Android apps as [explained in our FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#workarounds), exclude Nextcloud and Notes from the battery "optimizations" of your device and add your accounts again. If you still have troubles, please open a new issue in [the issue tracker of the Notes Android app](https://github.com/stefan-niedermann/nextcloud-notes/issues/new?assignees=&labels=bug&template=bug_report.md) filling the issue template you will see there (this repository is **only** for the Notes server app, which is developed independently from the Notes Android app).
