### ISSUE TITLE
Every User on a Nextcloud Server get a Folder named Notizen

### ISSUE THREAD

**Issue by WST1811** [nextcloud/notes#872]
Please make a clear and concise description of what the bug is. Please note, that issues with the Android app have to be reported under https://github.com/stefan-niedermann/nextcloud-notes/issues and issues with Nextcloud's Text app have to be reported under https://github.com/nextcloud/text/issues .

## Steps to reproduce
1. Install https://apps.nextcloud.com/apps/notes on a Nextcloud Server (i have installed 24.0.1)
2. Create a new User
3. Login as this User, now you will get a Folder Notizen (i think it calls only in Germany Notizen)

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead
I have a couple of Users on my NC-Server, now every User is asking why he has an Folder Notizen. The Folder can be removed, but after a couple Minutes/Seconds it comes back.

## Server
Please complete the following information.

- Notes app version: 3.5.00
- Nextcloud version: 24.0.1
- OS: Bullseye (RaspberryPI 4B)
- Web server: apache2
- PHP version: 7.4
- Database: MariaDB

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

 sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.178.8",
            "nc.wsonntag.de",
            "91.42.146.43"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.1.1",
        "overwrite.cli.url": "http:\/\/192.168.178.8\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "DE",
        "default_language": "de",
        "default_locale": "de_DE",
        "force_language": "de",
        "force_locale": "de_DE",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
pi@raspberrypi:/var/www/html/nextcloud $

```
</details>

## Client
Please complete the following information.

- Browser (incl. version): Firefox 91.10.0esr
 - OS: Windows 8.1/10 (21H2)

## Log files
Add relevant parts of your `nextcloud.log` and/or your browser's JavaScript console here.
Where i finde the Logfiles?

I think its a bug, i, but i don't know when its started to bring a Folder Notizen to each user.

**Comment by korelstar** [comment]
I can't fully reproduce this. In my tests, the notes folder is created only when opening the Notes app or when doing a search using the Nextcloud unified search or if you have the Notes dashboard widget added to your dashboard. It is not created, if you just log-in. Are you sure that this is the case for you?

Nevertheless, I see the point. While I think it is okay that the notes folder is created when opening the Notes app or using the Notes dashboard widget, I understand that it should not be created if you are doing a search. I think, we can optimize this. However, I wouldn't say that this is a bug. It's rather an enhancement.

By the way: you are using a quite old version of the Notes app. Version 4.4.0 is the current version. Please tests also with the current version.

**Comment by WST1811** [comment]
Thanks for response. I'll wait for a update. ;)

The Version 3.5.0 ist the Android App, the Notes App in Nextcloud is Version 4.4.0. I'm allways looking for actually versions.
