### ISSUE TITLE
Discussion: Inline HTML

### ISSUE THREAD

**Issue by newhinton** [nextcloud/notes#880]
**Is your feature request related to a problem? Please describe.**
I have some html-tags to center specific content, that does not get rendered by MarkdownIT at the moment.

One possibility would be to allow markdown-it to render it, via it's `html: true`-flag. (As far as i understood the documentation, this should allow the source content to be rendered as html.) There could be security implications to rendering foreign markdown, so this needs to be discussed properly.

**Comment by korelstar** [comment]
I vote against this feature request. Supporting also HTML makes things much more complicated. As far as I know, the Android app also does not support HTML code and it's likely that it will never do. Do you agree, @stefan-niedermann ?

**Comment by korelstar** [comment]
Okay, let's do not realize this.
