### ISSUE TITLE
Can't remove some notes

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/notes#887]
I removed some notes, but they are still there, at least in the overview. If I click on them, they are empty.
Do I have to remove the notes entry in the database?
![grafik](https://user-images.githubusercontent.com/24530680/180726531-35a40a49-8b26-4415-8f49-9af49442477c.png)

**Comment by korelstar** [comment]
"Fehler vom Nextcloud-Server" means, that there was an error on the server-side. Please have a look at your server's `nextcloud.log`. There should be more information.

You do not need to manually remove notes entries from the database, this should be done automatically. But how did you removed the files? Using Nextcloud or directly in the file system? If you worked directly on the file system, you will have to run `php occ:files scan` from the server's command line.

How does the Nextcloud files app behaves? Do you see the notes files from there?

**Comment by jakobroehrl** [comment]
Thanks for your reply.
I deleted some notes within the notes app. Most of them are gone, some not with the error above.
Error in Log:
![image](https://user-images.githubusercontent.com/24530680/183305714-4f8e865a-d2e3-42d7-8d17-5a1a183063d2.png)
In the file app the file is gone.

**Comment by korelstar** [comment]
Hmm, that's strange. The notes app reads the list of notes files using the official Nextcloud API, so there should be no difference to the files app. Could you please nevertheless try to execute `php occ files:scan` from the server's command line? And please try also to restart your server.

**Comment by jakobroehrl** [comment]
Sorry, files:scan and restart did not change anything. :(

**Comment by korelstar** [comment]
Too bad. There is another thing you could try: delete the content of the database table `notes_meta` - but not the table itself.

**Comment by jakobroehrl** [comment]
Thanks for your help.
Deleting the database entry does not help, it was automatically recreated. 
I moved the complete subfolder (between notes) away, now the notes are gone.
