### ISSUE TITLE
Markdown for check box seems inconsistent

### ISSUE THREAD

**Issue by DuncanLithgow** [nextcloud/notes#895]
## Steps to reproduce
Try and make a check box
`- [ ]` is the only syntax that works, but it creates a list item at the same time so i get a dash bullet list follow by a check box. 

### Expected behaviour
I should only get a task list
![billede](https://user-images.githubusercontent.com/3223028/183866275-8e58a892-4c5b-46a9-8c33-0d6d2456613a.png)

### Actual behaviour
i get a dash bullet list follow by a check box.
what markdown specification is Notes using? I can't find it mentioned in the documentation & the syntax for check boxes doesn't follow the [syntax here on github](sudo -u www-data php occ config:list system). As far as I can see check boxes are not even part of the standard syntax https://daringfireball.net/projects/markdown/syntax but part of an extended syntax https://www.markdownguide.org/extended-syntax/#task-lists

If Notes cannot reference an existing standard then it needs it's own syntax guide.

### Screenshots
![billede](https://user-images.githubusercontent.com/3223028/183861586-9f0fc2ec-7734-491f-83fe-ede486706aeb.png)

## Server
Please complete the following information.

- Notes app version: please add the program version to the 'settings' dialog. Otherwise only admins know the version. Version is 4.4.0
- Nextcloud version: 24.0.03
- OS: linux server
- Web server: not sure
- PHP version: not sure
- Database: mySQL

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

## Client
Please complete the following information.

- Browser (incl. version): Firefox 103.0.1
 - OS: Windows 10

## Log files
Add relevant parts of your `nextcloud.log` and/or your browser's JavaScript console here.

**Comment by korelstar** [comment]
You are mentioning many different issues:

> i get a dash bullet list follow by a check box.

That's true, but I don't see the problem. The edit mode is a combined source code editor with some (not all!) formatting visualization. It is not a full WYSIWYG editor! If you want to see the final result, you could switch to preview mode (using the three-dots menu or using `CTRL+/`). This difference can be also seen for headings (in edit mode, the `#` chars are visible) and for links (in edit more, the source code is shown).

There were plans to integrate Nextcloud Text which provides a WYSIWYG editor. But currently, there are still major drawbacks of this approach. Therefore, the current state will be kept until the problems of Nextcloud Text are solved. Please see #331 for more details about this.


> what markdown specification is Notes using?

There is already an open issue for this: #477


> Notes app version: please add the program version to the 'settings' dialog. Otherwise only admins know the version.

I assume that only admins do report issues here. People who are not admin should first contact their local admin for first-level support.

**Comment by DuncanLithgow** [comment]
I actually like all your replies, and am glad #477 is on the radar. Thanks for the hard work on making this tool I use every day.
