### ISSUE TITLE
Notes `4.4.0` does not communicate all available API versions

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/notes#896]
Notes `4.4.0` does include [API version `1.3`](https://github.com/nextcloud/notes/blob/master/docs/api/v1.md), the `x-notes-api-versions` header however does respond with `0.2, 1.2`.

I would have expected it to be `0.2, 1.3`.

Background: I stumbled upon this issue while implementing support for [#795 Allow custom file extensions](https://github.com/nextcloud/notes/pull/795) in the Notes Android app.

**Comment by korelstar** [comment]
Oh no, that's indeed a bad bug. I will fix this and release a new version on the weekend.
