### ISSUE TITLE
Improve the Android app and the Notes app to be able to replace Evernotes

### ISSUE THREAD

**Issue by enoch85** [nextcloud/notes#90]
I've been using ownNotes for quite some time, and it includes an Android app to sync your notes. One could call it a complete Evernote replacement. You can find the repo here: https://github.com/Fmstrat/ownnote Unfortunately it's not maintained anymore...

Currently there are only smartphone apps for notes that are produced for ownCloud. Some of them work with Nextcloud, but now when 12 is released I think most of them will fail.
![screenshot_20170507-200142](https://cloud.githubusercontent.com/assets/4511254/25783691/24817daa-3361-11e7-9ed9-0e566f49ad9c.png)

I suggest that 
1. Make the notes app support images and other media as well. https://github.com/nextcloud/notes/issues/74
2. Develop an app for Android (to start with at least) (Maybe even fork @Fmstrat's repo?)

The Android app would be something that users would pay for, and I think the interest would be pretty big! I'm willing to pay at least 3 Euro for such an app.

**Comment by korelstar** [comment]
Regarding the Android app: There is a really good Android app which works with Nextcloud Notes: https://github.com/stefan-niedermann/nextcloud-notes (you have it in your screenshot at the first position, but it seems that the version on Google Play is not up-to-date (e.g. it has the old "ownCloud name") -- you find the latest version on F-Droid).

Please have a look at the following pages for further mobile clients for this Nextcloud app:
- https://github.com/nextcloud/notes/
- https://github.com/nextcloud/notes/wiki

**Comment by enoch85** [comment]
@korelstar Thanks, but it still doesn't support Images and can *not* be called a Evernotes replacement IMHO. 

Still, I think the Nextcloud notes dev(s) should take it one step further. We don't want to end up in a sutiation where something isn't maintained again. Because that sucks. :)

**Comment by enoch85** [comment]
Just took a closer look. Seems like this app "only" can handle markdown. Tell me one Windows user or noob that even know what markdown is, I can't come up with anyone. The ownNotes app provides a familiar interface and makes it possible to upload media as well. *That's* what I mean with Evernote replacement. :) If I just want notes, well then I could just use the existing Calendar or Tasks app and add my notes as tasks, which I already do as well.

![screenshot_20170507-231017](https://cloud.githubusercontent.com/assets/4511254/25785188/d16f8b2e-337a-11e7-80aa-45201b19eb96.png)

**Comment by enoch85** [comment]
Also, please rename the app on Google Play to stop confusion.

**Comment by Fmstrat** [comment]
I'm the maintainer (sort of) of ownNote. I have zero time to dedicate to the project anymore, which is really unfortunate. It doesn't need much, but if anyone from the Nextcloud team would like to take it on or integrate it into the supported packages I, and the many users of it, would certainly appreciate it.

@enoch85 If you look in the issues, people do have it working with Nextcloud with some minor updates.

**Comment by stefan-niedermann** [comment]
Sorry, yep. Play Store is currently outdated and will be updated very soon with v0.11.0. Also the branding, screenshots and app name will completely change to "Nextcloud Notes" (though it does and should keep work with ownCloud AND Nextcloud).

When the server app provides more APIs (like image support - or categories recently) - i will try to add those to the Android client as soon as possible.

**Comment by olantrust** [comment]
@Fmstrat 
@ThomasDaheim appears to be trying to get in touch with you to get access to ownnote (perhaps as a maintainer?) and to the Android app code.
See discussion https://github.com/Fmstrat/ownnote/issues/338
If you haven't already, perhaps you could contact him? Many thanks

**Comment by fulljackz** [comment]
I give my try too.

It would be awesome that the application transforms into a real evernote alternative.

I often use OmniNotes https://github.com/federicoiosue/Omni-Notes which is a very good alternative to Evernote : beautifull ui, easy writing (no markdown) and an easy media integration.

Why markdown is still used today into the app ? Why can't we use native markup such as others softs ? In 2017, markdown usage can frighten others :/

**Comment by enoch85** [comment]
@fulljackz Have a look at https://github.com/brantje/nextnote. The plan is to develop an Android App for that. Would be really cool if you could help.

**Comment by fulljackz** [comment]
@enoch85 Thanks, I will give it a try and I'll try to help if I can !

**Comment by jancborchardt** [comment]
See my comment at https://github.com/nextcloud/notes/issues/183#issuecomment-394510571
