### ISSUE TITLE
Cannot login to server with Notes. Other apps are fine.

### ISSUE THREAD

**Issue by codejp3** [nextcloud/notes#901]
Please make a clear and concise description of what the bug is. 

Bug: can't login to server through Notes App.

## Steps to reproduce
1. Open app for the first time and "create account"
2. Try to use the existing NC Files App account and get the following error:
`Your Nextcloud Files app currently does not support the single singon feature. Please update it (+link to NC app in the Play store)`
NC Files app is the latest, and even tried beta version.
3. Try to manually connect to the URL with username and password and get the following error:
`An account for the same user and server already exists on the device`
4. Create a token and try to use that to connect and get the same duplicate account error:
`An account for the same user and server already exists on the device`

### Expected behavior
Choose my existing NC account on my device and use that to connect.

### Actual behavior
Unable to connect. NC Files app connects fine, and so do other apps for bookmarks/passwords/news/etc. Notes is the only one giving me this error.

### Screenshots
![Screenshot_20220815-025805_Nextcloud_Notes](https://user-images.githubusercontent.com/26341487/184590501-71ff11be-3ace-491e-80e5-cff014a4f619.png)
![Screenshot_20220815-030007_Nextcloud](https://user-images.githubusercontent.com/26341487/184590528-9f19b81b-6c51-4d0e-9a09-76bddda0161c.png)

## Server

- Notes app version:  3.5 (android client), 4.5 (server)
- Nextcloud version: 24.04
- OS: Deb 11
- Web server: Apache / Nginx
- PHP version: 8.0
- Database: MariaDB/MySQL

## NC Files App
Tried Stable & Beta versions from both F-Droid & Play Store.
Version 20220810

## NC Notes App
Tried stable from F-Droid & Play Store, and tried beta from Play Store.
Version 3.5

**Comment by korelstar** [comment]
This issue is not related to the Notes server app (this repository) but to the Android Notes app ([other repository](https://github.com/stefan-niedermann/nextcloud-notes)). Please open an issue over there. But before doing this, please read the [Android app's FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md).

**Comment by stefan-niedermann** [comment]
@codejp3 due to [a bug of the SingleSignOn library](https://github.com/nextcloud/Android-SingleSignOn/issues/470) it is currently not possible to sign in with the Nextcloud Android App **Dev** app. You currently need to use the stable released version until this issue has been fixed.
