### ISSUE TITLE
FR: Read ZIM 0.4 Wiki Format as Note

### ISSUE THREAD

**Issue by marneu** [nextcloud/notes#902]
**Desktop Notebook ZIM is tied to Nextcloud sync Notes folder here.**
I'm always frustrated when I read the notes in Nexcloud Notes as they are different displayed:
```
Content-Type: text/x-zim-wiki
Wiki-Format: zim 0.4
Creation-Date: 2022-08-10T10:48:11+02:00

====== Mittwoch 10 Aug 2022 ======
```
**I'd like to have a view where the first 3 Lines are not displayed**
The header should be kept but not displayed, the following text could be interpreted following the ruleset on https://zim-wiki.org/manual/Help/Wiki_Syntax.html (kind of DokuWiki syntax). The type of default wiki markup/-down language etc. should be selectable as personal setting, as for shure more will have it on their wishlist.

**Comment by korelstar** [comment]
Nextcloud Notes uses Markdown for storing notes. That's a fundamental architecture decision. At a first glance, it looks nice if the Notes app would also support other storage backends and file formats. However, this is a small open source project and we do not have enough free time for maintaining this. Therefore, I must close this feature request as not planned.
