### ISSUE TITLE
notes spacing / new lines / newlines / markdown standard

### ISSUE THREAD

**Issue by bryanpedini** [nextcloud/notes#903]
## Steps to reproduce
1. create a note
2. insert more than two new lines
3. go into preview mode

### Expected behaviour
Either the "double space followed by a newline creates a newline" Markdown specification or the "just insert a `<br>` tag" specification (or both) be respected

### Actual behaviour
Even a hundred new lines are threated just like two new lines

### Screenshots
![Screenshot_20220816_175453](https://user-images.githubusercontent.com/45012292/184924420-c87c2325-492d-47fc-a8f9-38f1153ca5d0.png)
![Screenshot_20220816_175510](https://user-images.githubusercontent.com/45012292/184924427-6f4cd7d4-1f52-4780-a179-61e4ce6abec0.png)

## Server
Please complete the following information.

- Notes app version: 
- Nextcloud version: Docker Container tag `23.0.8-apache`
- OS: Dockerized
- Web server: Apache (Dockerized)
- PHP version: idk, Dockerized
- Database: MariaDB v10.8.3

**Nextcloud configuration:**

<details>
Executing from inside the container

```
sudo -u www-data php occ config:list system
```

Resulted in

```
Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 438272 bytes) in /var/www/html/3rdparty/composer/autoload_real.php on line 35
```
</details>

## Client
Please complete the following information.

- Browser (incl. version): independent, tho Ferdi app (https://getferdi.com)
- OS: Arch Linux

## Log files
N/A

### Additional
Sorry for the multiple things in the title, I thought to make it easier to search this issue if somebody else wants to see if there's already one by including basically everything I could think that matched the report

**Comment by stefan-niedermann** [comment]
According to the [`commonmark` specification](https://spec.commonmark.org/0.30/#blank-lines) this is the correct behavior.

> [Blank lines](https://spec.commonmark.org/0.30/#blank-line) between block-level elements are ignored, except for the role they play in determining whether a [list](https://spec.commonmark.org/0.30/#list) is [tight](https://spec.commonmark.org/0.30/#tight) or [loose](https://spec.commonmark.org/0.30/#loose).
> 
> Blank lines at the beginning and end of the document are also ignored.

References https://github.com/nextcloud/notes/issues/477

**Comment by bryanpedini** [comment]
Basically under this [`commonmark` specification](https://spec.commonmark.org/0.30/#hard-line-break) you have to do this:
![Screenshot_20220816_191253](https://user-images.githubusercontent.com/45012292/184939034-50e0d17b-01c3-44b4-badd-b0c5cebe7340.png)
![Screenshot_20220816_191321](https://user-images.githubusercontent.com/45012292/184939041-b1d7a609-d0f7-4064-ac0d-05b1c5bb2cf0.png)
