### ISSUE TITLE
Moving Notes between servers

### ISSUE THREAD

**Issue by Bergum** [nextcloud/notes#915]
Is there a way to move my notes between or sync between 2 servers?

I tryed to just move the catalog, but they dont show up on the new server.

**Comment by stefan-niedermann** [comment]
## Move to another instance

The notes are stored as plain `.txt` (or `.md` files) in your user directory. You can download them from the Web UI (with the files app), synchronize them with the default Nextcloud Desktop client, access them wie WebDAV, FTP and a billion other ways. Pushing them to your other Nextcloud instance is as simple as just upload the files again (in case of FTP or SSH you will need to run the `occ files:scan` command of course).

## Synchronize between instances

The same way as you would keep files in sync between several Nextcloud instances - probably the easiest way is using the default Nextcloud Desktop sync client. 

> I tryed to just move the catalog

What is a `catalog`? How did you move it exactly? My guess: You used SSH or FTP but did not run the [`occ files:scan`](https://docs.nextcloud.com/server/20/admin_manual/configuration_server/occ_command.html#scan) command?

**Comment by Bergum** [comment]
This is strange.
When I first copyed the files into the folder, nothing happened.
I created a new file in the mobile app, and i could see all files in the Nextcloud WebView.
Now however I can see all the files in the app, so I don't know what corrected it.
Thank you anyway for your reply.
