### ISSUE TITLE
Ability to change background colour

### ISSUE THREAD

**Issue by glidingthrough** [nextcloud/notes#917]
A white background is harsh on the eyes and the effects of blue light exposure are well documented as disruptive to the human body.

For ease of reading and writing over long periods, the ability to change the background colour to, for example, grey and/or a soft yellow would be appreciated.

**Comment by korelstar** [comment]
Please activate the dark mode in your Nextcloud's user settings. You will find it in the Accessibility settings. URL is https://yournextcloud/index.php/settings/user/accessibility
