### ISSUE TITLE
Cannot scroll in Nextcloud 25

### ISSUE THREAD

**Issue by blizzz** [nextcloud/notes#920]
## Steps to reproduce
1. Run NC 25 pre-release (RC 1 here)
2. Open Notes app and write a note longer than the screen size 
3. Go to the bottom of the note or try to scroll down

### Expected behaviour

Scrolls, i.e. you can see the bottom of the node

### Actual behaviour

Only the upper part of the note stays visible, nothing happens

## Server
Please complete the following information.

- Notes app version: 4.5.1
- Nextcloud version: 25 RC 1
- PHP version: 8.1

## Client
Please complete the following information.

- Browser (incl. version): Firefox 105.0.1
 - OS: Linux

**Comment by korelstar** [comment]
Thanks for this report. I can reproduce this issue. Looks like there are other things, that have to be fixed: #925
