### ISSUE TITLE
The distance to navigation is very large

### ISSUE THREAD

**Issue by miholzi085** [nextcloud/notes#931]
Hi!

I have installed a current Nextcloud version on a web host server. This works great so far, except for the notes app. The distance from the beginning of the text of a note to the navigation menu on the left is very large. [Screenshot](https://help.nextcloud.com/uploads/default/optimized/3X/9/6/960185132df2fd2405807110f16f57403fe13c3f_2_690x205.jpeg)

Tried in different browsers, always the same result.

What could be the problem?

Thank you very much for your help!
Michael

**Comment by korelstar** [comment]
Looks like you are using a large browser window. In this case, it is intended. Please see #415 and #182 for a reason of this.

**Comment by miholzi085** [comment]
@korelstar
Thanks for the link. I use a normal screen with a resolution of 1920x1080 (like 99% of all screens in our office). I also have this resolution at home.

The workaround with custom CSS works limited, there is still a lot of space to the left.

For many normal notes, the readability and line length is definitely useful. But I have notes where I write something down in tables, for example. And I only see part of the tables. I then have to go into the editor to see everything.

I'm currently using MS OneNote, but I'd like to get away from it. I think your notes app is great and would meet my requirements. But the empty space disturbs me a lot, this is the ground, why I don't actively use the app yet.

Thank you for all the work!

Regards
Michael

...sorry for my english, google helps me....
