### ISSUE TITLE
Checkboxes

### ISSUE THREAD

**Issue by Urbsey** [nextcloud/notes#932]
Checkboxes would be a great thing to add. It is a must-have for to-do lists. Could you make this happen? :)

**Comment by jakobroehrl** [comment]
You can use it by writing
 * [ ]

**Comment by Urbsey** [comment]
Well, if you use it as a shopping list and having like 20 things to cross out on the phone, it is much more convenient to have it like in Google Keeps or any other notekeeping sw. When you check it, the item goes below or at the bottom of the list. Not to mention that it is much easier to aim for the box instead the square bracket thingy. Or at least it is not working for me in that way.

**Comment by stefan-niedermann** [comment]
> When you check it, the item goes below or at the bottom of the list

https://github.com/nextcloud/notes/issues/681

> it is much easier to aim for the box instead the square bracket thingy.

Use the preview mode (👁️ icon) to toggle between rendered markdown and edit mode.

> Then you can have multi-layer of sub checkboxes

Intend with two <kbd>Space</kbd>s for nested checkbox lists:

```markdown
- [ ] Item
  - [ ] Subitem
```

- [ ] Item
  - [ ] Subitem

I recommend you to read a bit about Markdown, which the Notes app heavily relies on to apply formatting and semantics to notes 🙂.

**Comment by stefan-niedermann** [comment]
@brianjmurrell see https://github.com/nextcloud/notes/issues/477

**Comment by brianjmurrell** [comment]
@stefan-niedermann Fair enough.  Keeping it buried in an issue though doesn't really help a lot of people.  Having it documented "front-and-centre" somewhere, even maybe in a wiki page if not the top-level README.md I think would inform many many more people.

Perhaps one of the "example" notes that seem to get installed with the app should contain some documentation on the supported markdown.  That in fact seems like the **most** useful place in my mind.

**Comment by regs01** [comment]
How to avoid that dash line?
![](https://user-images.githubusercontent.com/10468217/229377760-0caee941-7b2e-449c-89e7-89e6ce6da7c5.png)
