### ISSUE TITLE
When changing the category of a note with image attachments, the attachments don't move and are broken.

### ISSUE THREAD

**Issue by srbaker** [nextcloud/notes#941]
When I have a note with image attachments, and change the category of that note, the image links are then broken.

## Steps to reproduce
1. Add an image attachment to a note.
2. Change the category of the note.

### Expected behaviour
The images that were in the note should not be broken links after the note is moved.

### Actual behaviour
The images show up as broken links.

Workaround: move the images manually in the Files app.

## Server
Please complete the following information.

- Notes app version: 4.5.1
- Nextcloud version: 23.0.3

**Comment by krisgesling** [comment]
Hi there, 
(I'm not a NextCloud rep)

I'm assuming this has been fixed as I just tested it on:
- Nextcloud v27.1.3.2
- Notes app v 4.8.1

Changed the category via the web interface, and then again using the Android app. In both cases the `.attachments.xxxxxx` directory was moved to the new category directory and the image displayed correctly.

Recommending closure.

**Comment by kondas** [comment]
Hi, this issue seems to be still present in notes 6.0.2.
