### ISSUE TITLE
API POST /notes does not work

### ISSUE THREAD

**Issue by christhulhu** [nextcloud/notes#949]
I want to write a program to store notes in Nextcloud notes. I interact directly with the REST-API.
Nextcloud Hub 3: 25.0.2
Nextcloud Notes: 4.6.0

API-Version: 1.3 under URL v1

## Steps to reproduce
Simple curl request:
```
curl -X POST -H "Content-Type: application/json" -d "{'title': 'New note.md', 'category': 'Test', 'content': 'New note and something more'}" https://$user:$password@$host/index.php/apps/notes/api/v1/notes 
```

Response:
```
{"id":3605,"title":"Neue Notiz (5)","modified":1670699949,"category":"","favorite":false,"readonly":false,"error":false,"errorType":"","content":"","etag":"32ce6a23ac3df501b3f25db142b7660c"}%
```

### Expected behaviour
I expect the response to have the values for "content" and "category" that were given in the request.
I expect the note to be created with the given values for "title", "content" and "category".

### Actual behaviour
A new note is created. But it is an empty note with another title than given in the request. Attributes for "content" and "category" are ignored

### Screenshots
n/a since this issue happens on the API and is reproduceable with cli-tools.

## Server
- Notes app version: 25.0.2
- Nextcloud version: 4.6.0
- OS: official Nextcloud Docker-Image nextcloud:latest
- Web server: Traefik as Reverse-Proxy to access official image
- PHP version: provided by official image
- Database: mariadb:latest

## Client
Curl and self written python skript

## Log files
docker logs show 200 HTTP for my request. Nextcloud Logs are empty about my request.

**Comment by juliushaertl** [comment]
I think you are passing invalid json therefore all values are empty strings by default. I could not reproduce this when using `"` instead of `'`:

```
curl -X POST -H "Content-Type: application/json" -d '{"title": "New note.md", "category": "Test", "content": "New note and something more"}' http://admin:admin@nextcloud.dev.local/index.php/apps/notes/api/v1/notes

{"id":6325,"title":"New note.md","modified":1672758441,"category":"Test","favorite":false,"readonly":false,"error":false,"errorType":"","content":"New note and something more","etag":"7b1ec7faba81cdbbd913820414dcdbf0"}%
```

**Comment by christhulhu** [comment]
Hello Julius,

thanks for your reply and the hint that I was using the wrong quotes. Seems legit to me, although I would have expected some feedback on this malformed json-object instead of ignoring all given values and doing something unexpected.
