### ISSUE TITLE
Note lost during "Error from Nextcloud-Server: OC\ServerNotAvailableException"

### ISSUE THREAD

**Issue by thomasfrobieter** [nextcloud/notes#950]
## Steps to reproduce
1. Edit a note (/apps/notes/note/x)
2. Leave it open for a couple of hours
3. Come back and try to change the page
4. Receive a warning message, that the content probably is not saved
5. Do some further editing in this note to trigger autosave
6. Again: Try to change the page and receive the not saved warning
7. F5 => Ignore warning
8. Notice lost "Error from Nextcloud-Server: OC\ServerNotAvailableException"

### Expected behaviour
The note should be saved, I should be able to leave the page ;)

### Actual behaviour
Note brakes due to OC\ServerNotAvailableException

### Screenshots
![grafik](https://user-images.githubusercontent.com/4060313/208147394-701d7d2e-5437-45c4-9296-f1c44dd5d21f.png)

## Server
Please complete the following information.

- Notes app version: 4.5.1
- Nextcloud version: 24.0.7
- OS: I don't know.. Hetzner.de managed Nextcloud hosting
- Web server: Hetzner.de managed Nextcloud hosting
- PHP version: I don't know
- Database: I don't know

**Nextcloud configuration:**

No access to commandline.

## Client
Please complete the following information.

- Browser (incl. version): Firefox 107.0.1
- OS: Windows 10.0.19045

## Log files
NC Log: "No log entries, everything works fine"
Javascript Console, no errors at all, when opening the broken notice. Only none relevant warnings like:
"jQuery is deprecated", "$ is deprecated", ...

**Comment by juliushaertl** [comment]
Can you share the relevant log entry from the Nextcloud log file?

**Comment by joshtrichards** [comment]
Closing due to lack of follow-up received after >18 months.
