### ISSUE TITLE
keyboard shortcut to add  a date/time stamp 

### ISSUE THREAD

**Issue by monperrus** [nextcloud/notes#954]
**Problem**
When taking notes, it's often useful to keep track of the moment of the idea/event.

**Describe the solution you'd like**
In some note-taking apps such as Tomboy, pressing Ctrl+d inserts a date/time stamp. It would be great to bind a keyboard shortcut to add the current date.

Thanks!

**Comment by joshtrichards** [comment]
Duplicate of nextcloud/text#4043
