### ISSUE TITLE
Change icon

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/notes#960]
Jan and me had a design review on Android and it was decided to slightly update the icon.
Please therefore also use the same on web: https://fonts.google.com/icons?selected=Material+Icons:edit:

**Comment by marinofaggiana** [comment]
Preview (draft):

<img width="95" alt="190-196-max" src="https://user-images.githubusercontent.com/8616947/220882774-65422c56-da75-4d60-b218-dc4b1da8fb82.png">

**Comment by AlvaroBrey** [comment]
> Preview (draft):
> 
> <img alt="190-196-max" width="95" src="https://user-images.githubusercontent.com/8616947/220882774-65422c56-da75-4d60-b218-dc4b1da8fb82.png">

That's the old pencil icon
