### ISSUE TITLE
Nextcloud 25 adjustments not effective

### ISSUE THREAD

**Issue by bolderbast** [nextcloud/notes#963]
Running Nextcloud 25 and Notes App 4.6.0, yet the fixes mentioned in https://github.com/nextcloud/notes/pull/928 are not effective.

## Steps to reproduce
1. Run Nextcloud 25
2. Run Notes app 4.6.0
3. Open the Notes "tab"

### Expected behaviour
Seeing the new design, as shown in https://github.com/nextcloud/notes/pull/928, and being able to scroll large notes

### Actual behaviour
Still seeing the old design, and not able to scroll long notes

### Screenshots
![image](https://user-images.githubusercontent.com/78593849/216806383-1e0f383a-bc96-4a91-956f-fd8306f6c220.png)

### Already tried:
Already tried:

- Using a different browser (FireFox and Chromium)
- Uninstalled & Re-installed the Notes App from the Nextcloud Admin interface

## Server
Please complete the following information.

- Notes app version: 4.6.0
- Nextcloud version: 25.0.3
- OS: Arch Linux (updated on 2023-02-04)
- Web server: nginx-1.20.2-1-x86_64
- PHP version: php-legacy-8.1.15-1-x86_64
- Database: mariadb-10.9.4-2-x86_64

**Nextcloud configuration:**

<details>
```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "<REMOVED>"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.3.2",
        "overwrite.cli.url": "https:\/\/breedborst.duckstad.net\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "logfilemode": 416,
        "loglevel": 2,
        "logdateformat": "F d, Y H:i:s",
        "default_phone_region": "NL",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "maintenance": false,
        "mysql.utf8mb4": true,
        "htaccess.RewriteBase": "\/nextcloud\/",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "app_install_overwrite": [
            "mail",
            "notes"
        ],
        "apps_paths": [
            {
                "path": "\/usr\/share\/webapps\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/lib\/nextcloud\/apps",
                "url": "\/wapps",
                "writable": true
            }
        ]
    }
}
```
</details>

## Client
Please complete the following information.

- Browser (incl. version): firefox-109.0-1-x86_64 and chromium-108.0.5359.124-1-x86_64
 - OS: Arch Linux (updated on 2023-02-01)

## Log files
Unknown which (parts) are relevant

**Comment by bolderbast** [comment]
OK, this is weird. I would have sworn I was already on Notes v 4.6.0, but I just now got a notification to update the Notes app to 4.6.0.

So I performed the upgrade (using occ upgrade), and it now 4.6.0 for sure:
![image](https://user-images.githubusercontent.com/78593849/216819600-1896164c-9e65-4561-91b2-222ad0edf4af.png)


But I still have the exact same behaviour, where I have the old design and unable to scroll (see the screenshot in the OP).

**Comment by juliushaertl** [comment]
I cannot reproduce this. Can you double check that the notes app was properly updated on the filesystem in your apps directory? appinfo/info.xml should contain the 4.6.0 version. One thing to double check would be if you have multiple app directories and if there is maybe two folders for notes?

**Comment by bolderbast** [comment]
Hmmm, this is indeed curious...:

```xml
[root@XXX /]# grep version /usr/share/webapps/nextcloud/apps/notes/appinfo/info.xml 
<?xml version="1.0"?>
        <version>4.4.0</version>
                <php min-version="7.4" max-version="8.1" />
                <nextcloud min-version="22" max-version="26" />
```

So I removed the app from the GUI and the directory/file mentioned above still existed. I moved it away into a backup location, and reinstalled the Notes app from the GUI.

Now the /usr/share/webapps/nextcloud/apps/notes directory does not exist, but the Notes app works and has the new design. Seems like it was using an old version of the app, installed in the wrong location (no idea why).

Looks like I have the new App installed at a different location:

```xml
[root@breedborst apps]# grep version /var/lib/nextcloud/apps/notes/appinfo/info.xml 
<?xml version="1.0"?>
        <version>4.6.0</version>
                <php min-version="7.4" max-version="8.1" />
                <nextcloud min-version="25" max-version="27" />
```

Not sure why. I'll investigate. But it's not related to this app I suppose, so we can close this issue. Thanks for pointing me in the right direction!

**Comment by bolderbast** [comment]
Ah, here we go:
https://wiki.archlinux.org/title/Nextcloud#Weird_behavior_of_one_or_more_apps

This is what happened... :-)
