### ISSUE TITLE
Newly integrated rich text editor does not load

### ISSUE THREAD

**Issue by PatrickJosh** [nextcloud/notes#982]
As the title says, if I switch to the newly integrated text editor for editing my notes, nothing happens and only a loading screen is shown when I want to edit a note. Moreover, there's an entry in the logs as well as my console which might be related.

## Steps to reproduce
1. Switch to new text editor
2. Try to edit a note.

### Expected behaviour
Text editor opens and note can be edited

### Actual behaviour
Infinite loading screen

### Screenshots
![afbeelding](https://user-images.githubusercontent.com/32456639/226591645-02aa717a-7c16-4e65-8a0f-4018221ca257.png)

## Server
Please complete the following information.

- Notes app version: 4.7.0
- Nextcloud version: 25.0.4
- OS: Fedora Linux 37
- Web server: Apache/2.4.56 (Fedora Linux)
- PHP version: PHP 8.1.17 (cli) (built: Mar 14 2023 19:50:20) (NTS gcc x86_64)
- Database: mariadb  Ver 15.1 Distrib 10.5.18-MariaDB, for Linux (x86_64) using  EditLine wrapper

**Nextcloud configuration:**

<details>

```

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.joshuanoeske.de",
            "127.0.0.1"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.4.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "default_language": "de",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "enabledPreviewProviders": [
            "OC\\Preview\\BMP",
            "OC\\Preview\\GIF",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MP3",
            "OC\\Preview\\PNG",
            "OC\\Preview\\TXT",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\Krita",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI"
        ],
        "default_phone_region": "DE",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "0"
        },
        "htaccess.RewriteBase": "\/",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 1,
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "logfilemode": 384,
        "lost_password_link": "disabled",
        "updater.release.channel": "stable",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "memories.gis_type": 1
    }
}

```
</details>

## Client
Please complete the following information.

- Browser (incl. version): Mozilla Firefox 110.0
 - OS: Fedora Linux 37

## Log files
Add relevant parts of your `nextcloud.log` and/or your browser's JavaScript console here.
```
{"reqId":"ZBmQaHDvVe1M3823b0LLkAABigc","level":2,"time":"2023-03-21T11:09:28+00:00","remoteAddr":"79.194.174.116","user":"joshua.noeske","app":"no app in context","method":"GET","url":"/apps/notes/note/204730","message":"Invalid config data provided to provideInitialState by notes","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0","version":"25.0.4.1","data":[],"id":"6419915547d69"}
```

And from my browser:
```
Uncaught (in promise) TypeError: window.OCA.Text is undefined
    t NoteRich.vue:86
    c Welcome.vue:20
    v Welcome.vue:20
    F Welcome.vue:20
    ti Welcome.vue:20
    o Welcome.vue:20
NoteRich.vue:86
```

**Comment by manumitted** [comment]
I basically see the same thing.

I'm somewhat new to Nextcloud and a little confused.  Do I need to enable some text editor app?  I don't think so, but there's one there that could be enabled.  But I don't think I need it, and there's some kind of built-in text editor (no app required), and I'm assuming that's the one Notes is intending to use?

**Comment by juliushaertl** [comment]
Thanks for reporting. Since I noticed you are on 25, the new editor integration is only available with Nextcloud 26, but for old releases we still fallback to the previous one. Now it seems that there is an issue with this fallback. Can you tell if after the upgrade you had the modal asking if you would want to use the new editor?

**Comment by manumitted** [comment]
Same here.

**Comment by provokateurin** [comment]
Also on 25, upgraded to 4.7.0 and enabled the rich text editor in the modal. I can still switch back to the old edit mode in the settings, but the new rich text edit mode fails to load.

**Comment by juliushaertl** [comment]
Found the reason why this is still triggered, I'll push a fix shortly

**Comment by juliushaertl** [comment]
v4.7.1 with a fix has just been released.

**Comment by Jerome-Herbinet** [comment]
Will #984 also fix this ? 

Below, I can't choose editor :
![2023-03-22_08-49](https://user-images.githubusercontent.com/33763786/226835435-07316c5e-09f3-4b46-bb3c-4a9440bb01c6.png)
![Sans titre](https://user-images.githubusercontent.com/33763786/226835455-e49493f0-ac3f-47ee-9fa4-2f1d21be106c.png)

**Comment by juliushaertl** [comment]
Looks like a different issue, can you report this separately with your nextcloud version, log messages if any and the full console output also before clicking the buttons?

**Comment by Jerome-Herbinet** [comment]
> Looks like a different issue, can you report this separately with your nextcloud version, log messages if any and the full console output also before clicking the buttons?

Yes, I'll do it after my daily meeting with my colleagues :-)

**Comment by Jerome-Herbinet** [comment]
@juliushaertl 
Server configuration detail

Operating system: Linux 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64

Webserver: Apache (fpm-fcgi)

Database: mysql 10.3.38

PHP version: 8.1.17

Modules loaded: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, json, iconv, SPL, Reflection, session, standard, mbstring, SimpleXML, sockets, tokenizer, xml, cgi-fcgi, mysqlnd, bcmath, curl, dba, dom, enchant, fileinfo, gd, imagick, imap, intl, ldap, exif, mysqli, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, redis, soap, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlwriter, xsl, zip, Zend OPcache

Nextcloud version: 25.0.4 - 25.0.4.1

Notes: 4.7.0 

Before clicking on buttons : 
![2023-03-22_09-45](https://user-images.githubusercontent.com/33763786/226849359-c85b2ed6-5cde-4919-8bfb-6095af503f49.png)

After clicking on both buttons : 
![2023-03-22_09-47](https://user-images.githubusercontent.com/33763786/226849450-aacd6287-3845-4a8e-99a7-5c84e6ba796a.png)

Note : Also, I cannot enable Rich Editor in my freshly updated android app (updated after server side app)

**Comment by juliushaertl** [comment]
Thanks, pushed a fix to #986

**Comment by Jerome-Herbinet** [comment]
OK, thanks, will this be backported to both NC 24 and 25 ?

**Comment by libre-hackerman** [comment]
I also keep having the same problem with Nextcloud 26 (Linuxserver Docker image) and Notes 4.7.1:

{"reqId":"k9If3eclZhxiiZ1WzXbG","level":2,"time":"2023-03-22T18:42:26+00:00","remoteAddr":"192.168.XX.XX","user":"XXXXXXXX","app":"no app in context","method":"GET","url":"/apps/notes/","message":"Invalid config data provided to provideInitialState by notes","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0","version":"26.0.0.11","data":[]}

**Comment by juliushaertl** [comment]
I just release 4.7.2 with solving another blocking case there.

**Comment by libre-hackerman** [comment]
4.7.2 solved it, thank you so much!

**Comment by daffydock** [comment]
Sadly, it did not fix it for me. 
When I try to go into the app on the web, it loads forever but after a while it might come up. Or it might hang. 
On the app, it will give me a set of errors. Like the following when I try to switch to Rich Text on my older phone.

```
App Version: 4.0.0 RC1
App Version Code: 40000051
App Flavor: fdroid

Files App Version Code: 30240190

---

OS Version: 3.18.31-perf-gd33f902(1906418273f7d)
OS API Level: 24
Device: sf340n
Manufacturer: LGE
Model (and Product): LG-M470 (sf340n_global_ca)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.google.gson.Gson.fromJson(java.io.Reader, java.lang.reflect.Type)' on a null object reference
	at com.nextcloud.android.sso.api.NextcloudAPI.convertStreamToTargetEntity(NextcloudAPI.java:159)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:130)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(D8$$SyntheticClass)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:219)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

```
