### ISSUE TITLE
NC26 Browser Popup when leaving Notes App whitin a note

### ISSUE THREAD

**Issue by apg1980** [nextcloud/notes#987]
Please make a clear and concise description of what the bug is. Please note, that issues with the Android app have to be reported under https://github.com/stefan-niedermann/nextcloud-notes/issues and issues with Nextcloud's Text app have to be reported under https://github.com/nextcloud/text/issues .

## Steps to reproduce
1.open notes and write a note
2. click on files app or another
3. browser popup appears whit hint unsafed data gets lost

### Expected behaviour
Data is safed

### Actual behaviour
Tell us what happens instead
![grafik](https://user-images.githubusercontent.com/9514965/226939949-ebce2c9d-e9b1-4d7b-90eb-05b6a4d4d0f9.png)

## Server
Please complete the following information.

- Notes app version: 4.7.1
- Nextcloud version: 26
- OS: ubuntu
- Web server: nginx
- PHP version: 8.1
- Database: postgree

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

## Client
Please complete the following information.

- Browser (incl. version): 
 - OS: 

## Log files
Add relevant parts of your `nextcloud.log` and/or your browser's JavaScript console here.

**Comment by JonnyTischbein** [comment]
I can confirm it with Nextcloud 25 and Notes app  4.7.1 (debain 11, nginx, php 8.2, mysql)

**Comment by juliushaertl** [comment]
This is a browser limitation as it is not guaranteed that any requests performed during the before unload event are handled. This event is explicitly only for asking for confirmation. As far as I'm aware there is no way we can ensure that the file would be saved before navigating away except blocking with this dialog.

**Comment by apg1980** [comment]
furthermore if i just stay on an note it appears while changing the nc site

**Comment by JonnyTischbein** [comment]
> why did it worked on nc25?
What do you mean with "it worked" ?

For me (on nc25 and nc26) it behaves as followed:
- If I edit a note wait for some seconds and then change to another app the note is saved and no warning appears
- If I edit a note and try to click fast enough on another app the warning appears

In other words (like the code in my comment showed https://github.com/nextcloud/notes/issues/987#issuecomment-1479888547 ):
If you leave the app faster than the background asyncronous saving of the note is finished the warning appears to prevent data loss.
The latency of automatically saving a note should depend on the servers performance and you network connectivity, If I am not mislead.

**Comment by apg1980** [comment]
i did never get an popup on latest nc25 with the latest notes app on realease date of nc26 before upgrading to nc26. this behaviour is new, the environment (server nginx etc did not changed)

**Comment by juliushaertl** [comment]
Do you use the plain markdown or the rich editing view? For the plain markdown the logic shouldn't have changed at all from 25.

**Comment by apg1980** [comment]
same behaviour on both methods.
next thin i can see, notes are not getting saved as expected before.
you can see the star beneth the note, latest changes are not saved after minutes.
i lost some important notes today, after leaving the typed notes.

**Comment by florianwgnr** [comment]
Links to #1008
