### ISSUE TITLE
Contrast in help is bad in dark mode

### ISSUE THREAD

**Issue by Wv5twkFEKh54vo4tta9yu7dHa3** [nextcloud/notes#991]
## Steps to reproduce
1. Enable dark mode
2. go to Notes app
1. Scroll down notes list
3. press help button
4. scroll down to shortcuts 

### Expected behaviour
Shortcuts list should be readable

### Actual behaviour
It is not readable

### Screenshots
![swappy-20230323_095336](https://user-images.githubusercontent.com/61561059/227151823-af2ccc74-41d4-4a4c-a57d-826e2bd0c443.png)

## Server

- Notes app version: 4.7.2

- Nextcloud version: 25.0.4

## Client

- Browser (incl. version): Firefox 110

**Comment by eckelon** [comment]
Hi! I saw this issue and I think I fixed it, it was just adding a color property in a the `table.notes-help tr:nth-child(even) {
` query in `AppHelp.vue`
I made it black but I'm not sure if that should be the right color. I'm submitting a PR if it's OK.

Thanks!
<img width="773" alt="image" src="https://user-images.githubusercontent.com/11048462/227266878-20632d10-5f1c-424d-8ebf-278e73abb58b.png">
